### PR TITLE
WIP: add de.demuc.colmap

### PR DESCRIPTION
**Pull request by kevinsmia1939**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*

I gave it a home access, because when I try to import some images I got this error.
`SQLite error [/run/build/COLMAP/src/base/database.cc, line 261]: unable to open database`

I have not tried CUDA feature as I don't have the graphics card.

- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** No respond https://github.com/colmap/colmap/issues/1180
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build de.demuc.colmap

**Comment by kevinsmia1939** [comment]
What should I do for build fail `fatal: No url found for submodule path 'shared-modules' in .gitmodules`?

**Comment by kevinsmia1939** [comment]
bot, build de.demuc.colmap

**Comment by kevinsmia1939** [comment]
COLMAP is missing an icon, COLMAP dev need one.

**Comment by nedrichards** [comment]
bot, build de.demuc.colmap

**Comment by FuchtelJockel** [comment]
I had written a colmap yaml some time ago. I could send it if you are having trouble.

**Comment by kevinsmia1939** [comment]
> I had written a colmap yaml some time ago. I could send it if you are having trouble.

Thanks for help, what is the difference? I am missing the app icon at the moment.

**Comment by FuchtelJockel** [comment]
There isn't a official icon but why not use the point cloud of some model you have with the little red cameras.
here is my file
[de.demuc.colmap.yml.txt](https://github.com/flathub/flathub/files/6804428/de.demuc.colmap.yml.txt)

**Comment by kevinsmia1939** [comment]
> There isn't a official icon but why not use the point cloud of some model you have with the little red cameras.
> here is my file
> [de.demuc.colmap.yml.txt](https://github.com/flathub/flathub/files/6804428/de.demuc.colmap.yml.txt)

I could but I think it would misrepresent what the app author intended. Unless the app author approve it, I don't think I should add a placeholder icon.

**Comment by barthalion** [comment]
I don't mind a placeholder icon if there's none.

**Pull request closed without merging**
