### PR TITLE
Add org.gnome.gitlab.cheywood.Buffer

### PR DESCRIPTION
**Pull request by cheywood**
Buffer - Embrace ephemeral text.

Celebrating transience, Buffer provides a minimal editing space for all those things that don't need keeping. Designed for keyboard workflows on desktop.

### Please confirm your submission meets all the criteria

- [x] Please describe your application briefly.
- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.gnome.gitlab.cheywood.Buffer

**Comment by bbhtt** [comment]
Is the the close button missing intended?

**Comment by cheywood** [comment]
> Is the the close button missing intended?

Yep. As written in the description the target is keyboard worksflows on desktop. 

A close button can be enabled in the preferences.

**Comment by cheywood** [comment]
I may change that to defaulting enabled, I'll have a think

**Comment by cheywood** [comment]
Changed default to showing close button (when menu is shown)

**Comment by cheywood** [comment]
bot, build org.gnome.gitlab.cheywood.Buffer

**Pull request closed without merging**
