### PR TITLE
add org.freedesktop.Sdk.Extension.bazel

### PR DESCRIPTION
**Pull request by albert-tomanek**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*. (No patches needed.)

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Review by hfiguiere — CHANGES_REQUESTED** [review]
Please rename the PR so that it reflect the name of the package. 

Thanks,

**Comment by albert-tomanek** [comment]
Thanks! Both should now be fixed.

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.Sdk.Extension.bazel

**Comment by hfiguiere** [comment]
the appstream file need to be installed.

**Comment by albert-tomanek** [comment]
bot, build org.freedesktop.Sdk.Extension.bazel

**Comment by albert-tomanek** [comment]
Whoops, need to validate the appdata file first

**Comment by albert-tomanek** [comment]
bot, build org.freedesktop.Sdk.Extension.bazel

**Pull request closed without merging**
