### PR TITLE
Add org.sugarlabs.MusicKeyboard

### PR DESCRIPTION
**Pull request by tchx84**
This Sugar activity display a piano keyboard in the screen and can be used to play music selecting sounds from different instruments. In devices with touch screen, can be used touching the screen, in devices without one, the laptop keyboard can be used.

### CODE REVIEW

**Comment by tchx84** [comment]
bot, build org.sugarlabs.MusicKeyboard

**Comment by tchx84** [comment]
I am looking into the arm failure...

**Comment by tchx84** [comment]
bot, build org.sugarlabs.MusicKeyboard

**Comment by tchx84** [comment]
bot, build org.sugarlabs.MusicKeyboard

**Comment by tchx84** [comment]
bot, build org.sugarlabs.MusicKeyboard

**Comment by tchx84** [comment]
@nedrichards wants to take a look at this one too ?

**Comment by nedrichards** [comment]
/merge

this is as good an argument as I've ever seen for n-way key rollover.

**Comment by tchx84** [comment]
@nedrichards I guess the bot is taking longer this time :confused: to do the actual merge

**Comment by nedrichards** [comment]
@tchx84 there's a bug, you can see the error in the github action https://github.com/flathub/flathub/commit/3476de66bd072681e643618f0292d05b5b17d8e0/checks?check_suite_id=319084803

**Comment by bilelmoussaoui** [comment]
The logs are somehow not available anymore
/merge

**Pull request closed without merging**
