### PR TITLE
Add re.sonny.Junction

### PR DESCRIPTION
**Pull request by sonnyp**
https://github.com/sonnyp/Junction

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/sonnyp/Junction
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by sonnyp** [comment]
bot, build re.sonny.Junction

**Comment by nedrichards** [comment]
bot, build re.sonny.Junction

**Comment by sonnyp** [comment]
I found a flatpak related bug . I cannot open links within Junction itself. When clicking on `Click here to test` or a link in the about dialog I get the following:

```
Error: /usr/lib64/firefox/firefox not found
       /usr/lib/firefox/firefox not found

```

The `openURI` portal method isn't even called so it doesn't appear to be a flatpak bug.

Most likely GTK is confused by `junction-wrapper`.

Will fix and let you know.

**Comment by sonnyp** [comment]
Issue is fixed. For the curious: https://github.com/sonnyp/Junction/commit/5140f410ffd2899a3bb1aba5929f9891741e02fb

**Comment by sonnyp** [comment]
bot, build re.sonny.Junction

**Comment by barthalion** [comment]
All my browsers come from Flathub (Firefox, Chromium, Web; global installation), and it seems to cause problems with displaying icons:

image

I see there are some permissions to access Flatpak files but it doesn't seem to do what it should?

**Comment by sonnyp** [comment]
Nevermind, you already mentioned it was - that must be why I couldn't see the bug, all my flatpak are installed as users - will look into it thanks.

**Comment by sonnyp** [comment]
bot, build re.sonny.Junction

**Comment by sonnyp** [comment]
bot, build re.sonny.Junction

**Pull request closed without merging**
