### PR TITLE
Add org.gnome.Tau

### PR DESCRIPTION
**Pull request by Cogitri**
I guess com.github.Cogitri.gxi could be removed after this is merged.

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build org.gnome.Tau

**Comment by Cogitri** [comment]
Added missing OARS content rating.

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.Tau

**Comment by Cogitri** [comment]
Oops, forgot to push, sorry

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.Tau

**Comment by barthalion** [comment]
Repository has been created: https://github.com/flathub/org.gnome.Tau

Thanks!

Side note: on Monday I'm going to deploy new release of flat-manager to Flathub, which brings EOL support with rebase on new app id. I'll test it then on gxi and archive the old repo.

**Comment by Cogitri** [comment]
Thank you very much! :)

-------- Original Message --------

**Comment by bilelmoussaoui** [comment]
> Repository has been created: https://github.com/flathub/org.gnome.Tau
> 
> Thanks!
> 
> Side note: on Monday I'm going to deploy new release of flat-manager to Flathub, which brings EOL support with rebase on new app id. I'll test it then on gxi and archive the old repo.

Oh, very good news 🎉

**Pull request closed without merging**
