### PR TITLE
Add io.github.breadmakesyoufull.bpm2fps

### PR DESCRIPTION
**Pull request by BreadMakesYouFull**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly.
  Match song beats to their closest frame for animation.

- [X] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read the and followed all the [Submission and licence requirements][reqs].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:**

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build io.github.breadmakesyoufull.bpm2fps

**Comment by bbhtt** [comment]
The file doesn't get saved unless the extension is added, and the only option in the filechooser seems to be json.

[gedG.webm](https://github.com/user-attachments/assets/8bf582d5-b077-4645-b1f0-f9f6359c01ae)

**Comment by BreadMakesYouFull** [comment]
Thanks for taking a look so swiftly @bbhtt and the thorough testing. Apologies for missing this, still learning about flatpak permissions portals etc, and should've known opening the dialog isn't enough to check the export is working!

I can see one way forwards would be to expose xdg-documents or home:
``flatpak run --filesystem=xdg-documents io.github.breadmakesyoufull.bpm2fps``

But there is not a way to tell the QML dialog that defers to the system dialog that it should only show a specific folder:
https://doc.qt.io/qt-6/qml-qtquick-dialogs-filedialog.html 

I'll have a think about how to fix, this but it seems like the approaches available are:
* expose xdg-documents / home, warn user with popup if they accept on non accessible folder after the fact.
* expose xdg-documents, remove file save dialog, pop-up "file saved to: <xdg-documents>/<unique-name>.<format>

**Comment by BreadMakesYouFull** [comment]
Opted to expose xdg-documents + desktop and log more explicit message in terminal if file save fails

**Comment by bbhtt** [comment]
bot, build io.github.breadmakesyoufull.bpm2fps

**Pull request closed without merging**
