### PR TITLE
Add Beaker browser

### PR DESCRIPTION
**Pull request by G-Ray**
https://beakerbrowser.com

"Beaker is an experimental browser for exploring and building the peer-to-peer Web."

I encountered an issue about letting the app execute a specific command from the host: Beaker currently need to execute `xdg-mime` on the host. So I alloed filesystem acces to `host` and exported PATH=$PATH:/var/run/host/usr/bin before executing the app. That may not be ideal but do you know a better way to deal with it ?

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.beakerbrowser.Beaker

**Comment by nedrichards** [comment]
Are you sending the appdata upstream? (you should)
Is it possible to build from source? (or are there blocker issues in your testing)

**Comment by nedrichards** [comment]
The appimage is only for x86-64 so the builds on other architectures failed https://flathub.org/builds/#/builders/2/builds/2471 you need to use a flathub.json like so https://github.com/flathub/com.spotify.Client/blob/master/flathub.json to restrict the build to the architectures you need.

**Comment by G-Ray** [comment]
Thank you for your review @nedrichards.
I uploaded a flathub.json file to restrict builds to `x86_64` only.
By "sending the appdata upstream" you mean sending the file to the beakerbrowser repository ?

I tried to build from the sources first, but Beaker needs to re-compile some npm dependencies from sources with the electron headers, but I did not find a way to do it unfortunately.

**Comment by nedrichards** [comment]
yes, I meant send the appdata to the beaker repository. appdata is good for everyone!

**Comment by nedrichards** [comment]
bot, build com.beakerbrowser.Beaker

**Comment by nedrichards** [comment]
bot, build com.beakerbrowser.Beaker

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.beakerbrowser.Beaker

**Pull request closed without merging**
