### PR TITLE
Add com.github.PintaProject.Pinta (pinta-flatpak)

### PR DESCRIPTION
**Pull request by scx**
[Pinta](https://pinta-project.com/pintaproject/pinta) is a free, open source program for drawing and image editing.

See also:
https://github.com/PintaProject/Pinta
https://github.com/scx/pinta-flatpak
https://github.com/scx/flathub/tree/com.github.PintaProject.Pinta

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.github.PintaProject.Pinta

**Comment by scx** [comment]
Builds clean: https://flathub.org/builds/#/builders/2/builds/6624

**Comment by scx** [comment]
[AppData]: a pull request has been sent to the upstream vendor.

**Comment by scx** [comment]
Moving away from the 3.28 GNOME runtime.
See also:
https://flathub.org/builds/#/builders/2/builds/6720
https://github.com/flathub/org.freedesktop.Sdk.Extension.mono5/issues/2#issuecomment-446722486

**Comment by nedrichards** [comment]
testbot, build com.github.PintaProject.Pinta

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.github.PintaProject.Pinta

**Comment by scx** [comment]
@nedrichards 
Thank you for creating a repo!

I would like to extend filesystem permissions to at least `home`. What do you think about it? It's a Gtk+2 (Gtk#) application, it can not use portals.

**Pull request closed without merging**
