### PR TITLE
Add com.valvesoftware.Steam.VulkanLayer.MangoHud

### PR DESCRIPTION
**Pull request by gasinvein**
MangoHud is a Vulkan overlay displaying various GPU and other stats.
Here it is build as an extension for Steam flatpak.
~~Waiting for flathub/com.valvesoftware.Steam#531 to land in `stable` flatpak branch.~~
CC @nanonyme

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build com.valvesoftware.Steam.VulkanLayer.MangoHud

**Comment by gasinvein** [comment]
bot, build com.valvesoftware.Steam.VulkanLayer.MangoHud

**Comment by gasinvein** [comment]
bot, build com.valvesoftware.Steam.VulkanLayer.MangoHud

**Comment by barthalion** [comment]
LGTM. I can merge it if it works for you.

**Comment by gasinvein** [comment]
@barthalion Upstream didn't respond just yet, but I guess it isn't a blocker?
The HUD itself works just fine.

**Comment by gasinvein** [comment]
@barthalion So, should we wait for upstream blessing? If not, I'd like this merged.

**Pull request closed without merging**
