### PR TITLE
Add VectorSlicer

### PR DESCRIPTION
**Pull request by jsparber**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build org.gnome.design.VectorSlicer

**Comment by jsparber** [comment]
The CI seams not to like `        "build-args" : [
            "--share=network"
        ]`

It requires network because of cargo. Is there a better way?

**Comment by bilelmoussaoui** [comment]
> The CI seams not to like ` "build-args" : [ "--share=network" ]`
> 
> It requires network because of cargo. Is there a better solution?

You need to bundle all the dependencies in a tarball, you should get one with `ninja dist` and upload it to the release tag before using it

**Comment by nedrichards** [comment]
there's also the cargo generator stuff, but I've not used that myself https://github.com/flatpak/flatpak-builder-tools/blob/master/cargo/flatpak-cargo-generator.py

**Comment by barthalion** [comment]
@jsparber Have you had a chance to look at making the build offline?

**Comment by jsparber** [comment]
bot, build org.gnome.design.VectorSlicer

**Comment by jsparber** [comment]
bot, build org.gnome.design.VectorSlicer

**Comment by jsparber** [comment]
I finally had time to fix the offline build. I think this can be included now.

**Pull request closed without merging**
