### PR TITLE
Add GNOME-Feeds

### PR DESCRIPTION
**Pull request by GabMus**

### CODE REVIEW

**Comment by GabMus** [comment]
bot, build org.gabmus.gnome-feeds

**Comment by nedrichards** [comment]
@GabMus you need to use GTKFileChooserNative to open and save files otherwise you can't poke holes in the sandbox to get access to them https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html

(as an aside, the app could probably do with following the 'empty state' pattern to make it easier to work out what to do if you haven't added a feed yet - but that's not a blocker)

**Comment by GabMus** [comment]
bot, build org.gabmus.gnome-feeds

**Comment by GabMus** [comment]
@nedrichards thanks for the heads up, hope this new version is fine now :grin:

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gabmus.gnome-feeds

**Pull request closed without merging**
