### PR TITLE
Add io.github.Foldex.r2mod

### PR DESCRIPTION
**Pull request by Foldex**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build io.github.Foldex.r2mod

**Comment by barthalion** [comment]
```
builddir/files/share/appdata/io.github.Foldex.r2mod.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
```

**Comment by Foldex** [comment]
Added the missing oars tag.

**Comment by hfiguiere** [comment]
bot, build io.github.Foldex.r2mod

**Comment by barthalion** [comment]
As it's CLI application, https://github.com/Foldex/r2mod_cli/blob/master/flatpak/io.github.Foldex.r2mod.metainfo.xml#L2 should be changed to `console-application`, and you will also need to disable the icons check explicitly like here: https://github.com/flathub/org.gnome.NautilusPreviewer/commit/04c82823447983b62b1033bc26f1d7a71bdf2c8e

**Comment by Foldex** [comment]
bot, build io.github.Foldex.r2mod

**Comment by Foldex** [comment]
Thanks fellas, appreciate the help!

**Pull request closed without merging**
