### PR TITLE
Add re.chiaki.Chiaki

### PR DESCRIPTION
**Pull request by AsciiWolf**
Chiaki is [already available](https://github.com/flathub/com.github.thestr4ng3r.Chiaki) on Flathub. I am just renaming the Flatpak to match the id used by upstream. I will EOL the current Flatpak after this new one is accepted.

### Please confirm your submission meets all the criteria

- [*] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [*] My pull request follows the instructions at [App Submission][submission].
- [*] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [*] All assets referenced in the manifest are redistributible by any party.  If not, the unredistributable parts are using an extra-data source type.
- [*] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/thestr4ng3r/chiaki/issues/40#issuecomment-712470769
- [*] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [*] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build re.chiaki.Chiaki

**Comment by AsciiWolf** [comment]
Everything seems to work fine. :-)

**Comment by barthalion** [comment]
/merge @thestr4ng3r 

@AsciiWolf please remember to properly EOL the old app. https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life

**Comment by AsciiWolf** [comment]
@barthalion Done! :-) Could you please archive the old repo? Thanks!

**Pull request closed without merging**
