### PR TITLE
Add dev.bragefuglseth.Fretboard

### PR DESCRIPTION
**Pull request by bragefuglseth**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build dev.bragefuglseth.Fretboard

**Comment by hfiguiere** [comment]
build needs to be performed offline.

Either use a tarball with vendored crates or the flatpak-buider-tools to generate a manifest from the cargo lock. https://github.com/flatpak/flatpak-builder-tools/tree/master/cargo

**Comment by bragefuglseth** [comment]
Let's see if it works now…

bot, build dev.bragefuglseth.Fretboard

**Comment by bragefuglseth** [comment]
hooray!

**Comment by hfiguiere** [comment]
works great here

**Comment by bragefuglseth** [comment]
works on my end as well 👍

**Comment by barthalion** [comment]
/,erge

**Pull request closed without merging**
