### PR TITLE
Add manifest for org.kde.zanshin

### PR DESCRIPTION
**Pull request by flyingcakes85**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. **No patches**

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by flyingcakes85** [comment]
bot, build org.kde.zanshin

**Comment by flyingcakes85** [comment]
CC @travier 

This application is for beta.
It builds correctly, but doesn't launch. It gets stuck at `Migrating tags, please wait...`.

**Comment by travier** [comment]
CC @flathub/kde

**Comment by travier** [comment]
bot, build org.kde.zanshin

**Comment by travier** [comment]
Probably need something like https://github.com/flathub/org.kde.kontact/blob/master/run_kontact.sh

**Comment by flyingcakes85** [comment]
bot, build org.kde.zanshin

**Comment by barthalion** [comment]
bot, build org.kde.zanshin

**Comment by barthalion** [comment]
it seems to be stuck on `Migrating tags, please wait...` here on GNOME.

**Comment by flyingcakes85** [comment]
Same on KDE.

I'm keeping this on hold for now.

**Pull request closed without merging**
