### PR TITLE
Publish Amberol 0.1.0

### PR DESCRIPTION
**Pull request by ebassi**
Amberol is a simple music player that has no delusions of grandeur.

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions.
- [x] All assets referenced in the manifest are redistributable by any party.
- [x] I am an upstream contributor to the project.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build io.bassi.Amberol

**Comment by ebassi** [comment]
Tested the build, and everything works as expected.

**Comment by hfiguiere** [comment]
LGTM

**Pull request closed without merging**
