### PR TITLE
Add io.balena.etcher

### PR DESCRIPTION
**Pull request by x80486**

### CODE REVIEW

**Comment by x80486** [comment]
bot build io.balena.etcher

**Comment by x80486** [comment]
bot, build io.balena.etcher

**Comment by x80486** [comment]
bot, build io.balena.etcher

**Comment by x80486** [comment]
bot, build io.balena.etcher

**Comment by x80486** [comment]
OK, one less problem...now it is something with `pkexec` and/or `kdesudo`:

```shell
error Error: Unable to find pkexec or kdesudo.
    at test (/app/balenaEtcher/re…prompt/index.js:205)
    at /app/balenaEtcher/re…prompt/index.js:212
    at FSReqCallback.oncomplete (fs.js:165)
```

**Comment by gasinvein** [comment]
How this is going to work? Etcher requires elevated privileges, which are impossible to gain inside the sandbox.

**Comment by x80486** [comment]
> How this is going to work? Etcher requires elevated privileges, which are impossible to gain without running outside the sandbox.

Well, I didn't know that. If that's the case, then this application is (close to) impossible to run as Flatpak, right? Are there any workarounds?

**Comment by gasinvein** [comment]
> this application is (close to) impossible to run as Flatpak, right?

I guess so, unless the app supports some privileged helper running outside the sandbox, e.g. UDisks2.

**Comment by p1u3o** [comment]
You could use flatpak-spawn to gain elevated permissions (GST does this to read memory information). Wouldn't Etcher just need to be patched to do something along the lines of

```
flatpak-spawn --host pkexec dd if=/location/of/file.iso of=/dev/xxx status="progress"
```

**Comment by gasinvein** [comment]
@p1u3o 
>  Wouldn't Etcher just need to be patched to do something along the lines of
> 
> ```
> flatpak-spawn --host pkexec dd if=/location/of/file.iso of=/dev/xxx status="progress"
> ```

AFAIK Etcher doesn't use `dd` or any other well-known utility to write images, so patching the app to do so wouldn't be as easy as it may seem.

**Comment by barthalion** [comment]
Also anything with permissions to run `flatpak-spawn` is essentially unsandboxed.

**Comment by x80486** [comment]
All right! I guess there is really nothing I can do to make this work as it stands right now. If something changes in the future I will give it another try.

**Comment by p1u3o** [comment]
It sounds like the best solution would be for upstream to use Udisks2, which wouldn't just help Flatpak :)

**Comment by thundron** [comment]
Unfortunately that is out of scope for us now, maybe in the future we'll consider it or a reasonable solution will pop-up

**Comment by A6GibKm** [comment]
It is not possible to temporarily build a working build without sandbox?

**Comment by p1u3o** [comment]
Not really, the sandbox is how Flatpak can make sure the dependencies are loaded from the runtime, not the host.

**Pull request closed without merging**
