### PR TITLE
Add io.github.dida_code.OpstaKultura

### PR DESCRIPTION
**Pull request by dida-code**
### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build io.github.dida_code.OpstaKultura

**Comment by hfiguiere** [comment]
none of the questions in the template have been answered.

**Comment by hfiguiere** [comment]
sorry I didn't mean to close it. GitHub is just plain stupid here.

**Comment by hfiguiere** [comment]
the PR should be done against the `new-pr` branch which is what triggered the closing when I changed it.

**Comment by dida-code** [comment]
what should i do now? should I repeat the PR?

**Comment by hfiguiere** [comment]
sadly yes, create a new one. against `new-pr` and not master, as per the instructions.

**Comment by hfiguiere** [comment]
hold on.

**Comment by dida-code** [comment]
Ok, thanks for your reply

**Comment by dida-code** [comment]
When I try to create a new PR I get the following message:
"There isn’t anything to compare.
flathub:new-pr and dida-code:OpstaKultura are entirely different commit histories."

**Comment by hfiguiere** [comment]
you need to rebase on the `new-pr` branch first.

**Pull request closed without merging**
