### PR TITLE
Add org.freedesktop.adriconf

### PR DESCRIPTION
**Pull request by jlHertel**
## Description
This is moving the existing adriconf application from the id `br.com.jeanhertel.adriconf` to the name `org.freedesktop.adriconf`.
Existing repository is [here][1].
Issue describing this migration can be seen [here][2].

[1]:https://github.com/flathub/br.com.jeanhertel.adriconf
[2]: https://github.com/flathub/br.com.jeanhertel.adriconf/issues/9

### CODE REVIEW

**Comment by jlHertel** [comment]
bot, build org.freedesktop.adriconf

**Comment by jlHertel** [comment]
bot, build org.freedesktop.adriconf

**Comment by jlHertel** [comment]
@bilelmoussaoui Is there anything else we need to do here to move this forward?

**Comment by bilelmoussaoui** [comment]
/merge
Please ping me once you have EOL'ed the old app so I can archive the repository. Thanks

**Comment by jlHertel** [comment]
@bilelmoussaoui I think it will be a bit confusing to users if I EOL the current app without being able to point to this new one. Can we merge this first before marking the other one as end of life?

**Comment by bilelmoussaoui** [comment]
Sorry, it was the bot's fault.
/merge

**Comment by jlHertel** [comment]
@bilelmoussaoui Cool, thanks for clarification. Let me know once you manage to merge this and create the new repository, so I can properly EOL the old app.

**Comment by bilelmoussaoui** [comment]
Hmm, it should work now
/merge

**Pull request closed without merging**
