### PR TITLE
Add xyz.hyperplay.HyperPlay

### PR DESCRIPTION
**Pull request by flavioislima**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by flavioislima** [comment]
Hey guys, some extra information here:
HyperPlay is a fork of Heroic Games Launcher, already on Flathub: https://github.com/flathub/com.heroicgameslauncher.hgl

It has the same features so that's why it has the same list of permissions and basically the same build file with just a few adjustments since it does not use an AppImage but a `tar.xz `file with the app content in it.

Let me know if you guys have any other question.

**Comment by flavioislima** [comment]
bot, build xyz.hyperplay.HyperPlay

**Comment by flavioislima** [comment]
bot, build xyz.hyperplay.HyperPlay

**Comment by flavioislima** [comment]
bot, build xyz.hyperplay.HyperPlay

**Comment by flavioislima** [comment]
bot, build xyz.hyperplay.HyperPlay

**Comment by flavioislima** [comment]
bot, build xyz.hyperplay.HyperPlay

**Comment by flavioislima** [comment]
bot, build xyz.hyperplay.HyperPlay

**Comment by flavioislima** [comment]
bot, build xyz.hyperplay.HyperPlay

**Comment by flavioislima** [comment]
bot, build xyz.hyperplay.HyperPlay

**Comment by barthalion** [comment]
bot, build xyz.hyperplay.HyperPlay

**Pull request closed without merging**
