### PR TITLE
net.technicpack.TechnicLauncher

### PR DESCRIPTION
**Pull request by Somaxa8**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
PR shall be made against the `new-pr` branch

**Comment by hfiguiere** [comment]
Also https://github.com/flathub/flathub/pull/2800

**Comment by barthalion** [comment]
As you marked "I am an upstream contributor…" as done, can you elaborate on that? Are you an upstream developer, or have they given you permission to submit it?

**Comment by rowbawts** [comment]
> #2800 This was attempted before, the developers are against this.

Yeah I saw this and was so confused I thought I was pretty sure I'd seen it before.

**Pull request closed without merging**
