### PR TITLE
Matcha-sea gtk-3.0 theme for flathub

### PR DESCRIPTION
**Pull request by vinceliuice**
Manjaro gnome default theme : Matcha-sea

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build org.gtk.Gtk3theme.Matcha-sea

**Comment by bilelmoussaoui** [comment]
You should open a PR against new-pr branch.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gtk.Gtk3theme.Matcha-sea

**Comment by vinceliuice** [comment]
Thanks!

**Pull request closed without merging**
