### PR TITLE
Add org.alicevision.meshroom

### PR DESCRIPTION
**Pull request by FakeShemp**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link: https://github.com/alicevision/meshroom/issues/1517**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

https://alicevision.org/#meshroom

### CODE REVIEW

**Comment by FakeShemp** [comment]
I'm having a final issue with the manifest in that the packing stage gives me `ZIP does not support timestamps before 1980`. Is there a way to avoid changing the timestamps to one before 1980 and do another date?

**Comment by FakeShemp** [comment]
bot, build

**Comment by FakeShemp** [comment]
bot, build org.alicevision.Meshroom

**Comment by FakeShemp** [comment]
bot, build org.alicevision.Meshroom

**Comment by hfiguiere** [comment]
> I'm having a final issue with the manifest in that the packing stage gives me `ZIP does not support timestamps before 1980`. Is there a way to avoid changing the timestamps to one before 1980 and do another date?

I think everything in the sandbox get set to the unix epoch which is Jan 1 1970 UTC.

**Comment by hfiguiere** [comment]
Not sure if that would work, but could add `no-python-timestamp-fix: true` in the corrsponding python module in the manifest.

**Comment by FakeShemp** [comment]
> Not sure if that would work, but could add `no-python-timestamp-fix: true` in the corrsponding python module in the manifest.

It's already set afaik.

**Comment by barthalion** [comment]
Python's zipfile module takes strict_timestamps parameter that would possibly allow working around the problem: https://docs.python.org/3.8/library/zipfile.html#zipfile-objects

**Comment by FakeShemp** [comment]
`strict_timestamps` does not seem to be available on `PyZipFile` used in the app. I've submitted a bug report...

**Comment by kevinsmia1939** [comment]
Can you build this with CUDA on?

**Comment by kevinsmia1939** [comment]
> `strict_timestamps` does not seem to be available on `PyZipFile` used in the app. I've submitted a bug report...

Hi, can you show me where is the bug report?

**Comment by FakeShemp** [comment]
> > `strict_timestamps` does not seem to be available on `PyZipFile` used in the app. I've submitted a bug report...
> 
> Hi, can you show me where is the bug report?

https://bugs.python.org/issue45140

**Comment by natowi** [comment]
For convenience, here is the Github link to the bug mentioned: https://github.com/python/cpython/issues/89303

**Pull request closed without merging**
