### PR TITLE
Initial manifest for org.laptop.TurtleArtActivity

### PR DESCRIPTION
**Pull request by cosimoc**
A lot of custom patches are needed to build the flatpak at the moment, which I upstreamed in https://github.com/sugarlabs/turtleart-activity/pull/64.

Also, I used a git commit because the latest v218 release is not tagged in git upstream. (I asked for the next release to be tagged, if my fixes are accepted.)

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build org.laptop.TurtleArtActivity

**Comment by nedrichards** [comment]
If I read your patches correctly, there's still no OARS or version tags?

**Comment by cosimoc** [comment]
Added patches both here and upstream to do that.

**Comment by nedrichards** [comment]
bot, build org.laptop.TurtleArtActivity

**Comment by cosimoc** [comment]
bot, build org.laptop.TurtleArtActivity

**Comment by nedrichards** [comment]
bot, build org.laptop.TurtleArtActivity

**Comment by cosimoc** [comment]
bot, build org.laptop.TurtleArtActivity

**Comment by nedrichards** [comment]
bot, build org.laptop.TurtleArtActivity

**Comment by nedrichards** [comment]
bot, build org.laptop.TurtleArtActivity

**Comment by nedrichards** [comment]
bot, build org.laptop.TurtleArtActivity

**Comment by nedrichards** [comment]
bot, build org.laptop.TurtleArtActivity

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.laptop.TurtleArtActivity

**Pull request closed without merging**
