### PR TITLE
com.github.jkotra.eovpn

### PR DESCRIPTION
**Pull request by jkotra**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/jkotra/eOVPN
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by jkotra** [comment]
bot, build com.github.jkotra.eovpn

**Comment by jkotra** [comment]
bot, build com.github.jkotra.eovpn

**Comment by jkotra** [comment]
bot, build com.github.jkotra.eovpn

**Comment by barthalion** [comment]
I have tried to add `https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip` in settings but the save button doesn't seem to do anything so I don't have a way to test it as it is.

**Comment by jkotra** [comment]
@barthalion, after clicking 'save' button, you need to click 'update' from menu. 

(if a crt is provided inside zip file, it will be automatically set on first update)

**Comment by barthalion** [comment]
I think it would be less confusing if it happened implicitly, either via `save` button or re-using the data after validation.

**Comment by jkotra** [comment]
@barthalion , i made several improvements to settings window UI. 

```
- add "settings saved" notification.
- update on save if previous remote is None (empty).
- simplify statusbar pushing with generic function.
- remove config(s) liststore on reset.
```

**Comment by jkotra** [comment]
bot, build com.github.jkotra.eovpn

**Comment by jkotra** [comment]
bot, build com.github.jkotra.eovpn

**Comment by jkotra** [comment]
bot, build com.github.jkotra.eovpn

**Comment by jkotra** [comment]
@barthalion

Request to review.

**Comment by barthalion** [comment]
Sorry, there will be some noise as I test some automation changes.

/merge

**Pull request closed without merging**
