### PR TITLE
Build manifest for ws.openarena.OpenArena

### PR DESCRIPTION
**Pull request by cosimoc**
Based on the Freedesktop 1.6 SDK.

### CODE REVIEW

**Comment by TingPing** [comment]
Test build: https://flathub.org/builds/#/builders/5/builds/284

**Comment by TingPing** [comment]
Could you start specifying `project_license` in your appdatas? I think it is valuable information to have.

**Comment by TingPing** [comment]
i386 failed.

**Comment by cosimoc** [comment]
Thanks, I pushed a patch that should hopefully fix it.

**Comment by TingPing** [comment]
Repository has been created: https://github.com/flathub/ws.openarena.OpenArena

**Pull request closed without merging**
