### PR TITLE
LLVM 16

### PR DESCRIPTION
**Pull request by Lctrs**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Lctrs** [comment]
friendly ping @Erick555 :)

**Comment by Lctrs** [comment]
bot, build org.freedesktop.Sdk.Extension.llvm16

**Comment by Erick555** [comment]
It's huge coincidence that we both independently created this within few minutes timeframe: https://github.com/flathub/flathub/pull/4117

**Comment by Lctrs** [comment]
I have no problem closing mine in favor of yours since I have a feeling you'll be the primary one to maintain it :D

**Comment by Lctrs** [comment]
Closing in favor of #4117

**Pull request closed without merging**
