### PR TITLE
Add RSS Guard Lite

### PR DESCRIPTION
**Pull request by guihkx**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/martinrotter/rssguard
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

---

Hello. This is the exact same app as of PR #3736, except with no built-in web browser support.

If this gets accepted, please add @martinrotter as a collaborator as well.

Thank you!

### CODE REVIEW

**Comment by guihkx** [comment]
bot, build io.github.martinrotter.rssguardlite

**Comment by barthalion** [comment]
Can you explain why would someone use Lite variant instead of the main one? The difference size is marginal (saving 100MB when runtimes take 2-3GB doesn't seem to matter), and it sounds like users who don't want to use the built-in browser can just not do it?

**Comment by martinrotter** [comment]
> Can you explain why would someone use Lite variant instead of the main one? The difference size is marginal (saving 100MB when runtimes take 2-3GB doesn't seem to matter), and it sounds like users who don't want to use the built-in browser can just not do it?

I do not honestly understand why would you even ask this question? You could instead do 1 minute research and you would find "lite" (also known as "nowebengine" in RSS Guard community) variant of our program is actually used bit MORE than full-blown variant. Both variants of RSS Guard are used frequently by many many users for various reasons (philosophical and technical) and it really makes no sense dissecting those reasons here.

**Comment by guihkx** [comment]
Let's calm ourselves. 👼 

>Can you explain why would someone use Lite variant instead of the main one?

Personal opinion (might not reflect @martinrotter's): QtWebEngine isn't updated as frequently as the web browser you and I use daily, which is not particularly good for security. At the same time, I believe that there are users who enjoy reading their news within RSS Guard itself, without having to rely on an external browser for that (I'm not one of them 😄).

>The difference size is marginal (saving 100MB when runtimes take 2-3GB doesn't seem to matter)

I disagree on this point, every MB we can save is definitely worth it. Additionally, memory footprint on the Lite version is lower as well... And I imagine that if Flatpak didn't have file deduplication to help save disk space, it wouldn't be as popular, so disk space usage seems like an important topic.

>and it sounds like users who don't want to use the built-in browser can just not do it?

That's true to *some* extent: There is a `--no-web-engine` option on the "regular" build that forces the usage of a simpler "webview reader", but even then, Qt will still launch `QtWebEngineProcess` and, unfortunately, it seems [we can't prevent it](https://github.com/martinrotter/rssguard/issues/713#issuecomment-1114662018).

**Comment by martinrotter** [comment]
Moreover, there are people who hate Google and their code and do not want it on their PCs. QtWebEngine module is de-facto Chromium core.

**Comment by barthalion** [comment]
@martinrotter It would be more than sufficient to just reply that these are considered separate applications. No need to be hostile because a reviewer is reviewing your submission.

**Comment by martinrotter** [comment]
> @martinrotter It would be more than sufficient to just reply that these are considered separate applications. No need to be hostile because a reviewer is reviewing your submission.

I do not feel being hostile, but OK.

Yes, they are considered two distinctive flavors of one application.

**Comment by guihkx** [comment]
(Another example is how RSS Guard has two different packages on Arch Linux: [rssguard](https://archlinux.org/packages/community/x86_64/rssguard/) and [rssguard-nowebengine](https://archlinux.org/packages/community/x86_64/rssguard-nowebengine/))

**Pull request closed without merging**
