### PR TITLE
Add io.qt.qtwebkit511.BaseApp

### PR DESCRIPTION
**Pull request by eszlari**
https://github.com/flathub/io.qt.qtwebkit.BaseApp/issues/5

tested with: https://github.com/flathub/org.shotcut.Shotcut

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build io.qt.qtwebkit511.BaseApp

**Comment by barthalion** [comment]
I'd much prefer if we could get this as branch (with PR to buildbot-config) instead.

**Comment by barthalion** [comment]
Also if you would like to take care of changes to buildbot-config, master should be renamed to 5.9 to avoid confusion.

**Comment by barthalion** [comment]
https://github.com/flathub/buildbot-config/pull/40

**Pull request closed without merging**
