### PR TITLE
Add info.cemu.Cemu

### PR DESCRIPTION
**Pull request by Doomsdayrs**
### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/cemu-project/Cemu/issues/22
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build info.cemu.Cemu

**Comment by barthalion** [comment]
I'm nor particularly sure what's the point of this PR even if it's marked as a draft. There's literally nothing to review here at this point.

**Comment by Doomsdayrs** [comment]
> I'm nor particularly sure what's the point of this PR even if it's marked as a draft. There's literally nothing to review here at this point.

A draft is not meant to be reviewed at all. It just states someone is working on it.
I intend to get this finished on Friday once I am free of college work.

**Comment by hfiguiere** [comment]
What @barthalion said. I just explained what "Draft" means.

**Comment by Doomsdayrs** [comment]
> What @barthalion said. I just explained what "Draft" means.

Was this written elsewhere so I could have known before hand?

**Comment by LeandroStanger** [comment]
bot, build info.cemu.Cemu

**Comment by Doomsdayrs** [comment]
Closing due to lack of motivation

**Pull request closed without merging**
