### PR TITLE
Add org.gnome.Brasero

### PR DESCRIPTION
**Pull request by AppleMayExist**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://gitlab.gnome.org/GNOME/brasero/-/issues/368
- [x] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

Rationale for the non-upstreamed patches:
 - `patch/brasero-vcdimager-version.patch`, which updates the supported version of vcdimager, hasn't been submitted upstream as I haven't tested the vcdimager plugin, because I do not have any VCD hardware.
 - `patch/dvdauthor-no-doc.patch` just disables documentation, as I don't believe dvdauthor's buildsys allows you to do this. This obviously shouldn't be upstreamed.
 - `patch/use-app-dir.patch` changes the installation prefix. It isn't used though, as I have yet to get cdrtools to install successfully, and so it is disabled. Again, obviously shouldn't be merged upstream.

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by AppleMayExist** [comment]
bot, build

**Comment by bbhtt** [comment]
bot, build org.gnome.brasero

**Comment by bbhtt** [comment]
bot, build org.gnome.Brasero

**Comment by bbhtt** [comment]
Copy and replace config.guess, sub with the ones from runtime `/usr/share/gnu-config/config.sub, cp -f /usr/share/gnu-config/config.guess`

**Comment by AppleMayExist** [comment]
bot, build org.gnome.Brasero

**Comment by wjt** [comment]
Re. screenshots: if you give me your wiki.gnome.org username, I'll add you to https://wiki.gnome.org/TrustedEditorGroup so you can update the screenshots. Another approach used by a lot of apps is to check the screenshots into Git (either the flathub repo, or the upstream) and link to the blob.

**Comment by AppleMayExist** [comment]
I suppose I can give a shot at taking some screenshots. My username is DanielFoster. Should I post the screenshots here before I overwrite the old ones?

**Comment by wjt** [comment]
Added you there.

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#screenshots has some guidelines. Assuming that you're using GNOME, https://extensions.gnome.org/extension/881/screenshot-window-sizer/ may be useful to resize the window to the appropriate size & aspect ratio.

**Comment by AppleMayExist** [comment]
Thanks!

**Comment by AppleMayExist** [comment]
I have updated the screenshots, however Brasero no longer shows the main window behind dialogues, which means the CD copy screenshot is really small, so I have replaced it with the screenshot of the new project screen, and submitted the change [upstream](https://gitlab.gnome.org/GNOME/brasero/-/merge_requests/25#note_2019002).

**Comment by bbhtt** [comment]
bot, build org.gnome.Brasero

**Comment by bbhtt** [comment]
cleanup `/lib/cmake`, `/share/info`.

**Pull request closed without merging**
