### PR TITLE
Initial flatpaking of Play it Slowly

### PR DESCRIPTION
**Pull request by bochecha**
The 4 patches were all merged upstream, they can be removed at the next release.

I don't know when such a release will happen, but I asked upstream to make one: https://github.com/jwagner/playitslowly/pull/18#issuecomment-314378629

In any case, the manifest is ready for review. 😄

### CODE REVIEW

**Comment by TingPing** [comment]
Could you please rebase the PR onto `new-pr` (Click `Edit` in top right) and rebase your branch off it too?

**Comment by TingPing** [comment]
Test build: https://flathub.org/builds/#/builders/5/builds/471

**Comment by bochecha** [comment]
@TingPing I rebased the branch and the PR, but that closed the PR. 😕

**Comment by TingPing** [comment]
Weird... expected that to work.

Anyway the build succeeded so I'll just pull from your repo manually tomorrow.

**Comment by TingPing** [comment]
@bochecha Your branch doesn't contain your commit at all...

**Comment by bochecha** [comment]
Huh? It does https://github.com/bochecha/flathub/commit/1c211f487d323fe9bb3798f24a0dea9e4d813f84

**Comment by TingPing** [comment]
Repository has been created: https://github.com/flathub/ch.x29a.playitslowly

**Comment by bochecha** [comment]
Thanks @TingPing !

**Pull request closed without merging**
