### PR TITLE
Add io.github.mmstick.FontFinder

### PR DESCRIPTION
**Pull request by TingPing**
@mmstick Do you have any interest in maintaining this as an official package?

@matthiasclasen Since this was made on your request could you please test it out =)

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build io.github.mmstick.FontFinder

**Comment by nedrichards** [comment]
I care about this too. Will also test.

This needs OARS in the appdata, probably the only potentially sensitive thing is any data it sends to Google Fonts, although I believe that's pretty anonymous. We should obviously also try and get the appdata upstream ;-)

**Comment by nedrichards** [comment]
I've opened an upstream PR to fix the desktop file validation warning https://github.com/mmstick/fontfinder/pull/12 (just a nit, but, y'know)

**Comment by nedrichards** [comment]
Compiled, installed and tested locally, works fine.

**Comment by barthalion** [comment]
LGTM

**Comment by mmstick** [comment]
@TingPing I can maintain it if you want me to.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/io.github.mmstick.FontFinder

**Comment by nedrichards** [comment]
Cool, @mmstick I've sent you an invitation to the newly created repo.

**Pull request closed without merging**
