### PR TITLE
Add org.sugarlabs.TurtlePondActivity

### PR DESCRIPTION
**Pull request by tchx84**
A strategy game. The goal is to surround the turtle before it runs off the screen. You can load your own strategy for the turtle by importing Python code.

### CODE REVIEW

**Comment by tchx84** [comment]
bot, build Add org.sugarlabs.TurtlePondActivity

**Comment by tchx84** [comment]
bot, build org.sugarlabs.TurtlePondActivity

**Comment by bilelmoussaoui** [comment]
Looks ready to me

**Pull request closed without merging**
