### PR TITLE
Add org.freedesktop.Sdk.Extension.symfony

### PR DESCRIPTION
**Pull request by francoism90**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly. 

This would SDK would be addition over https://github.com/flathub/org.freedesktop.Sdk.Extension.php84. The current php Sdk is to limited when working with popular frameworks like Symfony and Laravel.

Both of these popular frameworks need more extensions for IDE completion support, and it would be useful to enable connecting support to your database(s) or sockets, when using these kind of extensions on VSCode.

The current workaround is to either expose your IDE to a `toolbox` by breaking the sandbox, or run it inside a container using `podman remote`. However both are really hard to setup and maintain, and it requires an user to have knowledge of Toolbox or run Podman.

Both SDKs would be useful, this one would be compared to `ffmpeg-full`. Sometimes you need more codecs, in this you would need more extensions. It's still limited to the current Flatpak SDK, but it should offer a good base for any Symfony/Laravel developer.

- [X] The domain used for the application ID is [controlled by the application developer(s)][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read and followed all the [Submission requirements][reqs] and the [Submission guide][reqs2].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor to the project. If not, I contacted upstream developers about this submission. **Link:**

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[reqs2]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by francoism90** [comment]
I've created a PR (https://github.com/flathub/org.freedesktop.Sdk.Extension.php84/pull/4#issuecomment-2560419002) on `org.freedesktop.Sdk.Extension.php84`, however I disagree with the `docker` and `podman` workarounds.

Both are very limited supported, and because it hooks in your current container, it may cause your container(s) to crash or you may end up with weird behavior (https://github.com/containers/podman/discussions/24898).

This may happen on containers running PHP in memory. Because the IDE (e.g. VSCode) may kill the PHP-process, the container will restart frequently or may even overlap. The only (good) workaround would be running an additional 'dev' container, but must users won't even know how to setup this.

I do understand the `podman remote` solution (didn't tested Docker), but stated before, this is very difficult to setup, and sometimes you don't even have a container instance running. Like I do developing on a Chromebook, which isn't even capable of running any containers. But it does push it upstream to my homelab.

**Comment by Lctrs** [comment]
Still not convinced by the need of this extension...

That being said, I think the name is confusing as it can be used for developing with other frameworks as well. Why not following `ffmpeg` example and naming it `org.freedesktop.Sdk.Extension.php-full` ?

**Comment by hfiguiere** [comment]
why not just adding it all to the PHP extensions?

**Comment by bbhtt** [comment]
> Both SDKs would be useful, this one would be compared to ffmpeg-full.

ffmpeg-full exists because of legal reasons for shipping patented codecs and it is extending something shipped in the runtime by default.

>  Sometimes you need more codecs, in this you would need more extensions.

Not more, if this is installed, then php-84 extension doesn't seem to be of use, since you are shipping a competing copy of PHP too.


Ideally it'd be in the original extension.

**Comment by francoism90** [comment]
Except from 4 extensions, these are all built in PHP extensions. They don't require any additional packages or libs.

@bbhtt These are the original provided from PHP itself. GD for example is, and same for pdo mysql. The only package I've added is Redis. The reason for this, is that it's a very popular cache backend and some frameworks expect it to exists as a class.

The author of the php84 sdk doesn't want to enable more inbuilt extensions. That's why I've created this SDK.

It would be great if Flatpak could somehow allow the customizable of SDKs. Like for node, sometimes you don't need npm, but need yarn or any other package manager.. which isn't something the current SDK allows.

The world doesn't consists of a minimal. People use more languages than C or Rust you know.

**Comment by Lctrs** [comment]
It's not that I don't want to add more extensions, it's just that I'm very surprised that a development tool need to be able to run your project to work properly.

**Comment by francoism90** [comment]
@Lctrs This is needed for IDE completion, it doesn't run the project itself.

But let's say you're on a clean PHP project (without any framework or tools), and you need to connect to a remote MySQL database. When not using flatpaks, you would install php-pdo as a package, which would offer you adapters to connect to most major databases. Since VSCode doesn't run in a sandbox in this example, it's able to use all the extensions you have setup in your main environment.

Now say you want to run PHP in VSCode and connect to a database, you can't. The php binary doesn't have the required extensions to talk to any database using the inbuilt terminal or extensions that allow you to run code (e.g. run as php).

I fully agree about not adding extensions just because it's possible. But like I stated before not everyone has container experienced, and sometimes you don't even want to use it. You just want to run the code directly in your IDE instead.

Again, not saying you shouldn't, but you'd be surprised how many do this, or just need a basic set (like me) that does understand how to complete inbuilt PHP methods and classes.

**Comment by bbhtt** [comment]
> It would be great if Flatpak could somehow allow the customizable of SDKs. Like for node, sometimes you don't need npm, but need yarn or any other package manager.. which isn't something the current SDK allows.

Not possible, it's read-only once built and put to the repo.

**Comment by francoism90** [comment]
@bbhtt I think that's a valid point. :)

One final question about `ffmpeg-ful`:

> ffmpeg-full exists because of legal reasons for shipping patented codecs and it is extending something shipped in the runtime by default.

Do you recommend against something like this (e.g. php-full)? If that's the case, the only thing I can think of are dev-containers (this requires podman and the podman-sdk).

But this still requires a lot of loops and things aren't that complete either https://github.com/flathub/com.visualstudio.code/issues/55#issuecomment-913864265

As you can see this is only for VSCode + Podman, for other apps I don't have any idea.

I'll close this PR for now, as I don't see this becoming a thing.

**Comment by bbhtt** [comment]
I'm not convinced entirely with a second `-full` extension like this as I said. There is no precedent for this other than `ffmpeg-full` which was purely for legal reasons and maintained alongside the runtime sharing the sources and dependencies with the copy in the runtime.


Ideally it should be in the current PHP extensions, if there are concerns with maintenance bandwidth, maybe co-maintenance can be set up.

**Comment by francoism90** [comment]
@bbhtt Just see the trouble of adding your own things: https://github.com/flathub/com.visualstudio.code/issues/55#issuecomment-2561905012

The problem isn't the number of missing extensions in this Sdk, it's flatpak not offering any real solution for this.

**Pull request closed without merging**
