### PR TITLE
ml.mdwalters.Lemonade

### PR DESCRIPTION
**Pull request by mdwalters**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

### CODE REVIEW

**Comment by mdwalters** [comment]
bot, build ml.mdwalters.Lemonade

**Comment by mdwalters** [comment]
bot, build ml.mdwalters.Lemonade

**Comment by hfiguiere** [comment]
`Error loading desktop file: Failed to find icon: Failed to find icon lemonade`

**Comment by hfiguiere** [comment]
the .desktop file is wrong upstream. You can use `desktop-file-edit` to fix it, until it's fixed upstream.

**Comment by hfiguiere** [comment]
The appdata will also fail to validate. it is insufficient. missing `releases`, `content_rating`, `url`. at least.

**Comment by mdwalters** [comment]
bot, build ml.mdwalters.Lemonade

**Comment by mdwalters** [comment]
bot, build ml.mdwalters.Lemonade

**Comment by mdwalters** [comment]
bot, build ml.mdwalters.Lemonade

**Comment by barthalion** [comment]
```
~ 2.2s ❱ flatpak run ml.mdwalters.Lemonade
Traceback (most recent call last):
  File "/app/share/lemonade/lemonade/main.py", line 89, in on_activate
    self.win = LemonadeWindow(application=app)
  File "/app/share/lemonade/lemonade/main.py", line 41, in __init__
    self.home()
  File "/app/share/lemonade/lemonade/main.py", line 59, in home
    self.refresh()
  File "/app/share/lemonade/lemonade/main.py", line 69, in refresh
    if post["community"]["description"] == None:
KeyError: 'description'
```

**Comment by mdwalters** [comment]
bot, build ml.mdwalters.Lemonade

**Comment by mdwalters** [comment]
> ```
> ~ 2.2s ❱ flatpak run ml.mdwalters.Lemonade
> Traceback (most recent call last):
>   File "/app/share/lemonade/lemonade/main.py", line 89, in on_activate
>     self.win = LemonadeWindow(application=app)
>   File "/app/share/lemonade/lemonade/main.py", line 41, in __init__
>     self.home()
>   File "/app/share/lemonade/lemonade/main.py", line 59, in home
>     self.refresh()
>   File "/app/share/lemonade/lemonade/main.py", line 69, in refresh
>     if post["community"]["description"] == None:
> KeyError: 'description'
> ```

it should be fixed now

**Comment by mdwalters** [comment]
@hfiguiere how does it look now?

**Pull request closed without merging**
