### PR TITLE
Add DatMan

### PR DESCRIPTION
**Pull request by SjoerdB93**
DatMan is a simple but powerful data manipulation tool developed with Libadwaita using Gnome Builder. It opens and plots two-column data files which then easily can be manipulated and transformed. Alternatively, data can be inserted and plotted using an equation. The transformed data can also be saved as .txt file for further use.

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by SjoerdB93** [comment]
Just to comment on the permissions, it does have access to the home directory. This is because I want it to be able to save edited files to arbitrary places. I save data using np.savetxt(), which doesn't work without access to home. 

I could limit access to be in the document folder only if that's preferred, but that may be confusing for the end user. Opening works great without that permission as the Filechooser uses the xdg-desktop-portal if I recall correctly. But I don't think Python otherwise has access to saving files.

**Comment by SjoerdB93** [comment]
bot, build se.sjoerd.DatMan

**Comment by barthalion** [comment]
I think you would need to wrap np.savetxt() somehow so it properly uses a portal. Unfortunately, it's not like Flatpak achieved world domination and can rig `open()` to make that happen automatically.

/merge

**Comment by SjoerdB93** [comment]
> I think you would need to wrap np.savetxt() somehow so it properly uses a portal. Unfortunately, it's not like Flatpak achieved world domination and can rig `open()` to make that happen automatically.
> 
> /merge

I've asked for help online, and if you treat the filepath as immutable and don't cut parts of them, then it actually works without home permissions. I removed the extension in the end and appended ` _edited.txt ` to the file path string. This breaks whatever kind of abstraction this portal uses for some reason. Now I no longer add this _edited part in the file and now it works without permissions. 

They'll be removed in the next build :)

**Pull request closed without merging**
