### PR TITLE
Add org.kde.bomber 

### PR DESCRIPTION
**Pull request by cho2**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of [permissions](https://invent.kde.org/packaging/flatpak-kde-applications/-/blob/master/org.kde.bomber.json#L10). 
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. 
  - I am a member of [KDE Team on Flathub](https://github.com/orgs/flathub/teams/kde/members).
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
  - KDE project owns the domain
- [x] Any additional patches or files have been submitted to the upstream projects concerned. 
  - https://invent.kde.org/games/bomber/-/merge_requests/1
  - https://invent.kde.org/games/bomber/-/merge_requests/2

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by cho2** [comment]
bot, build org.kde.bomber

**Comment by cho2** [comment]
```
flatpak run org.kde.bomber
Qt: Session management error: Could not open network socket
Failed to create OpenAL device
Failed to create OpenAL buffer: Error code 40964
Failed to create OpenAL buffer: Error code 40964
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: Tidak ada berkas atau direktori seperti itu
libGL error: failed to load driver: i965
```

**Comment by cho2** [comment]
bot, build org.kde.bomber

**Comment by cho2** [comment]
@tsdgeos

**Comment by tsdgeos** [comment]
Looks, good to me, let's finish the discussion upstream about which kind of actual oars rating we want before merging though

**Comment by cho2** [comment]
bot, build org.kde.bomber

**Comment by cho2** [comment]
bot, build org.kde.bomber

**Pull request closed without merging**
