### PR TITLE
Add com.github.dail8859.NotepadNext

### PR DESCRIPTION
**Pull request by zocker-160**
I would like to submit Notepad Next which is an open source, cross-platform reimplementation of Notepad++.

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/dail8859/NotepadNext/issues/84
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

#### additional notes

- The `--filesystem=home` permission is needed, so users can open files in the editor.
- The upstream developer @dail8859 is not only aware of me submitting NotepadNext, but he is supporting the effort and it would be great if he had write access to the new repo if this submission gets accepted. I was just helping him to get started with Flatpak.

### CODE REVIEW

**Comment by dail8859** [comment]
I am the developer of Notepad Next and fully support @zocker-160 submitting this.

> he is supporting the effort and it would be great it he had write access to the new repo if this submission gets accepted

Access for both @zocker-160 and I would be appreciated.

**Comment by zocker-160** [comment]
bot, build

**Comment by zocker-160** [comment]
bot, build com.github.dail8859.NotepadNext.yml

**Comment by hfiguiere** [comment]
bot, build com.github.dail8859.NotepadNext

**Comment by zocker-160** [comment]
looking good for me, I will test ARM build later today

Screenshot_20220417_115631

**Comment by zocker-160** [comment]
run great on Raspberry Pi to
Screenshot_20220417_140405
o

**Comment by zocker-160** [comment]
thank you very much!

**Comment by zocker-160** [comment]
thank you very much @barthalion !

**Pull request closed without merging**
