### PR TITLE
Create org.gnome.Four-in-a-row.json

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Upstream discussion: https://gitlab.gnome.org/GNOME/four-in-a-row/issues/14

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.Four-in-a-row

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.Four-in-a-row

**Comment by nedrichards** [comment]
bot, build org.gnome.Four-in-a-row

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gnome.Four-in-a-row

**Pull request closed without merging**
