### PR TITLE
Added org.gimp.GIMP.Plugin.GMic

### PR DESCRIPTION
**Pull request by hfiguiere**
DO NOT BUILD THIS YET

This is GMic, one of the most anticipated GIMP plugin.

This depend on https://github.com/flathub/org.gimp.GIMP/pull/75 being merged to build.

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.gimp.GIMP.Plugin.GMic

**Comment by hfiguiere** [comment]
bot, build org.gimp.GIMP.Plugin.GMic

**Comment by Jehan** [comment]
@dtschump Would you accept to co-maintain with @hfiguiere the flatpak for G'MIC extension in GIMP? It's always nicer if a flatpak is maintained upstream.

**Comment by dtschump** [comment]
At first glance I would say that this packaging work should be left to those who master it. I don't know Flatpack, I've never used it (and honestly I don't have the time to invest in it).
Therefore, I don't think I can do a good job of packaging G'MIC for Flatpack.
If nobody really wants to do it, I could take a look at it, but it won't be for a while!

More generally, I'm trying to get rid of G'MIC's packaging tasks, in order to devote myself to the development itself, where I'm most likely to bring added value.

**Comment by hfiguiere** [comment]
it's all good. I can manage.

**Comment by Jehan** [comment]
@dtschump Just to be clear, I was not suggesting that you take over the full task of maintaining this package. It's just always nicer when a package officially comes from upstream (like a seal of approval!). And since @hfiguiere did all the work until now, I figured he would happily continue to be the main maintainer of the flatpak, which he confirmed (I sure hope so, at least!).

**Comment by nedrichards** [comment]
The extension point for this has been merged now, right?

**Comment by hfiguiere** [comment]
Yes it has been. Otherwise the build wouldn't have gone through.

**Comment by Jehan** [comment]
Just for the record, at GIMP's, we are really looking forward being able to announce finally the possibility to install these various plug-ins. This was one of the major critics of the GIMP flatpak as many advanced users absolutely required some of these plug-ins. 🙂

**Comment by bilelmoussaoui** [comment]
bot, build org.gimp.GIMP.Plugin.GMic

**Comment by nedrichards** [comment]
bot, build org.gimp.GIMP.Plugin.GMic

**Pull request closed without merging**
