### PR TITLE
add image-optimizer

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
The appdata patch was sent upstream. Should be included in the next release.

@GijsGoudzwaard Are you interested in having push access to the new flathub repo? this will allow you to push new releases to flathub easily without having to wait for me or another maintainer to do it.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.github.gijsgoudzwaard.image-optimizer

**Comment by bilelmoussaoui** [comment]
Fails to build optipng on aarch64

**Comment by barthalion** [comment]
The problem is that opting bundles few libraries, including libpng. Passing `--with-system-libs` should fix it, although you will have to add these dependencies yourself.

**Comment by bilelmoussaoui** [comment]
@barthalion Will take care of that this evening

**Comment by bilelmoussaoui** [comment]
@barthalion Used --with-system-libs and it works without any issue. Not sure about aarch64. It doesn't require anything for me. optipng requires zlib and libpng which seems to be in the freedesktop runtime

**Comment by barthalion** [comment]
bot, build com.github.gijsgoudzwaard.image-optimizer

**Comment by bilelmoussaoui** [comment]
Builds perfectly https://flathub.org/builds/#/builders/2/builds/3346

**Comment by barthalion** [comment]
Repository has been created: https://github.com/flathub/com.github.gijsgoudzwaard.image-optimizer

Thanks!

**Pull request closed without merging**
