### PR TITLE
Create com.getmailspring.Mailspring.yml

### PR DESCRIPTION
**Pull request by prateekmedia**
Ready to merge, also you can include @thiblahute to the repository, so that if I am busy he can update the things.
https://github.com/Foundry376/Mailspring/pull/2348 is still not merged, but that's not a blocker.

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** [Github](https://github.com/Foundry376/Mailspring/issues/345#issuecomment-761738617) and [Discourse](https://community.getmailspring.com/t/flatpak-distribution-on-linux/68/5)
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by hfiguiere** [comment]
```
builddir/files/share/appdata/com.getmailspring.Mailspring.appdata.xml: FAILED:
• tag-missing           : <release> required
Validation of files failed
```

**Comment by hfiguiere** [comment]
From what I can see, the Sync engine is GPL-3.0, like the rest of the project. https://github.com/Foundry376/Mailspring-Sync/

So I don't see a licensing problem with it. IANAL.

Definitely an aarch64 would be nice given we still lack Thunderbird on that architecture,.

**Comment by nedrichards** [comment]
Yes a *number* of things have changed in the world since 2018!

**Comment by thiblahute** [comment]
fwiw I have tried to build from source but were getting problems. fmopv it would be better indeed but I don't think it is a good reason to not get it in based on the `.deb` first tbh.

**Comment by nedrichards** [comment]
@thiblahute thanks for chiming in, makes sense to me. If there's been a good faith effort then that's helpful to know.

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by prateekmedia** [comment]
@hfiguiere Can you check why the build is failing, although I have `rename-icon` line at the top, it is still failing to detect the icon.

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by hfiguiere** [comment]
Check that there is no `/app/usr`. If that's the case you are hitting  a known bug.

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Comment by prateekmedia** [comment]
bot, build com.getmailspring.Mailspring

**Pull request closed without merging**
