### PR TITLE
Add net.lutris.Lutris.Runner.Wine

### PR DESCRIPTION
**Pull request by gasinvein**
Wine build for Lutris flatpak.
~~Depends on flathub/net.lutris.Lutris#13~~

### CODE REVIEW

**Comment by gasinvein** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by gasinvein** [comment]
@LeandroStanger please don't trigger rebuild. It's not working yet.

**Comment by gasinvein** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by gasinvein** [comment]
Updated Lutris (with multilib) wasn't yet published during previous build.
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
I can not install
Captura de tela de 2019-07-07 17-20-00

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by FastOSlinux** [comment]
$ flatpak install --user https://dl.flathub.org/build-repo/5645/net.lutris.Lutris.Runner.Wine.flatpakref
erro: Can't load uri https://dl.flathub.org/build-repo/5645/net.lutris.Lutris.Runner.Wine.flatpakref: Server returned status 404: Not Found

**Comment by LeandroStanger** [comment]
flathubbot: WARNINGS
```
builddir/files/share/appdata/net.lutris.Lutris.Runner.Wine.appdata.xml: FAILED:
• tag-missing           : <update_contact> is not present
• value-missing         : <!-- Copyright [year] [name] --> is not present
```

**Comment by gasinvein** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by Saroufim** [comment]
It's still giving a 404 error.

**Comment by gasinvein** [comment]
@nedrichards @barthalion Looks like each build becomes unavailable for installation right after it's finished. Is there something wrong with the bot, or with this manifest?

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by Saroufim** [comment]
404

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by Saroufim** [comment]
Has anyone figured how to bypass the 404 error?

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
@barthalion @alexlarsson @nedrichards Could help?

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by gasinvein** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by dockerest** [comment]
`/cc @IBM`

**Comment by alexlarsson** [comment]
@barthalion, this seem to be fallout from https://github.com/flathub/buildbot/pull/7

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
Server returned status 404: Not Found
Captura de tela de 2019-07-07 17-20-00
@barthalion @alexlarsson @nedrichards Could help?

**Comment by Saroufim** [comment]
Can confirm the same error.

**Comment by barthalion** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by krashekspres** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by krashekspres** [comment]
Test build still returns 404

**Comment by barthalion** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by barthalion** [comment]
Repo itself is definitely there. I'll try to fix it tomorrow.

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by Saroufim** [comment]
Instead of a 404 I'm getting a 503 now

**Comment by barthalion** [comment]
It happens, just try again.

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by Saroufim** [comment]
Works fine now. Thanks!

**Comment by gasinvein** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by barthalion** [comment]
@gasinvein Is it ready to merge? I assume we want this also under `beta` branch?

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by gasinvein** [comment]
@barthalion I believe it is. The were no significant changes (except updates) for a long time.
> I assume we want this also under `beta` branch?

Yes, same as Lutris currently.

**Comment by gasinvein** [comment]
@barthalion Thanks!

**Comment by gasinvein** [comment]
Oh. I've received the invitation, but the repository doesn't seem to be created.

**Pull request closed without merging**
