### PR TITLE
Add ca.littlesvr.asunder

### PR DESCRIPTION
**Pull request by Eonfge**
Simple but powerful CD Ripper:
http://littlesvr.ca/asunder/index.php

### CODE REVIEW

**Comment by Eonfge** [comment]
bot, build ca.littlesvr.asunder

**Comment by nedrichards** [comment]
What does upstream think about this?

On a related note, could you send the appdata file upstream as a patch? Looks like the bugzilla is pretty active and this will help all Linux distributions and users.

I'll dig my USB CD drive out soon to test, but would appreciate if anyone else can do a functionality test as well.

**Comment by nedrichards** [comment]
Oh and for the question on `--device=all` you'd need https://github.com/flatpak/flatpak/issues/12 to be fixed.

**Comment by Eonfge** [comment]
bot, build ca.littlesvr.asunder

@nedrichards I've made an issue upstream about my packaging it for Flathub:
https://littlesvr.ca/bugs/show_bug.cgi?id=64

**Comment by Eonfge** [comment]
Looking downstream, it seems that Asunder is never directly involved with distribution packaging. In [Fedora](https://koji.fedoraproject.org/koji/packageinfo?packageID=5255), [Debian](https://packages.debian.org/sid/asunder) and [Arch](https://www.archlinux.org/packages/community/x86_64/asunder/), packaging is done by different people.

**Comment by nedrichards** [comment]
/merge

I'm happy that we've made the effort here and that the upstream author can get access whenever they want.

**Pull request closed without merging**
