### PR TITLE
add de.rwth aachen.ient.rd plot

### PR DESCRIPTION
**Pull request by nolyn**

### CODE REVIEW

**Comment by nolyn** [comment]
bot, build de.rwth_aachen.ient.RDPlot

**Comment by nolyn** [comment]
this is the continuation of PR #563

**Comment by nolyn** [comment]
bot, build de.rwth_aachen.ient.RDPlot

**Comment by alexlarsson** [comment]
sorry, had to cancel the build to update buildbot
will queue a new build when updated.

**Comment by nolyn** [comment]
version doens't show correctly yet when running the app. otherwise I think its done. I'll figure out how to fix that ...
Anything else I have to do yet?

**Comment by nolyn** [comment]
bot, build de.rwth_aachen.ient.RDPlot

**Comment by nolyn** [comment]
bot, build de.rwth_aachen.ient.RDPlot

**Comment by nolyn** [comment]
bot, build de.rwth_aachen.ient.RDPlot

**Comment by nolyn** [comment]
I think its done :). Let me know if anything is missing

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/de.rwth_aachen.ient.RDPlot

**Comment by nedrichards** [comment]
@nolyn just to make you aware, there's some new features for maintainers in flathub https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

**Pull request closed without merging**
