### PR TITLE
Add org.widelands.Widelands (widelands-flatpak)

### PR DESCRIPTION
**Pull request by scx**
**Widelands** is an open source (GPLed), realtime-strategy game.
https://github.com/scx/flathub/tree/org.widelands.Widelands
https://github.com/scx/widelands-flatpak

Upstream participation request:
https://bugs.launchpad.net/widelands/+bug/1807625

See also:
https://wl.widelands.org
https://launchpad.net/widelands/build19
https://github.com/widelands/widelands

### CODE REVIEW

**Comment by scx** [comment]
Previous pull request:
https://github.com/flathub/flathub/pull/394

It was automatically closed because I have changed the branch name due to changing the Application ID.
https://github.com/scx/flathub/commit/fec8154f78c89032a38384d0c94ab277bd454ec5

Before posting a comment, make sure you are familiar with this:
 * https://github.com/flathub/flathub/pull/394#discussion_r244643903

**Comment by scx** [comment]
testbot, build org.widelands.Widelands

**Comment by nedrichards** [comment]
bot, build org.widelands.Widelands
testbot, build org.widelands.Widelands

**Comment by scx** [comment]
Builds clean: https://flathub.org/builds/#/builders/2/builds/7995

**Comment by nedrichards** [comment]
bot, build org.widelands.Widelands

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.widelands.Widelands

**Comment by nedrichards** [comment]
If there's anyone else who needs to be added to the repo, let us know

**Pull request closed without merging**
