### PR TITLE
Rename com.gitlab.JakobDev.jdAppdataEdit to  page.codeberg.JakobDev.j…

### PR DESCRIPTION
**Pull request by JakobDev**
…dAppStreamEdit

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build page.codeberg.JakobDev.jdAppStreamEdit

**Comment by barthalion** [comment]
bot, build page.codeberg.JakobDev.jdAppStreamEdit

**Comment by JakobDev** [comment]
bot, build page.codeberg.JakobDev.jdAppStreamEdit

**Comment by JakobDev** [comment]
bot, build page.codeberg.JakobDev.jdAppStreamEdit

**Comment by JakobDev** [comment]
@barthalion Thanks. The [old Repo](https://github.com/flathub/com.gitlab.JakobDev.jdAppdataEdit) has been marked as EOL, so you can archive it, when you like. Also please mark the new App ID as verified.

**Comment by barthalion** [comment]
Shouldn't you be able to verify it via website check?

**Comment by JakobDev** [comment]
No. Codeberg is not supported.

**Comment by barthalion** [comment]
I don't see why it wouldn't be? You can place a website token at `jakobdev.codeberg.page/.well-known/.....`.

**Comment by JakobDev** [comment]
This does not work
grafik
Even when, it would be a bit complicated to create a own repo which publishes a Website just for verification.

**Pull request closed without merging**
