### PR TITLE
Add com.termius.Termius

### PR DESCRIPTION
**Pull request by x80486**
- [ ] Contact Terminus folks to see if it's OK to publish the application in Flathub
- [ ] Check the "local" terminal issues/integration
- [ ] Ask about the URL

### CODE REVIEW

**Comment by x80486** [comment]
bot build com.terminus.Terminus

**Comment by x80486** [comment]
bot, build com.termius.Termius

**Comment by x80486** [comment]
bot, build com.termius.Termius :angry:

**Comment by LeandroStanger** [comment]
bot, build com.termius.Termius

**Comment by x80486** [comment]
I didn't know there was already a `Pull Request` for this application :man_shrugging:

**Pull request closed without merging**
