### PR TITLE
Add org.kde.massif-visualizer (Massif Visualizer)

### PR DESCRIPTION
**Pull request by Siosm**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build org.kde.massif-visualizer

**Comment by Siosm** [comment]
Mention @tsdgeos as he currently is a maintainer of several KDE related packages on Flathub.

**Comment by Siosm** [comment]
bot, build org.kde.massif-visualizer

**Comment by Siosm** [comment]
bot, build org.kde.massif-visualizer

**Comment by Siosm** [comment]
bot, build org.kde.massif-visualizer

**Comment by tsdgeos** [comment]
needs the --cups thing for the print dialog

**Comment by Siosm** [comment]
bot, build org.kde.massif-visualizer

**Comment by tsdgeos** [comment]
Looks good to me :)

**Comment by Siosm** [comment]
@nedrichards Can you add the KDE team as maintainers for this application? Thanks!

**Pull request closed without merging**
