### PR TITLE
Add org.gimp.GIMP.Plugin.Resynthesizer

### PR DESCRIPTION
**Pull request by hfiguiere**
This is the first GIMP Plugin to be packaged for GIMP as a flatpak. It was requested in https://github.com/flathub/org.gimp.GIMP/issues/22 

This is waiting on changes in https://github.com/flathub/org.gimp.GIMP/pull/75 to land as it is still being discussed with the maintainer of the Flatpak.
Once it lands this should be able to be built.

### CODE REVIEW

**Comment by bootchk** [comment]
If I can help, please ask (I maintain Resynthesizer.)

Note that there is one branch of Resynthesizer that should have no dependencies on Gtk.  If that would help, I can hasten moving that branch into the release branch.  Currently, one control widget/plugin of Resynthesizer is written in C using Gtk and thus depends on Gtk.  In the branch, the control widget/plugin is written in Python using the GUI facilities of PyGimp.  That should make Resynthesizer dependent on Gimp, but not on Gtk (I think? maybe it still depends on PyGtk)

Possibly related, the plan is that Gimp 3 plugins will use GObject Introspection.  I suppose such plugins could still be flatpaked and still have a dependency on libgimp, which I think is the main problem you are fixing?

**Comment by hfiguiere** [comment]
Currently it's only blocked by the changes in the GIMP 2.10.x Flatpak that need to land in order to build, nothing else. Gtk is absolutely not a problem here, the extension is built against whatever GIMP uses. (it all build and work locally here)

I'd love to have you on board to help maintain the flatpak. It's mostly a matter updating when there is a new release. We try as much as possible to involve upstream.

As for GIMP 3, I don't know yet how things will be, but I doubt they'll be a problem if the plugin uses Gtk3.

**Comment by hfiguiere** [comment]
In my opinion, I think Python make things more complicated here.

**Comment by hfiguiere** [comment]
I'll make a PR for the patch I did to the build system to allow flexibility in the path to install.

**Comment by hfiguiere** [comment]
bot, build org.gimp.GIMP.Plugin.Resynthesizer

**Comment by hfiguiere** [comment]
I was too optimistic it seems. Need to wait a little bit more for the right GIMP flatpak to be available.

**Comment by hfiguiere** [comment]
bot, build org.gimp.GIMP.Plugin.Resynthesizer

**Comment by hfiguiere** [comment]
bot, build org.gimp.GIMP.Plugin.Resynthesizer

**Comment by Jehan** [comment]
@bootchk Would you accept to co-maintain the flatpak for Resynthesizer with @hfiguiere ? It's better to have redundancy and double-better for a flatpak to be also maintained by the code upstream. :-)

**Comment by bootchk** [comment]
@Jehan  Yes.

A little background/history: I have maintained resynthesizer for almost ten years.  But  I should have ported it long ago to be under the Gimp.org umbrella or to a GEGL plugin.  Flatpaking resynthesizer delays that. I do think it is good that the flatpak machinery for third-party plugins exists.

**Comment by hfiguiere** [comment]
I'm not sure I understand how it delays it.

**Comment by bootchk** [comment]
I am just saying that if Resynthesizer is flatpaked, I have no motivation
to move it down the chain into a bonafide library or a GEGL plugin.  I
should have said "changes my priorities."

**Comment by bootchk** [comment]
I am just saying that if Resynthesizer is flatpaked, I have no motivation to move it down the chain into a bonafide library or a GEGL plugin.  I should have said "changes my priorities."

**Comment by bilelmoussaoui** [comment]
bot, build org.gimp.GIMP.Plugin.Resynthesizer

**Comment by nedrichards** [comment]
bot, build org.gimp.GIMP.Plugin.Resynthesizer

**Pull request closed without merging**
