### PR TITLE
Add org.freedesktop.LinuxAudio.Lv2Plugins.AVLDrums

### PR DESCRIPTION
**Pull request by hfiguiere**
This is a DrumKit LV2 plugin for Linux audio apps. With Ardour #831 almost ready, this would be an important plugin.

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Lv2Plugins.AVLDrums

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Lv2Plugins.AVLDrums

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Lv2Plugins.AVLDrums

**Comment by Bleuzen** [comment]
Hi @hfiguiere, thank you for pushing all of this pro audio software to flathub.
Just leaving this here as an idea: would be nice if you can package Geonkick, which is also a nice plugin for making drums. It sometimes fits better than AVLDrums, so it would be useful too.
https://github.com/iurie-sw/geonkick

**Comment by hfiguiere** [comment]
I'll add to the list

**Comment by hfiguiere** [comment]
> Just leaving this here as an idea: would be nice if you can package Geonkick,

See #1542

**Pull request closed without merging**
