### PR TITLE
JetBrains DataGrip

### PR DESCRIPTION
**Pull request by x80486**
Flatpak for **JetBrains DataGrip**.

~~DataGrip uses various methods to store the datasource passwords, being the _native keychain_ the default one. I'm getting a warning message stating that the application cannot access it – and while there is another option to use KeePass (automatically integrated), I would really like to get the default one to work.~~

~~Other than that, I didn't find anything else.~~

This is effectively working with datasources/databases:

- Started as Docker containers
- Installed natively in the operating system
- Located in cloud computing services – read: in AWS or GCP

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build com.jetbrains.DataGrip

**Comment by x80486** [comment]
OK, this is working now with `Freedesktop` :tada:

I can't use version `18.08` for now, otherwise there would be an annoying warning at start-up: `External file changes sync may be slow: File watcher failed to start`...and while not strictly needed, I think it's best not to have it at all :wink:

@AsciiWolf, can you do the `bot build` stuff again?

**Comment by x80486** [comment]
@AsciiWolf, is there anything else that needs to be done for this one? I haven't had any comments, so I'm assuming it's OK.

**Comment by AsciiWolf** [comment]
@x80486 Sorry, I am not sure. Try asking @TingPing or @barthalion. ;-)

**Comment by nedrichards** [comment]
bot, build com.jetbrains.DataGrip

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.jetbrains.DataGrip

**Pull request closed without merging**
