### PR TITLE
Move jdMinecraftLauncher to Codeberg

### PR DESCRIPTION
**Pull request by JakobDev**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

This replaces [com.gitlab.JakobDev.jdMinecraftLauncher](https://github.com/flathub/com.gitlab.JakobDev.jdMinecraftLauncher)

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build page.codeberg.JakobDev.jdMinecraftLauncher

**Comment by JakobDev** [comment]
@barthalion  You need to merge the PR which adds the Exception first

**Comment by barthalion** [comment]
I've merged another PR there today. Can you resolve conflicts?

**Comment by JakobDev** [comment]
The conflicts are now resolved

**Comment by JakobDev** [comment]
bot, build page.codeberg.JakobDev.jdMinecraftLauncher

**Comment by JakobDev** [comment]
Looks like the new exception is currently not in cache. Let's wait a few Minutes.

**Comment by JakobDev** [comment]
bot, build page.codeberg.JakobDev.jdMinecraftLauncher

**Comment by JakobDev** [comment]
@barthalion You can archive [com.gitlab.JakobDev.jdMinecraftLauncher](https://github.com/flathub/com.gitlab.JakobDev.jdMinecraftLauncher) now

**Pull request closed without merging**
