### PR TITLE
Add org.sonic3air.Sonic3AIR

### PR DESCRIPTION
**Pull request by Kekun**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

Personal notes:
- I am not an upstream contributor but I contacted the author and they were very supportive, as it all was private conversations I don't have a link to share.
- The author own the domain.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
bot, build org.sonic3air.Sonic3AIR

**Comment by Eukaryot** [comment]
I am the original author of the Sonic 3 A.I.R. project, and owner of the sonic3air.org domain.
I'd like to confirm that this submission does indeed have my support.

**Comment by Kekun** [comment]
The game has been built for x86 or x86-64, IDK, but it certainly won't work on any other arches. I need to disable the other ones.

**Comment by nedrichards** [comment]
bot, build org.sonic3air.Sonic3AIR

**Comment by barthalion** [comment]
@Kekun @Eukaryot App description *needs* to state that users should buy the game before the app is useful to them.

**Pull request closed without merging**
