### PR TITLE
Added io.github.dida_code.lettreplacer

### PR DESCRIPTION
**Pull request by dida-code**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build io.github.dida_code.lettreplacer

**Comment by dida-code** [comment]
the application works

**Comment by dida-code** [comment]
What is the next step for hosting app to flathub store?

**Comment by dida-code** [comment]
I didn't make myself clear in the description. These are the following characters: "æ": "ć", "Æ": "Ć", "": "ž", "": "Ž", "": "š", "": "Š",  "è": "č", "È": "Č", "ð": "đ". Some characters are not showing clearly in this answer

**Comment by dida-code** [comment]
https://raw.githubusercontent.com/dida-code/lettreplacer/main/data/resources/Screenshot2.png

**Pull request closed without merging**
