### PR TITLE
add quickaccess

### PR DESCRIPTION
**Pull request by g-fb**
https://gitlab.com/g-fb/quickaccess

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.georgefb.quickaccess

**Comment by g-fb** [comment]
bot, build com.georgefb.quickaccess

**Comment by nedrichards** [comment]
```
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
```

you need `--device=dri` to get hardware acceleration for Qt.

**Comment by nedrichards** [comment]
@g-fb you don't want the id to have .desktop as well: https://gitlab.com/g-fb/quickaccess/blob/master/src/com.georgefb.quickaccess.appdata.xml#L3 and then add the launchable referencing that as mentioned in https://github.com/flathub/flathub/wiki/AppData-Guidelines

Also, it's kinda hard to launch it yourself (especially on a disto where qdbus isn't as popular), I know you mention that a little in the description but it's always worth being as helpful as possible up front.

**Comment by g-fb** [comment]
> you need --device=dri to get hardware acceleration for Qt

done

> you don't want the id to have .desktop
> add the launchable referencing that

done

> Also, it's kinda hard to launch it yourself (especially on a disto where qdbus isn't as popular), I know you mention that a little in the description but it's always worth being as helpful as possible up front.

I updated both the readme and appdata description with more information on how to use and examples for qdbus and dbus-send.

**Comment by nedrichards** [comment]
bot, build com.georgefb.quickaccess

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.georgefb.quickaccess

**Pull request closed without merging**
