### PR TITLE
Add com.jetbrains.PyCharm.Packages.mysqlclient

### PR DESCRIPTION
**Pull request by FakeShemp**
`mysqlclient` requires a MySQL client and its headers to be present at install from `pip`, which doesn't work in a standard sandbox. This package includes both the client and the `mysqlclient` python module.

### CODE REVIEW

**Comment by FakeShemp** [comment]
bot, build com.jetbrains.PyCharm.Packages.mysqlclient

**Comment by FakeShemp** [comment]
bot, build com.jetbrains.PyCharm.Packages.mysqlclient

**Comment by FakeShemp** [comment]
bot, build com.jetbrains.PyCharm.Packages.mysqlclient

**Comment by FakeShemp** [comment]
bot, build com.jetbrains.PyCharm.Packages.mysqlclient

**Comment by FakeShemp** [comment]
bot, build com.jetbrains.PyCharm.Packages.mysqlclient

**Comment by FakeShemp** [comment]
bot, build com.jetbrains.PyCharm.Packages.mysqlclient

**Comment by barthalion** [comment]
We really need generic `Tools` extension point for SDKs. This isn't PyCharm specific.

**Comment by FakeShemp** [comment]
@barthalion Very true. Any Python IDE would benefit from this. Do you have any more detailed thoughts of how this should be handled? Were you thinking of something like `org.freedesktop.Sdk.Extension.Tools` as a base extension, which acts as a mediator for things like this package.

**Comment by p1u3o** [comment]
> We really need generic `Tools` extension point for SDKs. This isn't PyCharm specific.

Agreed, there's already
https://github.com/flathub/io.dbeaver.DBeaverCommunity.Client.mariadb
and
https://github.com/flathub/io.dbeaver.DBeaverCommunity.Client.pgsql

**Pull request closed without merging**
