### PR TITLE
Add io.github.baldeuniversel.am-okay

### PR DESCRIPTION
**Pull request by baldeuniversel**
### Please confirm your submission meets all the criteria

- [X] Please describe your application briefly.
- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I have [built][build] and tested the submission locally.
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by guihkx** [comment]
Looks much better now!

Now please just change the title of this pull request to `Add io.github.baldeuniversel.am-okay`, and wait for reviewers. :)

**Comment by baldeuniversel** [comment]
> Looks much better now!
> 
> Now please just change the title of this pull request to `Add io.github.baldeuniversel.am-okay`, and wait for reviews from the Flathub team. :)

Done !

**Comment by guihkx** [comment]
Not quite, you forgot the `Add` at the beginning.

**Comment by baldeuniversel** [comment]
> Not quite, you forgot the `Add` at the beginning.

Done ! 🤔

**Comment by baldeuniversel** [comment]
Hi ! @guihkx @bbhtt 

Why do I get this error message every day at 1 hour plus minus 42 minutes?

Screenshot_20240316-015112_GitHub_1

**Comment by guihkx** [comment]
Go to [this page](https://github.com/baldeuniversel/flathub/actions/workflows/stale.yml) and [disable](https://i.imgur.com/c1L51PK.png) the workflow.

**Comment by baldeuniversel** [comment]
> Go to [this page](https://github.com/baldeuniversel/flathub/actions/workflows/stale.yml) and [disable](https://i.imgur.com/c1L51PK.png) the workflow.

Thanks .

**Pull request closed without merging**
