### PR TITLE
Add com.empesol.timetracker.TimeTracker

### PR DESCRIPTION
**Pull request by TadejLogar**
I would like to rename the app id from `com.empesol.timetracker` (https://github.com/flathub/com.empesol.timetracker, https://github.com/flathub/flathub/pull/5767) to `com.empesol.timetracker.TimeTracker` to enable app verification on a subdomain https://timetracker.empesol.com/.

- [X] Please describe the application briefly.
Track your daily work hours and monitor the progress of Jira tasks. Time Tracker app can publish this data to Ridango Bamboo HR and Ridango Jira.
- [X] The domain used for the application ID is [controlled by the application developer(s)][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read and followed all the [Submission requirements][reqs] and the [Submission guide][reqs2].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor to the project.

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[reqs2]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
Why do you need to do that on the subdomain?

**Comment by hfiguiere** [comment]
this was merged 4 days ago.

**Comment by bbhtt** [comment]
Why didn't you say this in the previous submission? You checked "I have control over the domain.." in the PR checklist and it is very ckearly written what you must have control over.

**Comment by TadejLogar** [comment]
At the time of the previous submission, I didn’t understand how app verification is done. I have control over the main domain. For apps within the same category/group, I think it makes more sense to split them onto their own subdomain, with the initial lowercase parts of the app id representing the location and the final camel-cased part representing the app name.

**Comment by hfiguiere** [comment]
> For apps within the same category/group, I think it makes more sense to split them onto their own subdomain

No. For verification purpose this is totally unecessary.

**Comment by TadejLogar** [comment]
Yeah, for verification isn’t necessary, and I can put the files on the main domain. From an organizational perspective, though, it seems more appropriate to use a new name. But you’re the right person to say what the best way is.

**Comment by hfiguiere** [comment]
whatever you do on your website is your problem.

**Comment by bbhtt** [comment]
> For apps within the same category/group, I think it makes more sense to split them onto their own subdomain, with the initial lowercase parts 

You can have multiple tokens in `empesol.com/.well-known/org.flathub.VerifiedApps.txt` for multiple apps. It does not need to be in a subdomain.

See for example gnome.org/.well-known/org.flathub.VerifiedApps.txt


It doesn't matter as long as you have control over the main domain.

**Pull request closed without merging**
