### PR TITLE
Add firefox-nightly

### PR DESCRIPTION
**Pull request by proletarius101**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

Not sure if it's still possible to publish the firefox nightly into flathub, as the release version is provided by the upstream. If no, I'll just build it somewhere else for my personal use.

## TODO

- [ ] ~https://github.com/flathub/flatpak-external-data-checker/blob/master/src/checkers/firefoxchecker.py~ (dropped: https://github.com/flathub/flatpak-external-data-checker/commit/e2028f7bf48038b8a7e8086dec93ffd8de5f3299#diff-c9e96561a7b681f3c04177c362792e29e78987bf2503cf0ec372b6dd750f9691)

### CODE REVIEW

**Comment by proletarius101** [comment]
bot, build org.mozilla.FirefoxNightly

**Comment by proletarius101** [comment]
bot, build org.mozilla.FirefoxNightly

**Comment by proletarius101** [comment]
Hmm, it's [supposed](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) to validate by `appstream-util validate-relax` but actually `appstream-util validate`?

**Comment by proletarius101** [comment]
bot, build org.mozilla.FirefoxNightly

**Comment by barthalion** [comment]
This is not going to be accepted – you should figure out with Mozilla folks how to do it right from their own pipeline. I have started some work at https://phabricator.services.mozilla.com/D72615 but I'm unlikely to get back to it this month.

**Comment by proletarius101** [comment]
@barthalion Sorry but, are they even related? This is firefox-nightly, while your link is about not to fix the flatpak app id?

**Comment by barthalion** [comment]
Obviously it is related, as we likely want to re-use assets such as appdata from the existing pipeline via environment variables.

**Comment by proletarius101** [comment]
@barthalion You mean after the reusing assets issue is solved, they will provide a Nightly channel, which doesn't exist currently?

**Comment by barthalion** [comment]
There's some background here: https://bugzilla.mozilla.org/show_bug.cgi?id=163336

The general idea is to re-use at least [the desktop file](https://hg.mozilla.org/mozilla-central/file/tip/taskcluster/docker/firefox-flatpak/org.mozilla.firefox.desktop) across Firefox release channels that would end up on Flathub. As it would be preferred to have them co-installable, they do need to be published under different IDs. (The common use case is to run Nightly/Developer Edition for testing/development, so having to do `flatpak run --branch=` instead of separate launcher is not ideal).

I initially planned to re-use the same appdata file but that would look bad on the website, so each channel would need its own file. Feel free to poke me on IRC/Matrix if you would like to take this over from me.

**Comment by barthalion** [comment]
Also yes, if all of this is sorted out, Mozilla will handle pushing to Flathub from their own CI/CD.

**Pull request closed without merging**
