### PR TITLE
Build manifest for net.sourceforge.TuxFootball

### PR DESCRIPTION
**Pull request by cosimoc**
Based on the Freedesktop 1.6 SDK.

### CODE REVIEW

**Comment by Barthalion** [comment]
Can you update the appdata to include the project license?

**Comment by cosimoc** [comment]
Done

**Comment by Barthalion** [comment]
Scheduled a build: https://flathub.org/builds/#/buildrequests/1748?redirect_to_build=true

**Comment by Barthalion** [comment]
Another one with autoreconf: https://flathub.org/builds/#/builders/5/builds/316

**Comment by Barthalion** [comment]
It worked! https://flathub.org/builds/#/builders/5/builds/317

**Comment by cosimoc** [comment]
Similar to what I commented in #24, there was a `rm-configure: true` missing, so the `autogen.sh` script was not actually getting called. I pushed a few commits to avoid copying `config.guess` and `config.sub`.

**Comment by Barthalion** [comment]
Merged, thanks!

**Pull request closed without merging**
