### PR TITLE
Add im.bernard.Funkcio

### PR DESCRIPTION
**Pull request by wbernard**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Screenshot url in AppStream metadata is incorrect. The correct one should be `https://raw.githubusercontent.com/wbernard/funkcio/main/data/screenshots/screenshot.png`.

**Comment by wbernard** [comment]
Does it have to be `https://raw.githubusercontent.com...`? Just fixing the branch name should work, no?

**Comment by LeandroStanger** [comment]
bot, build im.bernard.Funkcio

**Comment by wbernard** [comment]
Tried the manifest locally with flatpak-builder, should be all fixed now.

**Comment by nedrichards** [comment]
bot, build im.bernard.Funkcio

**Comment by nedrichards** [comment]
You've got the height and width specifications inverted in the appdata ;-) once that's fixed you can kick off a rebuild as well.

**Comment by wbernard** [comment]
bot, build im.bernard.Funkcio

**Pull request closed without merging**
