### PR TITLE
add scrcpy

### PR DESCRIPTION
**Pull request by nexustar**
It a gui app to control android device, but need to be launched from cli. not has icon etc.

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build com.Genymobile.Scrcpy

**Comment by barthalion** [comment]
Why does it need to be launched from terminal if it has GUI?

**Comment by nexustar** [comment]
> Why does it need to be launched from terminal if it has GUI?

it is like mpv,get args from terminal and show the video and control the android device in gui. Author doesn't provide appstream file or icon. Are they still necessary in this case?

**Comment by barthalion** [comment]
You still need metainfo file which can be generated with https://www.freedesktop.org/software/appstream/metainfocreator/#/ or https://bilelmoussaoui.github.io/metainfo-generator/ and add flathub.json with:

```
{
    "skip-icons-check": true
}
```

**Comment by nexustar** [comment]
bot, build com.Genymobile.Scrcpy

**Comment by nexustar** [comment]
bot, build com.Genymobile.Scrcpy

**Pull request closed without merging**
