### PR TITLE
org.freedesktop.sdk.extension.mono6

### PR DESCRIPTION
**Pull request by darkdragon-001**
Release Mono 6.x as separate package as requested in https://github.com/flathub/org.freedesktop.Sdk.Extension.mono5/pull/12#issuecomment-621085574.

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.sdk.extension.mono6

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.Sdk.Extension.mono6

**Comment by darkdragon-001** [comment]
@barthalion Could you have a look since you suggested adding mono6 as separate package?

**Comment by barthalion** [comment]
@darkdragon-001 Can you force-push a single commit adding all the files based on `new-pr` branch instead of preserving entire history of unrelated repository?

**Comment by darkdragon-001** [comment]
@barthalion done.

**Comment by barthalion** [comment]
bot, build org.freedesktop.Sdk.Extension.mono6

**Pull request closed without merging**
