### PR TITLE
Added manifest.

### PR DESCRIPTION
**Pull request by leozide**
Added https://leocad.org to flathub.

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build org.leocad.LeoCAD

**Comment by barthalion** [comment]
It looks like your app is either missing or installing appdata file under wrong name. We have some documentation on it on our wiki:

https://github.com/flathub/flathub/wiki/App-Requirements#Appstream
https://github.com/flathub/flathub/wiki/AppData-Guidelines

This is to display your application on our web page but also in GNOME Software or KDE Discover.

**Comment by barthalion** [comment]
bot, build org.leocad.LeoCAD

**Comment by barthalion** [comment]
Current appdata file uses wrong ID, it should match app-id used for the flatpak manifest.

Apart from that, it will fail validation:
```
• tag-invalid           : <metadata_license> is not valid [GPL-2.0]
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• tag-missing           : <release> required
```

`metadata_license` should be permissive license as described in [specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html).

**Comment by leozide** [comment]
Thanks for the help trying to get it working but unfortunately I missed the part about the license requirements.

**Comment by barthalion** [comment]
`metadata_license` is only about appdata, not the project itself. `project_license` is for application itself and it goes up to being proprietary if you need.

**Comment by leozide** [comment]
Oops, let me start over.

**Comment by barthalion** [comment]
No worries, sorry if I was unclear.

**Pull request closed without merging**
