### PR TITLE
Build manifest for com.tux4kids.tuxmath

### PR DESCRIPTION
**Pull request by cosimoc**
Based on the Freedesktop 1.6 SDK.

### CODE REVIEW

**Comment by Barthalion** [comment]
Scheduled a build: https://flathub.org/builds/#/buildrequests/1703?redirect_to_build=true

**Comment by cosimoc** [comment]
Pushed a commit that should fix ARM64 build failures.

**Comment by Barthalion** [comment]
Take number two: https://flathub.org/builds/#/builders/5/builds/312

**Comment by Barthalion** [comment]
Another one: https://flathub.org/builds/#/builders/5/builds/315

**Comment by Barthalion** [comment]
For some reason it's still unhappy on aarch64, but I'm not sure why. Logs: https://flathub.org/builds/#/builders/7/builds/314

**Comment by cosimoc** [comment]
@Barthalion Thanks... I think that your last commit is not necessary, and the issue is that we were missing a `rm-configure: true`. I pushed new commits in the PR.

**Comment by Barthalion** [comment]
Ah, I thought I don't have to remove it. Another take: https://flathub.org/builds/#/builders/7/builds/335

**Comment by Barthalion** [comment]
There we go. Thanks!

**Pull request closed without merging**
