### PR TITLE
add Yaru-blue-dark

### PR DESCRIPTION
**Pull request by Muqtxdir**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/ubuntu/yaru
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
This one is already on flathub

https://github.com/flathub/org.gtk.Gtk3theme.Yaru-Blue-dark

**Comment by Muqtxdir** [comment]
no this is different. **_Yaru-Blue_** part of [`Yaru-colors`](https://github.com/Jannomag/Yaru-Colors) project. All variants produced from official [`Yaru`](https://github.com/ubuntu/yaru) have lowercase after `Yaru-`

That being said, will talk with @jannomag to mark them as [EOL](https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life) to all the variants that have similar naming to avoid this conflict.

**Comment by Muqtxdir** [comment]
bot, build org.gtk.Gtk3theme.Yaru-blue-dark

**Pull request closed without merging**
