### PR TITLE
Add org.freedesktop.LinuxAudio.Plugins.Ninjas2

### PR DESCRIPTION
**Pull request by hfiguiere**
Sampler slicer LV2 and VST plugins using the new unified extension point. Several of the apps have been updated already.

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Lv2Plugins.Ninjas2

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Lv2Plugins.Ninjas2

**Comment by hfiguiere** [comment]
This plugin also has a VST. I'll see about implementing a new structure first: 
    https://github.com/flathub/org.freedesktop.LinuxAudio.BaseExtension/issues/1

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.Ninjas2

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.Ninjas2

**Comment by bilelmoussaoui** [comment]
Let me know which repos need to be archived once they have been eol'd.

/merge:19.08

**Pull request closed without merging**
