### PR TITLE
Add com.github.hughsie.appstream-glib

### PR DESCRIPTION
**Pull request by barthalion**

### CODE REVIEW

**Comment by barthalion** [comment]
FYI @hughsie

We would like to use latest appstream-util in Flathub CI for improved appdata validation. It's not technically user-facing application but I'd like you to review the manifest anyway (or raise possible issues).

**Comment by barthalion** [comment]
bot, build com.github.hughsie.appstream-glib

**Comment by hughsie** [comment]
Not org.freedesktop.AppStreamGlib? I think we used that in other places...

**Comment by barthalion** [comment]
Fair point, I see `/org/freedesktop/appstream-glib` in the code. Will rename the manifest.

**Comment by barthalion** [comment]
bot, build org.freedesktop.appstream-glib

**Comment by barthalion** [comment]
Repository has been created: https://github.com/flathub/org.freedesktop.appstream-glib

**Pull request closed without merging**
