### PR TITLE
add Numix Circle/Square(Light) icon themes

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
This PR adds:
- Numix Circle (the app icons + the base theme)
- Numix Circle Light (the app icons + the light version of the base theme)
- Numix Square (the app icons + the base theme)
- Numix Square Light (the app icons + the light version of the base theme)

The Gtk theme will be added in a different PR in 2018.

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Can anyone look at this please? :) Just because I have other apps waiting for a PR

**Comment by Barthalion** [comment]
Correct me if I'm wrong, but I thought that recent flatpak versions just mount icons from the host system, so it's not needed to provide icon themes via flatpak anymore.

**Comment by bil-elmoussaoui** [comment]
Oh yes, you're right... Didn't knew about that. The Paper icon theme should be removed from flathub then :+1:

**Comment by TingPing** [comment]
Once we have a process for app removal from flathub it can be done.

**Pull request closed without merging**
