### PR TITLE
Add org.freedesktop.LinuxAudio.Lv2Plugins.KapitonovPluginsPack

### PR DESCRIPTION
**Pull request by hfiguiere**
LV2 plugins for Guitar amps and effects

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Lv2Plugins.KapitonovPluginsPack

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Lv2Plugins.KapitonovPluginsPack

**Comment by LeandroStanger** [comment]
bot, build org.freedesktop.LinuxAudio.Lv2Plugins.KapitonovPluginsPack

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Lv2Plugins.KapitonovPluginsPack

**Pull request closed without merging**
