### PR TITLE
Add io.lbry.lbry-app

### PR DESCRIPTION
**Pull request by julianrichen**
LBRY is a free, open, and community-run digital marketplace for multimedia.
Site: https://lbry.io/
Source: https://github.com/lbryio/lbry

---

This pr adds the LBRY client via a deb file. I tried building from source with node/npm/yarn but like other flathub users mentioned, it was overly complicated.

Should [OARS](https://odrs.gnome.org/oars) tags be added to the appdata file and if so how? Content on LBRY is created by users so it _can_ contain any of the content warnings found in OARS.

What isn't subject to the content are these settings found in the app:
* "Share Diagnostic Data" is **enabled** by default
* "Show NSFW content" is **disabled** by default

Maybe OARS needs a new tag like `social-content` with None, Regulated, Unregulated? This might be better discussed on the the OARS bugtracker (if they have one).

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build io.lbry.lbry-app

**Comment by hughsie** [comment]
@nedrichards there's no OARS bugtracker per-se, I'll work on something today.

**Comment by hughsie** [comment]
@nedrichards here you go: https://github.com/hughsie/oars -- I've asked @jimmac to look at the styling and UX today as i agree it's not the most beautiful thing to use and he might have some ideas.

**Comment by julianrichen** [comment]
Thanks for taking a look into the OARS question. I guess we can wait to add them until OARS is ready to support more general applications?

Build was also successful :)
https://flathub.org/builds/#/builders/4/builds/1206

**Comment by nedrichards** [comment]
Yep, happy to wait on that.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/io.lbry.lbry-app

**Comment by hughsie** [comment]
Would https://hughsie.github.io/oars/ be good enough?

**Comment by julianrichen** [comment]
See https://github.com/hughsie/oars/issues/1 for more about general OARS options.

**Pull request closed without merging**
