### PR TITLE
Add org.gnome.Mahjongg

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
I took over https://github.com/flathub/flathub/pull/755 and added a patch to fix the appdata file.
Of course, I sent that patch upstream: https://gitlab.gnome.org/GNOME/gnome-mahjongg/merge_requests/14

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.Mahjongg

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.Mahjongg

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.Mahjongg

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.Mahjongg

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gnome.Mahjongg

**Pull request closed without merging**
