### PR TITLE
Add com.voxdsp.TempleDriver

### PR DESCRIPTION
**Pull request by BeverlyCode**
### Please confirm your submission meets all the criteria

- [A 3D video game based on Terry A. Davis] Please describe your application briefly.
- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build com.voxdsp.TempleDriver

**Comment by hfiguiere** [comment]
> > Build [121760 failed](https://buildbot.flathub.org/#/builders/6/builds/121760)
> 
> Even stranger, this one succeeded, but failed?! O_o

no it didn't

```
HEAD is now at a396f9e Update main.c
FB: Running: git lfs checkout
FB: Running: git rev-parse --verify --quiet a396f9e83e57c4113ac25f7da94f056235994258:.gitmodules
]2;flatpak-builder: Installing templedriverRunning: cc main.c glad_gl.c assets/high/alien.o assets/high/bg.o assets/high/car.o assets/high/cia.o assets/high/e1.o assets/high/e2.o assets/high/track.o assets/high/train.o assets/high/terry.o -I inc -Ofast -L/app/lib -lglfw -lasound -pthread -lm -o templedriver
FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/templedriver --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-aarch64/build/.flatpak-builder/build/templedriver-1 --bind-mount=/run/build/templedriver=/srv/buildbot/worker/build-aarch64/build/.flatpak-builder/build/templedriver-1 --build-dir=/run/build/templedriver --bind-mount=/run/ccache=/srv/buildbot/worker/build-aarch64/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1716032194 '--env=CFLAGS=-O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=80 /srv/buildbot/worker/build-aarch64/build/.flatpak-builder/rofiles/rofiles-6oMr52 /bin/sh -c 'cc main.c glad_gl.c assets/high/alien.o assets/high/bg.o assets/high/car.o assets/high/cia.o assets/high/e1.o assets/high/e2.o assets/high/track.o assets/high/train.o assets/high/terry.o -I inc -Ofast -L/app/lib -lglfw -lasound -pthread -lm -o templedriver'' on host
/usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: unknown architecture of input file `assets/high/alien.o' is incompatible with aarch64 output
/usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: unknown architecture of input file `assets/high/bg.o' is incompatible with aarch64 output
/usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: unknown architecture of input file `assets/high/car.o' is incompatible with aarch64 output
/usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: unknown architecture of input file `assets/high/cia.o' is incompatible with aarch64 output
/usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: unknown architecture of input file `assets/high/e1.o' is incompatible with aarch64 output
/usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: unknown architecture of input file `assets/high/e2.o' is incompatible with aarch64 output
/usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: unknown architecture of input file `assets/high/track.o' is incompatible with aarch64 output
/usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: unknown architecture of input file `assets/high/train.o' is incompatible with aarch64 output
/usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: unknown architecture of input file `assets/high/terry.o' is incompatible with aarch64 output
collect2: error: ld returned 1 exit status
FB: host_command_exited_cb 915126 256
```

**Comment by hfiguiere** [comment]
> It might be because it uses pre-built .o files for x86 only? If I exclude aarch maybe it will work? Is it possible to exclude aarch as a build target?

how about this time you add a build system in the project before you try to build it on flathub. Flatpak build is NOT a build system. Having to call `gcc` directly is considered a bug.

**Comment by hfiguiere** [comment]
also why using pre-built?

**Comment by hfiguiere** [comment]
```
	<project_license>GPL-2.0-only</project_license>
```

This is clearly wrong. You can't have GPL-2.0 code that require binaries like that.

**Comment by hfiguiere** [comment]
This is not done:

> Please describe your application briefly.

**Comment by bbhtt** [comment]
Yes, we do.

**Comment by bbhtt** [comment]
To figure out what an app is about when reviewing.

**Pull request closed without merging**
