### PR TITLE
Add com.github.manisandro.gImageReader-qt5 (gImageReader-qt5-flatpak)

### PR DESCRIPTION
**Pull request by scx**
**gImageReader** is a simple optical character recognition (OCR) application which acts as a frontend to the tesseract OCR engine.
https://github.com/manisandro/gImageReader
https://github.com/scx/flathub/tree/com.github.manisandro.gImageReader-qt5

See also:
https://github.com/scx/gimagereader-flatpak (Gtk+3/Qt5)
https://github.com/scx/gimagereader-flatpak/tree/qt5 (Qt5)
https://github.com/scx/gimagereader-flatpak/tree/gtk3 (Gtk+3)

### CODE REVIEW

**Comment by scx** [comment]
This app has several variants: `Gtk+3`, `Qt4`, `Qt5`. I decided to submit the `Qt5` version, because it seems to be the most polished.

**Comment by scx** [comment]
testbot, build com.github.manisandro.gImageReader-qt5

**Comment by nedrichards** [comment]
I see upstream PRs for the appdata: https://github.com/manisandro/gImageReader/pull/397 and a request to participate in flathub https://github.com/manisandro/gImageReader/issues/396

**Comment by scx** [comment]
Builds clean: https://flathub.org/builds/#/builders/2/builds/7438

**Comment by scx** [comment]
@nedrichards 

There are also patches for [QtSpell](https://github.com/manisandro/qtspell).
https://github.com/manisandro/qtspell/issues/8
https://github.com/manisandro/qtspell/pull/9

**Comment by scx** [comment]
testbot, build com.github.manisandro.gImageReader-qt5

**Pull request closed without merging**
