### PR TITLE
Adementary Theme

### PR DESCRIPTION
**Pull request by digiberk**
"Adementary is a GTK theme based on Adwaita, blended with elementary OS visual design."

### CODE REVIEW

**Comment by digiberk** [comment]
bot, build org.gtk.Gtk3theme.Adementary

**Comment by digiberk** [comment]
bot, build org.gtk.Gtk3theme.Adementary

**Comment by digiberk** [comment]
bot, build org.gtk.Gtk3theme.Adementary

**Comment by digiberk** [comment]
bot, build org.gtk.Gtk3theme.Adementary

**Comment by TingPing** [comment]
Based off the wrong branch but otherwise seems fine.

**Comment by digiberk** [comment]
> Based off the wrong branch but otherwise seems fine.

What do you mean, is this why I can't test the build?

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gtk.Gtk3theme.Adementary

**Pull request closed without merging**
