### PR TITLE
Add Kaidan

### PR DESCRIPTION
**Pull request by JBBgameich**

### CODE REVIEW

**Comment by nedrichards** [comment]
@JBBgameich is there anyone else from upstream who'd like commit rights to the repo? (I know you are!)

**Comment by nedrichards** [comment]
bot, build im.kaidan.kaidan

**Comment by JBBgameich** [comment]
It would be useful if @melvo and @lnjx could be granted commit access as well.

**Comment by LeandroStanger** [comment]
bot, build im.kaidan.kaidan

**Comment by nedrichards** [comment]
Upstream ticket to fix the OARS and version tags: https://invent.kde.org/kde/kaidan/issues/312

**Comment by JBBgameich** [comment]
I added the release metadata as a patch here for now since the discussion on how to automate this is still ongoing in KDE as far as I know.

**Comment by nedrichards** [comment]
bot, build im.kaidan.kaidan

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/im.kaidan.kaidan

**Pull request closed without merging**
