### PR TITLE
io.github.quodlibet.QuodLibet

### PR DESCRIPTION
**Pull request by fkrull**
Add [Quod Libet](https://quodlibet.readthedocs.io). See also quodlibet/quodlibet#1806.

This is based on the branch for the as-of-yet-unreleased 4.1 release. I just wanted to get this in and identify any other upstream changes that might be needed before the release.

The Makefile and readme are just for maintenance convenience. The manifest builds entirely on its own.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build io.github.quodlibet.QuodLibet

**Comment by nedrichards** [comment]
builds fine: https://flathub.org/builds/#/builders/2/builds/1721

**Comment by barthalion** [comment]
@fkrull @lazka Should someone beside you have push access to the repo?

**Comment by lazka** [comment]
@declension as well

**Comment by nedrichards** [comment]
@barthalion 
> This is based on the branch for the as-of-yet-unreleased 4.1 release. I just wanted to get this in and identify any other upstream changes that might be needed before the release.

Ideally we'd have held this until 4.1 was actually out.

**Comment by lazka** [comment]
We are already in bugfix only "freeze", so not that big of a problem.

**Comment by barthalion** [comment]
@nedrichards Woop, sorry. Fortunately upstream is involved so no bigger harm done.

**Pull request closed without merging**
