### PR TITLE
Add io.gitlab.jstest_gtk.jstest_gtk

### PR DESCRIPTION
**Pull request by Grumbel**
Flatpak manifest for https://jstest-gtk.gitlab.io/

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build io.gitlab.jstest_gtk.jstest_gtk

**Comment by nedrichards** [comment]
Given this are you sure you want this (and the expected bug reports!) on flathub:

>  Update for 2018: The /dev/input/jsX interface that jstest-gtk uses is largely obsolete. Most newer software will use /dev/input/eventX, so neither the calibration nor the remapping functionality will have any effect.

> evtest-qt is a similar piece of software that works with the new interface, however it won't be able to provide calibration or remapping either.

**Comment by Grumbel** [comment]
Yes, I am sure. The program is a little older, but the joydev interface in Linux isn't going away anytime soon and there are a few games left that still use it (e.g. Flightgear). So it still has plenty of utility, even so some of it's configuration functionality won't work together with newer SDL2/evdev based games.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/io.gitlab.jstest_gtk.jstest_gtk

**Pull request closed without merging**
