### PR TITLE
Add com.obsproject.Studio.Plugin.WebSocket

### PR DESCRIPTION
**Pull request by HugLifeTiZ**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/Palakis/obs-websocket/issues/442#issuecomment-768545929
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

This is a plugin for OBS Studio using the recently committed plugin extension point infrastructure. It's used for remotely controlling a running instance of OBS Studio by way of web applications or command line clients like [obs-cli](https://github.com/leafac/obs-cli).

The maintainer did not reply to my inquiry regarding maintainership of this repo.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by HugLifeTiZ** [comment]
bot, build com.obsproject.Studio.Plugin.WebSocket

**Comment by nedrichards** [comment]
bot, build com.obsproject.Studio.Plugin.WebSocket

**Comment by HugLifeTiZ** [comment]
```
stat: cannot stat 'builddir/*/share/app-info/xmls/com.obsproject.Studio.Plugin.WebSocket.xml.gz': No such file or directory
```

I don't know what this is telling us. Does the metainfo.xml file need to be something else?

**Comment by HugLifeTiZ** [comment]
Oh, that makes sense.

bot, build com.obsproject.Studio.Plugin.WebSocket

**Comment by HugLifeTiZ** [comment]
bot, build com.obsproject.Studio.Plugin.WebSocket

**Comment by barthalion** [comment]
bot, build com.obsproject.Studio.Plugin.WebSocket

**Pull request closed without merging**
