### PR TITLE
com.yubico.yubikey_manager

### PR DESCRIPTION
**Pull request by Lunarequest**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*
the patches used are simply to build in a flatpak using things like /app as the install dir or look for .h files in /app
[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Lunarequest** [comment]
bot, build com.yubico.yubikey_manager

**Comment by Lunarequest** [comment]
bot, build com.yubico.yubikey_manager

**Comment by Lunarequest** [comment]
bot, build com.yubico.yubikey_manager

**Comment by Lunarequest** [comment]
bot, build com.yubico.yubikey_manager

**Comment by Lunarequest** [comment]
> Has the metainfo file been submitted upstream?

Not yet. I will submit it right away

**Comment by hfiguiere** [comment]
bot, build com.yubico.yubikey_manager

**Comment by nedrichards** [comment]
So yes, other than some confirmation that this actually does what it's supposed to this lgtm.

**Comment by nedrichards** [comment]
bot, build com.yubico.yubikey_manager

**Comment by nedrichards** [comment]
So this is blocked by https://github.com/flathub/com.yubico.yubioath/issues/26 ?

**Comment by Lunarequest** [comment]
> So this is blocked by [flathub/com.yubico.yubioath#26](https://github.com/flathub/com.yubico.yubioath/issues/26) ?

pretty much

**Pull request closed without merging**
