### PR TITLE
Add build manifest for org.gnome.Recipes

### PR DESCRIPTION
**Pull request by matthiasclasen**

### CODE REVIEW

**Comment by TingPing** [comment]
Test build: https://flathub.org/builds/#/builders/5/builds/234

**Comment by Barthalion** [comment]
Uhm, we have it already: https://github.com/flathub/org.gnome.Recipes

@matthiasclasen, do you want push access there?

**Comment by matthiasclasen** [comment]
In fact, I would like to own it. Lets test our conflict resolution for when the upstream owner shows up :-)

**Comment by Barthalion** [comment]
Added you to collaborators.

**Comment by jurf** [comment]
This could actually use some discussion. Should app devs have adminiatrator access to repos? I guess it’s their right, they may want to change teams or whatever, but also there should be _some_ kind of control. Maybe a sub-admin role?

**Comment by Barthalion** [comment]
Yes, I think that one of the main goals of Flathub is letting upstream handle manifests on their own, unless it is something that requires strict security policy. If developers of the project are interested, I don't see a reason not to let them in.

What we do so far is adding authors of pull requests to collaborators – it doesn't give much more over push permission to given repository and I believe that at this point it's really enough. Down the road we should think about creating teams in the organization, but for now it seems to be overkill. We have mailing list for such discussions now, so maybe bring it up there?

For the record, Alex migrated Recipes repository from the old branch-based Flathub, so it was effectively an orphan anyway.

**Comment by matthiasclasen** [comment]
how are the roles of cllaborator and admin defined ?

**Comment by TingPing** [comment]
I don't think maintainers should have full control over a repo, it isn't like a package needs large complex teams and keeping them a collaborator level allows us to do things like disabling force push on the repo so we can enforce that the git history is accurate.

**Comment by jurf** [comment]
snimka obrazovky z 2017-05-10 19-39-41

**Comment by jurf** [comment]
@TingPing what if the dev wants collaborators, especially if it’s a big app, or they packagers that do the job for the devs?

**Comment by TingPing** [comment]
They can request we add a co-collaborator. Large projects requiring multiple people keeping it working are likely the exception.

**Comment by alexlarsson** [comment]
There are two things here. Members of the flathub *organization*, and collaborators in the repo.
Members of the organization can write to all repos, and create new ones etc.
collaborators of an individual repo can have different levels: read/write/admin, where admin == write + can add collaborators.

**Comment by Barthalion** [comment]
We can create a team named after organization or `app-id` and let them manage members. But the case really should be justified (i.e. GNOME and KDE), and at the moment, we hardly are that popular.

**Comment by alexlarsson** [comment]
@Barthalion or we could make them collaborators with admin privs?

**Comment by TingPing** [comment]
As I see it the *only* downside of granting them admin IMO is the fact they can do destructive operations on the git repo.

**Comment by jurf** [comment]
Could they be able to kick members of the Flathub org out?

**Comment by Barthalion** [comment]
No, they would be admins of repository or members of a team, not owners of the organization. But as @TingPing says, it means that they could remove the repo as well,

**Comment by jurf** [comment]
I don’t think that’s a problem though. If the devs don’t want the app on Flathub I guess they should be able to remove it, or?

**Comment by TingPing** [comment]
@jurf If we assume the worst that malicious things happen I want the git history to be there at least.

**Pull request closed without merging**
