### PR TITLE
add net.freerct.FreeRCT

### PR DESCRIPTION
**Pull request by Newbytee**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

Please note that this isn't ready to merge yet as we haven't tagged the actual 0.1 release yet. But, I'm still making this now so we can get some initial review and ensure that things go smooth on the day we want to release it.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Newbytee** [comment]
bot, build net.freerct.FreeRCT

**Comment by Newbytee** [comment]
bot, build net.freerct.FreeRCT

**Comment by Newbytee** [comment]
> Today is March 14. But:
> `<release version="0.1" date="2022-03-19">`

Yes, this is deliberate. That is the planned release date for v0.1. I'm making this PR ahead of time to ensure it's ready when we actually get to the 19th, so we can have a Flatpak available on Flathub the same day.

**Comment by Newbytee** [comment]
bot, build net.freerct.FreeRCT

**Comment by Newbytee** [comment]
@Noordfrees Do you mind if I mark this as ready now? Also, do you want to be co-maintainer of the Flathub repo?

**Comment by Noordfrees** [comment]
Good to go from my side :) 

I don't think I need maintainer access currently.

**Comment by Newbytee** [comment]
> I don't think I need maintainer access currently.

It wouldn't particularly hurt either, but sure.

**Pull request closed without merging**
