### PR TITLE
Add org.librepcb.LibrePCB

### PR DESCRIPTION
**Pull request by ubruhin**
A free EDA software to develop printed circuit boards.

Project repository: https://github.com/LibrePCB/LibrePCB
Website: https://librepcb.org/

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Looks great. It would be great to have the releases tags upstream. The app doesn't export any mimetype definitions, not sure if the application will be associated automatically to those extensions without it.

**Comment by bilelmoussaoui** [comment]
Oups didn't saw that mimetype file! my bad :p For the releases, I meant the releases tags on the appdata file. They are shown on the software centers to show the user what's the latest release, the release date and the changelog (think like PlayStore or Appstore). You could also add the developer_name tag.

**Comment by ubruhin** [comment]
Ah, I see. Unfortunately the appdata file is contained in the source repo and the tag is created, so I can no longer change it^^ But I think I can provide a patch which gets applied before building the Flatpak...

Thanks for your help - I will get back with the patch soon.

**Comment by nedrichards** [comment]
Right, once there are release tags in the appdata this is good to go.

**Comment by ubruhin** [comment]
I added the patch for the appdata xml, does it look good?

> Which functionality do you need full home access for?

LibrePCB needs a so-called "workspace", a directory where part libraries, project files etc. are created. When running LibrePCB the very first time, it asks the user where to create that workspace, while "~/LibrePCB-Workspace" is the default path.

In addition, LibrePCB creates a config file, but for that the xdg-config directory should be used so it doesn't matter where it is located.

I have to admit that I don't know yet how the "files portal" works, and if the home directory is actually needed or not. I can try to remove `--filesystem=home`, but I think I need some time to do so (I'm a bit busy at the moment, and I would need to set up a clean machine for further Flatpak testing).

**Comment by nedrichards** [comment]
bot, build org.librepcb.LibrePCB

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.librepcb.LibrePCB

**Comment by ubruhin** [comment]
Thanks! :smiley:

**Pull request closed without merging**
