### PR TITLE
Add app.xemu.Xemu

### PR DESCRIPTION
**Pull request by j8r**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/mborgerson/xemu/issues/396#issuecomment-923440133
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

--- 

Permissions explanation:
- `device=all`: keyboard, mouse, controllers
- `filesystem=host:ro`:  ROMs
- `share=network`: multi-player/internet support
- `socket=pulseaudio`: sound
- `socket=wayland`, `socket=fallback-x11`, `share=ipc`: Wayland and X11

I don't expect Xemu working on aarch64, or if it does having abysmal performance, being quite demanding on "native" x86-64 platforms (even though it uses qemu i386).

~I have picked images generated by YouTube from the official channel for the screenshots for now, since I don't have any other "official" images.~ `flatpak run org.freedesktop.appstream-glib validate app.xemu.Xemu.metainfo.xml` cannot download this (webp) images, thus marking them as invalid files.

### CODE REVIEW

**Comment by j8r** [comment]
bot, build app.xemu.xemu

**Comment by j8r** [comment]
bot, build app.xemu.Xemu

**Comment by hfiguiere** [comment]
PR should be made against the `new-pr` branch.

**Comment by j8r** [comment]
oh sorry missed that again :/

**Pull request closed without merging**
