### PR TITLE
Add psqlodbc Driver for org.kicad.KiCad

### PR DESCRIPTION
**Pull request by jmaibaum**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions.
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project.
- [x] The KiCAD project owns the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.kicad.KiCad.ODBCDriver.psqlodbc

**Comment by jmaibaum** [comment]
Local tests using a test DB for KiCad are good. I consider this extension ready to be merged.

**Comment by jmaibaum** [comment]
bot, build org.kicad.KiCad.ODBCDriver.psqlodbc

**Comment by jmaibaum** [comment]
bot, build org.kicad.KiCad.ODBCDriver.psqlodbc

**Comment by jmaibaum** [comment]
Accidentally asked the bot twice. Is it possible to cancel bot builds?

**Pull request closed without merging**
