### PR TITLE
Add com.netease.CloudMusic

### PR DESCRIPTION
**Pull request by wsgalaxy**
Netease Cloud Music is a popular music player in China.

main page:  https://music.163.com/#
download page: https://music.163.com/#/download

### CODE REVIEW

**Comment by wsgalaxy** [comment]
bot, build com.netease.CloudMusic

**Comment by wsgalaxy** [comment]
bot, build com.netease.CloudMusic

**Comment by wsgalaxy** [comment]
Run well in my computer now

**Comment by wsgalaxy** [comment]
bot, build com.netease.CloudMusic

**Comment by nedrichards** [comment]
bot, build com.netease.CloudMusic

**Comment by nedrichards** [comment]
There's a bunch of Qt SSL errors but I don't think that's your fault:
> No appenders assotiated with category qt.network.ssl
[Warning] <> QSslSocket: cannot resolve CRYPTO_num_locks

However the appdata really needs a Chinese translation since this is an app aimed at Chinese speakers. Other than that, lgtm.

**Comment by wsgalaxy** [comment]
bot, build com.netease.CloudMusic

**Comment by wsgalaxy** [comment]
bot, build com.netease.CloudMusic

**Comment by nedrichards** [comment]
@wsgalaxy On the translation, I meant like this https://github.com/flathub/org.jdownloader.JDownloader/blob/4257cfa3a3c578428d2fc7c901003c48d192d6dd/org.jdownloader.JDownloader.appdata.xml but actually putting something in the default english would be helpful too as a flathub.org website isn't localized.

**Comment by wsgalaxy** [comment]
bot, build com.netease.CloudMusic

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.netease.CloudMusic

**Comment by wsgalaxy** [comment]
@nedrichards Could you please give me the write access of the new repo(https://github.com/flathub/com.netease.CloudMusic) ?
there is some update for this software but I could not merge the pr, Thanks!

**Pull request closed without merging**
