### PR TITLE
Init com.ranfdev.Lobjur at v1.0.0

### PR DESCRIPTION
**Pull request by ranfdev**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. 
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
you deleted the content of the PR description that provide information to reviewers....

**Comment by hfiguiere** [comment]
bot, build com.ranfdev.Lobjur

**Comment by ranfdev** [comment]
> you deleted the content of the PR description that provide information to reviewers....

I've created the PR from vscode.dev, and that interface didn't pre-fill the PR description

**Comment by ranfdev** [comment]
The build fails on the archive extraction. I wonder what tar version is inside org.gnome.Platform...
The archive has been compressed with GNU tar, using
```
tar -czf com.ranfdev.Lobjur.tar.xz build/
```
Indeed, I can extract the archive without problems.

I'll try re-compressing with bsd tar or _something else_, I don't know...

**Comment by ranfdev** [comment]
bot, build com.ranfdev.Lobjur

**Comment by ranfdev** [comment]
bot, build com.ranfdev.Lobjur

**Pull request closed without merging**
