### PR TITLE
READY: add net.sourceforge.scidavis.Scidavis

### PR DESCRIPTION
**Pull request by kevinsmia1939**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://sourceforge.net/p/scidavis/discussion/708155/thread/a41121371c/
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis.Scidavis

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis.SciDAVis

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis.SciDAVis

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis.SciDAVis

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis.SciDAVis

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis.SciDAVis

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis.SciDAVis

**Comment by kevinsmia1939** [comment]
The build fail because this error, which is also the same error for Veusz https://github.com/flathub/flathub/pull/2252
sip: Unable to find file "QtCore/QtCoremod.sip"

I was unable to solve it until now. It probably the issue about how python-sip is build.

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis.SciDAVis

**Comment by hfiguiere** [comment]
bot, build net.sourceforge.scidavis

**Comment by hfiguiere** [comment]
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• tag-missing           : <release> required
Validation of files failed

**Comment by kevinsmia1939** [comment]
I'm waiting for SciDAVis dev to update, so we can use cmake.

**Comment by kevinsmia1939** [comment]
Well.. might as well send pr upstream to fix appdata

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis.SciDAVis

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis

**Comment by kevinsmia1939** [comment]
Cannot build PyQt5 on ARM.

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis

**Comment by kevinsmia1939** [comment]
bot, build net.sourceforge.scidavis

**Comment by kevinsmia1939** [comment]
This should be good now.

**Comment by barthalion** [comment]
bot, build net.sourceforge.scidavis

**Review by barthalion — APPROVED** [review]
LGTM. Can you ask Scidavis developers if they would like to have write access to the Flathub repo?

**Comment by kevinsmia1939** [comment]
> LGTM. Can you ask Scidavis developers if they would like to have write access to the Flathub repo?

I comment on the thread here, waiting for reply.
https://sourceforge.net/p/scidavis/discussion/708155/thread/a41121371c/

**Comment by kevinsmia1939** [comment]
@highperformancecoder Would you like to be a co-owner of the SciDAVis flathub repo?

**Comment by kevinsmia1939** [comment]
@MehdiChinoune Are you interest in co-owning the Flathub repo of SciDAVis? I will be maintaining it as well.

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune Are you interest in co-owning the Flathub repo of SciDAVis? I will be maintaining it as well. 

Sorry, I am not an active member.

**Comment by kevinsmia1939** [comment]
@MehdiChinoune Ok, thanks.

@barthalion I will be the maintainer for scidavis for the time being.

**Pull request closed without merging**
