### PR TITLE
add org.kde.kturtle

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by cho2** [comment]
bot, build org.kde.kturtle

**Comment by cho2** [comment]
bot, build org.kde.kturtle

**Comment by cho2** [comment]
bot, build org.kde.kturtle

**Comment by cho2** [comment]
cc @tsdgeos 
see also https://invent.kde.org/education/kturtle/-/merge_requests/4

**Comment by tsdgeos** [comment]
Looks good to me :)

**Pull request closed without merging**
