### PR TITLE
Add org.freedesktop.LinuxAudio.Plugins.Ratatouille

### PR DESCRIPTION
**Pull request by runiq**
### Please confirm your submission meets all the criteria

- [x] Please describe the application briefly.
  Ratatouille is a Neural Model loader and mixer for Linux/Windows.
- [x] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [x] I have read the and followed all the [Submission and licence requirements][reqs].
- [x] I have [built][build] and tested the submission locally.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:** https://github.com/brummer10/Ratatouille.lv2/issues/24

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.Ratatouille

**Comment by hfiguiere** [comment]
```
=================== DONE =======================
make[1]: warning: -j1 forced in submake: resetting jobserver mode.
 INFO: optimised for -march=armv8 
 INFO: build with    aarch64-unknown-linux-gnu-g++
 INFO: using         -std=c++20
Building object file ../NeuralAmpModelerCore/NAM/activations.o 
cc1plus: error: unknown value ‘armv8’ for ‘-march’
cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8.7-a armv8.8-a armv8-r armv9-a armv9.1-a armv9.2-a armv9.3-a native; did you mean ‘armv8-a’?
Assembler messages:
Error: unknown architecture `armv8'
Error: unrecognized option -march=armv8
make[1]: *** [makefile:245: ../NeuralAmpModelerCore/NAM/activations.o] Error 1
make: *** [makefile:36: Ratatouille] Error 2
FB: host_command_exited_cb 3428615 512
```

**Comment by runiq** [comment]
[Filed a bug](https://github.com/brummer10/Ratatouille.lv2/issues/25). I don't have an ARM device to test on. :(

**Comment by runiq** [comment]
[Fixed](https://github.com/runiq/org.freedesktop.LinuxAudio.Plugins.Ratatouille) in a new commit.

There are only a few commits on top of the version I'm currently packaging. Do I have permission to build from the current main branch until the ARM fix ends up in a release?

**Comment by hfiguiere** [comment]
that (a specific commit, not the branch) or you get the patch and apply it. Usually I'd do the latter.

**Comment by runiq** [comment]
Okay, I'll see if the patch applies cleanly and try that first.

**Comment by runiq** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.Ratatouille

**Comment by runiq** [comment]
Tested manually (on x86_64) and it appears to work. I loaded two NAM models, two AIDA-X models and an IR.

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.Ratatouille

**Pull request closed without merging**
