### PR TITLE
Add org.freecadweb.FreeCAD

### PR DESCRIPTION
**Pull request by hadess**
Based upon https://github.com/amigadave/freecad-flatpak

Will need more work, I don't even have enough space in my /home to be able to export the repo. But the build works, if anyone wants to try it out.

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
Since the manifest builds FreeCAD from git, wouldn't it make sense to drop Qt 4?

**Comment by hadess** [comment]
> Since the manifest builds FreeCAD from git, wouldn't it make sense to drop Qt 4 and use the KDE SDK instead?

I know nothing about FreeCAD, if you do, please feel free to make changes to the manifest. Hopefully somebody upstream and/or that knows Qt can make the necessary changes to get this working and pushed.

**Comment by hadess** [comment]
This version compiles. I think that the GUI got disabled, so there's no .desktop file installed, but it compiles!

**Comment by nedrichards** [comment]
bot, build org.freecadweb.FreeCAD

**Comment by eszlari** [comment]
I got the Qt4 to build and run.

I also try to build the Qt5 version, but can't get Pyside to compile:
https://bugreports.qt.io/browse/PYSIDE-787
Maybe @aleixpol has an idea?!

**Comment by eszlari** [comment]
> Did you make any change to the manifest file that you'd like to share?

I did not base my manifest on this one.

**Comment by hadess** [comment]
> I did not base my manifest on this one.

Could you then share it? Otherwise there's really not much of a point discussing it here.

**Comment by mdhill** [comment]
Not sure what I'm doing wrt building with Qt, but for Qt5 these changes get as far as the Pyside2 failure:
https://bugreports.qt.io/browse/PYSIDE-787
Shiboken2, Pyside2, and Pyside2-tools are in the same repo. Shiboken2 will build independently (is it _necessary_ to build it first?), and presumably Pyside2-tools will need to be added before FreeCAD.
If I comment out Pyside2 in the manifest, FreeCAD fails with the "can't find the libraries that were just built" error which seems to happen irrespective of CMake version (3.12.2 added to the manifest, 3.12.1 in org.kde.Sdk, or 3.12 in org.freedesktop.Sdk).
I'm anticipating that other missing dependencies will come to light when the FreeCAD build gets further.

[qt5.diff.txt](https://github.com/flathub/flathub/files/2388430/qt5.diff.txt)

**Comment by mdhill** [comment]
For Qt4, with no changes to the manifest, my build ends here:

[  5%] Linking CXX shared library ../../lib/libFreeCADBase.so
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot find -lmpi_cxx
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot find -lmpi
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot find -lxerces-c
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot find -lboost_filesystem
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot find -lboost_program_options
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot find -lboost_regex
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot find -lboost_signals
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot find -lboost_system
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot find -lboost_thread
collect2: error: ld returned 1 exit status
make[2]: *** [src/Base/CMakeFiles/FreeCADBase.dir/build.make:2604: lib/libFreeCADBase.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:675: src/Base/CMakeFiles/FreeCADBase.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
Error: module freecad: Child process exited with code 2

**Comment by mdhill** [comment]
Shiboken2, Pyside2, and Pyside2-tools build on Fedora (Rawhide) with this:
CC=clang CXX=clang++ python setup.py build --qmake=/usr/bin/qmake-qt5 --ignore-git --build-tests --jobs=8
...from...
https://forum.qt.io/topic/86955/pyside2-5-9-branch-qt-5-8-gcc-6-4-linux-build-failure

Translating to flatpak-builder, it doesn't work pasted into the manifest as-is (as the simple buildsystem line), but I'll play with it.

**Comment by eszlari** [comment]
Qt5-based PR: https://github.com/flathub/flathub/pull/683

**Pull request closed without merging**
