### PR TITLE
Add io.gitlab.guillermop.Counters

### PR DESCRIPTION
**Pull request by guillerm0p**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly. 
Simple counting application that lets you create counters to keep track of anything you want
- [X] The domain used for the application ID is [controlled by the application developer(s)][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read and followed all the [Submission requirements][reqs] and the [Submission guide][reqs2].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor to the project. If not, I contacted upstream developers about this submission. **Link:**

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[reqs2]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build io.gitlab.guillermop.Counters

**Comment by guillerm0p** [comment]
bot, build io.gitlab.guillermop.Counters

**Comment by guillerm0p** [comment]
bot, build io.gitlab.guillermop.Counters

**Pull request closed without merging**
