### PR TITLE
add org.gnome.ColorViewer

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
Lets see if I have super powers here:

bot, build org.gnome.ColorViewer
testbot, build org.gnome.ColorViewer

**Comment by nedrichards** [comment]
bot, build org.gnome.ColorViewer

**Comment by hughsie** [comment]
Close, but not cigar -- with this:

    flatpak run --filesystem=~/.local/share/icc:ro --filesystem=/usr/share/color/icc:ro --system-talk-name=org.freedesktop.ColorManager org.gnome.ColorViewer

I can see all the profiles in my homedir, but none of the ones installed on my host /usr/share/color/icc directory...

**Comment by nedrichards** [comment]
bot, build org.gnome.ColorViewer
testbot, build org.gnome.ColorViewer

**Comment by nedrichards** [comment]
Anyone else to add from upstream?

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gnome.ColorViewer

**Pull request closed without merging**
