### PR TITLE
Add BaseApp with qtwebkit

### PR DESCRIPTION
**Pull request by barthalion**

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build io.qt.qtwebkit.BaseApp

**Comment by TingPing** [comment]
One problem going forward will be the multiple versions of the KDE runtime with Flathub's current setup only allowing one version per repo.

**Comment by barthalion** [comment]
We don't have that many applications depending on qtwebkit though. I will submit pull requests to these using 5.9 (with update + switch to base app) when I merge this one.

**Comment by TingPing** [comment]
Should probably still make the `branch` `5.10` to be explicit though?

**Comment by barthalion** [comment]
What does it change with how buildbot works now? I'd rather say it will complain about branch mismatch or ignore it completely, pushing objects to `stable` anyway.

**Comment by TingPing** [comment]
Oh wasn't sure it actually enforced that now. This will be fine then.

**Comment by barthalion** [comment]
https://github.com/flathub/io.qt.qtwebkit.BaseApp

**Pull request closed without merging**
