### PR TITLE
Create com.github.eudaldgr.elements.json

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Yet another elementary OS application.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.github.eudaldgr.elements

**Comment by nedrichards** [comment]
Would @eudaldgr like to be added to the repo?

**Comment by bilelmoussaoui** [comment]
That would be really great. Especially that we use the elementary BaseApp which makes building elementary apps really easy. 
I will be around to make sure that everything works before it's merged of course!

**Comment by bilelmoussaoui** [comment]
Builds successfully https://flathub.org/builds/#/builders/2/builds/3085

**Comment by eudaldgr** [comment]
Hi, i don't know what repo is this, i have no problem with adding elements app to any repo, but the base branch it's in developement, and have some issues, the second release are better to do that. If you can explain better what you do here, thanks.

**Comment by TingPing** [comment]
@eudaldgr Flatpak is just a cross distro package format and Flathub is just a general repo for it.

If the application is not stable and ready for wide adoption then I agree it shouldn't be hosted here yet.

**Comment by bilelmoussaoui** [comment]
@TingPing The application is stable. I don't really understand what @eudaldgr means with the base branch at all.

**Comment by eudaldgr** [comment]
Yes, the application is stable, but i'm now interested in this package format and how i can adopt it on my github repository, thanks.

**Comment by eudaldgr** [comment]
@bilelmoussaoui i try to say that code on master branch or in the last commit on github is not finished, the code on the releases page are stable and finished. Sorry for the mistake.

**Comment by nedrichards** [comment]
OK, sounds good. Since this uses a stable release I'll add it.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.github.eudaldgr.elements

**Pull request closed without merging**
