### PR TITLE
Migrate Iotas to new app id org.gnome.World.Iotas

### PR DESCRIPTION
**Pull request by cheywood**
Hello,

This is an app id rename for [Iotas](https://flathub.org/apps/org.gnome.gitlab.cheywood.Iotas), `org.gnome.gitlab.cheywood.Iotas` as part of its move into GNOME World. Can you please help me with the timing around doing the `end-of-life-rebase` on the old id? (or do it for me?)

Many thanks :pray: :pray: 

Chris

---

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

### CODE REVIEW

**Comment by bbhtt** [comment]
Once this one is published to Flathub, you can eol-rebase the old one. See https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life


bot, build

**Comment by bbhtt** [comment]
bot, build org.gnome.World.Iotas

**Comment by cheywood** [comment]
Test build looks good :+1: 

> Once this one is published to Flathub, you can eol-rebase the old one. See https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life

Thanks. Yep I've had a read over the docs. Is a need for any delay between this one being published and creating the eol?

**Comment by cheywood** [comment]
@bbhtt if there's anything I need to do to move this forward please let me know

**Comment by bbhtt** [comment]
No, please have patience someone will merge it soon.

**Comment by cheywood** [comment]
> No, please have patience, someone will merge it soon.

Thanks that's completely fine :+1: 

I just wasn't sure if it was stuck with me :slightly_smiling_face:

**Comment by cheywood** [comment]
Thanks @barthalion and @bbhtt !

I've also put the end-of-life-rebase [in the old repo](https://github.com/flathub/org.gnome.gitlab.cheywood.Iotas). Please let me know if there's anything else I need to do (for that to be applied and the old app removed/archived) :pray:

**Comment by bbhtt** [comment]
archived the old repo.

**Pull request closed without merging**
