### PR TITLE
Add org.sugarlabs.StoryActivity

### PR DESCRIPTION
**Pull request by tchx84**
Story prompts the learner to tell a story by displaying images at random. The learner should try to tell a story that ties the images together into a comprehensive narrative.

### CODE REVIEW

**Comment by tchx84** [comment]
bot, build org.sugarlabs.StoryActivity

**Comment by tchx84** [comment]
`fatal: write error: No space left on device`, can someone tell me which is the limit? I can try to reduce the images...

**Comment by barthalion** [comment]
bot, build org.sugarlabs.StoryActivity

**Comment by barthalion** [comment]
> `fatal: write error: No space left on device`, can someone tell me which is the limit? I can try to reduce the images...

It was infrastructure issue.

**Pull request closed without merging**
