### PR TITLE
Create manifest for RStudio

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
Please don't merge this yet.

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
bot, build com.rstudio.RStudio

**Comment by LeandroStanger** [comment]
@Alexander-Wilms How is progress of the flatpak version of RStudio going?

**Comment by Alexander-Wilms** [comment]
It seemed to work fine. I don't want to maintain it, though, since I don't know R. Upstream is considering using Flatpak, Snap or AppImages, so depending on their decision, they might want to publish RStudio on Flathub: https://github.com/rstudio/rstudio/issues/3079

The latest manifest is kept here: https://github.com/Alexander-Wilms/flathub/tree/rstudio

**Comment by btreut** [comment]
I don't know, if you need to maintain it, but it would be a good starting point. I downloaded the flatpak you provided on Google and found not problems.

**Comment by Alexander-Wilms** [comment]
The RStudio version I use in the current manifest crashes when setting up the HTML GUI.

**Comment by LeandroStanger** [comment]
@bilelmoussaoui Could you keep RStudio Flatpak?

**Comment by btreut** [comment]
> The last time I tried it, the widgets in the main window didn't seem to be native Qt widgets, but were rendered as part of a web view. I'm not sure if that's correct, but since it works now, it doesn't matter anyway.

hmm, in EndlessOS the widgets look native, but in Q4OS the file dialog looks like a pure X dialog box and pops down under the main window, which is a bit strange.

> Maybe I should get the TeX Live extension merged, that would make it easier to build the RStudio flatpak.

I think that is a good idea.

**Pull request closed without merging**
