### PR TITLE
ar.com.tuxguitar

### PR DESCRIPTION
**Pull request by gabops**
TuxGuitar is a free and open-source tablature editor, which includes features such as tablature editing, score editing, and import and export of Guitar Pro gp3, gp4, and gp5 files. In addition, TuxGuitar's tablature and staff interfaces function as basic MIDI editors.

TuxGuitar's mascot and namesake is Tux, the penguin mascot of many games and programs originally designed for Linux.

The program is written in the Java programming language and is released under version 2.1 of the GNU Lesser General Public License.

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build ar.com.tuxguitar

**Comment by gabops** [comment]
Why the build has been triggered for arm and aarch64 if I only have declared i386 and x86_64 in flathub.yml?

**Comment by LeandroStanger** [comment]
@gabops Rename flathub.yml to flathub.json

**Comment by LeandroStanger** [comment]
bot, build ar.com.tuxguitar

**Comment by LeandroStanger** [comment]
@gabops Rename ID ar.com.tuxguitar to ar.com.tuxguitar.TuxGuitar

**Comment by gabops** [comment]
> ar.com.tuxguitar.TuxGuitar

Do you mean just the app-id in the manifest or any reference/file name and the branch itself?

**Comment by LeandroStanger** [comment]
@gabops Any reference, file name and the branch itself

**Pull request closed without merging**
