### PR TITLE
Add org.gnome.Games.LibretroPlugin.MAME

### PR DESCRIPTION
**Pull request by Kekun**

### CODE REVIEW

**Comment by Exalm** [comment]
Note that currently Games doesn't list MAME games because the plugin isn't very good quality. I can merge the fix for 3.36, but at least for 3.34 there's not much point in this.

**Comment by Exalm** [comment]
bot, build org.gnome.Games.LibretroPlugin.MAME

**Comment by Kekun** [comment]
Ouch, it failed *linking* the .so.

**Comment by Exalm** [comment]
The prebuilt core in RetroArch is 293mb (ouch!), and serialization seems to work with wip/exalm/n64 branch. It won't land in 3.36, but will probably in 3.38. However, there's a weird bug with controls and pausing/unpausing. Anyway, I think it's way too early for FlatHub at this point. :)

**Comment by bilelmoussaoui** [comment]
I have marked this as a WIP, please let us know when you want us to look at it again :)

**Pull request closed without merging**
