### PR TITLE
org.gnome.Totem.Devel

### PR DESCRIPTION
**Pull request by hadess**
This is a special PR. This is a stand-in PR for a `beta` branch-only repository, which should be a fork from the beta branch in the `org.gnome.Totem` repository.

The goal is to be able to ship a beta track version of the application, with 99% the same code, but a separate app-id so it appears as a separate application.

See https://github.com/flathub/flathub/issues/2821

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build org.gnome.Totem.Devel

**Comment by barthalion** [comment]
The repository has been created: https://github.com/flathub/org.gnome.Totem.Devel

**Comment by barthalion** [comment]
Note it still needs renaming the main manifest to org.gnome.Totem.Devel, but other than this, it should build fine.

**Comment by hadess** [comment]
> Note it still needs renaming the main manifest to org.gnome.Totem.Devel, but other than this, it should build fine.

I have a link to the .Devel name locally (makes cherry-picking easier), which I probably forgot to force push.

**Pull request closed without merging**
