### PR TITLE
WIP: Add com.github.tkashkin.gamehub

### PR DESCRIPTION
**Pull request by tkashkin**
[GameHub](https://github.com/tkashkin/GameHub) is a games manager/downloader/library written in Vala. It supports Steam, GOG and Humble Bundle as game sources.

I have partially got it to work, but I have some issues:
* ~~Network is weird, it works for `webkit2gtk` and `libsoup` but doesn't work for `glib`~~
* FS portals are not working for selecting directories (`GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER is not supported by GtkFileChooserNativePortal`)
* Is it not possible to run any binaries outside of sandbox? Does it mean app should install games inside sandbox to be able to run them? Or maybe this app can't be properly sandboxed at all?

### CODE REVIEW

**Comment by LeandroStanger** [comment]
@tkashkin The flatpak applications are independent of the system you will have to run all the games in the sandbox
See the Steam code as an example https://github.com/flathub/com.valvesoftware.Steam

**Comment by tkashkin** [comment]
@LeandroStanger Thanks, I'll look into it.

Can flatpak package have an optional dependencies, for example can package depend on `com.valvesoftware.Steam`, run its binaries and read its configs?

**Comment by tkashkin** [comment]
I've got network and some GOG/Humble games working in sandbox (I did use parts of https://github.com/flathub/com.valvesoftware.Steam and https://github.com/kujeger/flatpak-gog).

I'm still not sure how to implement Steam client integration. GameHub should be able to:
* (optional) Check if Steam client is installed and prompt user to install it if not
* Read user profile id from Steam config file
* Read Steam games directory to check if games are installed
* Ask Steam client to install or run game with `steam://rungameid/<appid>`

**Comment by LeandroStanger** [comment]
@alexlarsson Could you help us?

**Comment by tkashkin** [comment]
I've got large part of my GOG library running in sandbox, but unfortunately not all of them yet.
Humble Bundle games installation seems to be broken now (need to uncompress archives manually instead of relying on `file-roller`).

**Comment by TingPing** [comment]
> GameHub is a games manager/downloader/library written in Vala. It supports Steam, GOG and Humble Bundle as game sources.

Honestly, this is diving into another deep dark pit I don't think we should. Steam is an unsupportable mess that will never completely work and I don't think that should be duplicated.

**Comment by barthalion** [comment]
To expand on what TingPing said, Steam at least provides some common runtime that publishers/developers can base on, and even if that in mind, it doesn't really work. Just go through issues reported on Flathub's Steam repository – many games are broken because of dependence on external libraries or applications that are not correctly shipped. GameHub doesn't provide even that and it's impractical to add every missing dependency to Flatpak application itself.

GOG clearly states on their website that only Ubuntu is supported and even the release differs between particular games. Humble Bundle is even more trigger happy and I had even less luck with few games I bought there. Not to mention that some are 32-bit only, making it even harder to make everything work. All this results in bad user experience, especially for players with no technical Linux background and I can't see Gamehub being any different.

(On a side note, we are also considering removing Steam.)

**Comment by LeandroStanger** [comment]
@barthalion give GameHub another chance. The GameHub evolved a lot can be considered an alternative to the Lutris

**Comment by tkashkin** [comment]
@LeandroStanger, @barthalion no, I agree that flatpak is not very suitable for such project. See my comment [here](https://github.com/tkashkin/GameHub/issues/15#issuecomment-427567290).

**Pull request closed without merging**
