### PR TITLE
Add org.shotcut.Shotcut

### PR DESCRIPTION
**Pull request by eszlari**
Please don't merge this until https://github.com/flatpak/flatpak/issues/1307 is fixed.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build org.shotcut.Shotcut

**Comment by eszlari** [comment]
Now that the flatpak bug is fixed, this is ready-to-go from my side.

**Comment by nedrichards** [comment]
bot, build org.shotcut.Shotcut

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.shotcut.Shotcut

**Pull request closed without merging**
