### PR TITLE
Add Gajim plugin: omemo

### PR DESCRIPTION
**Pull request by a-andre**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build org.gajim.Gajim.Plugin.omemo

**Comment by nedrichards** [comment]
As I suspect you know, it doesn't build properly: https://flathub.org/builds/#/builders/2/builds/2694

**Comment by a-andre** [comment]
It should work now.

**Comment by nedrichards** [comment]
bot, build org.gajim.Gajim.Plugin.omemo

**Comment by nedrichards** [comment]
builds fine https://flathub.org/builds/#/builders/2/builds/5946

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gajim.Gajim.Plugin.omemo

**Pull request closed without merging**
