### PR TITLE
add org.gtk.Gtk3theme.deepin

### PR DESCRIPTION
**Pull request by lumnn**
Manifest files for deepin Gtk theme.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build org.gtk.Gtk3theme.deepin

**Comment by nedrichards** [comment]
Is there anyone else from upstream we should add to the repo when created?

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gtk.Gtk3theme.deepin

**Comment by lumnn** [comment]
@nedrichards No idea. I'm not related with the deepin themes at all. I'm just an user and wanted to share my work to get flatpak apps looking nice when using this theme.

If anyone from upstream comes, then I'm aware they'll get access.

Before that happens. Can you confirm that when theme get update I should update build files to latest version by updating the newly created repository. Are there any tests or verification related with that or everything relies entirely on me?

**Comment by TingPing** [comment]
> Can you confirm that when theme get update I should update build files to latest version by updating the newly created repository. 

Correct. Once you update it everything will automatically build and show up here: https://flathub.org/builds/#/

> Are there any tests or verification related with that or everything relies entirely on me?

Any further testing is up to you.

**Pull request closed without merging**
