### PR TITLE
Build manifest for org.armagetronad.ArmagetronAdvanced

### PR DESCRIPTION
**Pull request by cosimoc**
Based on the Freedesktop 1.6 SDK.

### CODE REVIEW

**Comment by TingPing** [comment]
Test build: https://flathub.org/builds/#/buildrequests/1581?redirect_to_build=true

**Comment by cosimoc** [comment]
Looks like something went wrong in the build configuration... Can you try to issue a test build again?

**Comment by TingPing** [comment]
Take 2: https://flathub.org/builds/#/buildrequests/1592?redirect_to_build=true

**Comment by cosimoc** [comment]
This failed on ARM64; pushed a tentative fix.

**Comment by TingPing** [comment]
Repository has been created: https://github.com/flathub/org.armagetronad.ArmagetronAdvanced

**Comment by TingPing** [comment]
Oh in the future try not to branch off of `master` that pulled in extra commits (which i removed).

**Comment by cosimoc** [comment]
Thanks, will do.

**Pull request closed without merging**
