### PR TITLE
Add org.kde.kshisen

### PR DESCRIPTION
**Pull request by travier**
### Please confirm your submission meets all the criteria

- [x] Please describe your application briefly:
    - KDE Game: https://apps.kde.org/kshisen/
- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. 
    - I'm part of the KDE Team on Flathub
- [x] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [x] Any additional patches or files have been submitted to the upstream projects concerned.
    - No patches for now

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by travier** [comment]
CC @flathub/kde

**Comment by travier** [comment]
bot, build org.kde.kshisen

**Comment by bbhtt** [comment]
Please add a patch for this.

**Comment by travier** [comment]
bot, build org.kde.kshisen

**Comment by travier** [comment]
Works for me. In the logs:

```
QIBusPlatformInputContext: invalid portal bus.
kdegames.audio: Failed to create OpenAL device
kdegames.audio: Failed to create OpenAL buffer: Error code 40964
kdegames.audio: Failed to create OpenAL buffer: Error code 40964
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
```

**Comment by travier** [comment]
bot, build org.kde.kshisen

**Comment by travier** [comment]
I've added access to pulseaudio.

**Pull request closed without merging**
