### PR TITLE
Add org.kde.itinerary

### PR DESCRIPTION
**Pull request by nicolasfella**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
  I am an upstream contributor. @vkrause is the maintainer though

- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*
 https://invent.kde.org/pim/itinerary/-/merge_requests/34

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by nicolasfella** [comment]
bot, build org.kde.itinerary

**Comment by nicolasfella** [comment]
bot, build org.kde.itinerary

**Comment by nicolasfella** [comment]
bot, build org.kde.itinerary

**Comment by nicolasfella** [comment]
The builds works in principle now.

I'd like to make sure https://invent.kde.org/pim/itinerary/-/merge_requests/33 is included before publishing, either by adding another patch or waiting for the 21.04.3 release

**Comment by hfiguiere** [comment]
Adding the patch is OK.

**Comment by nedrichards** [comment]
@flathub/kde

**Comment by tsdgeos** [comment]
Looks good to me

**Comment by cho2** [comment]
bot, build org.kde.itinerary

**Comment by nedrichards** [comment]
OK - this did get created and merged https://github.com/flathub/org.kde.itinerary and all the invitations are sent properly but I there was an error in the github action so you don't get the nice message here.

**Pull request closed without merging**
