### PR TITLE
add io.github.barryran.QtScrcpy

### PR DESCRIPTION
**Pull request by proletarius101**
Signed-off-by: proletarius101 <proletarius101@protonmail.com>

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/barry-ran/QtScrcpy/issues/740#issuecomment-1368457136
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build io.github.barryran.QtScrcpy

**Comment by barthalion** [comment]
LGTM, but I need some screenshots that it actually works. I don't own an Android smartphone.

**Comment by Eckoa** [comment]
The paths patch doesnt allow for the user to change settings in the .var folder. The paths need to be changed to point to the exported directories in the ~/.var folder

Ive also found the .sh file isnt required but the app does need to have running in the background disabled or it doesnt terminate properly on exit. This is also the case for the AUR/Binaries from the authors git. 

The only other thing is I still havent heard from the author on adding this to flathub. I was trying to avoid the users possibly going to their repo with flatpak issues when they havent approved or and dont maintain it.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/flathub/pull/3769#issuecomment-1383655261

@Eckoa, is lack of explicit confirmation a blocker?

**Comment by Eckoa** [comment]
> > [#3769 (comment)](https://github.com/flathub/flathub/pull/3769#issuecomment-1383655261)
> 
> @Eckoa, is lack of explicit confirmation a blocker?

I would say so for me at least, Im not going to risk people sending issues to the developer for a package they dont maintain and havent acknowledged. I feel that when asking directly about putting it onto flathub and getting no response thats effectively a "no" and I would much rather have permission. 

That cant stop anyone else from doing so but it wont be from me.

**Pull request closed without merging**
