### PR TITLE
Rename WolfenDoom to Wolfenstein

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
### Please confirm your submission meets all the criteria

The project has been [renamed](https://github.com/Realm667/WolfenDoom/tree/master/dist) and thus https://github.com/flathub/com.realm667.WolfenDoom_Blade_of_Agony should be EOL'd.

Wolfenstein: Blade of Agony will be released on the 30th, that's why the manifest currently references a git commit. Once a release version has been tagged I can update the manifest. The developers also plan on shipping a development version of gzdoom for now, and bundling a proper release version of gzdoom with Wolfenstein: BoA 3.1

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
  - `--device=all` for using joysticks
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/Realm667/WolfenDoom/issues/529#issuecomment-828707419 
Please add  @Talon1024 as a maintainer.
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*
  - I don't know of a way to resize the icons at build time without adding e.g. imagemagick

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
bot, build com.realm667.Wolfenstein_Blade_of_Agony

**Comment by Alexander-Wilms** [comment]
bot, build com.realm667.Wolfenstein_Blade_of_Agony

I fixed the screenshot links and added the release date, but since the date is in the future, validation will fail.

**Comment by AsciiWolf** [comment]
> "WolfenDoom - Blade of Agony" | Important: This is only meant for development and testing purposes. You are NOT ALLOWED to use material from this repository for your own projects. Important: This repository is for development and testing purposes, you are NOT ALLOWED to use the copyrighted material for your own projects without our permission!

Hmm. I wonder what is the actual project license...

**Comment by Alexander-Wilms** [comment]
According to the metainfo file, it's CC-BY-NC-SA-3.0: https://github.com/Realm667/WolfenDoom/blob/master/dist/com.realm667.Wolfenstein_Blade_of_Agony.metainfo.xml#L7

**Comment by Alexander-Wilms** [comment]
bot, build com.realm667.Wolfenstein_Blade_of_Agony

**Comment by Alexander-Wilms** [comment]
bot, build com.realm667.Wolfenstein_Blade_of_Agony

**Comment by Alexander-Wilms** [comment]
I added an EOL notice to the flathub.json of https://github.com/flathub/com.realm667.WolfenDoom_Blade_of_Agony

**Comment by Alexander-Wilms** [comment]
Thanks!

**Pull request closed without merging**
