### PR TITLE
Create com.github.bleakgrey.tootle.json

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
@bleakgrey Would you be interested in having write access to the Flathub repository too? That would be awesome if you can keep the package up to date!

### CODE REVIEW

**Comment by bleakgrey** [comment]
Yeah, that would be awesome :)

**Comment by barthalion** [comment]
We've been actually talking about it on Mastodon a month ago (IIRC). Nice to see it here!

@cagatay-y, would you like to help too, as someone who flatpaked it "first"?

**Comment by barthalion** [comment]
bot, build com.github.bleakgrey.tootle

**Comment by bilelmoussaoui** [comment]
@barthalion My Flatpak package wasn't based on anyone's package. But yeah, some help will be appreciated of course.

**Comment by bilelmoussaoui** [comment]
Builds perfectly https://flathub.org/builds/#/builders/2/builds/3211

**Comment by nedrichards** [comment]
As an elementary app, does this need to be patched to require the elementary theme? Or are you OK with how it looks under other themes?

**Comment by bleakgrey** [comment]
I don't think it should require eOS theme even though it was designed for it. It looks decent enough without it, thanks to GTK. There will be some problems with missing icons though, but this is the part to be fixed on my side.

**Comment by nedrichards** [comment]
OK, that's fine - developer's choice!

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.github.bleakgrey.tootle

**Comment by cagatay-y** [comment]
Not sure what I can help with but sure, I would like to.

**Pull request closed without merging**
