### PR TITLE
Add org.freedesktop.Sdk.Extension.php84

### PR DESCRIPTION
**Pull request by Lctrs**
### Please confirm your submission meets all the criteria

- [x] Please describe the application briefly. Just PHP 8.4 for freedesktop 24.08 SDK.
- [x] The domain used for the application ID is [controlled by the application developer(s)][appid-domain] and the [application id guidelines][appid] are followed.
- [x] I have read and followed all the [Submission requirements][reqs] and the [Submission guide][reqs2].
- [ ] I have [built][build] and tested the submission locally.
- [ ] I am an author/developer/upstream contributor to the project. If not, I contacted upstream developers about this submission. **Link:**

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[reqs2]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by Lctrs** [comment]
bot, build

**Comment by Lctrs** [comment]
bot, build org.freedesktop.Sdk.Extension.php84

**Comment by xanscale** [comment]
@Lctrs seams more a legacy of the past, from 7.0 (2015) seams more organized and PhpStorm has language level.

creating new extension without maintain it and deprecating the old one seams much useless, if we need multiple versions we should maintain it.

i just ask to evalutate it

**Comment by Lctrs** [comment]
bot, build org.freedesktop.Sdk.Extension.php84

**Pull request closed without merging**
