### PR TITLE
Add org.kde.ktouch

### PR DESCRIPTION
**Pull request by sebasgo**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build org.kde.ktouch

**Comment by nedrichards** [comment]
We should remove the skip-appstream-check which is intended as a transition method for apps and fix the issues upstream, we can apply patches to the build here before dropping them with the next release.

**Comment by barthalion** [comment]
bot, build org.kde.ktouch

**Comment by sebasgo** [comment]
> We should remove the skip-appstream-check which is intended as a transition method for apps and fix the issues upstream, we can apply patches to the build here before dropping them with the next release.

This more difficult as it may seem. To make the appstream file pass validation, we must fill the `<releases>` tag. This not so easy to achieve for repos part of the KDE Apps bundle. They are released automatically (roughly once per month). There is infrastructure to update the version number of the apps themselves, but nothing to add release information to the appstream file.

I can fix this in the flathup repo, but the proper upstream fix may take a while.

**Comment by sebasgo** [comment]
bot, build org.kde.ktouch

**Comment by barthalion** [comment]
Downstream patch works. We agreed on skipping appdata checks for existing KDE apps because of my poor communication on introducing the validation, but it's hard requirement for anything new.

**Comment by barthalion** [comment]
Repository has been created: https://github.com/flathub/org.kde.ktouch

Thanks!

**Pull request closed without merging**
