### PR TITLE
Initial package: Mupen64plus

### PR DESCRIPTION
**Pull request by wberrier**

### CODE REVIEW

**Comment by wberrier** [comment]
Ah, just found a post from @TingPing:

https://blog.tingping.se/2017/10/31/flatpaked-emulators.html

Maybe this work has been done already.  I launch mupen64plus from kodi, so I don't mind if it doesn't have a UI.

**Comment by wberrier** [comment]
Upstream inquiry for flatpak:

https://github.com/mupen64plus/mupen64plus-user-issues/issues/707

**Comment by wberrier** [comment]
And I should send the appdata file upstream...

**Comment by barthalion** [comment]
So does it ship with UI or not?

**Comment by wberrier** [comment]
This package doesn't ship with a UI, but is runnable from the command line.

**Comment by barthalion** [comment]
It has to provide some frontend to be accepted to Flathub.

**Comment by wberrier** [comment]
Ah, I see.  I can look into that.

**Comment by wberrier** [comment]
Sent appdata upstream: https://github.com/mupen64plus/mupen64plus-ui-console/pull/49

**Pull request closed without merging**
