### PR TITLE
xyz.eclipium.TetraSwap

### PR DESCRIPTION
**Pull request by SpeedCode210**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
You shouldn't be check source code (or build artificats) into this repository.

**Comment by SpeedCode210** [comment]
So, what am I supposed to pull to the repository ?

**Comment by hfiguiere** [comment]
In the documentation you acknowledge having read:
https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

> Add your app’s manifest to the branch, commit it and push the commit

**Comment by hfiguiere** [comment]
the manifest pull sources or build artifacts from where they are published by upstream.

**Comment by SpeedCode210** [comment]
Okay, so I must recreate a pull request with only the manifest ?

**Comment by hfiguiere** [comment]
and eventually a few extra bits like mandatory appstream and .desktop, when they are missing, or patches.

**Pull request closed without merging**
