### PR TITLE
Add io.github.sigmasd.stimulator

### PR DESCRIPTION
**Pull request by sigmaSd**
### Please confirm your submission meets all the criteria

- [ x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ x] My pull request follows the instructions at [App Submission][submission].
- [ x] I have [built][build] and tested the submission locally.
- [ x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x ] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by sigmaSd** [comment]
This is a rename of https://flathub.org/apps/io.github.sigmasd.nosleep

**Comment by sigmaSd** [comment]
I can submit endoflife for the original one after this one is merged.

**Comment by sigmaSd** [comment]
bot, build io.github.sigmasd.stimulator

**Comment by sigmaSd** [comment]
bot, build io.github.sigmasd.stimulator

**Comment by barthalion** [comment]
bot, build io.github.sigmasd.stimulator

**Pull request closed without merging**
