### PR TITLE
Add Cockatrice

### PR DESCRIPTION
**Pull request by subpop**
Cockatrice is an open-source multi-platform supported program for playing tabletop card games over a network. The program's server design prevents any kind of client modifications to gain an unfair advantage in a game. The client also has a built in single-player mode where you can create decks
without being connected to a server.

~This PR is dependent on [flathub/shared-modules#7](https://github.com/flathub/shared-modules/pull/7)~

### CODE REVIEW

**Comment by TingPing** [comment]
Test build: https://flathub.org/builds/#/buildrequests/2205?redirect_to_build=true

**Comment by subpop** [comment]
I fixed the invalid `shared-modules` submodule target.

**Comment by TingPing** [comment]
https://flathub.org/builds/#/builders/1/builds/391

**Comment by Barthalion** [comment]
Another try: https://flathub.org/builds/#/builders/1/builds/609

**Comment by Barthalion** [comment]
Merged with some minor changes, thanks!

**Pull request closed without merging**
