### PR TITLE
Add net.sourceforge.Fillets

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build net.sourceforge.Fillets

**Comment by nedrichards** [comment]
bot, build net.sourceforge.Fillets

**Comment by nedrichards** [comment]
Is there a reason you don't just give the appdata and desktop files the app-id name? (and modify the id element in the appdata appropriately)

Also, I assume that all of this stuff was sent upstream - but it's dormant (given the 2011 release date)

**Comment by AsciiWolf** [comment]
You're right, I have fixed the app-name.

Regarding the upstream, desktop/icon files are from Fedora (under CC0-1.0 license), appdata.xml is written by me, but as you said - upstream is quite dead and the last release is from 2011, so I didn't try to upstream the metadata.

**Comment by AsciiWolf** [comment]
bot, build net.sourceforge.Fillets

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/net.sourceforge.Fillets

**Pull request closed without merging**
