### PR TITLE
Add io.conduktor.Conduktor manifest

### PR DESCRIPTION
**Pull request by Eonfge**
This might take a bit more introduction: Some months ago, I asked the makers of [Conduktor](https://www.conduktor.io/) if they were interested in putting their application on Flathub. They were certainly interested, and they would look into it with their full release.

last week they published 2.0, and I figured it would be nice to give it myself a shot. Now I want to show them the power of Flathub, and the easy of updates and Java bundling it will bring them.

_Don't approve please until they've commented on the package. This is a generous attempt of me to get them to support Flathub natively._

### CODE REVIEW

**Comment by Eonfge** [comment]
bot, build io.conduktor.Conduktor

**Comment by Eonfge** [comment]
bot, build io.conduktor.Conduktor

**Comment by Eonfge** [comment]
bot, build io.conduktor.Conduktor

@bilelmoussaoui Upstream reacted enthusiastic, so I asked them to contact Flathub and to greenlight the package once they feel comfortable doing so.

**Comment by bilelmoussaoui** [comment]
> 
> @bilelmoussaoui Upstream reacted enthusiastic, so I asked them to contact Flathub and to greenlight the package once they feel comfortable doing so. I also explained the basic of maintaining the package, so I hope that they would like to do so themselves.

Perfect, thanks for reaching out to them. We will merge it once the upstream developers chime in

**Comment by Eonfge** [comment]
bot, build io.conduktor.Conduktor

**Comment by Eonfge** [comment]
bot, build io.conduktor.Conduktor

**Comment by Eonfge** [comment]
bot, build io.conduktor.Conduktor

**Comment by Eonfge** [comment]
bot, build io.conduktor.Conduktor

**Comment by Eonfge** [comment]
bot, build io.conduktor.Conduktor

**Comment by Eonfge** [comment]
bot, build io.conduktor.Conduktor

**Pull request closed without merging**
