### PR TITLE
Added net.sourceforge.Hugin

### PR DESCRIPTION
**Pull request by hfiguiere**
TODO:

- [x] fix the build - missing source
- [x] talk to upstream
- [x] update runtime to 20.08 (build crashes doing so at the moment
- [x] test the whole workflow

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build net.sourceforge.Hugin

**Comment by hfiguiere** [comment]
bot, build net.sourceforge.Hugin

**Comment by hfiguiere** [comment]
bot, build net.sourceforge.Hugin

**Comment by hfiguiere** [comment]
Appdata patch submitted https://bugs.launchpad.net/hugin/+bug/1907917

**Comment by hfiguiere** [comment]
I had mistakenly deleted exiftool in the cleanup phase.

**Comment by hfiguiere** [comment]
bot, build net.sourceforge.Hugin

**Comment by hfiguiere** [comment]
Back to draft, I need to address a couple of things.

**Comment by nedrichards** [comment]
bot, build net.sourceforge.Hugin

**Comment by hfiguiere** [comment]
(I was missing the other .desktop entries, it's now addressed)

**Comment by barthalion** [comment]
/merge

As usually, please poke us if someone from upstream wants to help out.

**Comment by PopoutApps** [comment]
I don't know what I've done here (:

**Pull request closed without merging**
