### PR TITLE
Add Freedoom Phase 2 manifest

### PR DESCRIPTION
**Pull request by Alexander-Wilms**

### CODE REVIEW

**Comment by Barthalion** [comment]
Test build: https://flathub.org/builds/#/builders/1/builds/648

**Comment by Barthalion** [comment]
Merged, thanks.

**Comment by Alexander-Wilms** [comment]
Thanks. The aarch64 build failed, though: Option parsing failed: Unknown option --delete-build-dirs

**Comment by Barthalion** [comment]
The faulty builder has been disabled for now. I restarted the build.

**Pull request closed without merging**
