### PR TITLE
Add org.sugarlabs.MathHurdler

### PR DESCRIPTION
**Pull request by SudoSu-bham**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly.
   game designed to help teach children math in accordance with the Common Core standard for fourth grade students.

- [X] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read the and followed all the [Submission and licence requirements][reqs].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:**

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by SudoSu-bham** [comment]
cc @tchx84
Separating the port patch into `monitors.patch` and `port.patch` was causing the patch to fail, therefore I have used a single `port.patch` file.

**Comment by tchx84** [comment]
> cc @tchx84 Separating the port patch into `monitors.patch` and `port.patch` was causing the patch to fail, therefore I have used a single `port.patch` file.

The splitting is not the issue, please make sure to prepare these patches correctly and update

**Comment by hfiguiere** [comment]
bot, build org.sugarlabs.MathHurdler

**Comment by SudoSu-bham** [comment]
> The splitting is not the issue, please make sure to prepare these patches correctly and update

I have separated the patches in my [local repo](https://github.com/SudoSu-bham/org.sugarlabs.MathHurdler) may you please review it, it is not working as expected.

This is the warning I am getting, when I try to run `flatpak-builder --user --install --force-clean build-dir org.sugarlabs.MathHurdler.json`
```
HEAD is now at 6762e69 fix: Stop activity button (#17)
Applying patch mathhurdler-port.patch
patching file math_hurdlerActivity.py
Applying patch mathhurdler-info.patch
patching file activity/activity.info
Applying patch mathhurdler-monitors.patch
patching file math_hurdlerActivity.py
Hunk #1 FAILED at 14.
Hunk #2 succeeded at 27 (offset -1 lines).
1 out of 2 hunks FAILED -- saving rejects to file math_hurdlerActivity.py.rej
Error: module MathHurdler: Child process exited with code 1
```

**Pull request closed without merging**
