### PR TITLE
It.dotslashplay.little big adventure 2

### PR DESCRIPTION
**Pull request by bam80**

### CODE REVIEW

**Comment by bam80** [comment]
bot, build it.dotslashplay.little-big-adventure-2

**Comment by bam80** [comment]
bot, build it.dotslashplay.little-big-adventure-2

**Comment by nedrichards** [comment]
This can't be hosted on flathub. You can absolutely host the recipe yourself and help other users to be able to run the game from within a flatpak but we can't put an out of the box version of this on the website because it relies upon purchasing the game separately.

> <p>INSTALLATION:</p>
>     <ul>
>       <li>This is a Linux installer for GOG's Windows distribution of the game. So before continue, please purchase the game in official store from the link below.
>         After purchasing, you will be able to download "OFFLINE BACKUP GAME INSTALLER" for Windows: "setup_lba2_2.1.0.8.exe" from your Games page: www.gog.com/account.</li>
>       <li>Download the installer to the following new directory in your home directory (creating symbolic link to this location will work also):</li>
>     </ul>
>     <p>.local/share/flatpak/extra-data/022492f7b4d1a40c12e7fe9416cd17130f6a1dc26f75ac23fe0bfa63d5ea1c55/</p>
>     <ul>
>       <li>Install the application</li>
>     </ul>
> 
>     <p>To toggle fullscreen mode, press Alt+Enter.</p>
> 
>     <p>NOTE: This installer is not verified by, affiliated with, or supported neither by GOG sp. z o.o. nor Didier Chanfray SARL.
>       If you appreciate my work, please consider donation. Thanks!</p>
>   </description>

**Comment by bam80** [comment]
> we can't put an out of the box version of this on the website because it relies upon purchasing the game separately

Ok I already kinda humbled it wont be hosted, but is there any written rule on this restriction?

**Comment by barthalion** [comment]
We always expect some visible dialog window, but it still would be a bad UI to get an app from store like GNOME Software just to see window telling "you need to buy this there".

**Comment by bam80** [comment]
@barthalion my question was about formal written rule describing restriction you are talking about.
So that people wouldn't waste their time in the future making PRs like this..

**Pull request closed without merging**
