### PR TITLE
Add org.gimp.GIMP.Plugin.LiquidRescale

### PR DESCRIPTION
**Pull request by hfiguiere**
This is the LiquidRescale GIMP plugin.

It needs https://github.com/flathub/org.gimp.GIMP/pull/75 to build.

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.gimp.GIMP.Plugin.LiquidRescale

**Comment by hfiguiere** [comment]
bot, build org.gimp.GIMP.Plugin.LiquidRescale

**Comment by bilelmoussaoui** [comment]
bot, build org.gimp.GIMP.Plugin.LiquidRescale

**Comment by nedrichards** [comment]
bot, build org.gimp.GIMP.Plugin.LiquidRescale

**Pull request closed without merging**
