### PR TITLE
Add com.rabbit_company.passky

### PR DESCRIPTION
**Pull request by zigazajc007**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by zigazajc007** [comment]
bot, build com.rabbit_company.passky

**Comment by zigazajc007** [comment]
bot, build com.rabbit_company.passky

**Comment by zigazajc007** [comment]
When I execute:
`flatpak install --user https://dl.flathub.org/build-repo/79206/com.rabbit_company.passky.flatpakref`
I get a warning:
`Warning: Not exporting file com.rabbit_company.passky.appdata.xml of unsupported type.`
but installation is completed successfully.

I have performed:
`appstream-util validate-relax --nonet com.rabbit_company.passky.appdata.xml`
and it returned:
`com.rabbit_company.passky.appdata.xml: OK`

So appdata seems to be valid.

Is this a problem or it's normal?

**Comment by zigazajc007** [comment]
Both running `flatpak run com.rabbit_company.passky` and opening Passky thru applications works for me.

In the previous PR, someone tried to install it, but it doesn't open. Can someone test that?

Thanks

**Comment by nedrichards** [comment]
Works for me locally now. However you should add the --device=dri finish-arg to enable GPU acceleration and silence a bunch of warnings. Looks like there may be a dbus address you're trying to connect to that isn't allowlisted as well.

I'll have a look at the appdata issue as well when I have a moment.

**Comment by zigazajc007** [comment]
bot, build com.rabbit_company.passky

**Comment by zigazajc007** [comment]
https://docs.flatpak.org/en/latest/sandbox-permissions.html

I can see that access to d-bus is not recommended, so if the application just works I should just ignore this error and not give permission to Electron.

**Comment by zigazajc007** [comment]
bot, build com.rabbit_company.passky

**Comment by zigazajc007** [comment]
bot, build com.rabbit_company.passky

**Comment by zigazajc007** [comment]
Build [81363](https://flathub.org/builds/#/builders/32/builds/81363) had invalid xml for appdata, so the bot is now trying to build it but it can't. Can someone stop this build?

**Comment by hfiguiere** [comment]
> `Warning: Not exporting file com.rabbit_company.passky.appdata.xml of unsupported type.`

You can really ignore that issue. It's a recent "regression" that is being addressed.

**Comment by hfiguiere** [comment]
> I can see that access to d-bus is not recommended, so if the application just works I should just ignore this error and not give permission to Electron.

You can enable access to DBus names as needed. It allow whole access to the bus that is discouraged (there are a few case where it would be needed)

**Comment by zigazajc007** [comment]
> > I can see that access to d-bus is not recommended, so if the application just works I should just ignore this error and not give permission to Electron.
> 
> You can enable access to DBus names as needed. It allow whole access to the bus that is discouraged (there are a few case where it would be needed)

How can I get DBus name from this:
`[3:0312/181359.440532:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`

**Comment by zigazajc007** [comment]
> > > I can see that access to d-bus is not recommended, so if the application just works I should just ignore this error and not give permission to Electron.
> > 
> > 
> > You can enable access to DBus names as needed. It allow whole access to the bus that is discouraged (there are a few case where it would be needed)
> 
> How can I get DBus name from this: `[3:0312/181359.440532:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`

I mean, to be honest, it's not needed. It would be better if I use as less permissions as possible. And application works great even without DBus permission.

**Comment by zigazajc007** [comment]
Another question. I have now moved appdata.xml file from app/share/appdata to app/share/metainfo based on https://freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location

It says:
`AppStream tools scan the /usr/share/appdata/ path for legacy compatibility as well. It should not be used anymore by new software though, even on older Linux distributions (like RHEL 7 and Ubuntu 16.04 LTS) the metainfo path is well supported. Support for the legacy path will likely be dropped completely with a future AppStream 1.0 release.`

Flathub buildbot did provide me with an error:
`Error loading AppData file: AppData file /app/share/appdata/com.rabbit_company.passky.appdata.xml was not valid`

Should I move appdata.xml file back to /app/share/appdata folder even tho it's deprecated?

**Comment by hfiguiere** [comment]
just ignore the error. As I mentioned it's a new "regression".

technically if it is in `metainfo` it should be `metainfo.xml` but this is not an error in our setup. It's still quite flexible.

**Comment by hfiguiere** [comment]
> I mean, to be honest, it's not needed. It would be better if I use as less permissions as possible. And application works great even without DBus permission.

This is your call. 

I was just giving option to balance feature (access to dbus) and security (limit what is available). `--log-session-bus` and `--log-system-bus` passed to `flatpak run` allow checking what's happening if you need to and determining which name should be allowed.

**Comment by zigazajc007** [comment]
bot, build com.rabbit_company.passky

**Comment by zigazajc007** [comment]
bot, build com.rabbit_company.passky

**Comment by zigazajc007** [comment]
image

Screenshots in Store are not showing. I think it might be a reason, that I didn't specify height and width for images. So this next build would probably fix that. If not, I don't know what would be the reason.

**Comment by zigazajc007** [comment]
> image
> 
> Screenshots in Store are not showing. I think it might be a reason, that I didn't specify height and width for images. So this next build would probably fix that. If not, I don't know what would be the reason.

Didn't work.

**Comment by hfiguiere** [comment]
I don't expect the screenshot to work locally in locally installed packages.

And I don't recommend putting the sizes, but if they end up not match the build will fail.

**Comment by zigazajc007** [comment]
bot, build com.rabbit_company.passky

**Comment by zigazajc007** [comment]
I have tested the build and it seems to be working great. Can someone try on their system just to be sure?

Thanks

**Pull request closed without merging**
