### PR TITLE
Build manifest for net.sourceforge.torcs

### PR DESCRIPTION
**Pull request by cosimoc**
Based on the Freedesktop 1.6 SDK.

### CODE REVIEW

**Comment by Barthalion** [comment]
Test build: https://flathub.org/builds/#/buildrequests/1413?redirect_to_build=true

**Comment by cosimoc** [comment]
Test build failed because I forgot to actually add the shared-modules submodule here, which I now fixed.

**Comment by Barthalion** [comment]
Here's another one: https://flathub.org/builds/#/builders/5/builds/256

**Comment by cosimoc** [comment]
Pushed another commit that should fix the ARM64 build failure.

**Comment by Barthalion** [comment]
https://flathub.org/builds/#/buildrequests/1442?redirect_to_build=true

**Comment by cosimoc** [comment]
Pushed one more ARM64 fix, hopefully that will do it.

**Comment by Barthalion** [comment]
Merged [here](https://github.com/flathub/net.sourceforge.torcs), thanks!

**Pull request closed without merging**
