### PR TITLE
Add org.clawsmail.Claws

### PR DESCRIPTION
**Pull request by karras**

### CODE REVIEW

**Comment by nedrichards** [comment]
Build failed as you're not exporting an appdata file with the app-id but aside from that it built well:

https://flathub.org/builds/#/builders/2/builds/1263

**Comment by karras** [comment]
Thanks for the feedback! They're actually available in the sources but not shipped:

http://git.claws-mail.org/?p=claws.git;a=tree;f=appdata;hb=HEAD

I'll check if I can integrate them into the build process.

**Comment by nedrichards** [comment]
Awesome. that appdata file should ideally have more info in it to pass flathub review as well. Particularly release tags and [OARS metadata](http://hughsie.github.io/oars). It'd be great if you could get that into the upstream version.

**Comment by barthalion** [comment]
Has upstream been made aware of this pull request or that's completely "downstream" initiative?

**Comment by karras** [comment]
@barthalion I asked the dev team if they would be interested in maintaining it on their own or if I can go ahead before I opened the PR:

http://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=4020

**Comment by barthalion** [comment]
:+1:

**Comment by nedrichards** [comment]
Upstream aren't interested but they're happy to proceed if @karras wants to maintain. There's still the fixes above to do if they wish.

**Comment by barthalion** [comment]
I'm closing it due to inactivity – but please re-open it or resubmit as new pull request if you would like to see it merged in the future.

**Pull request closed without merging**
