### PR TITLE
Add com.calibre_ebook.calibre

### PR DESCRIPTION
**Pull request by ghisvail**

### CODE REVIEW

**Comment by ghisvail** [comment]
capture d ecran de 2018-09-08 08-05-01

**Comment by AsciiWolf** [comment]
bot, build com.calibre_ebook.calibre

**Comment by barthalion** [comment]
Were the desktop and appdata files submitted upstream though?

**Comment by ghisvail** [comment]
> I don't mind binary builds as the author often forks libraries, which breaks Calibre in subtle ways if "original" code is used.

Yeah, I am aware of the challenges on the Debian packaging side.

> Were the desktop and appdata files submitted upstream though?

Upstream *generates* its own desktop and appdata files from the build system in the source distribution.

Not sure mine are of interest then.

**Comment by barthalion** [comment]
Whoa, I didn't know. Looks good then, I'll merge it today.

**Comment by nedrichards** [comment]
Would be good to help upstream improve the quality of the appdata anyway, but fine.

**Comment by barthalion** [comment]
Repository has been created. Thanks!

**Pull request closed without merging**
