### PR TITLE
Add org.kde.filelight (Filelight)

### PR DESCRIPTION
**Pull request by Siosm**
Initial import from https://invent.kde.org/packaging/flatpak-kde-applications

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build org.kde.filelight

**Comment by Siosm** [comment]
Updated with a patch also sent upstream: https://invent.kde.org/utilities/filelight/-/merge_requests/2

**Comment by bilelmoussaoui** [comment]
bot, build org.kde.filelight

**Comment by bilelmoussaoui** [comment]
It seems to complain about 
```
libEGL warning: wayland-egl: could not open /dev/dri/card0 (No such file or directory)
```
Adding `--device=dri` to finish-args should fix this

**Comment by Siosm** [comment]
Mention @tsdgeos as he currently is a maintainer of several KDE related packages on Flathub.

**Comment by Siosm** [comment]
Updated to add `device-dri`

**Comment by Siosm** [comment]
bot, build org.kde.filelight

**Comment by tsdgeos** [comment]
I'm a bit concern about this, i mean the default view is kind of not that useful, the app gets confused by the filesystem hiding done by flatpak, on the other hand if you only want info of your home, i guess it's useful, but it's defenitely worse than "the actual" filelight

**Comment by Siosm** [comment]
I agree. There is work to do to make the app more Flatpak aware.

**Comment by Siosm** [comment]
This need the `awaiting-changes` label.

**Pull request closed without merging**
