### PR TITLE
Add com.humatarayici.od

### PR DESCRIPTION
**Pull request by VastSea0**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly.
Hüma Browser is a web browser developed by prioritising user freedom, transparency, and originality. It is an open source, freedom and privacy-oriented experimental web browser.

- [X] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read the and followed all the [Submission and licence requirements][reqs].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:** https://github.com/VastSea0/Huma

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build om.humatarayici.od

**Comment by bbhtt** [comment]
bot, build com.humatarayici.od

**Comment by bbhtt** [comment]
```
install: cannot stat 'metadata/huma-launcher.sh': No such file or directory
```

**Comment by VastSea0** [comment]
@bbhtt  I resolved the errors that occurred and sent the commit again.

**Comment by bbhtt** [comment]
bot, build com.humatarayici.od

**Comment by bbhtt** [comment]
bot, build com.humatarayici.od

**Comment by bbhtt** [comment]
Does this not have any English localisation?

**Comment by VastSea0** [comment]
> Does this not have any English localisation?

There will be no soon with a few languages ​​will be compiled soon

**Comment by bbhtt** [comment]
Then maybe we should wait for that? Not having any English localisation means most of the people using Flathub won't be able to use it.

**Comment by VastSea0** [comment]
> Then maybe we should wait for that? Not having any English localisation means most of the people using Flathub won't be able to use it.
ok it can be better i'm already working on a better version i was planning to compile it with Turkish and English language by default. i'll send the commit again with that update

**Comment by VastSea0** [comment]
@bbhtt I released the new version and I updated the repo and now we can build it again

**Comment by bbhtt** [comment]
Can you put the icon desktop file and metainfo file somewhere upstream https://github.com/Huma-Browser/browser ? These are not specific to Flatpak.

**Comment by VastSea0** [comment]
> Can you put the icon desktop file and metainfo file somewhere upstream https://github.com/Huma-Browser/browser ? These are not specific to Flatpak.

I sent the commit that keeps files in different repo

**Comment by bbhtt** [comment]
bot, build om.humatarayici.od

**Comment by bbhtt** [comment]
bot, build com.humatarayici.od

**Comment by bbhtt** [comment]
there are some appstream related errors, oars missing and invalid date format.

See https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#oars-information and https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#release

**Comment by VastSea0** [comment]
Thanks I didn't realize I solved it

**Comment by bbhtt** [comment]
bot, build com.humatarayici.od

**Comment by VastSea0** [comment]
When it will be published on flathub.org

**Comment by bbhtt** [comment]
When it is merged into a new repo. See the FAQ https://docs.flathub.org/docs/for-app-authors/submission#faq on how the process works.

**Pull request closed without merging**
