### PR TITLE
Switch pull request template to check list

### PR DESCRIPTION
**Pull request by barthalion**

### CODE REVIEW

**Comment by barthalion** [comment]
I'm not sure if it's possible to preview it in diff view so pasting it here instead:

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributible by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

**Comment by TheEvilSkeleton** [comment]
> [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**

If we have contacted upstream developers but they don't reply, what happens then; can we create a flatpak for the program or not?

**Comment by bilelmoussaoui** [comment]
> > [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
> 
> If we have contacted upstream developers but they don't reply, what happens then; can we create a flatpak for the program or not?

The flatpak is already created by you submitting the manifest ;) being published on Flathub is different though and is handled per case basis

**Comment by nedrichards** [comment]
lgtm! and thanks for improving!

And yes, to follow up on what bilal said, anyone can create any flatpak they like and host their own repo. If you want to use flathub and you're not the upstream developer of the software then it's on a case by case basis. This isn't a new policy (it's been there from the beginning!) we're just trying to make it a more obvious part of the submission flow.

**Pull request merged**
