### PR TITLE
add kubectl

### PR DESCRIPTION
**Pull request by brokenpip3**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.  **Link:** https://github.com/kubernetes/kubectl/issues/1057
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by brokenpip3** [comment]
bot, build io.kubernetes.kubectl

**Comment by hfiguiere** [comment]
I failed to undestand the benefit of this flatpak

Also you use an x86_64 binary to make an aarch64 package.

There is no appstream file, icon or desktop entry.

**Comment by brokenpip3** [comment]
First of all thanks for the review

> I failed to undestand the benefit of this flatpak

There is no way right now to install the kubectl binaries using flatpak. Are the cli applications outside the scope of flathub?

> Also you use an x86_64 binary to make an aarch64 package.

Sorry, firts time of doing a flatpak package, where is the manifest entry where I specified that this is a `aarch64` package?

> There is no appstream file, icon or desktop entry.

Let me create the appstream file, for the icon/desktop-entry are those necessary since we are talking about a cli application?

Thanks!

**Comment by brokenpip3** [comment]
bot, build io.kubernetes.kubectl

**Comment by hfiguiere** [comment]
> > I failed to undestand the benefit of this flatpak
> 
> There is no way right now to install the kubectl binaries using flatpak. Are the cli applications outside the scope of flathub?

And still I don't see any benefit.

> > Also you use an x86_64 binary to make an aarch64 package.
> 
> Sorry, firts time of doing a flatpak package, where is the manifest entry where I specified that this is a `aarch64` package? How I can specify a matrix build for the 2 different architecture? I was not able to find examples about the cross-compiling

It's in the documentation you acknowledged having write. There is no cross-compiling.

> > There is no appstream file, icon or desktop entry.
> 
> Let me create the appstream file, for the icon/desktop-entry are those necessary since we are talking about a cli application?

Yes they are necessary, at least the appstream file.

**Review by hfiguiere — CHANGES_REQUESTED** [review]
The appstream file needs to be installed.

It will also not validate.

**Pull request closed without merging**
