### PR TITLE
Add com.jetbrains.CLion

### PR DESCRIPTION
**Pull request by Steveice10**
Initially based on the [PyCharm Community Edition](https://github.com/flathub/com.jetbrains.PyCharm-Community) flatpak, but modified to download the app as external data.

### CODE REVIEW

**Comment by Steveice10** [comment]
Dropping this due to sandbox limitations.

**Comment by aiamuzz** [comment]
hmmmmm ... would have been nice to have it working as a flatpak 
:(

**Comment by Steveice10** [comment]
Feel free to pick it up if you want. Potential problems include how libraries and tools installed on the host won't be in the usual /usr directories in CLion, which could be problematic for some build setups.

**Comment by aiamuzz** [comment]
@Steveice10  ... i wish ... unfortunately not a techie ... wish someone could pick it up !!!

**Pull request closed without merging**
