### PR TITLE
add org.kde.kig

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by cho2** [comment]
bot, build org.kde.kig

**Comment by cho2** [comment]
bot, build org.kde.kig

**Comment by cho2** [comment]
cc @tsdgeos. 
See also https://invent.kde.org/education/kig/-/merge_requests/2

**Comment by tsdgeos** [comment]
Looks good to me :)

**Comment by bilelmoussaoui** [comment]
Now that I remember, we might have missed adding `@flathub/kde` to some of the lately merged KDE apps.  Let me know if you notice any missing ones and will take care of that.

**Pull request closed without merging**
