### PR TITLE
Add Max Control

### PR DESCRIPTION
**Pull request by janbrummer**

### CODE REVIEW

**Comment by janbrummer** [comment]
bot, build org.tabos.maxcontrol

**Comment by janbrummer** [comment]
bot, build org.tabos.maxcontrol

**Comment by barthalion** [comment]
```

**Comment by barthalion** [comment]
```
~ $ flatpak run org.tabos.maxcontrol
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

It misses some `--talk-name` or `--own-name`. You can pass `--log-session-bus` or `--log-system-bus` to check what names exactly you need. Even with `--socket=session-bus` it fails with `No cubes detected` message though.

**Comment by janbrummer** [comment]
Do you own a maxcube? Otherwise it will not work.

**Comment by barthalion** [comment]
I don't. It would be nice to have that error printed in GUI rather than terminal.

**Comment by janbrummer** [comment]
Yeah maybe, but i didn't expect someone to install a UI for controlling Max!Cube devices without the necessary hardware.

**Comment by janbrummer** [comment]
Is this a stopper?

**Comment by bilelmoussaoui** [comment]
As it's already mentioned on the project description I think we can merge this for now but it would be nice to have a message displayed on the UI in the future.

**Comment by bilelmoussaoui** [comment]
Repository has been created: https://github.com/flathub/org.tabos.maxcontrol


Thanks!

**Pull request closed without merging**
