### PR TITLE
Added io.github.tcobbs.LDView

### PR DESCRIPTION
**Pull request by hfiguiere**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/tcobbs/ldview/issues/55
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge). **I follow the rules set**
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* 
  - MIME change https://github.com/tcobbs/ldview/pull/56
  - AppStream https://github.com/tcobbs/ldview/pull/57

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build io.github.tcobbs.LDView

**Comment by hfiguiere** [comment]
bot, build io.github.tcobbs.LDView

**Comment by hfiguiere** [comment]
Disabled on aarch64 because GLES.

See upstream https://github.com/tcobbs/ldview/issues/58

**Comment by hfiguiere** [comment]
bot, build io.github.tcobbs.LDView

**Comment by nedrichards** [comment]
Nice! There's nothing wrong here, I just want to give it a little while for upstream's linux maintainer to decide on their possible involvement.

**Comment by hfiguiere** [comment]
We are still working on the GLES build issue, which is not a blocker either. The other two PR have been merged.

**Comment by nedrichards** [comment]
/merge @pbartfai 

you can ignore this invitation if you don't want it!

**Pull request closed without merging**
