### PR TITLE
Add com.grangerhub.Tremulous

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
`Error: module tremulous-data: Error moving file /home/asciiwolf/Code/com.grangerhub.Tremulous/.flatpak-builder/build/tremulous-data-3/.uncompressLT904Y/gpp_11/vm: File exists`

Unfortunately, I am not able to build the Flatpak because of this error and cannot figure out what the problem is.

**Comment by alexlarsson** [comment]
Thats a weird error, but i think moving as install is generally a bad idea. Does it work if you copy instead of move the files?

**Comment by AsciiWolf** [comment]
@alexlarsson Nope, same error.

**Comment by AsciiWolf** [comment]
I have force pushed a new version that replaces mv with cp, unfortunately, it did not fix the issue.

**Comment by AsciiWolf** [comment]
It looks like the error is not related to the build-commands. It happens even if there is nothing in the build-commands section.

**Comment by Barthalion** [comment]
I can confirm it also happens here (on btrfs, if it makes any difference). I will try to debug it more when I have time.

**Comment by AsciiWolf** [comment]
Any news?

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build com.grangerhub.Tremulous

**Comment by alexlarsson** [comment]
bot, build com.grangerhub.Tremulous

**Comment by nedrichards** [comment]
Build is at: https://flathub.org/builds/#/builders/1/builds/841

**Comment by alexlarsson** [comment]
How did you add the submodule? Its like git isn't aware that there is a submodule at all. `git submodule status` returns nothing and `git submodule update --init` doesn't get the submodule repo.

**Comment by alexlarsson** [comment]
bot, build com.grangerhub.Tremulous

(Testing the bot)

**Comment by AsciiWolf** [comment]
Sorry, I was moving the files manually between repos and forgot to add the shared-modules submodule. It should be fixed now.

**Comment by Barthalion** [comment]
bot, build com.grangerhub.Tremulous

**Comment by AsciiWolf** [comment]
The issue has been fixed (workarounded), thanks to @alexlarsson! The game now builds without any issues and looks to be fully working.

**Comment by AsciiWolf** [comment]
bot, build com.grangerhub.Tremulous

**Comment by AsciiWolf** [comment]
bot, build com.grangerhub.Tremulous

**Comment by AsciiWolf** [comment]
bot, build com.grangerhub.Tremulous

**Comment by Barthalion** [comment]
Merged; you should receive an invitation to collaborators (also for openarena, btw). Thanks!

**Pull request closed without merging**
