### PR TITLE
Add com.adobe.Reader

### PR DESCRIPTION
**Pull request by konradmb**
The last available version of Adobe Reader for Linux.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build com.adobe.Reader

**Comment by TingPing** [comment]
PDF readers are a huge security target and Reader `9.x` are completely unsupported. I do not want this on Flathub.

**Comment by konradmb** [comment]
@TingPing But it's running in sandbox, the scope of damage is limited. If you want to edit PDF with XFA forms, it's the only one viewer that fully supports them.

**Comment by TingPing** [comment]
> But it's running in sandbox, the scope of damage is limited.

```
  - --socket=x11
  - --share=ipc
  - --device=dri
  - --socket=pulseaudio
  - --filesystem=xdg-documents:rw
  - --filesystem=xdg-download:rw
  - --filesystem=xdg-desktop:rw
  - --share=network
```

Those permissions mean you have host execution and can upload many documents to a malicious server, or mine crypto, or whatever.

This is not secure and will never be secure.

**Comment by konradmb** [comment]
Ok, I fully understand your stance.

**Pull request closed without merging**
