### PR TITLE
Add org.kde.subtitlecomposer.json

### PR DESCRIPTION
**Pull request by herzenschein**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://invent.kde.org/multimedia/subtitlecomposer/-/issues/56 **Developer:** @maxrd2
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by maxrd2** [comment]
> Is there any preference about the source being "archive" or is it fine for it to be "git"? Since we now have a tarball on download.kde.org.
> 
> Both methods show the correct tag.

The tarball also includes localizations which are in separate repository on kde. Think tarball is better

**Comment by barthalion** [comment]
cc @flathub/kde

**Comment by nedrichards** [comment]
bot, build org.kde.subtitlecomposer

**Comment by hfiguiere** [comment]
build fail as the patch to build on aarch64 https://github.com/flathub/flathub/pull/2562#issuecomment-937980225 never got added.

**Comment by herzenschein** [comment]
Aye. @maxrd2 , could the fixes on master be backported to 7.1 or should we wait for 7.2 first?

**Comment by hfiguiere** [comment]
> Aye. @maxrd2 , could the fixes on master be backported to 7.1 or should we wait for 7.2 first?

I would simply add the patch to the flatpak build. Done that many times. (and submit upstream of course)

**Pull request closed without merging**
