### PR TITLE
Package Carcara

### PR DESCRIPTION
**Pull request by MateusRodCosta**
Hi, so this is one proprietary game which the game developers have shown interest in packaging as a Flatpak.
As far as I managed to find, there's no place specifying the license (so, I have to assume it's proprietary) and this might pose some problems in distributing.
The game is also currently only available from a file sharing website.

So, discussing with the devs and @TingPing some of the things that would we should do are:

* Get the license of the game or, in case it doesn't exist, ask the devs to write one.
* Think about how to deal with the situation where an proprietary app developer wants to distribute their apps on flathub (This would include them themselves doing that on their own, or someone else with their permission)

I will send an email soon-ish to the devs pointing to this issue.

### CODE REVIEW

**Comment by renanssba** [comment]
Hello, I'm the developer of the game here.
Just writing to say that I have interest in distributing Carcara game in flatpack format and help with whatever's necessary.

About the licenses, what kind of license the packages distributed in flatpack have to be?

**Comment by TingPing** [comment]
This would be the first proprietary application actually hosted on Flathub so we haven't discussed licensing issues. @ramcq Also brought up that since much of the infrastructure is donated because this is an open source project those donors might not be happy about this. So these are just questions that will have be worked out so your patience is appreciated @renanssba =).

**Comment by MateusRodCosta** [comment]
This might be a weird idea, but if proprietary apps can't be hosted it could allow Carcara to be redistributed.

What if Super Nova relicensed Carcara with a Creative Commons license such as CC-BY-NC-ND?

We would have to credit them, not sell the game for a fee and not create derivates works.
However it might allow to redistibute the full game. And if the CC license itself doesn't allow, the authors could easily grant an exception which might pose less legal problems.

So, maybe this specific license could be somewhat restrictive as a proprietary license while still allowing redistribution.

Of course, I am not sure of how legal this approach could be. But, it could be a solution.

**Comment by renanssba** [comment]
well, if the platform is not open for proprietary apps, maybe it is not a good fit for Carcara distribution.
we may not be interested in relicensing Carcara to a different license, as there are other good platforms more fit for distributing it in its current state.

thanks for the interest Mateus, and for the time, Mr TingPing

**Comment by ramcq** [comment]
We've changed our thinking a bit since then, it's OK for Flathub to host apps in binary form provided they are correctly identified as proprietary apps in the appstream metadata, and those binaries have a transferrable (ie, including Flathub and anyone who gets them from us) license to redistribute.

**Comment by MateusRodCosta** [comment]
I see that now the game might be accepted without having to download from the file hosting site or setting up a mirror, since we could distribute it as binary.
So, I am willing to get back to packaging it, I shouldn't have to make many changes outside of updating to a newer runtime.

@renanssba Are you able to give us redistribution permissions as @ramcq mentioned in the previous comment?

**Comment by renanssba** [comment]
I'm sorry @MateusRodCosta, but we have lost interest in distributing Carcará through the Flathub platform.
We believe that there are other platforms more fit for our game. Thanks for the interest and everyone that contributed to this thread, and I hope the discussion was valid.
Thanks for the contact @MateusRodCosta and I hope the game was a good experience to you

**Pull request closed without merging**
