### PR TITLE
Add a poezio flatpak

### PR DESCRIPTION
**Pull request by linkmauve**
poezio is a console XMPP client whose 0.12 just got released including a [flatpak manifest](https://git.louiz.org/poezio/tree/data/io.poez.Poezio.json) and [appdata file](https://git.louiz.org/poezio/tree/data/io.poez.Poezio.appdata.xml).

### CODE REVIEW

**Comment by barthalion** [comment]
Does it ship a desktop file too?

**Comment by barthalion** [comment]
bot, build io.poez.Poezio

**Comment by barthalion** [comment]
Build failed on non-x86_64 architectures because you are using binary wheels. Take a look at pip generator from [flatpak-builder-tools](https://github.com/flatpak/flatpak-builder-tools) to generate json snippets for building from source. The x86_64 build failed due to misnamed or not installed appdata file (https://flathub.org/builds/#/builders/31/builds/431). The name has to match the chosen appid; you can use `rename-appdata-file` for now but it would be better to rename it upstream in the next release.

**Comment by linkmauve** [comment]
I just added a .desktop file upstream, but we’ll need to publish a new revision on pypi before this flatpak can use it.

I also made it build both slixmpp and poezio from sources instead of using wheels, as per `flatpak-pip-generator`’s suggestion.

As for appdata, where should I install it?  It’s already present in the poezio archive, but I didn’t know I should install it from there before making the 0.12 release.

**Comment by nedrichards** [comment]
per the spec:  

> "Upstream projects can ship one or more metainfo files in /usr/share/metainfo/%{id}.metainfo.xml, where id is a unique identifier of this specific component. "

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html 

For flatpak that'd be /app/share/metainfo/io.poez.Poezio.metainfo.xml

**Comment by nedrichards** [comment]
bot, build io.poez.Poezio

**Comment by nedrichards** [comment]
Oh, just to note - for metainfo read appdata interchangably. e.g. these should all work the same:

* /app/share/appdata/io.poez.Poezio.appdata.xml
* /app/share/appdata/io.poez.Poezio.metainfo.xml
* /app/share/metainfo/io.poez.Poezio.appdata.xml

**Comment by linkmauve** [comment]
Hi, thanks for the help, this is [now](https://git.louiz.org/poezio/commit/?id=f2d2c4df3c48fc0ff04c1ce811e5f291500eb1f9) [fixed](https://git.louiz.org/poezio/commit/?id=0e7ebf974e3ec4f47e5f0781781ff43d99c4f6f3) in master.

I have added some hotfixes in this flatpak manifest, but they’ll be included in the next minor release we’ll do.

**Comment by nedrichards** [comment]
Your desktop file needs to start up a terminal to run the app in, otherwise it just closes straight away.

**Comment by linkmauve** [comment]
Isn’t `Terminal=true` enough for that?  At least in gnome-shell it does start poezio in xterm just fine.

**Comment by nedrichards** [comment]
It should be, this could be a different bug (not in anything you or flatpak have done)

**Comment by linkmauve** [comment]
Is it possible to download the generated package, to check if it would be some traceback happening on start or something like that?  When I build it on my laptop it seem to work as is.

**Comment by linkmauve** [comment]
Should be fixed in this new preview .desktop file.

**Comment by nedrichards** [comment]
bot, build io.poez.Poezio

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/io.poez.Poezio

**Comment by linkmauve** [comment]
Is there a reason poezio still doesn’t appear at https://flathub.org/apps/search/poezio btw?

**Pull request closed without merging**
