### PR TITLE
Add dev.edfloreshz.Tasks

### PR DESCRIPTION
**Pull request by edfloreshz**
### Please confirm your submission meets all the criteria

- [x] Please describe the application briefly.
A simple task management application for the COSMIC™ desktop
- [x] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [x] I have read the and followed all the [Submission and licence requirements][reqs].
- [x] I have [built][build] and tested the submission locally.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:**

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements#control-over-domain
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build dev.edfloreshz.Tasks

**Comment by hfiguiere** [comment]
What's the difference with https://github.com/flathub/flathub/pull/3105 ?

**Comment by bbhtt** [comment]
bot, build dev.edfloreshz.Tasks

**Comment by bbhtt** [comment]
Some of the emojis in set icon are missing colour on a default Fedora 40 VM. That's not a blocker though.

**Comment by edfloreshz** [comment]
Besides that, everything is working fine for me 👍🏼 we can merge and I'll fix the emoji issue in the next version.

**Comment by hfiguiere** [comment]
> What's the difference with #3105 ?

Any answer? Since that was your app that seem to do the same thing. Except it was EOL.

**Comment by edfloreshz** [comment]
Ah! Sorry, I must've missed your question.

Done was created to consolidate multiple task services into a single app, but unfortunately I struggled to maintain it due to lack of time and had to mark it as EOL.

Instead I created Tasks, which is a simpler app that just handles local tasks, easier to maintain, I took inspiration from Done's design but they are separate projects.

**Pull request closed without merging**
