### PR TITLE
Add io.github.lawstorant.boxflat

### PR DESCRIPTION
**Pull request by Lawstorant**
### Please confirm your submission meets all the criteria

- [x] Please describe the application briefly.

This application is a Linux alternative for Moza Racing [Pit House](https://support.mozaracing.com/en/support/solutions/folders/70000478308). It enabled users to change settings of their Moza Racing devices such as wheelbases, rims, pedals and more.

`--device=all` access is needed for serial communication (Moza devices present their serial interfaces as `/dev/ttyACM*`)
~`/etc/` access is used to check if host os has udev rules that enable user access to Moza serial devices~

- [x] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [x] I have read the and followed all the [Submission and licence requirements][reqs].
- [x] I have [built][build] and tested the submission locally.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:** https://github.com/Lawstorant/boxflat

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
> /etc/ access is used to check if host os has udev rules that enable user access to Moza serial devices

All you need is check permissions on the device node itself.

**Comment by hfiguiere** [comment]
bot, build io.github.lawstorant.boxflat

**Comment by Lawstorant** [comment]
bot, build io.github.lawstorant.boxflat

**Comment by Lawstorant** [comment]
bot, build io.github.lawstorant.boxflat

**Comment by bbhtt** [comment]
If you have the hardware, can you show a screenrecord of the app in a working condition?

**Comment by Lawstorant** [comment]
[Screencast from 2024-07-31 18-09-15.webm](https://github.com/user-attachments/assets/44e30d90-c16c-4aa0-b9e1-4ef5398011d0)
Colors are a bit wonky, but that's the general idea. It's hard to show that it actually does anything without recording the hw itself, but as you can see, it read all teh settings from the connected devices.

The last wheel disconnection/connection is my doing it deliberately, to show it detects hardware properly

**Comment by bbhtt** [comment]
thanks.

**Comment by Lawstorant** [comment]
bot, build io.github.lawstorant.boxflat

**Pull request closed without merging**
