### PR TITLE
Add net.daase.journable

### PR DESCRIPTION
**Pull request by BjoernDaase**
Hey folks,

I am the author of Journable and would like to see it on flathub. That is the first time I am doing this release process so I hope I am doing it right :)

Thanks,
Björn

### CODE REVIEW

**Comment by BjoernDaase** [comment]
bot, build net.daase.journable

**Comment by BjoernDaase** [comment]
bot, build net.daase.journable

**Comment by BjoernDaase** [comment]
bot, build net.daase.journable

**Comment by barthalion** [comment]
Hi @BjoernDaase, you can generate almost valid appdata file with https://www.freedesktop.org/software/appstream/metainfocreator/#/

You will need to add `<releases>` section to it, for example:

```
  <releases>
    <release version="1.0" date="2020-03-29">
        <description>
            <p>First release.</p>
      </description>
    </release>
  </releases>
```

 and OARS rating (can be generated with https://hughsie.github.io/oars/).

**Comment by BjoernDaase** [comment]
bot, build net.daase.journable

**Comment by BjoernDaase** [comment]
bot, build net.daase.journable

**Comment by bilelmoussaoui** [comment]
You can validate the manifest locally with https://github.com/flathub/flathub/wiki/AppData-Guidelines#use-flathubs-appstream-util

**Comment by BjoernDaase** [comment]
bot, build net.daase.journable

**Comment by BjoernDaase** [comment]
> Hi @BjoernDaase, you can generate almost valid appdata file with https://www.freedesktop.org/software/appstream/metainfocreator/#/
> 
> You will need to add `<releases>` section to it, for example:
> 
> ```
>   <releases>
>     <release version="1.0" date="2020-03-29">
>         <description>
>             <p>First release.</p>
>       </description>
>     </release>
>   </releases>
> ```
> 
> and OARS rating (can be generated with https://hughsie.github.io/oars/).

Thanks, I already found that in the build logs. I decided to try to make a meaningful one right away :)

**Comment by BjoernDaase** [comment]
> You can validate the metainfo/appdata locally with https://github.com/flathub/flathub/wiki/AppData-Guidelines#use-flathubs-appstream-util

Ah perfect, that is exactly what I needed. Sorry for spamming builds on the pipeline :(

```
/home/bjoern/Projects/journable/data/net.daase.journable.appdata.xml.in: OK
```
is the local output now, so I think the file should be correct now. 

Could you please enable the bot again? 😬

**Comment by bilelmoussaoui** [comment]
bot, build net.daase.journable

**Comment by BjoernDaase** [comment]
bot, build net.daase.journable

**Comment by BjoernDaase** [comment]
Alright, build worked and everything works perfect :)

**Comment by barthalion** [comment]
What's `New` button supposed to do? Do you need full `--filesystem=home` access? if your application can use `GtkFileChooserNative` instead to open files, it will use the portal instead so "legacy" permissions won't be needed.

**Comment by BjoernDaase** [comment]
> What's New button supposed to do?

The New button let's you create a new empty journal. This might be useful if you want to save your journal, e.g. at the end of a week, and create a new and empty one (e.g. for the upcoming week). We had the same discussion [here](https://gitlab.gnome.org/BjoernDaase/journable/-/issues/1) already.

> Do you need full `--filesystem=home` access? if your application can use `GtkFileChooserNative` instead to open files, it will use the portal instead so "legacy" permissions won't be needed.

Ah, thanks! No, I simply was not aware of `GtkFileChooserNative` but tried it out and it works perfectly fine so I can remove the permission :smile:

**Comment by BjoernDaase** [comment]
bot, build net.daase.journable

**Comment by BjoernDaase** [comment]
> > What's New button supposed to do?
> 
> The New button let's you create a new empty journal. This might be useful if you want to save your journal, e.g. at the end of a week, and create a new and empty one (e.g. for the upcoming week). We had the same discussion [here](https://gitlab.gnome.org/BjoernDaase/journable/-/issues/1) already.
> 
> > Do you need full `--filesystem=home` access? if your application can use `GtkFileChooserNative` instead to open files, it will use the portal instead so "legacy" permissions won't be needed.
> 
> Ah, thanks! No, I simply was not aware of `GtkFileChooserNative` but tried it out and it works perfectly fine so I can remove the permission smile

Converted and permissions removed :)

**Comment by nedrichards** [comment]
This latest build isn't in fact saving the JSON file outside the sandbox using the portal.

**Comment by BjoernDaase** [comment]
> This latest build isn't in fact saving the JSON file outside the sandbox using the portal.

Indeed, it in the end places it somewhere in `/run/user` :(

**Comment by BjoernDaase** [comment]
My original solution was inspired by what `gedit` actually does. It even has the following comment:  
```
        /* We want full fs access so we can read the files */
        "--filesystem=host",
```
So is there a way around having that permission?

**Comment by barthalion** [comment]
@bilelmoussaoui Mind having a look?

**Comment by BjoernDaase** [comment]
> @bilelmoussaoui Mind having a look?
> 
> It's problem with the code, but Bilel will likely know from the get-go instead of my poking.

Just that you don't have to search, this is the point in code: https://gitlab.gnome.org/BjoernDaase/journable/-/blob/master/src/window.py#L234.

**Comment by bilelmoussaoui** [comment]
> 
> 
> > @bilelmoussaoui Mind having a look?
> > It's problem with the code, but Bilel will likely know from the get-go instead of my poking.
> 
> Just that you don't have to search, this is the point in code: https://gitlab.gnome.org/BjoernDaase/journable/-/blob/master/src/window.py#L234.

From a quick look: Any reason for not using Gio.File that you can get with `dialog.get_file()`? that should solve the problem you're having

**Comment by BjoernDaase** [comment]
> > > @bilelmoussaoui Mind having a look?
> > > It's problem with the code, but Bilel will likely know from the get-go instead of my poking.
> > 
> > 
> > Just that you don't have to search, this is the point in code: https://gitlab.gnome.org/BjoernDaase/journable/-/blob/master/src/window.py#L234.
> 
> From a quick look: Any reason for not using Gio.File that you can get with `dialog.get_file()`? that should solve the problem you're having

That indeed solves writing to the file, thanks!  
But I still need to know the full file path (it is displayed in the ui and there must be a .json appended if there was not extension given) and `get_path()` in the Gio.File via `dialog.get_file()` still returns the `/run/user` file...

**Comment by barthalion** [comment]
The path is opaque and irrelevant to your app, it's handled a file descriptor. Is filename not enough or is it also randomish?

**Comment by BjoernDaase** [comment]
There is no need to display the file path in the UI but, from my POV, it is a pretty nice to have feature.  
On the other hand, appending the `.json` extension (even if technically not needed), is a must have.

**Comment by BjoernDaase** [comment]
And furthermore I need the full path of the file to be able to reopen it on the startup of the next session (after closing and reopening the window) to retain the content of the journal.

**Comment by bilelmoussaoui** [comment]
> 
> 
> And furthermore I need the full path of the file to be able to reopen it on the startup of the next session (after closing and reopening the window) to retain the content of the journal.

That's not something you can achieve with the current documents portal.

**Comment by BjoernDaase** [comment]
> > And furthermore I need the full path of the file to be able to reopen it on the startup of the next session (after closing and reopening the window) to retain the content of the journal.
> 
> That's not something you can achieve with the current documents portal.

Hmmm, that's unfortunate.  
So I guess we have to add full `--filesystem=home` access?

**Comment by nedrichards** [comment]
> > And furthermore I need the full path of the file to be able to reopen it on the startup of the next session (after closing and reopening the window) to retain the content of the journal.
> 
> That's not something you can achieve with the current documents portal.

Right, that's a feature that's just being added as part of the directory features, right? (If I understand the intention of those correctly)

**Comment by barthalion** [comment]
> Hmmm, that's unfortunate.
> So I guess we have to add full `--filesystem=home` access?

Your applications has write access to `$XDG_DATA_HOME` by default. What about storing files here instead?

Even when directory portal becomes supported by GTK, it's by design initiated by user and won't grant you access after application is freshly started.

**Comment by BjoernDaase** [comment]
> Your applications has write access to `$XDG_DATA_HOME` by default. What about storing files here instead?

That would work if we could restrict the GtkFileChooserNative to `$XDG_DATA_HOME` only. And AFAICS this is not easily achievable (or user-friendly according to https://stackoverflow.com/questions/44023311/python-gtk3-filechooser-restrict-folder). Or do I miss something here? Otherwise, the user could select a file somewhere outside the sandbox.  
And yes, we somehow have to give the user the ability to store stuff in folders to manager their journals otherwise this might end up in a big mess :(

**Comment by BjoernDaase** [comment]
> > > And furthermore I need the full path of the file to be able to reopen it on the startup of the next session (after closing and reopening the window) to retain the content of the journal.
> > 
> > 
> > That's not something you can achieve with the current documents portal.
> 
> Right, that's a feature that's just being added as part of the directory features, right? (If I understand the intention of those correctly)

Interesting. Out of curiosity, to you have a link tot that?

**Comment by nedrichards** [comment]
> > > > And furthermore I need the full path of the file to be able to reopen it on the startup of the next session (after closing and reopening the window) to retain the content of the journal.
> > > 
> > > 
> > > That's not something you can achieve with the current documents portal.
> > 
> > 
> > Right, that's a feature that's just being added as part of the directory features, right? (If I understand the intention of those correctly)
> 
> Interesting. Out of curiosity, do you have a link to that?

As pointed out above, I had the wrong end of the stick I'm afraid. There's some interesting workflow questions about how one should "best" do this sort of thing for users but that's getting rather off topic for helping get this quite useful app to more people!

**Comment by BjoernDaase** [comment]
> As pointed out above, I had the wrong end of the stick I'm afraid. There's some interesting workflow questions about how one should "best" do this sort of thing for users but that's getting rather off topic

Alright. But as you said, it feels like there is some room for improvement on the portal design here. Maybe we should continue this discussion in the GTK GitLab?

> for helping get this quite useful app to more people!

That would indeed be a pity if we can not work out the permissions and instead have tjose as a blocker to publish this app on flathub.

**Comment by bilelmoussaoui** [comment]
> > As pointed out above, I had the wrong end of the stick I'm afraid. There's some interesting workflow questions about how one should "best" do this sort of thing for users but that's getting rather off topic
> 
> Alright. But as you said, it feels like there is some room for improvement on the portal design here. Maybe we should continue this discussion in the GTK GitLab?
> 
> > for helping get this quite useful app to more people!
> 
> That would indeed be a pity if we can not work out the permissions and instead have tjose as a blocker to publish this app on flathub.

I don't think there's much to be done, the documents portal is allowed to give you a temporary access to a file/directory, if you want permanent access to a directory, you should use --filesystem in your manifest.

**Comment by BjoernDaase** [comment]
> > > As pointed out above, I had the wrong end of the stick I'm afraid. There's some interesting workflow questions about how one should "best" do this sort of thing for users but that's getting rather off topic
> > 
> > 
> > Alright. But as you said, it feels like there is some room for improvement on the portal design here. Maybe we should continue this discussion in the GTK GitLab?
> > > for helping get this quite useful app to more people!
> > 
> > 
> > That would indeed be a pity if we can not work out the permissions and instead have tjose as a blocker to publish this app on flathub.
> 
> I don't think there's much to be done, the documents portal is allowed to give you a temporary access to a file/directory, if you want permanent access to a directory, you should use --filesystem in your manifest.

Alright, I readded `--filesystem=home` to the mainfest.

**Comment by BjoernDaase** [comment]
bot, build net.daase.journable

**Pull request closed without merging**
