### PR TITLE
Moving Phase1 to new slug

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by Eonfge** [comment]
bot, build io.github.freedoom.Phase1

**Comment by bilelmoussaoui** [comment]
bot, build io.github.freedoom.Phase1

**Comment by bilelmoussaoui** [comment]
bot, build io.github.freedoom.Phase1

**Comment by Eonfge** [comment]
bot, build io.github.freedoom.Phase1

**Comment by bilelmoussaoui** [comment]
Thanks! I'm going to merge all the three, publish them and EOL the old app-id's.
/merge

**Pull request closed without merging**
