### PR TITLE
Add org.gnome.Mines

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Upstream discussion: https://gitlab.gnome.org/GNOME/gnome-mines/issues/38

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.Mines

**Comment by bilelmoussaoui** [comment]
The upstream maintainer is interested in co-maintaining this.

**Comment by evfool** [comment]
Hello, I am the upstream maintainer, please grant me write access.

**Comment by barthalion** [comment]
bot, build org.gnome.Mines

**Comment by barthalion** [comment]
bot, build org.gnome.Mines

**Comment by barthalion** [comment]
Looks like GitHub stopped sending webhook events about 1 hour ago.

**Comment by barthalion** [comment]
bot, build org.gnome.Mines

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gnome.Mines

**Pull request closed without merging**
