### PR TITLE
Add com.cuperino.qprompt

### PR DESCRIPTION
**Pull request by Cuperino**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions.
- [X] All assets referenced in the manifest are redistributable by any party.
- [X] I am an upstream contributor to the project.
- [X] I own the domain used in the application ID.
- [X] Any additional patches or files have been submitted to the upstream projects concerned.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Cuperino** [comment]
bot, build com.cuperino.qprompt

**Comment by hfiguiere** [comment]
AppData fails to validate:
```
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• style-invalid         : Not enough <screenshot> tags, minimum is 1
• tag-missing           : <release> required
• tag-missing           : <url> is not present
```

**Comment by Cuperino** [comment]
There are two copies of the Manifest file in QPrompt. I modified one and forgot to copy those changes to the other one.

**Comment by Cuperino** [comment]
bot, build com.cuperino.qprompt

**Comment by Cuperino** [comment]
bot, build com.cuperino.qprompt

**Comment by Cuperino** [comment]
I merged main into com.cuperino.qprompt by accident and unintentionally added a large number of participants into the original PR #2724. This is why I deleted that PR and created this one to replace it.

**Comment by Cuperino** [comment]
After installing from the testing repository QPrompt runs with terrible performance, and I see the following errors on launch: Is Are these because I removed the "--device=all" permission?

```
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: iris
```

**Comment by hfiguiere** [comment]
you need the `--device=dri` permission

**Comment by Cuperino** [comment]
bot, build com.cuperino.qprompt

**Comment by Cuperino** [comment]
bot, build com.cuperino.qprompt

**Pull request closed without merging**
