### PR TITLE
"Little Big Adventure 2" game

### PR DESCRIPTION
**Pull request by bam80**
This is a Linux installer for GOG's Windows distribution of the "Little Big Adventure 2" game:
https://www.gog.com/game/little_big_adventure_2

@AsciiWolf @TingPing

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Hmm, I am not sure if such wrappers for Windows games are allowed on Flathub.

/cc @nedrichards

**Comment by bam80** [comment]
The flatpak itself contains only installer scripts.
Original game archive is pulled at install-time as extra-data

**Comment by bam80** [comment]
GOGs games are DRM-free, so there should be no issues here

**Comment by LeandroStanger** [comment]
bot, build it.dotslashplay.little-big-adventure-2

**Comment by bam80** [comment]
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/3117/it.dotslashplay.little-big-adventure-2.flatpakref
> ```

If you would like to test the build, please read Installation instructions here:
https://github.com/flathub/flathub/pull/994/commits/5e7fb399efd714696a613b024c85b271fd45261a?file-filters%5B%5D=.json&file-filters%5B%5D=.xml#diff-16699913ea09b3ff2c549c1c16462e8eR21

**Comment by hadess** [comment]
The instructions in the only commit make it clear that this isn't good enough to include in Flathub. The applications need to be able to actually run after installation from Flathub.

**Comment by bam80** [comment]
@hadess, it will. Just put the archive in practice proper place before the installation.
Unfortunately, it's the only way for now to feed extra-data to flatpak if it's not accessible over http

**Comment by LeandroStanger** [comment]
bot, build it.dotslashplay.little-big-adventure-2

**Comment by hadess** [comment]
> @hadess, it will. Just put the archive in practice proper place before the installation.
> Unfortunately, it's the only way for now to feed extra-data to flatpak if it's not accessible over http

This isn't good enough. Otherwise Flathub would be full of installers for ScummVM, DOSBox or Quake engines with no data included.

**Comment by bam80** [comment]
@hadess it's just no one bothered to do it, I guess ;)

**Comment by cpba** [comment]
@bam80 this doesn't fit in with flathub's policies, it won't be accepted. However, it doesn't mean your work has to go to waste, have you thought about self-hosting?

It doesn't require more than an http server and you could be running your own repo.

**Comment by TingPing** [comment]
As mentioned that isn't an acceptable way to package things on Flathub.

**Comment by bam80** [comment]
Devs from upstream project, https://www.dotslashplay.it/, didn't express much interest in hosting this.
So if I knew it won't be accepted on Flathub, I wouldn't start it all.
From the explanations, I really don't understand what flathub's policies it doesn't fit, and how could I know it beforehand.

It took several months of work for me, and the ease you closing it now are really disappointing, and probably will keep me away from participating the project in the future, unfortunately.

**Comment by TingPing** [comment]
The application has to launch, shouldn't that be obvious? Telling users to download binaries and place them somewhere is clearly unacceptable.

**Comment by bam80** [comment]
> Telling users to download binaries and place them somewhere is clearly unacceptable.

It's just shortcoming of current flatpak's extra-data implementation which I believe could be fixed in the future. Actually, corresponding issues already exist.

**Comment by bam80** [comment]
- [supporting local path in --extra-data](https://github.com/flatpak/flatpak/issues/713)
- [Consider how to handle extra-data when installing or updating over P2P](https://github.com/flatpak/flatpak/issues/969):

> We might be able to come up with a better way of propagating extra-data, but only if we are actually allowed to do so — I think part of the point of extra-data is to support application blobs which we are not allowed to redistribute (but users are allowed to download themselves).

**Comment by TingPing** [comment]
If there is a good user workflow for this in the future I am fine with re-evaluating this.

I do not believe at this time it is acceptable though.

**Comment by bam80** [comment]
@TingPing Can we publish it on flathub-beta meanwhile?

**Comment by bam80** [comment]
@TingPing Can we publish it on flathub-beta meanwhile?

**Pull request closed without merging**
