### PR TITLE
Add org.kde.kcachegrind (KCachegrind)

### PR DESCRIPTION
**Pull request by Siosm**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build org.kde.kcachegrind

**Comment by Siosm** [comment]
Mention @tsdgeos as he currently is a maintainer of several KDE related packages on Flathub.

**Comment by Siosm** [comment]
bot, build org.kde.kcachegrind

**Comment by tsdgeos** [comment]
i guess it needs the device dri thing to fix

libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: El fitxer o directori no existeix
libGL error: failed to load driver: i965

**Comment by Siosm** [comment]
bot, build org.kde.kcachegrind

**Comment by tsdgeos** [comment]
Needs graphviz in the package so you can see the nice graphs, see 

imatge

in my regular system vs

imatge

in the flatpak version

**Comment by Siosm** [comment]
bot, build org.kde.kcachegrind

**Comment by tsdgeos** [comment]
I think it needs the option to be able to read the whole filesystem --filesystem=host ? otherwise when opening a trace with debug it fails to find the sourcecode because the files are not there, i.e. 

imatge

Where it says "i can't find /home/tsdgeos/devel/kde/okular/shell/okular_main.cpp" but that file actually exists

**Comment by Siosm** [comment]
bot, build org.kde.kcachegrind

**Comment by tsdgeos** [comment]
Looks good to me :)

**Comment by Siosm** [comment]
@nedrichards Can you add the KDE team as maintainers for this application? Thanks!

**Pull request closed without merging**
