### PR TITLE
Add com.xnview.XnRetro (xnretro-flatpak)

### PR DESCRIPTION
**Pull request by scx**
**XnRetro** allows you to create stunning images with vintage or instant effect on your Desktop.
https://github.com/scx/flathub/tree/com.xnview.XnRetro

See also:
https://www.xnview.com/en/xnretro/
https://github.com/scx/xnretro-flatpak
https://github.com/scx/xnretro-flatpak/tree/v1.01

### CODE REVIEW

**Comment by scx** [comment]
The vendor developer has been notified.

**Comment by scx** [comment]
bot, build com.xnview.XnRetro

**Comment by pierrexn** [comment]
Thanks

**Comment by nedrichards** [comment]
Hrm, this is i386 only, right? Absolutely doesn't work with 64bit libraries?

**Comment by scx** [comment]
@nedrichards 

> Hrm, this is i386 only, right?

The latest version for **x86_64** is _1.01_ and _1.26_ is **i386**-only.

See also:
https://github.com/flathub/flathub/pull/899/commits/b02de0fed1acc63d1a4a25ad83ad8c04fd0d5fd6

> Absolutely doesn't work with 64bit libraries?

I need at least these deps compiled for **i386**:
 * `gstreamer` and `gstreamer-plugins-base` _0.10_ (`libgstapp-0.10.so.0`) - all Freedesktop runtimes from 1.0 to 18.08 contain only `gstreamer` _1.0_
 * `libpng12` (`libpng12.so.0`)
 * `qt4` (especially `libq*.so`: `libqgif.so`, `libqico.so`, `libqjpeg.so`, `libqmng.so`, `libqsvg.so`, `libqtga.so`, `libqtiff.so`) - https://newsgroup.xnview.com/viewtopic.php?f=81&t=27942&start=15&p=155208#p155208

And as far as I know, it is impossible to build i386 modules when building for x86_64. For multilib packages I can only use pre-build i386 binaries, right?
https://github.com/flatpak/freedesktop-sdk-images/issues/101
https://github.com/flatpak/flatpak/issues/2586#issuecomment-454499579
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/348

However, it shouldn't be a problem to install and run a i386 flatpak package on x86_64.

**Comment by nedrichards** [comment]
Yeah, it's just more annoying to test with our test build system on the command line and I'm not certain that some software stores will promote i386 correctly, anyway, as you say, not a blocker.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.xnview.XnRetro

**Comment by scx** [comment]
@nedrichards 

Thanks!

**Pull request closed without merging**
