### PR TITLE
add org.bleachbit.BleachBit

### PR DESCRIPTION
**Pull request by proletarius101**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/bleachbit/bleachbit/issues/632#issuecomment-1368202546
- [x] ~I~ The Upstream owns the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by dginovker** [comment]
You're missing an appdata.xml

**Comment by az0** [comment]
I wonder what this requirement means. It is not phrased asking for consent, but consent is not required for open source software.

>I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.

**Comment by barthalion** [comment]
Flathub's primary goal is to be an app publishing platform for developers, but the reality is that not all devs are interested in packaging their apps. While it doesn't say "consent", it's really that – we want to make sure that if a team is not interested, they are not against someone else maintaining it either.

**Comment by barthalion** [comment]
bot, build org.bleachbit.BleachBit

**Pull request closed without merging**
