### PR TITLE
Add com.mikrotik.Winbox

### PR DESCRIPTION
**Pull request by Alberto97**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Alberto97** [comment]
bot, build com.mikrotik.Winbox

**Comment by hfiguiere** [comment]
This is a Windows app.

**Comment by Alberto97** [comment]
Of course it is an app build on Win32 API but Mikrotik itself says it can be run through wine:
"It is a native Win32 binary but can be run on Linux and macOS (OSX) using Wine."(https://help.mikrotik.com/docs/display/ROS/Winbox).
I've been running this app for years with wine without issues. Is this not allowed on flathub?

**Comment by hfiguiere** [comment]
>  Is this not allowed on flathub?

In general no.

**Comment by Alberto97** [comment]
Uhm ok, considering that there are similar apps that do pretty much the same thing I thought it was allowed.
I think it would be helpful making the documentation a bit more clear in this regard.

**Pull request closed without merging**
