### PR TITLE
Greybird GTK theme dark variant

### PR DESCRIPTION
**Pull request by Mau-G**
I'm one of the upstream maintainers of this project and I would like to submit it to Flathub:
https://github.com/shimmerproject/Greybird

### CODE REVIEW

**Comment by Mau-G** [comment]
https://github.com/shimmerproject/Greybird

**Comment by Mau-G** [comment]
bot, build org.gtk.Gtk3theme.Greybird-dark

**Comment by Mau-G** [comment]
bot, build org.gtk.Gtk3theme.Greybird-dark

**Comment by nedrichards** [comment]
@Mau-G is there anyone else from upstream who should be added?

**Comment by Mau-G** [comment]
i think it’s ok if it’s just me for now. We can gradually add someone else later if needed

**Pull request closed without merging**
