### PR TITLE
Add com.github.lpereira.hardinfo (hardinfo-flatpak)

### PR DESCRIPTION
**Pull request by scx**
[HardInfo](https://help.ubuntu.com/community/HardInfo) is a system profiler and benchmark for Linux systems. It is able to obtain information from both hardware and basic software, and organize them in a simple to use GUI.

Upstream participation request:
https://github.com/lpereira/hardinfo/issues/326

See also:
https://github.com/lpereira/hardinfo
https://github.com/scx/hardinfo-flatpak
https://github.com/scx/flathub/tree/com.github.lpereira.hardinfo

### CODE REVIEW

**Comment by scx** [comment]
I'm not sure if Flathub is a good place for this type of software. Let me present my thoughts first and we will see whether there are valid points or not.

Cons:
1. Flatpak enforces a sandbox and this kind of software will never be fully functional here, at least without resorting to certain tricks.
2. It uses `--talk-name=org.freedesktop.Flatpak` permission and `flatpak-spawn` to access some of host commands.
3. The last stable version was released on April 6, 2009 and is simply outdated.

Pros:
1. The same applies to many other programs that have already been published on Flathub. In particular, this applies to any IDE. Even some GNOME applications [suffer](https://gitlab.gnome.org/GNOME/totem/issues/258) from sandbox limitations. And what is more important here, HardInfo is already quite functional under Flatpak.
2. These kind of tricks are used by programs already present on Flathub, such as **Atom**, **Visual Studio Code**, **GNOME Builder**, **GNOME Games**, **Octave** or even **Lollypop**. Moreover, HardInfo is functional even without it. Please keep in mind, that most of the commands used by HardInfo are pre-installed in almost every Linux distro. Have you ever met a desktop Linux system without lsmod or lsusb? As for lm-sensors, no package system can guarantee that the kernel module will be loaded when our program is running, and every user accepts it.
3. This program is very actively developed on GitHub. There is no reason to use outdated release.
4. This app is very unique. There is no other graphical program like that for Linux. We have tools to show OpenGL extensions ([GPU-Viewer](https://github.com/arunsivaramanneo/GPU-Viewer), [The OpenGL Hardware Capability Viewer](https://github.com/SaschaWillems/glCapsViewer)), device info ([Hardware Lister](https://ezix.org/project/wiki/HardwareLiSter), [Udev Discover](https://launchpad.net/udev-discover)) or some kind of network information ([GNOME Nettool](https://projects-old.gnome.org/gnome-network/index.shtml), sensor readers ([Open Hardware Monitor](https://github.com/openhardwaremonitor/openhardwaremonitor), [Psensor](http://wpitchoune.net)), or even benchmarks ([Phoronix Test Suite](https://www.phoronix-test-suite.com/), [UNIGINE Benchmarks](https://benchmark.unigine.com)), but there is no software for for such a complete hardware and system analysis. The nearest alternative would probably be [I-Nex](http://i-nex.linux.pl) or [Sysinfo](https://sourceforge.net/projects/gsysinfo).

Notes:
- Although HardInfo already has support for Gtk+3, it is in alpha stage and many features are unavailable here, especially benchmarks.
- In the past, this program was able to upload benchmark results, but currently this option probably doesn't work.
- Please don't treat this manifest as final. It may contains leftovers from unused modules (e.g. `kmod`) and permissions (e.g. `--socket=session-bus`, `--socket=system-bus`, `--device=all`).

TODO:
- I am trying to reduce the host dependencies as much as possible, bundling whatever I can (e.g. `glxinfo`, `lspci`, `xdpyinfo`, `xrandr`), but only if it makes sense. For example, users expect the information about locales to come from the host, rather than from the Freedesktop environment. There is still room for further improvement. We can probably opt out of using some of network tools on the host side and improve the relevance of system information.
- Currently, instead of providing patches, I use the `sed` command widely. I will change it when the program development stabilizes. Ideally, I would like to see Flatpak support directly in the program.
- As for README, I would like to document what works, what doesn't work, and what requires commands on the host side. The build section will probably be removed in the future.

**Comment by barthalion** [comment]
If it's not being actively developed and upstream author is not interested in fixing their application for better flatpak support, I don't really see it on Flathub.

**Comment by scx** [comment]
@barthalion 

> If it's not being actively developed and upstream author is not interested in fixing their application for better flatpak support, I don't really see it on Flathub.

It is actively developed. Only this month there already have been 18 commits. That's more than in Eye of GNOME, Kdenlive, Pitivi or MyPaint during the same period. What's more, it's not just maintenance mode, but [new features](https://github.com/lpereira/hardinfo/issues/225) are still coming.
Of course, there is no need to rush. We can wait until we achieve the desired quality.

**Comment by AsciiWolf** [comment]
testbot, build com.github.lpereira.hardinfo

**Comment by scx** [comment]
testbot, build com.github.lpereira.hardinfo

**Comment by scx** [comment]
testbot, build com.github.lpereira.hardinfo

**Comment by scx** [comment]
testbot, build com.github.lpereira.hardinfo

**Comment by AsciiWolf** [comment]
@scx Why did you close the PR?

**Comment by scx** [comment]
@AsciiWolf 

> Why did you close the PR?

I changed the branch name because of changing the Application ID, so this PR was automatically closed. Don't worry, I'll fix it soon.

**Comment by scx** [comment]
Closed due to changing the Application ID.
https://github.com/scx/flathub/commit/cc000463a072bb32f19d781c2a5a0ad881258343

New pull request:
https://github.com/flathub/flathub/pull/846

**Pull request closed without merging**
