### PR TITLE
Add org.gimp.GIMP.Plugin.Lensfun

### PR DESCRIPTION
**Pull request by hfiguiere**
This is the Lensfun GIMP plugin.

Needs https://github.com/flathub/org.gimp.GIMP/pull/75 to build.

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.gimp.GIMP.Plugin.Lensfun

**Comment by bilelmoussaoui** [comment]
bot, build org.gimp.GIMP.Plugin.Lensfun

**Comment by nedrichards** [comment]
bot, build org.gimp.GIMP.Plugin.Lensfun

**Pull request closed without merging**
