### PR TITLE
Add io.github.seadve.Kooha

### PR DESCRIPTION
**Pull request by SeaDve**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by SeaDve** [comment]
bot, build io.github.seadve.Kooha

**Comment by nedrichards** [comment]
Claims that "endless:GNOME" is not supported so I can't test it easily locally on the machine I have here. Endless is very GNOMEy so you might want to relax https://github.com/SeaDve/Kooha/blob/152d70d029270c92673b6d498e3f5ecb35e9c76f/src/window.py#L73 a little.

**Comment by nedrichards** [comment]
/merge

Works great on the Pinebook Pro, looking forward to future improvements.

**Comment by SeaDve** [comment]
> Claims that "endless:GNOME" is not supported so I can't test it easily locally on the machine I have here. Endless is very GNOMEy so you might want to relax https://github.com/SeaDve/Kooha/blob/152d70d029270c92673b6d498e3f5ecb35e9c76f/src/window.py#L73 a little.

I'll work on it

**Comment by SeaDve** [comment]
Hi, not sure if this the right place to ask it, but for some reason, the images are not showing on the flathub page.
https://flathub.org/apps/details/io.github.seadve.Kooha
image

**Pull request closed without merging**
