### PR TITLE
Rename kmcaster

### PR DESCRIPTION
**Pull request by Yajo**
Rename from io.github.davejarvis.kmcaster (created recently in #2165) to com.whitemagicsoftware.kmcaster

Respecting original author's will, expressed in https://github.com/DaveJarvis/kmcaster/issues/10#issuecomment-805007010.

After merging this PR and creating the renamed repo:

- [ ] Merge https://github.com/flathub/io.github.davejarvis.kmcaster/pull/1.
- [ ] Archive https://github.com/flathub/io.github.davejarvis.kmcaster repo.

The contents of this PR are basically the same as #2165, but with the rename applied.

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/DaveJarvis/kmcaster/issues/1
- [x] ~~I~~ @DaveJarvis owns the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* Patches have not been yet moved upstream because I didn't have time. I prefer to get the app packaged quickly and I will upstream those later. Progress can be followed in https://github.com/DaveJarvis/kmcaster/issues/10.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by DaveJarvis** [comment]
@Yajo, was the license added to the app's appdata file?

The App Maintenance section requires documentation stating how to build the application. Find the instructions at: https://github.com/DaveJarvis/kmcaster/blob/master/BUILD.md

Everything else looks good and I agree to the terms.

**Comment by nedrichards** [comment]
bot, build com.whitemagicsoftware.kmcaster

**Comment by Yajo** [comment]
> was the license added to the app's appdata file?

Yes, you can see it here: https://github.com/flathub/flathub/blob/80c77dc3862f9f823c6c829927d14a3dde5a419b/io.github.davejarvis.kmcaster.metainfo.xml#L7

> The App Maintenance section requires documentation stating how to build the application.

I can't find those instructions...

> Find the instructions at: https://github.com/DaveJarvis/kmcaster/blob/master/BUILD.md

Thanks for those docs, I was looking for them when I packaged the 1st time and had to make a guess on the subject. Very helpful indeed 😊 

However, the app is not specifically being built here. Instead, I'm repackaging the binary you release upstream. Read the story in https://github.com/flathub/flathub/pull/2165#issuecomment-803082132 if you're interested. Basically, I'll be able to build here when https://github.com/flatpak/flatpak-builder-tools/issues/37 is fixed. I'm not a java dev, so I'm not the best one to fix it myself... 🤷🏼‍♂️ 

---


So, can we merge this one?

**Comment by barthalion** [comment]
@Yajo Make sure to EOL the old one, specifically using both `end-of-life` for deprecation message and `end-of-life-rebase` to set the new ID. See https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life

/merge @DaveJarvis

**Comment by Yajo** [comment]
Yes, I'll merge https://github.com/flathub/io.github.davejarvis.kmcaster/pull/1 as soon as this one is merged. Or should I merge it now?

**Comment by Yajo** [comment]
Please, some maintainer could archive the https://github.com/flathub/io.github.davejarvis.kmcaster repo? Thanks.

**Pull request closed without merging**
