### PR TITLE
Add io.freetubeapp.FreeTube

### PR DESCRIPTION
**Pull request by mat8913**
https://freetubeapp.io/

### CODE REVIEW

**Comment by mat8913** [comment]
bot, build io.freetubeapp.FreeTube

**Comment by nedrichards** [comment]
bot, build io.freetubeapp.FreeTube

**Comment by mat8913** [comment]
I have gotten permission from upstream: https://github.com/FreeTubeApp/FreeTube/pull/244#issuecomment-476712078

**Comment by nedrichards** [comment]
Cool, I'll try and do a final manual check of the test build later but otherwise this lgtm.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/io.freetubeapp.FreeTube

**Pull request closed without merging**
