### PR TITLE
se.emijoh.mpw

### PR DESCRIPTION
**Pull request by emiljoha**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build se.emijoh.mpw

**Comment by emiljoha** [comment]
bot, build se.emijoh.mpw

**Comment by emiljoha** [comment]
bot, build se.emijoh.mpw

**Comment by emiljoha** [comment]
bot, build se.emijoh.mpw

**Comment by barthalion** [comment]
As it is, it's just simpler to skip the appdata check like here: https://github.com/flathub/org.xiphos.Xiphos/commit/c5dee73ae0c88fa9e2600b03965cbed34d41e42d

Components that are not `desktop-application` are currently not visible on https://flathub.org but we're going to change that eventually.

**Comment by barthalion** [comment]
Oops, wrong button.

**Comment by emiljoha** [comment]
bot, build se.emijoh.mpw

**Comment by emiljoha** [comment]
bot, build se.emijoh.mpw

**Comment by emiljoha** [comment]
@barthalion 

> As it is, it's just simpler to skip the appdata check like here: flathub/org.xiphos.Xiphos@c5dee73

Nice, thanks!

>Components that are not desktop-application are currently not visible on https://flathub.org but we're going to change that eventually.

I think that is fair, its not at all evident how to do that in a good way.

**Pull request closed without merging**
