### PR TITLE
Add io.github.david_swift.Flashcards

### PR DESCRIPTION
**Pull request by david-swift**
### Please confirm your submission meets all the criteria

Please describe your application briefly below.

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I have [built][build] and tested the submission locally.
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/david-swift/Memorize/commits?author=david-swift
- [X] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by david-swift** [comment]
bot, build io.github.david_swift.Flashcards

**Comment by david-swift** [comment]
Installation via the testing repository works as expected.

**Comment by david-swift** [comment]
bot, build io.github.david_swift.Flashcards

**Comment by hfiguiere** [comment]
This is missing:

> Please describe your application briefly below.

**Comment by david-swift** [comment]
Ah sorry, I directly jumped to the check boxes 🙈.
Is this enough as a description?

> A native GNOME app for organizing and studying flashcards

**Comment by david-swift** [comment]
Thank you!

**Pull request closed without merging**
