### PR TITLE
supersedes org.racket_lang.DrRacket

### PR DESCRIPTION
**Pull request by capfredf**
Based on feedback from the Racket community, the entry point is preferred to be `racket`, which is consistent with other Racket distributions. However, using the new entry point with the old application id means that `flatpak run org.racket_lang.DrRacket` opens a repl, which is very likely to throw users off.

Therefore, the new application is created. The old application will later be declared EOL.

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by capfredf** [comment]
Based on the feedback from the Racket community, the entry point is preferred to
be `racket`, which is consistent with other Racket distributions. However, using
the new entry point with the old application id means that `flatpak run
org.racket_lang.DrRacket` opens a repl, which is very likely to throw users off.

Therefore, the new application is created. The old application will later be
declared EOL.

**Comment by capfredf** [comment]
bot, build org.racket_lang.Racket

**Comment by barthalion** [comment]
I don't think I get the point, and even more so I'm disappointed this needs renaming a day after it has been merged. Renames are not something to be done on a whim, and it sounds like the community could be asked for opinion before this has been published.

Make sure to EOL the old ref as described in the docs, and please open a separate issue about archiving the old repo.

/merge

**Comment by capfredf** [comment]
@barthalion my bad. I didn't know the id was not changeable. I thought I could change everything later after the app was published. I am sorry for causing any trouble

**Comment by barthalion** [comment]
This is not a trouble per se, it's just inconvenient to users when ID changes, and also means I need to archive the repo.

**Pull request closed without merging**
