### PR TITLE
READY: Add io.github.veusz.Veusz

### PR DESCRIPTION
**Pull request by kevinsmia1939**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/veusz/veusz/issues/523
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by kevinsmia1939** [comment]
> ### Please confirm your submission meets all the criteria
> 
>     * [x]  I have read the [App Requirements](https://github.com/flathub/flathub/wiki/App-Requirements) and [App Maintenance](https://github.com/flathub/flathub/wiki/App-Maintenance) pages.
> 
>     * [x]  My pull request follows the instructions at [App Submission](https://github.com/flathub/flathub/wiki/App-Submission).
> 
>     * [x]  I am using only the minimal set of permissions. _(If not, please explain each non-standard permission.)_
> 
>     * [x]  All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
> 
>     * [ ]  I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
> 
>     * [ ]  I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
> 
>     * [x]  Any additional patches or files have been submitted to the upstream projects concerned. _(If not, explain why.)_

**Comment by kevinsmia1939** [comment]
bot, build io.gitHub.veusz.Veusz

**Comment by kevinsmia1939** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
The build fail because this error, which is also the same error for SciDAVis https://github.com/flathub/flathub/pull/2253
`sip: Unable to find file "QtCore/QtCoremod.sip"`

I was unable to solve it until now. It probably the issue about how python-sip is build.

**Comment by kevinsmia1939** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
I don't understand the error.

**Comment by barthalion** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
Waiting for dev to reply about some python modules.
https://github.com/veusz/veusz/issues/527

**Comment by hfiguiere** [comment]
I can find astropy there https://pypi.org/project/astropy/#files

**Comment by kevinsmia1939** [comment]
> I can find astropy there https://pypi.org/project/astropy/#files

I was experimenting on my local machine. I add astropy, but Veusz won't see it. I will upload my manifest.

**Comment by kevinsmia1939** [comment]
bot, build io.github.veusz.Veusz

**Comment by hfiguiere** [comment]
`flatpak-builder-tools` is usefull for this. `flatpak-pip-generator` can generate a manifest fragment for flatpak.

**Comment by kevinsmia1939** [comment]
Thanks will try it out.

**Comment by hfiguiere** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
bot, build io.github.veusz.Veusz

**Comment by barthalion** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
I can't get python-iminuit to build, no clue why.

**Comment by kevinsmia1939** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
bot, build io.github.veusz.Veusz

**Comment by kevinsmia1939** [comment]
This should be ready now.

**Comment by barthalion** [comment]
bot, build io.github.veusz.Veusz

**Comment by barthalion** [comment]
Hey @korintje @jeremysanders, would you be interested in co-maintaining your app on Flathub? I assume Kevin will be doing the majority of involved work, but one of our goals is to be a platform for application developers, so it would be nice to give you write access just in case.

**Comment by jeremysanders** [comment]
@barthalion Ok - you can list me. I plan to make a new Veusz release at some point in the next few weeks, BTW.

**Pull request closed without merging**
