### PR TITLE
 Initial manifest for com.github.labyrinth_team.labyrinth

### PR DESCRIPTION
**Pull request by cosimoc**

### CODE REVIEW

**Comment by takluyver** [comment]
I don't know if Flatpak has a rule about this, but should the app ID be `io.github...` rather than `com.github...`? `github.io` is the domain that projects can use for their own website (although Labyrinth doesn't use it). Maybe this doesn't matter in practice, though.

**Comment by cosimoc** [comment]
There seem to be both kind of app IDs in use on Flathub... Here I went with `com.github` because like you say there is no website associated to the project.

**Comment by barthalion** [comment]
bot, build com.github.labyrinth_team.labyrinth

**Comment by barthalion** [comment]
Fails to build on aarch64: https://flathub.org/builds/#/builders/36/builds/290

**Comment by nedrichards** [comment]
Specifically, replicating the changes to libglade in this commit should fix it. https://github.com/flathub/org.gnucash.GnuCash/commit/f01f9a6805c9871023f425bcb7daae58e400395a

**Comment by cosimoc** [comment]
Thanks, pushed a commit for that.

**Comment by barthalion** [comment]
bot, build com.github.labyrinth_team.labyrinth

**Comment by barthalion** [comment]
Repository has been created: https://github.com/flathub/com.github.labyrinth_team.labyrinth

@takluyver, make sure to accept the invitation to be able to push changes there.

Thanks!

**Pull request closed without merging**
