### PR TITLE
Add org.openclonk.OpenClonk

### PR DESCRIPTION
**Pull request by jcaesar**

### CODE REVIEW

**Comment by jcaesar** [comment]
Ah, I'm very sorry but I just learned that we messed up with 8.1, and it may not build/work for architectures other than x86_64… Feel free to either leave  this on hold till we fix that or ignore other architectures for now.

**Comment by TingPing** [comment]
bot, build org.openclonk.OpenClonk

**Comment by nedrichards** [comment]
bot, build org.openclonk.OpenClonk

**Comment by ramcq** [comment]
bot, build org.openclonk.OpenClonk

**Comment by TingPing** [comment]
bot, build org.openclonk.OpenClonk

**Comment by TingPing** [comment]
Builds and everything looks good at glance. Before merging can you just give the final go over that everything is working (desktop file, saving configs, etc) and you are satisfied with the current state?

**Comment by jcaesar** [comment]
@TingPing: I think I have everything.

**Comment by nedrichards** [comment]
bot, build org.openclonk.OpenClonk

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.openclonk.OpenClonk

**Pull request closed without merging**
