### PR TITLE
Add com.tutanota.Tutanota

### PR DESCRIPTION
**Pull request by valentindavid**
Note that the `flatpak-npm-generator.py` is modified from https://github.com/flatpak/flatpak-builder-tools/blob/master/npm/flatpak-npm-generator.py to fix an issue with git urls using branch names. I shall make a merge request there.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.tutanota.Tutanota

**Comment by valentindavid** [comment]
I think I fixed compilation on other architectures. It worked for i386.

**Comment by nedrichards** [comment]
bot, build com.tutanota.Tutanota

**Comment by nedrichards** [comment]
@valentindavid fwiw you can run the bot commands as well if you wish these days.

**Comment by valentindavid** [comment]
bot, build com.tutanota.Tutanota

**Comment by nedrichards** [comment]
@valentindavid have you discussed with upstream if they'd like to be involved. We want to see that before we merge.

**Comment by barthalion** [comment]
@valentindavid It's enough to open an issue in upstream repository just to get some visibility.

**Comment by valentindavid** [comment]
Sorry. I did not get the time to follow up. I commented on the currently opened issue about flatpak.
https://github.com/tutao/tutanota/issues/986

**Comment by valentindavid** [comment]
@charlag I have updated the version in this MR.

I do not think we need integrate the whole flatpak build into your code. But I will certainly make pull requests to add some support for plain directory releases in your `dist.js`. For the moment I use patches.

**Comment by valentindavid** [comment]
bot, build com.tutanota.Tutanota

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.tutanota.Tutanota

**Comment by nedrichards** [comment]
@charlag i've sent you an invitation to the repo, let me know any more usernames we need to add from upstream.

**Comment by charlag** [comment]
@nedrichards thanks. We would kindly ask you to add @mpfau @armhub @bedhub and @ganthern

**Comment by barthalion** [comment]
Invitations sent. Make sure to accept them to get write access to the repo.

**Pull request closed without merging**
