### PR TITLE
Add net.sourceforge.dmidiplayer

### PR DESCRIPTION
**Pull request by pedrolcl**
initial commit

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions.
- [x] All assets referenced in the manifest are redistributable by any party.
- [x] I am an upstream contributor to the project.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by pedrolcl** [comment]
bot, build net.sourceforge.dmidiplayer

**Comment by nedrichards** [comment]
This is a Qt app right? Any special reason it doesn't support wayland or file access portals? Not a blocker, just interested. Other than that lgtm.

**Comment by hfiguiere** [comment]
A lot of Qt app bug with Wayland (at least within Mutter).

Actually by default Wayland QPA should be disabled on such sessions except that the KDE sdk revert the patch.

(I haven't check this one)

**Comment by pedrolcl** [comment]
@nedrichards: This flatpak is modelled after the VMPK one by @hfiguiere, both applications depending on Drumstick. So, I really didn't think too much about Wayland or Portals, I've simply duplicated that part. What I know for sure is that VMPK needs XCB/X11 as a hard dependency, but this probably can be relaxed in dmidiplayer in the future (will need some work, though). On the other hand, dmidiplayer reads more file types. Exactly like VMPK, this program needs to load soundfont files (usually without opening the file open dialog or any other user interaction) but also MIDI/Karaoke and Cakewalk files provided in the command line, contained in playlist files, after an open file dialog, or a drag&drop operation from the file manager.

**Comment by hfiguiere** [comment]
I had disabled wayland on VMPK because there was a bug with menus not being position properly bug that occured only with Wayland.

However
1. it's possible the bug is fixed in more recent Qt 
2. I tried dmidiplayer with `--socket=wayland` and it seemed to work ok.

In the latter case, there is still the classic `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`, but beside spaming the console it's usually harmless (and absolutely not specific to this app)

**Comment by pedrolcl** [comment]
@hfiguiere : when running vmpk with `--socket=wayland`, the worst problem is that the option "Raw Computer Keyboard" does not work at all. This option is very important for users using non-English national keyboard layouts with diacritics (dead keys), because it allows mapping such keys for note input. On the other hand, in dmidiplayer that is not an issue, and I can confirm it works well with it.

I've tested the flatpak in Fedora 34 and Ubuntu 21.04, with different results. The sound in Fedora 34 doesn't work at all most of the time, and changing the synth backend freezes the application. In Ubuntu 21.04 I've not observed this problem.

**Comment by barthalion** [comment]
/merge

Feel free to address adding `--socket=wayland` in the newly created repo. Thanks!

**Pull request closed without merging**
