### PR TITLE
Add org.kde.telly-skout.yml

### PR DESCRIPTION
**Pull request by plata**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by plata** [comment]
Not sure about the domain part. The app is released as part of Plasma Mobile Gear.

**Comment by travier** [comment]
CC @flathub/kde

**Comment by hfiguiere** [comment]
```
error: /srv/buildbot/worker/build-x86_64-5/build/builddir/export/share/icons/hicolor/scalable/apps/org.kde.telly-skout.svg is not a valid icon: Expected a square icon but got: 134x99
```

**Comment by plata** [comment]
Is there any reasonable way how I can fix this problem for the already released version? Unfortunately, the KDE Flatpak CI didn't complain.

**Comment by hfiguiere** [comment]
a patch, like anywhere else.

**Comment by plata** [comment]
bot, build org.kde.telly-skout

**Comment by plata** [comment]
bot, build org.kde.telly-skout

**Comment by hfiguiere** [comment]
```
builddir/files/share/appdata/org.kde.telly-skout.appdata.xml: FAILED:
• style-invalid         : Not enough <screenshot> tags, minimum is 1
• tag-missing           : <release> required
• tag-missing           : <url> is not present
Validation of files failed
```

**Comment by plata** [comment]
bot, build org.kde.telly-skout

**Comment by plata** [comment]
bot, build org.kde.telly-skout

**Comment by plata** [comment]
bot, build org.kde.telly-skout

**Comment by plata** [comment]
bot, build org.kde.telly-skout

**Comment by plata** [comment]
bot, build org.kde.telly-skout

**Comment by plata** [comment]
```
Traceback (most recent call last):
  File "/app/bin/flat-manager-client", line 36, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```
How to fix this?

**Comment by hfiguiere** [comment]
@barthalion any idea ? ^^^

**Comment by barthalion** [comment]
bot, build org.kde.telly-skout

**Comment by travier** [comment]
Manifest LGTM. We usually use the JSON format but we should we able to move to YAML now that we're massively using the checker for updates. @tsdgeos How do you feel about that?

Application not yet tested.

**Comment by tsdgeos** [comment]
i'd honestly be happier with json, but i can live with this being yml

App seems to start fine

**Pull request closed without merging**
