### PR TITLE
Add com.fightcade.Fightcade.Wine.yml

### PR DESCRIPTION
**Pull request by Pobega**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** **(Does this apply to the extension (e.g. Wine devs?), or do I already pass this due to having permission from Fightcade devs?)**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge). **(Again, unsure how to answer this one - I already use com.fightcade.Fightcade with permission from the Fightcade team, so I assume this falls under that?)**
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Pobega** [comment]
This adds a Wine extension for com.fightcade.Fightcade.

Wine is optional for certain emulators but should be installed by default. Unfortunately building wine as part of the main Flatpak causes updates to take up to ~10 hours to propagate which is unsatisfactory since being out of date breaks usability.

WoW64 is required which is why the build code is so wacky.

I'm also not sure if this will just build as-is since the `stable` version of `com.fightcade.Fightcade` currently doesn't have the `/app/wine` extension point created (the `beta` branch does), so I'm not sure the best way to go about testing this without pushing breaking changes to stable.

**Comment by Pobega** [comment]
bot, build com.fightcade.Fightcade.Wine

**Comment by gasinvein** [comment]
If you want to build with FAudio (or with any 32-bit dependency from the app buindle), you'll likely need to add
```yaml
ldflags: -L/app/lib32 -Wl,-z,relro,-z,now -Wl,--as-needed
ldflags-override: true
```
to `build-options` of the 32-bit wine module.

**Comment by gasinvein** [comment]
> why are the builders looking for a 128x128 icon?

Just set `skip-icons-check` to `true` in `flathub.json`.

**Comment by Pobega** [comment]
bot, build com.fightcade.Fightcade.Wine

**Comment by Pobega** [comment]
bot, build com.fightcade.Fightcade.Wine

**Pull request closed without merging**
