### PR TITLE
Add io.github.MrPiggy92.ScriptedJourneys

### PR DESCRIPTION
**Pull request by MrPiggy92**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly.
ScriptedJourneys is a text-based adventure game where players can explore various maps, solve puzzles, and embark on exciting quests. The game features rich storytelling and a variety of maps to choose from, offering a unique experience each time you play. Discover hidden secrets and unravel mysteries in this engaging adventure.

- [X] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read the and followed all the [Submission and licence requirements][reqs].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:**

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by MrPiggy92** [comment]
So I should rebase it on _your_ new-pr branch, or should I commit everything to _my_ new-pr branch?

Also, the manifest requires all the source code to be in the correct location so I can't remove the source code or it won't build correctly.

This is my first time submitting to Flathub so I don't really know what to do; could you give me some help with anything that may need fixing please?

**Comment by bbhtt** [comment]
Source code should be hosted on a code forge like GitHub Gitlab Codeberg etc. not on the PR.

Once source code is removed use it as a git source in the manifest https://docs.flatpak.org/en/latest/module-sources.html#git-sources

Once that is done, open the PR against `new-pr` with just the manifest.

**Comment by MrPiggy92** [comment]
I've updated it, should I start a new PR or will this one continue to be used?

Thanks for the help, by the way.

**Comment by bbhtt** [comment]
Yea.

Clone your fork of this repo. Then switch to the new-pr branch: `git checkout new-pr`, then create a branch for your app `git checkout -b your_branch_name`.

Then commit the manifest and push it.

**Comment by hfiguiere** [comment]
> I've removed the source code,

Doesn't look like it:

image

**Pull request closed without merging**
