### PR TITLE
add com.endlessnetwork.missilemath

### PR DESCRIPTION
**Pull request by alexthemighty**
submission of Missile Math game.  Thanks again for your time and patience as I get the pile of these submitted. Almost done!

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build com.endlessnetwork.missilemath

**Comment by LeandroStanger** [comment]
FAILURE
https://flathub.org/builds/#/builders/32/builds/2112
```
Can't load 'com.endlessnetwork.missilemath.json': Failed to open file “/srv/buildbot/worker/download-sources/build/com.endlessnetwork.missilemath.json”: No such file or directory
```

**Comment by LeandroStanger** [comment]
bot, build com.endlessnetwork.missilemath

**Comment by LeandroStanger** [comment]
bot, build com.endlessnetwork.missilemath

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.endlessnetwork.missilemath

**Pull request closed without merging**
