### PR TITLE
Add io.github.cleomenezesjr.aurea

### PR DESCRIPTION
**Pull request by CleoMenezesJr**
Aurea is a simple preview banner made to read metainfo files from Flatpak apps and represent them as they would on Flathub.

### Please confirm your submission meets all the criteria

- [x] Please describe your application briefly.
- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- - home: the file dialog returns the temp dir, the app needs the real file path
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an author/developer/upstream contributor of the project.
- [x] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by CleoMenezesJr** [comment]
bot build io.github.clemenezesjr.aurea

**Comment by CleoMenezesJr** [comment]
bot, build io.github.cleomenezesjr.aurea

**Comment by hfiguiere** [comment]
This is missing

> Please describe your application briefly.

**Comment by CleoMenezesJr** [comment]
bot, build io.github.cleomenezesjr.aurea

**Comment by CleoMenezesJr** [comment]
> This is missing
> 
> > Please describe your application briefly.

Sorry. Fixed

**Comment by CleoMenezesJr** [comment]
bot, build io.github.cleomenezesjr.aurea

**Comment by bbhtt** [comment]
bot, build io.github.cleomenezesjr.aurea

**Pull request closed without merging**
