### PR TITLE
Create io.github.TheAssassin.AppImageLauncher.yml

### PR DESCRIPTION
**Pull request by prateekmedia**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/TheAssassin/AppImageLauncher/issues/428#issuecomment-952059215
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Lunarequest** [comment]
This can not be flatpaked as appimage launcher depends on the kernel FUSE apis.

**Comment by prateekmedia** [comment]
@Lunarequest maybe talk-name or system-talk-name can be used to connect with fuse kernel module.

**Comment by barthalion** [comment]
I'm not interested in deciphering someone else's C++ code, but as long as all it does is executing an appimage with some switch to extract desktop file and icon, it can be done with `flatpak-spawn`.

@prateekmedia Kernel modules aren't D-Bus interfaces so in no way you can achieve anything this way.

**Comment by Lunarequest** [comment]
You can't build it without having acess to kernel modules which isn't allowed by flatpak. I have tried a few times but until libappimage stops depending on squashfuse(which is probably never) this isn't a viable  flatpak

**Comment by gasinvein** [comment]
> it can be done with `flatpak-spawn`.

An unofficial flatpak package of an app that downloads and launches other arbitrary applications, have permission to escape the sandbox? Please, no.

**Comment by prateekmedia** [comment]
This doesn't seem feasible and supportive to flatpaks sandbox architecture, if anyone wants to build this then they can continue working on my flatpak manifest or create their own.

**Pull request closed without merging**
