### PR TITLE
Wasabi Wallet

### PR DESCRIPTION
**Pull request by proletarius101**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/zkSNACKs/WalletWasabi/issues/726#issuecomment-804800168
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by proletarius101** [comment]
bot, build io.wasabiwallet.WasabiWallet

**Comment by proletarius101** [comment]
bot, build io.wasabiwallet.WasabiWallet

**Comment by proletarius101** [comment]
bot, build io.wasabiwallet.WasabiWallet

**Comment by proletarius101** [comment]
bot, build io.wasabiwallet.WasabiWallet

**Comment by proletarius101** [comment]
bot, build io.wasabiwallet.WasabiWallet

**Comment by barthalion** [comment]
Is anyone from upstream team interested in co-maintaining the app on Flathub?

**Comment by oppilate** [comment]
> Is anyone from upstream team interested in co-maintaining the app on Flathub?

At least no response yet

**Comment by proletarius101** [comment]
> Is anyone from upstream team interested in co-maintaining the app on Flathub?

No response yet unfortunately

**Comment by proletarius101** [comment]
> Is anyone from upstream team interested in co-maintaining the app on Flathub?

I believe that's not blocking?

**Pull request closed without merging**
