### PR TITLE
Scribus (future 1.6)

### PR DESCRIPTION
**Pull request by jurf**
(Take №2, as #332 just went nuts.)

This still builds from master, but I’ll add it here anyway, since:

 * It’ll prevent work duplication (I invested a tonne of time into this)
 * Flathub builds all 4 platforms
 * Feedback is useful

I’ll keep the development over at [jurf/scribus-flatpak](https://github.com/jurf/scribus-flatpak), though I’ll merge the changes here from time to time. Although, sheesh, it took me like half an hour to get it here with the git history.

### CODE REVIEW

**Comment by jurf** [comment]
bot, build net.scribus.Scribus

**Comment by nedrichards** [comment]
Wise move getting builds for the other platforms https://flathub.org/builds/#/builders/2/builds/677

**Comment by jurf** [comment]
Oh for fuck’s sake. A simple rebase melding the last two commits into one to preserve history and GitHub suddenly thinks it has no common history, although, according to git itself, it has.

**Comment by jurf** [comment]
bot, build net.scribus.Scribus

**Pull request closed without merging**
