### PR TITLE
Add com.github.taiko2k.tauonmb

### PR DESCRIPTION
**Pull request by Taiko2k**
I'd like to add my application https://github.com/Taiko2k/TauonMusicBox to flathub. Hopefully I've done this right.

Its a music player. I've been distributing via Flatpak for a while so I'm sure things genreally work, more the matter is if things are up to Flathub standards.

Appdata is upstream. I have the license set to proprietary since there is a closed-source dependency.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.github.taiko2k.tauonmb

**Comment by bilelmoussaoui** [comment]
The desktop file should live upstream. it's an xdg standard, it's used by every distro and packaging system on Linux.

**Comment by nedrichards** [comment]
bot, build com.github.taiko2k.tauonmb

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.github.taiko2k.tauonmb

**Pull request closed without merging**
