### PR TITLE
net.mediaarea.AVIMetaEdit

### PR DESCRIPTION
**Pull request by g-maxime**
Tested with flatpak-builder v0.10.3 and flatpak v0.10.2.1 on Gentoo x86_64

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build net.mediaarea.AVIMetaEdit

**Comment by nedrichards** [comment]
bot, build net.mediaarea.AVIMetaEdit

**Comment by nedrichards** [comment]
Have you sent the appdata patch upstream? If not, it'd be a good idea to.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/net.mediaarea.AVIMetaEdit

**Comment by g-maxime** [comment]
@nedrichards  Thanks

**Pull request closed without merging**
