### PR TITLE
Add org.gnome.NetworkDisplays

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by Lctrs** [comment]
bot build org.gnome.NetworkDisplays

**Comment by Lctrs** [comment]
I tested it locally with the pipewire packages below on my host (Fedora 32 Silverblue) with success : 
```
[jparmentier@localhost org.gnome.NetworkDisplays]$ rpm -qa \*pipewire\*
pipewire-0.3.7-2.fc32.x86_64
pipewire0.2-libs-0.2.7-2.fc32.x86_64
pipewire-libs-0.3.7-2.fc32.x86_64
```

**Comment by nedrichards** [comment]
bot, build org.gnome.NetworkDisplays

**Comment by nedrichards** [comment]
Do you mean that notification is in the appdata description field?

**Comment by Lctrs** [comment]
@nedrichards No it's just in the README of the flatpak wrapper for now.

**Comment by nedrichards** [comment]
I mean, that is effectively invisible to people installing the app. If you think it's critical for users to know before installing then you should put it into the description as well since that's what people see before pressing the install button.

Other than that, Endless OS doesn't ship pipewire at all so I have no means of testing, I'll have to let someone like @bilelmoussaoui review properly ;-)

**Comment by Lctrs** [comment]
bot, build org.gnome.NetworkDisplays

**Comment by Lctrs** [comment]
@nedrichards Warning added in the appdata file. What do you think ? Is the wording good enough ?

**Comment by nedrichards** [comment]
@Lctrs yep, that's fine. 

No obligation copy advice "GNOME Network Displays allows you to cast your desktop to a remote display. Currently implemented is support for casting to Wi-Fi Display capable devices (a.k.a. Miracast)." reads a bit awkwardly, consider maybe "Cast your desktop to a remote display or TV. GNOME Network Displays works with Wi-Fi Display capable devices (a.k.a. Miracast)."

**Comment by Lctrs** [comment]
You should ask @benzae about it :)

**Comment by nedrichards** [comment]
Cool, anything else needed from your perspective @benzea @Lctrs ? Other than, wait an appropriate amount of time for Pipewire 0.3.8 to be installed in places where Pipewire is installed. Which is what? Available in Fedora updates? (debian still has 0.2.x right?)

**Comment by Lctrs** [comment]
I've been using this build all the evening on an up to date Fedora Silverblue 32 so everything is good on my side. Just my fans which spins like crazy when I stream.

**Pull request closed without merging**
