### PR TITLE
Package GStreamer debug viewer

### PR DESCRIPTION
**Pull request by thiblahute**
This is WIP in the sense that we sould wait for GStreamer 1.14 to be released so that we have a proper release of the "package" containing the newly merged appdata file.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build org.freedesktop.GstDebugViewer

**Comment by nedrichards** [comment]
Built fine, as you'd expect: https://flathub.org/builds/#/builders/2/builds/57

**Comment by thiblahute** [comment]
Cool, I will update as soon as we have a release and I pin it in the manifest.

**Comment by nedrichards** [comment]
Congrats on the release!

**Comment by thiblahute** [comment]
> Congrats on the release!

Thanks! - Updated and it is now based on the 3.28 Sdk.

**Comment by thiblahute** [comment]
bot, build org.freedesktop.GstDebugViewer

**Comment by thiblahute** [comment]
I just did that, won't the bot listen to non owners?

**Comment by nedrichards** [comment]
That's it. When you get the repo you can not build to your heart's content.

**Comment by thiblahute** [comment]
All green :-)

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.freedesktop.GstDebugViewer

**Pull request closed without merging**
