### PR TITLE
add com.redis.RedisInsight-v2

### PR DESCRIPTION
**Pull request by proletarius101**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/RedisInsight/RedisInsight/issues/1545
- [x] ~I~ The Upstream owns the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by zalenskiSofteq** [comment]
bot, build com.redis.RedisInsight-v2

**Comment by barthalion** [comment]
/merge @zalenskiSofteq

@zalenskiSofteq, can you please me know if I should invite more people from RedisInsight team to the Flathub repo? Thanks!

**Comment by zalenskiSofteq** [comment]
@barthalion Thanks!
Invite please also @ViktarStarastsenka and @arthosofteq

**Comment by ViktarStarastsenka** [comment]
hi @barthalion :
1. can you please provide admin permissions to ViktarStarastsenka, arthosofteq, and zalenskiSofteq so we can maintain and update official images?
2. could you add the following people (with admin permissions as well) from the RedisInsight team to the FlatHub repo?
K-Jo
ollopaci
uglide

**Pull request closed without merging**
