### PR TITLE
Add com.endlessnetwork.dragonsapprentice

### PR DESCRIPTION
**Pull request by alexthemighty**
Howdy guys, thanks for taking the time to review this submission!

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build com.endlessnetwork.dragonsapprentice

**Comment by LeandroStanger** [comment]
bot, build com.endlessnetwork.dragonsapprentice

**Comment by LeandroStanger** [comment]
@nedrichards 
Captura de tela de 2019-04-03 18-34-45

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.endlessnetwork.dragonsapprentice

**Pull request closed without merging**
