### PR TITLE
Add com.humatarayici.od

### PR DESCRIPTION
**Pull request by VastSea0**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly.
  Hüma Browser is a web browser developed by prioritising user freedom, transparency, and originality. It is an open source, freedom and privacy-oriented experimental web browser.

- [X] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.

- [X] I have read and followed all the [Submission and licence requirements][reqs].

- [X] I have [built][build] and tested the submission locally.

- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:** https://github.com/VastSea0/Huma

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
PR is supposed to be against `new-pr` branch.

**Comment by VastSea0** [comment]
Add com.humatarayici.od on `new-pr` branch.

**Comment by VastSea0** [comment]
Add com.humatarayici.od on new-pr branch.

**Comment by VastSea0** [comment]
> PR is supposed to be against `new-pr` branch.
pr deleted off branch I don't know what to do. Should I send a pull request again?

**Comment by bbhtt** [comment]
Yea you can open a new one.

**Pull request closed without merging**
