### PR TITLE
Add org.gtk.Gtk3theme.Materia-compact

### PR DESCRIPTION
**Pull request by nana-4**
Hello,

Although I have not received any reply at https://github.com/flathub/flathub/pull/186#issuecomment-430832436, would you please add the missing Materia compact variants?

Best Regards.

### CODE REVIEW

**Comment by barthalion** [comment]
testbot, build org.gtk.Gtk3theme.Materia-compact

**Comment by nana-4** [comment]
Sorry for the inconvenience. I made a careless mistake...

I've updated the 3 branches. Please check.

**Comment by nedrichards** [comment]
testbot, build org.gtk.Gtk3theme.Materia-compact

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gtk.Gtk3theme.Materia-compact

**Pull request closed without merging**
