### PR TITLE
Add org.kde.filelight

### PR DESCRIPTION
**Pull request by travier**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
  - Filelight looks at disk space usage thus needs access to the entire directory tree.
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** Part of KDE Flathub team
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by travier** [comment]
Ping @flathub/kde.
The issues mentioned in https://github.com/flathub/flathub/pull/1578#issuecomment-643674418 are still there.
However, we should be able to publish that as beta only and we have a SoK student that may potentially work on fixing that.

**Comment by travier** [comment]
bot, build org.kde.filelight

**Comment by barthalion** [comment]
```
builddir/files/share/appdata/org.kde.filelight.appdata.xml: FAILED:
• attribute-invalid     : <screenshot> width (658) did not match specified (908) [https://cdn.kde.org/screenshots/filelight/filelight.png]
• attribute-invalid     : <screenshot> height (418) did not match specified (866) [https://cdn.kde.org/screenshots/filelight/filelight.png]
```

**Comment by travier** [comment]
I'll patch out the screenshot sizes.

**Comment by travier** [comment]
OK, this one works well (apart from the known issues). I think it would be good to have it in `beta` and then we can work on fixing the UX issues.

**Comment by tsdgeos** [comment]
Works for me

**Pull request closed without merging**
