### PR TITLE
Add org.sugarlabs.BaseApp

### PR DESCRIPTION
**Pull request by tchx84**
**NOTICE**: This is still work on progress.

### CODE REVIEW

**Comment by tchx84** [comment]
bot, build org.sugarlabs.BaseApp

**Comment by bilelmoussaoui** [comment]
You need a flathub.json with skip-appstream-check set to true like https://github.com/flathub/io.elementary.BaseApp/blob/branch/juno-19.08/flathub.json.

**Comment by tchx84** [comment]
A few questions for reviewers:

1. All of these apps will use `"command": "sugarapp"` to run, but it seems I still have to specify it per app. Is there another way to achieve / workaround it?

2.  Similar to the above question, but for `"finish-args"`.

**Comment by tchx84** [comment]
> You need a flathub.json with skip-appstream-check set to true like https://github.com/flathub/io.elementary.BaseApp/blob/branch/juno-19.08/flathub.json.

Thanks!

**Comment by tchx84** [comment]
bot, build org.sugarlabs.BaseApp

**Comment by bilelmoussaoui** [comment]
> A few questions for reviewers:
> 
>     1. All of these apps will use `"command": "sugarapp"` to run, but it seems I still have to specify it per app. Is there another way to achieve / workaround it?
> 
>     2. Similar to the above question, but for `"finish-args"`.

I think it's better to keep those at the application level

**Comment by tchx84** [comment]
I am still deciding whether to use a separate branch (E.g. "0.116" following the sugar release it's based on) or just leave it "stable"... on one hand, I _really_ don't want to overpopulate with many BaseApp versions that _will_ get dropped fast, on the other hand I think making updates too rigid could have risks, but considering current Sugar development state, it's extremely unlikely that future releases will break compatibility at this point. 

So, I am leaning towards just having one "stable" branch.

@TingPing @nedrichards  @barthalion @bilelmoussaoui  any suggestions?

**Comment by nedrichards** [comment]
this is honestly my biggest concern around using baseapps for this kind of workflow. Pragmatically I think it's OK to track a 'stable' but overall I don't like the loss of declarativeness on the app by app level, and it will need co-ordination across all users if it changes.

**Comment by tchx84** [comment]
> this is honestly my biggest concern around using baseapps for this kind of workflow. Pragmatically I think it's OK to track a 'stable' but overall I don't like the loss of declarativeness on the app by app level, and it will need co-ordination across all users if it changes.

I see that too.

Also, I realized that the runtime needs to be defined both in the BaseApp and in every app using that BaseApp. So, I am not exactly sure how the workflow would work if I only have one stable branch. There will be a delay between bumping the runtime version in the BaseApp and then in every app. So. I am not completely sure if having (even if only temporarily) different runtime versions (BaseApp vs app) could cause unexpected/unforeseen issues.

**Comment by tchx84** [comment]
bot, build org.sugarlabs.BaseApp

**Comment by tchx84** [comment]
@bilelmoussaoui how can I get this merged without triggering a build and publish job? I need to mimic what Elementary does of just having a "20.04" branch, and not really a "stable" one.

Mind explaining how these branches are managed in Flathub infra?

**Comment by bilelmoussaoui** [comment]
> 
> 
> @bilelmoussaoui how can I get this merged without triggering a build and publish job? I need to mimic what Elementary does of just having a "20.04" branch, and not really a "stable" one.
> 
> Mind explaining how these branches are managed in Flathub infra?

We can since https://github.com/flathub/flathub/pull/1256#issuecomment-552201762 create a repository and default to an other branch than `master` .

**Comment by bilelmoussaoui** [comment]
It looks good to me, let us know and we can merge it to `branch/20.04`

**Comment by tchx84** [comment]
@bilelmoussaoui great, please do merge.

**Comment by barthalion** [comment]
(For the record, `merge:20.04`, without `branch/` prefix.)

**Comment by bilelmoussaoui** [comment]
> (For the record, `merge:20.04`, without `branch/` prefix.)

We don't need `branch/` prefix anymore?

**Comment by barthalion** [comment]
Yeah, the code adds `branch/` to anything that isn't `beta`.

**Pull request closed without merging**
