### PR TITLE
Import org.kde.kwalletmanager5

### PR DESCRIPTION
**Pull request by travier**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
    - Will likely need more permissions. To be determined
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
    - Member of Flathub's KDE team
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*
    - https://invent.kde.org/utilities/kwalletmanager/-/merge_requests/16

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by travier** [comment]
bot, build org.kde.kwalletmanager5

**Comment by travier** [comment]
CC @flathub/kde

**Comment by travier** [comment]
```
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "org.freedesktop.DBus.Error.ServiceUnknown")
```

Should we run the service inside the Flatpak or outside?

**Comment by hfiguiere** [comment]
looks like missing DBus permissions to me.

**Comment by travier** [comment]
bot, build org.kde.kwalletmanager5

**Comment by travier** [comment]
Added permission will make it talk with the service running on the host, which is likely what we want.

**Comment by aleixpol** [comment]
It seems to run fine just with ` "--talk-name=org.kde.kwalletd5"`.

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
I think this one is ready (I already pushed the change mentioned by Aleix).

**Comment by barthalion** [comment]
bot, build org.kde.kwalletmanager5

**Comment by tsdgeos** [comment]
Seems to work for me

**Pull request closed without merging**
