### PR TITLE
Add Chromium BaseApp

### PR DESCRIPTION
**Pull request by refi64**
### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Erick555** [comment]
Should zypak be there as well?

**Comment by refi64** [comment]
@Erick555 no, the goal is to share this w/ Chromium, which doesn't need Zypak.

**Comment by Erick555** [comment]
Ha, I was sure chromium has zypak but it doesn't, nvm.

BTW, potential problem with baseapp is that it makes more difficult to test & fix issues as you have to merge them first in baseapp then rebuild chromium in order to test the result instead of just spinning chromium build.

Similar setup affects firefox right now where people need to wait till fix makes it to baseapp then wait till ff will be rebuild against new baseapp then find out inital fix was insufficient and the process must be repeated :smile:

**Comment by refi64** [comment]
It's definitely unfortunate, but these modules are going to be split across 6 Flatpaks (Chromium, UCG, Chrome, Chrome Dev [soon], Edge, Brave), so it felt like it was past time to make this a baseapp. IIRC I can still overwrite files in the base, so for quick testing I could copy-paste the module to the individual apps.

**Comment by nedrichards** [comment]
These seem pretty 'restful' dependencies with not super active release cycles but you're sure that these won't cause problems if any of the above apps get out of sync with the main upstream? (I'm always slightly suspicious about baseapps because 'specifying all your dependencies is the point' but I do understand their utility)

**Comment by refi64** [comment]
> but you're sure that these won't cause problems if any of the above apps get out of sync with the main upstream

Almost everything in the Chrome family is dynamically loaded at runtime for compat reasons, so if any dependencies had a major release change or similar, Chrome would likely support both for a *very* long time.

In addition, all the apps this would be used on follow a release cycle very close to upstream, with maybe a 2mo discrepancy between Chrome Dev and Chrome stable being the largest gap.

**Comment by nedrichards** [comment]
That's good to know, and yeah I'm aware my feelings could be accurately be described as "old man rages at cloud" so don't consider this a blocker ;-) 

Reviewing more generally, I assume that the chromium world will at some point move to libsecret 0.20> and at that point it'll get an extra data checker interface.

**Comment by refi64** [comment]
> I assume that the chromium world will at some point move to libsecret 0.20> and at that point it'll get an extra data checker interface.

The older version is used because Chromium requires APIs that the portal backend does not support.

Any updates on merging this? :sweat_smile: would like to get the Chrome-specific version up so the Dev Flatpak can be posted soon.

**Pull request closed without merging**
