### PR TITLE
Add org.learningequality.Kolibri.Plugin.kolibri-dynamic-collections-plugin

### PR DESCRIPTION
**Pull request by dylanmccall**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
   - This pull request is for an extension.
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
   - The upstream project lives at https://github.com/endlessm/kolibri-dynamic-collections-plugin and https://pypi.org/project/kolibri-dynamic-collections-plugin/.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned.
   - I am including a metainfo.xml file to describe the add-on, but that type of desktop metadata does not belong in the upstream project.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build org.learningequality.Kolibri.Plugin.kolibri-dynamic-collections-plugin

**Comment by dylanmccall** [comment]
bot, build org.learningequality.Kolibri.Plugin.kolibri-dynamic-collections-plugin

**Comment by dylanmccall** [comment]
bot, build org.learningequality.Kolibri.Plugin.kolibri-dynamic-collections-plugin

**Comment by dylanmccall** [comment]
bot, build org.learningequality.Kolibri.Plugin.kolibri-dynamic-collections-plugin

**Comment by dylanmccall** [comment]
Oof, sorry about the comment spam there. I had a small misunderstanding with buildbot and an ill-advised rebase. Should all be good now: I added a build step to run `appstream-compose` and updated `flathub.json` to skip the icon check.

**Comment by manuq** [comment]
@barthalion could you approve this extension?

**Pull request closed without merging**
