### PR TITLE
Add org.kde.kpat

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by tsdgeos** [comment]
Let's see if i can trick the bot

**Comment by tsdgeos** [comment]
bot, build org.kde.kpat

**Comment by bilelmoussaoui** [comment]
I'm getting ```
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
```
adding `--device=dri` should fix that.

The icon seems to be missing, per the build logs
```
Not exporting share/icons/hicolor/24x24/apps/kpat.png, non-allowed export filename
Not exporting share/icons/hicolor/22x22/apps/kpat.png, non-allowed export filename
Not exporting share/icons/hicolor/256x256/apps/kpat.png, non-allowed export filename
Not exporting share/icons/hicolor/32x32/apps/kpat.png, non-allowed export filename
Not exporting share/icons/hicolor/128x128/apps/kpat.png, non-allowed export filename
Not exporting share/icons/hicolor/64x64/apps/kpat.png, non-allowed export filename
Not exporting share/icons/hicolor/16x16/apps/kpat.png, non-allowed export filename
Not exporting share/icons/hicolor/48x48/apps/kpat.png, non-allowed export filename
```
You can use `rename-icon` for now and rename them upstream later.

**Comment by tsdgeos** [comment]
> You can use rename-icon for now and rename them upstream later.

I don't see any reason why we would rename the icon upstream later or ever, the icon has the correct name.

Where can I read about this other weird requirement flatpak has about icons?

**Comment by tsdgeos** [comment]
Anyhow, added rename-icon

**Comment by bilelmoussaoui** [comment]
> > You can use rename-icon for now and rename them upstream later.
> 
> I don't see any reason why we would rename the icon upstream later or ever, the icon has the correct name.
> 
> Where can I read about this other weird requirement flatpak has about icons?

Flatpak only exports the files that are prefixed with the app-id. See `/var/lib/flatpak/exports/`

**Comment by bilelmoussaoui** [comment]
bot, build org.kde.kpat

**Comment by nedrichards** [comment]
bot, build org.kde.kpat

**Pull request closed without merging**
