### PR TITLE
Moving Phase2 to new slug

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by Eonfge** [comment]
bot, build io.github.freedoom.Phase2

**Comment by Eonfge** [comment]
@bilelmoussaoui Any known issues with WebM images? They are mentioned in the official standard but this is the first time I see them come by.

**Comment by bilelmoussaoui** [comment]
I have no idea why the webp images are not working. Probably some missing dependencies on https://github.com/flathub/org.freedesktop.appstream-glib.
Any ideas @barthalion ?

**Comment by barthalion** [comment]
I don't think webp was ever supported by appstream-glib.

**Comment by bilelmoussaoui** [comment]
Per the specs 

> The value of the <image/> tag is a direct HTTP/HTTPS URL to a screenshot uploaded to a public location on the web. Images should ideally be provided in the PNG format, however using JPEG or WebP is also fine for images in metainfo files.

**Comment by barthalion** [comment]
Yes, it doesn't imply appstream-glib implements that though. It isn't reference implementation.

**Comment by Eonfge** [comment]
@bilelmoussaoui What is better in this situation? temporary host a different set of images and a custom metainfo.xml? I can image that this won't be added to appstream-glib within the coming weeks, and I rather proceed with this migration.

**Comment by bilelmoussaoui** [comment]
Yes, just ship the same screenshots as pngs and patch the metainfo.

**Comment by bilelmoussaoui** [comment]
bot, build io.github.freedoom.Phase2

**Comment by Eonfge** [comment]
bot, build io.github.freedoom.Phase2

**Pull request closed without merging**
