### PR TITLE
Add org.gnome.FontManager

### PR DESCRIPTION
**Pull request by Eonfge**
Got another one :grinning: 

This time, I figured that it would be nice to add a more advanced font manager to the repository, aptly named: Font Manager.
https://fontmanager.github.io/

A few points I wish to highlight right away:

- Upstream has been super supportive, and over the last couple of weeks we worked together in making the package Flatpak ready: https://github.com/FontManager/font-manager/issues/122
- The application slug is old, and this is one of those few apps that still uses _org.gnome.ID_ from before the time that GNOME had rules about this. This is also the tag that is used on Debian and Fedora, so I figured that it's good for the time being.

### CODE REVIEW

**Comment by Eonfge** [comment]
bot, build Org.gnome.FontManager

**Comment by Eonfge** [comment]
bot, build org.gnome.FontManager

_Damn you, case sensitive everything!_

**Comment by Eonfge** [comment]
bot, build org.gnome.FontManager

Upstream has been informed about the release info

**Comment by nedrichards** [comment]
> [font-manager]-Message: 17:59:30.027: ArchiveManager.vala:59: Install file-roller to enable archive support

Assume this is fine and that you don't need to bundle another app inside. I see you've had the dconf conversation already in https://github.com/FontManager/font-manager/issues/122#issuecomment-657142466

**Comment by JerryCasiano** [comment]
@nedrichards 

It uses dbus to talk to file-roller if it's available, if not it simply doesn't support archive extraction. I don't think that part would correctly in a sandbox environment anyway.

**Comment by bilelmoussaoui** [comment]
> @nedrichards
> 
> It uses dbus to talk to file-roller if it's available, if not it simply doesn't support archive extraction. I don't think that part would correctly in a sandbox environment anyway.

why not? you just need to add a `--talk-name` to finish-args so that your app can communicate over dbus with file-roller

**Comment by JerryCasiano** [comment]
> why not? you just need to add a --talk-name to finish-args so that your app can communicate over dbus with file-roller

Not sure.

Just assuming one or the other would have an issue accessing the temporary folders used during extraction.

But maybe not.

**Comment by Eonfge** [comment]
> > [font-manager]-Message: 17:59:30.027: ArchiveManager.vala:59: Install file-roller to enable archive support
> 
> Assume this is fine and that you don't need to bundle another app inside. I see you've had the dconf conversation already in [FontManager/font-manager#122 (comment)](https://github.com/FontManager/font-manager/issues/122#issuecomment-657142466)

Good catch. Had not seen that yet. Something to look into as well. I made a test-branch but it doesn't seem to work without some upstream tweaks;

https://github.com/Eonfge/flathub/tree/org.gnome.FontManager_experimental

**Comment by Eonfge** [comment]
Following the discussion upstream, I think we're in a good position to release.

Everything critical is working, and the minor things that don't work yet, are not critical enough to hold the release back with.

**Pull request closed without merging**
