### PR TITLE
Add io.github.lainsce.Countdown

### PR DESCRIPTION
**Pull request by lainsce**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build io.github.lainsce.Countdown

**Comment by lainsce** [comment]
I don't get it about this failure on 128×128 icon, I used the correct tools.

**Comment by hfiguiere** [comment]
the appdata file is missing the `launchable`

**Comment by lainsce** [comment]
Isn't it optional? The same structure of the appdata went well for Notejot, another of my apps.

**Comment by barthalion** [comment]
`Icon` field in the desktop file is empty.

**Comment by lainsce** [comment]
It's using meson to add the icon name there based of if it's devel or not, so if not, it should just have the icon name (not Devel icon name).

**Comment by barthalion** [comment]
I'm mentioning this because I've built it locally and checked:

```
> cat builddir/files/share/applications/io.github.lainsce.Countdown.desktop
[Desktop Entry]
Name=Countdown
Exec=io.github.lainsce.Countdown
Icon=
Keywords=event;countdown;days;
Terminal=false
Type=Application
StartupNotify=true
Categories=GTK;Utility;
```

I saw the `@icon@` placeholder in the source code but it's clearly not being expanded to the ID.

**Comment by lainsce** [comment]
Hm, I'll look into it.

**Comment by lainsce** [comment]
bot, build io.github.lainsce.Countdown

**Comment by lainsce** [comment]
Ah, found the error, I wasn't using rename-icon on the flatpak manifest.
The other apps I have on flathub all have it in their manifests.

**Comment by lainsce** [comment]
bot, build io.github.lainsce.Countdown

**Comment by lainsce** [comment]
I don't get it, the meson structure is the same structure for this and Notejot and Khronos for the icon name, so why is this failing and Notejot & Khronos not? :(

**Comment by lainsce** [comment]
I found it :facepalm:

**Comment by lainsce** [comment]
bot, build io.github.lainsce.Countdown

**Comment by lainsce** [comment]
If it fails now, it's cosmic rays, because there's no possible way.

**Comment by barthalion** [comment]
Something went wrong with producing appdata file this time:

```
@app_id@:                          AppData problem: markup-invalid : <id> has invalid character [@]
```

**Comment by lainsce** [comment]
bot, build io.github.lainsce.Countdown

**Comment by lainsce** [comment]
Sometimes things like these are a cat and mouse game to find what changed and what the build files need to change to...

**Comment by lainsce** [comment]
Heh, guess the bot never went on to start building

**Comment by lainsce** [comment]
bot, build io.github.lainsce.Countdown

**Pull request closed without merging**
