### PR TITLE
Add org.octave.Octave_BLAS_64.

### PR DESCRIPTION
**Pull request by siko1056**
This is the renamed PR of #1366.

All changes from #1366 are incorporated here.  Sorry for the noise with a new PR.

### CODE REVIEW

**Comment by nedrichards** [comment]
@mtmiller at https://github.com/flathub/flathub/pull/1366#issuecomment-585426586 yes - I'm not convinced at all that this should be a separate app or available separately. Feels like the main app should just be like this, or not.

**Comment by barthalion** [comment]
bot, build org.octave.Octave_BLAS_64

**Comment by barthalion** [comment]
I'll go with assumption that if @siko1056 found it worth submitting, there's apparently a valid use case.

**Comment by siko1056** [comment]
Thanks @barthalion .  In the long term, say one to three years, distributions and Octave will use 64-bit indexing for BLAS by default as machines and problem sizes grow, rather than shrink.  And this project will retire then.

At some point such builds must become easily available to a larger number of users, to find potential regressions, gain acceptance.  And flatpak is a smoothly working solution for this case for Linux.

**Comment by bilelmoussaoui** [comment]
This should contain a flathub.json to limit the build platforms to x86_64.

**Comment by siko1056** [comment]
@bilelmoussaoui Sorry for the failed builds, does https://github.com/flathub/flathub/pull/1368/commits/580542aab7c07e67ac55b1375e1c4f7c563ebff3 do it?

**Comment by bilelmoussaoui** [comment]
bot, build org.octave.Octave_BLAS_64

**Comment by nedrichards** [comment]
> I'll go with assumption that if @siko1056 found it worth submitting, there's apparently a valid use case.

I don't disagree with your point, but from what I can see the valid use case seems to be either "this should be a compilation option that replaces the current version" or "this is literally why flathub has a beta channel because this is not stable tested software". I'm not going to sit here and block it if people disagree, but I'd certainly be keen to think carefully.

**Pull request closed without merging**
