### PR TITLE
Create com.github.alecaddd.taxi.json

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Another elementary app that works pretty well without the elementary's GTK+ theme.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Do not merge yet. The application runs without any issue, but it seems that Glib.File.mount_enclosing_volume doesn't work on a sandboxed env. If you guys have any idea how to fix this, let me know, please. Thanks!

**Comment by nedrichards** [comment]
bot, build com.github.alecaddd.taxi

**Comment by bilelmoussaoui** [comment]
Builds successfully. But I don't have any idea why GLib fails to mount those URIs. Don't know If it requires a patch upstream on flatpak or GLib.

**Comment by nedrichards** [comment]
I believe that mounting a filesystem isn't something you can do from inside the flatpak sandbox - but could be wrong.

**Comment by bilelmoussaoui** [comment]
Maybe someone could give us an information about that? Just to know if I have to patch that upstream with a proper solution instead of using GLib's mount functions

**Comment by bilelmoussaoui** [comment]
@alexlarsson  @TingPing  Can you guys help with this? Thanks!

**Comment by bilelmoussaoui** [comment]
@barthalion Do you have any idea if it's possible to mount anything from a sandboxed env?

**Comment by barthalion** [comment]
Poked Alex on IRC about it.

**Comment by alexlarsson** [comment]
I think you might need to add gvfs access (`--talk-name=org.gtk.vfs.*`)

**Comment by bilelmoussaoui** [comment]
@alexlarsson  I have added the vfs access but I'm still having the same issue. Tried using `--log

**Comment by alexlarsson** [comment]
What kind of thing are you trying to mount?

**Comment by bilelmoussaoui** [comment]
FTP/SFTP/DAV/AFP

**Comment by alexlarsson** [comment]
Thats weird. The gvfs access *should* be enough for those. What kind of errors do you get?

**Comment by bilelmoussaoui** [comment]
```ERROR MOUNTING: volume doesn’t implement mount```

**Comment by alexlarsson** [comment]
ah, you're using the freedesktop runtime which doesn't have gvfs in it. You need to bundle the gvfs client libs. Here is an example:
https://github.com/flathub/org.libreoffice.LibreOffice/blob/856dd2822865ddf026f8c0a7e07af6f399e0272b/org.libreoffice.LibreOffice.json#L61

**Comment by LeandroStanger** [comment]
How is the progress of Taxi Flatpak going?

**Comment by bilelmoussaoui** [comment]
@LeandroStanger It doesn't work at all currently. I have talked with the maintainer and he is planning on rewriting the backend to make it work correctly with Flatpak too.

**Comment by bilelmoussaoui** [comment]
Closing as the project hasn't seen any progress recently. Will reopen in case that change in the future.

**Pull request closed without merging**
