### PR TITLE
Add org.kicad_pcb.KiCad.Library.Packages3D extension to org.kicad_pcb.KiCad

### PR DESCRIPTION
**Pull request by jmaibaum**
This is meant to reduce the installed size of org.kicad_pcb.KiCad by moving out 5.1GB of mechanical CAD 3D models into this new extension.

Since this depends on a newly defined extension point which is to be added to org.kicad_pcb.KiCad via https://github.com/flathub/org.kicad_pcb.KiCad/pull/34 I don't know how the procedure should go from here?

Can this extension be created and published *before* I have to merge https://github.com/flathub/org.kicad_pcb.KiCad/pull/34 ? Ideally I want to avoid stealing users their MCAD 3D models which would happen when I merge the above PR before the replacement (i.e. via this extension) is available to download.

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build org.kicad_pcb.KiCad.Library.Packages3D

**Comment by jmaibaum** [comment]
https://github.com/flathub/flathub/pull/1539/commits/281a711b4a80902079bd5ba441c8e6e5485664f3 only builds x86_64 for this extension.

Meanwhile, the extension endpoint has been merged to org.kicad_pcb.KiCad (https://github.com/flathub/org.kicad_pcb.KiCad/commit/0fe473da6b75321995c49eadd53571228f1bfdac) so that as soon as the build finishes (approx 2hrs from now), the test build for this extension could be retriggered.

**Comment by jmaibaum** [comment]
Had to restart the build for https://github.com/flathub/org.kicad_pcb.KiCad/commit/0fe473da6b75321995c49eadd53571228f1bfdac

**Comment by jmaibaum** [comment]
Code into main app is merged and available. A new test build can be started.

**Pull request closed without merging**
