### PR TITLE
add com.github.z.Cumulonimbus

### PR DESCRIPTION
**Pull request by prcastro**
The hardest thing about this PR is the developer's user name on github (https://github.com/z-------------). This isn't a valid ID, so I had to simplify it a little bit

### CODE REVIEW

**Comment by nedrichards** [comment]
It'd be great to send the appdata and desktop files upstream for future releases, and it'd be nicer to have a bit of a better description than "Simple podcast app developed with Electron" which doesn't say much about why a user should install it.

This appears to have a package-lock.json upstream as well (although it could be out of date) which means you might be able to experiment with [flatpak-npm-generator](https://github.com/alexlarsson/flatpak-npm-generator) and build it properly on Flathub.

**Comment by nedrichards** [comment]
bot, build com.github.z.Cumulonimbus

**Comment by prcastro** [comment]
Not it has a better description and uses the upstream desktop file. Now I'll try to push the appdata upstream as well. About the flatpak-npm-generator, I'll give it a try.

**Comment by nedrichards** [comment]
Thanks, that's cool. We're looking for feedback on this and are aiming to move all open source Electron apps over to being built from source as tooling allows. I may merge this before you get to that - but I'd love it if you could keep working on the source build in a PR. Since you can run your own test builds using bot, build once the repo is setup.

**Comment by nedrichards** [comment]
bot, build com.github.z.Cumulonimbus

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.github.z.Cumulonimbus

**Pull request closed without merging**
