### PR TITLE
Add io.github.fizzyizzy05.binary

### PR DESCRIPTION
**Pull request by fizzyizzy05**
Hopefully I've done this right, this is the first time I'm making an app and publishing it to flathub. Marking it as draft because I've had issues with metadata, however the xml is fine and i think it might be a cache issue. Please let me know if there's something I'm doing wrong here.

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [N/A] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build io.github.fizzyizzy05.binary

**Comment by hfiguiere** [comment]
AppStream file fail to validate:
```
        "tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]",
        "attribute-missing     : <release> has no timestamp"
```

**Comment by fizzyizzy05** [comment]
Hi, thank you for your reply. I've just updated the metadata for the content rating and release timestamp, I believe this should work.

**Comment by fizzyizzy05** [comment]
Hi, I've just updated the metadata for 0.1.2. It should have the release timestamps and content rating. Thank you.

**Comment by fizzyizzy05** [comment]
bot, build io.github.fizzyizzy05.binary

**Comment by fizzyizzy05** [comment]
Thank you for having a look (I would not have known to run the bot command). I've marked it as ready to review, since the metadata is fine on the build flatpak.

**Comment by barthalion** [comment]
bot, build io.github.fizzyizzy05.binary

**Pull request closed without merging**
