### PR TITLE
Add org.xaraxtreme.XaraLX (xaralx-flatpak)

### PR DESCRIPTION
**Pull request by scx**
**XaraLX** (AKA *Xara Xtreme for Linux*) is a powerful, general purpose vector graphics program.

See also:
http://www.xaraxtreme.org
https://github.com/scx/xaralx-flatpak
https://github.com/scx/flathub/tree/org.xaraxtreme.XaraLX

### CODE REVIEW

**Comment by scx** [comment]
I understand if you think that Flathub is not a right place for programs like this one. However, I would like to use the Flathub infrastructure (the `testbot`) to provide x86_64 binaries for end users.

So, I would like to keep it as it is. A review is not needed, as this pull request won't be merged anyway.

**Comment by scx** [comment]
testbot, build org.xaraxtreme.XaraLX

**Comment by scx** [comment]
testbot, build org.xaraxtreme.XaraLX

**Comment by scx** [comment]
testbot, build org.xaraxtreme.XaraLX

**Comment by barthalion** [comment]
You are abusing the build infrastructure despite being told we are not going to accept it. The only thing it's going to change is that using testbot will ignore non-maintainers like `bot` does.

**Comment by scx** [comment]
@barthalion 

> You are abusing the build infrastructure despite being told we are not going to accept it.

It surprises me that you have not already been expelled from Flathub because of your passively aggressive attitude and acting to the detriment of the community.
Anyway, I fail to see how the normal and reasonable use of the flatbot can be considered as excessive use of the infrastructure.
You should probably blame yourself because you have repeatedly demanded changes that have absolutely no value or sense, and in this way you have been abusing the build infrastructure by yourself.
What is more, less than two weeks ago you didn't mind sharing Flathub's infrastructure with others. Your current attitude only proves your hypocrisy.
https://github.com/flathub/flathub/pull/797#issuecomment-450625072
https://github.com/flathub/flathub/pull/797#issuecomment-450746966
Anyway, I made it clear that I don't expect to merge this PR, but you have ignored my words as you always do.
https://github.com/flathub/flathub/pull/808#issuecomment-453753049

**Pull request closed without merging**
