### PR TITLE
Add com.github.elfenware.badger

### PR DESCRIPTION
**Pull request by pervoj**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link: elfenware/badger#55**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by pervoj** [comment]
bot, build com.github.elfenware.badger

**Comment by pervoj** [comment]
Is there a way to use elementary platform?

**Comment by hfiguiere** [comment]
See how it's done in #2452

**Comment by pervoj** [comment]
bot, build com.github.elfenware.badger

**Comment by pervoj** [comment]
bot, build com.github.elfenware.badger

**Comment by pervoj** [comment]
@hfiguiere Thank you very much!

**Comment by dar5hak** [comment]
Okay, so it's using the Juno base app, but in the stylesheet, I am using variables only available on Odin, so there's a chance it might not look right.

**Comment by sonnyp** [comment]
LGTM on both Adwaita / Adwaita Dark

Screenshot from 2021-08-10 10-33-08

**Comment by dar5hak** [comment]
The “Reminders” label should be an h2 style and the time markers look kinda dim, but otherwise it looks usable. Feel free to merge, and I will try and fix these in a future release.

**Comment by pervoj** [comment]
@dar5hak
> ...and the time markers look kinda dim (is that normal in Adwaita?)

Yes, it's normal in Adwaita:
screenshot

**Comment by dar5hak** [comment]
@nedrichards I know this is sudden, but since elementary AppCenter now supports Flatpak downloads from the web, I have decided to maintain only [that version](https://appcenter.elementary.io/com.github.elfenware.badger/) and sunset the one on Flathub. Mainly because I want to rely on elementary SDK 6 and the niceties it provides.

I will reconsider the decision if the elementary SDK gets published (and maintained) on Flathub some day.

Meanwhile, can you archive the [repository](https://github.com/flathub/com.github.elfenware.badger)? I have already added an EOL message with a link to the maintained version. Thanks and sorry.

**Comment by hfiguiere** [comment]
so basically you just told `aarch64` user they can't use the app anymore since Elementary doesn't build on that.

**Comment by dar5hak** [comment]
@hfiguiere For now. They are doing experimental builds for Pi 4 and Pinebook Pro, so aarch64 support is definitely on the cards ([literally](https://github.com/orgs/elementary/projects/90#card-66324419)).

Till then, you can still use the current version on Flathub.

**Pull request closed without merging**
