### PR TITLE
Add org.freedesktop.Sdk.Extension.qt6

### PR DESCRIPTION
**Pull request by 4c0n**
In order to prevent Qt Creator from rebuilding Qt6 at every change and to make the build of Qt6 more re-usable, I have split off the modules in this Sdk Extension.
It will reduce build time of Qt Creator as requested. It is being used here: https://github.com/flathub/io.qt.QtCreator/blob/use-extension/io.qt.QtCreator.yaml and in order to merge that to the beta branch and test it, I need this package to be available first. 

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Erick555** [comment]
See https://github.com/flathub/flathub/pull/3013#issuecomment-1100066897

**Comment by 4c0n** [comment]
@Erick555 The case is different here, Qt6 needs to be available at all times in the Qt Creator package and not be allowed to  be uninstalled. It's currently part of the Qt Creator package itself and it's causing the build times of that package to be massive and isn't reusable.

**Comment by Erick555** [comment]
Then it absolutely can't be an extension. Extension are optional by flatpak design. You can either bundle it or make a baseapp. Or even better ask for adding missing modules in runtime.

**Comment by 4c0n** [comment]
This way it can be separated, decreasing build times and frequency and be useful to others.

**Comment by Erick555** [comment]
There are better ways to solve the problem. You chose one that doesn't fit. This is my point.

**Comment by 4c0n** [comment]
We disagree on that.

**Comment by Erick555** [comment]
Ok, that's fine. Let's hear opinion from others.

**Comment by hfiguiere** [comment]
is the build relocatable? I'm not even sure. See my other comment.

**Comment by Erick555** [comment]
There is also stability concern regarding to this one as in current form it's going to ship always latest Qt 6.x release and some apps/tools using it may need adjustments for new version especially if they selectively copy extension parts to avoid mismatches. KDE splits every major release (5.x, 6.x).

**Comment by 4c0n** [comment]
According to semantic versioning that would be a minor release and it should be backwards compatible, however in Qt's case it might not always be. However it would be fairly easy to overcome this issue.

**Comment by 4c0n** [comment]
bot, build org.freedesktop.Sdk.Extension.qt6

**Comment by DioEgizio** [comment]
Wanted to say that if this gets merged it'd be epic and highly beneficial for projects using qt6

**Comment by hfiguiere** [comment]
> Wanted to say that if this gets merged it'd be epic and highly beneficial for projects using qt6

There is a qt6 sdk/runtime already. This is something else.

**Comment by 4c0n** [comment]
It actually would be beneficial IMO as it would provide a complete Qt6 package that allows you to use the parts you need without having to figure out how to keep your own Qt modules compatible (ABI) and in sync with the runtime. It would also reduce build times for every app that uses it.

Thank you for expressing your support.

**Comment by Erick555** [comment]
Mentioned use case is exactly why it was [rejected](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/356#note_98819362) in the past so things are going in circle here:



> Using an SDK extension for dependencies is a really really bad UX.
>
> *  All users of it have to fiddle with paths manually
> *  All users of it have to copy the libs into their app
> * They lose automatic updates of dependencies for fixes
> * It makes deduplication less effective
> * The runtime still has to have the Qt extension points itself anyway for themes, platform modules, etc

**Comment by 4c0n** [comment]
Yup you shared one person's opinion and it's not even the actual reason that request was rejected, also we are capable of making other decisions than the Freedesktop project and don't all have to share the same opinion. I'd say those points are pretty debatable as well.
I however have lost hope in this becoming a thing and wish not to waste my time on these type of discussions on PR's with people that are not responsible for merging or denying it, glad you have so much time to spare and I wish you luck with trying to change peoples minds on things where you disagree.

**Comment by Erick555** [comment]
This opinion was from flathub organization [member](https://github.com/orgs/flathub/people).

All I tried is to convince you are wasting your time but somewhat you think I'm wasting it which is quite irony. Anyway the damage was done.

My last suggestion is to use #flatpak matrix channel to get straight to face opinion from flathub members on the matter.

**Comment by da2ce7** [comment]
@4c0n @Erick555 @hfiguiere https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/356#note_1186990257

**Pull request closed without merging**
