### PR TITLE
add com.github.theironrobin.siglo

### PR DESCRIPTION
**Pull request by theironrobin**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build com.github.theironrobin.siglo

**Review by hfiguiere — CHANGES_REQUESTED** [review]

**Comment by hfiguiere** [comment]
AppStram file can't be found. I is either never installed, or doesn't have the proper name.

**Review by alex-startengine — APPROVED** [review]

**Review by alex-startengine — APPROVED** [review]

**Comment by hfiguiere** [comment]
bot, build com.github.theironrobin.siglo

**Comment by hfiguiere** [comment]
There is a warning
```
WARNING: Icon referenced in desktop file but not exported: com.github.theironrobin.siglo
```

Parallel:
```
Exporting share/icons/com.github.theironrobin.siglo.svg
```
This is not the correct path fo the icon.
It should be `share/icons/hicolor/scalable/apps/com.github.theironrobin.siglo.svg`

**Comment by hfiguiere** [comment]
(not sure how the icon validation didn't fail here)

**Comment by theironrobin** [comment]
bot, build com.github.theironrobin.siglo

**Comment by theironrobin** [comment]
@hfiguiere did that address the icon issue?

**Comment by hfiguiere** [comment]
yes it does. (based on the build logs)

**Comment by nedrichards** [comment]
I just pressed the show settings button when launched:

> Start scanning
Bluetooth adapter not ready. Set `is_adapter_powered` to `True` or run 'echo "power on" | sudo bluetoothctl'.
'NoneType' object has no attribute 'get_device_set'
Traceback (most recent call last):
  File "/app/share/siglo/siglo/window.py", line 262, in on_bluetooth_settings_clicked
    subprocess.Popen(["gnome-control-center", "bluetooth"])
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gnome-control-center'


This is obviously not going to work because you're inside the container. You're going to need to detect if you're inside a flatpak and then use flatpak-spawn to launch external commands if you want this to work properly.

**Comment by theironrobin** [comment]
known issue, https://github.com/theironrobin/siglo/issues/84, but thanks for the flatpak-spawn tip

**Pull request closed without merging**
