### PR TITLE
Add com.chatterino.chatterino

### PR DESCRIPTION
**Pull request by ilyazzz**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** [not sure what would be a better way to submit proof](https://i.imgur.com/ofgzpA1.png) (fourtf is the [upstream owner](https://github.com/orgs/Chatterino/people))
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge). [chatterino.com](https://chatterino.com) is owned by the application
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

There's one concern: the build is not fully reproducible, because I haven't found a way to pin git submodules at a specific commit. This is also the reason why the source is a git repo and not a source code archive of a given release.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build com.chatterino.chatterino

**Comment by ilyazzz** [comment]
bot, build com.chatterino.chatterino

**Comment by ilyazzz** [comment]
Waiting for [this](https://github.com/Chatterino/chatterino2/issues/2566) to be resolved.

**Comment by hfiguiere** [comment]
> Waiting for [this](https://github.com/Chatterino/chatterino2/issues/2566) to be resolved.

Is there a problem with checking out the git repository with a specific tag+commit? This is perfectly acceptable for flathub builds.

As for appstream you can still patch locally.

**Comment by ilyazzz** [comment]
@hfiguiere for some reason, flatpak fails to update the submodules:

Doing it manually on a repo works, aka clone the repo, `git checkout v2.2.2` and `git submodule update` works and builds properly

In a flatpak:
```
sources:
- type: git
  url: https://github.com/Chatterino/chatterino2.git
  tag: v2.2.2
```
Gives 
```Cloning into '/home/ilya/dev/pkg/chatterino-flatpak/.flatpak-builder/build/chatterino-8/lib/libcommuni'...
fatal: git upload-pack: not our ref f3e7f97914d9bf1166d349a83d93a2b4f4743c39
fatal: remote error: upload-pack: not our ref f3e7f97914d9bf1166d349a83d93a2b4f4743c39
Fetched in submodule path 'lib/libcommuni', but it did not contain f3e7f97914d9bf1166d349a83d93a2b4f4743c39. Direct fetching of that commit failed.
``` 
on one of the submodules. (Other ones update properly)

**Comment by hfiguiere** [comment]
looks like the submodule commit is gone. Which isn't good.

(github automatic tarballs are mostly useless)

**Comment by ilyazzz** [comment]
Weird, because it works manually:
```
$ git checkout v2.2.2
$ git submodule update
From https://github.com/communi/libcommuni
 * branch            f3e7f97914d9bf1166d349a83d93a2b4f4743c39 -> FETCH_HEAD
Submodule path '../lib/libcommuni': checked out 'f3e7f97914d9bf1166d349a83d93a2b4f4743c39'
```

You can even go to that specific commit that it claims to be absent on github: https://github.com/Chatterino/libcommuni/commits/f3e7f97914d9bf1166d349a83d93a2b4f4743c39

I have also tried doing `git submodule update` manually as a build command, but it looks like there's no network access during the build process (or it's some misconfiguration on my end)

**Comment by hfiguiere** [comment]
> Weird, because it works manually:
> 
> ```
> $ git checkout v2.2.2
> $ git submodule update
> From https://github.com/communi/libcommuni
>  * branch            f3e7f97914d9bf1166d349a83d93a2b4f4743c39 -> FETCH_HEAD
> Submodule path '../lib/libcommuni': checked out 'f3e7f97914d9bf1166d349a83d93a2b4f4743c39'
> ```

It tries to fetch from `https://github.com/Chatterino/libcommuni` instead of the upstream repository (like in your test), which doesn't have the commit, as the `.gitmodules` file can attest. Not sure how to work around that. :-(

> You can even go to that specific commit that it claims to be absent on github: https://github.com/Chatterino/libcommuni/commits/f3e7f97914d9bf1166d349a83d93a2b4f4743c39

I think that here, github is fetching from the upstream repository if needed.

```
$ git clone https://github.com/Chatterino/libcommuni
Cloning into 'libcommuni'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 13444 (delta 0), reused 1 (delta 0), pack-reused 13438
Receiving objects: 100% (13444/13444), 5.61 MiB | 2.45 MiB/s, done.
Resolving deltas: 100% (8208/8208), done.
$ cd libcommuni/
$ git show f3e7f97914d9bf1166d349a83d93a2b4f4743c39
fatal: bad object f3e7f97914d9bf1166d349a83d93a2b4f4743c39
```

> I have also tried doing `git submodule update` manually as a build command, but it looks like there's no network access during the build process (or it's some misconfiguration on my end)

There is no network during the build steps, and even then I'm pretty sure this wouldn't work.

**Comment by hfiguiere** [comment]
```
$ git clone https://github.com/Chatterino/chatterino2
Cloning into 'chatterino2'...
remote: Enumerating objects: 30155, done.
remote: Total 30155 (delta 0), reused 0 (delta 0), pack-reused 30155
Receiving objects: 100% (30155/30155), 8.58 MiB | 1.95 MiB/s, done.
Resolving deltas: 100% (24335/24335), done.
$ cd chatterino2/
$ git submodule init
Submodule 'lib/WinToast' (https://github.com/mohabouje/WinToast.git) registered for path 'lib/WinToast'
Submodule 'lib/libcommuni' (https://github.com/Chatterino/libcommuni) registered for path 'lib/libcommuni'
Submodule 'lib/qBreakpad' (https://github.com/jiakuan/qBreakpad.git) registered for path 'lib/qBreakpad'
Submodule 'lib/qtkeychain' (https://github.com/Chatterino/qtkeychain) registered for path 'lib/qtkeychain'
Submodule 'lib/rapidjson' (https://github.com/Tencent/rapidjson) registered for path 'lib/rapidjson'
Submodule 'lib/serialize' (https://github.com/pajlada/serialize) registered for path 'lib/serialize'
Submodule 'lib/settings' (https://github.com/pajlada/settings) registered for path 'lib/settings'
Submodule 'lib/signals' (https://github.com/pajlada/signals) registered for path 'lib/signals'
Submodule 'lib/websocketpp' (https://github.com/ziocleto/websocketpp) registered for path 'lib/websocketpp'
```

The submodule definitely fetch from https://github.com/Chatterino/libcommuni

**Comment by hfiguiere** [comment]
it's getting weirder. It works if I move HEAD from `master` to `2.2.3-beta2` update the submodule, and then to `2.2.2`.

*sigh*

**Comment by barthalion** [comment]
bot, build com.chatterino.chatterino

**Comment by barthalion** [comment]
Well, the current commit works, so I'm fine with that. Appdata needs fixes though:

```
builddir/files/share/appdata/com.chatterino.chatterino.appdata.xml: FAILED:
• tag-missing           : <release> required
```

If you insist on using stable release, I can try upgrading git on runners but not sure if it's going to help.

**Comment by ilyazzz** [comment]
I'm personally fine with building from git, especially considering there hasn't been a stable release in a while even though the development is active.

I'll add the patches for appdata.

**Comment by ilyazzz** [comment]
bot, build com.chatterino.chatterino

**Comment by barthalion** [comment]
@ilyazzz Should we invite someone additionally from the upstream team?

**Comment by ilyazzz** [comment]
@barthalion I think the current state is acceptable, especially since the upstream dev said that it's not clear when a new stable release will be made.

They have a CI/CD for deploying "nightly" builds (for linux they generate appimages), and I'll look into integrating it with flathub. But for now, this is fine.

**Comment by ilyazzz** [comment]
They've recently merged cmake support in addition to the default qmake, I'll switch the package to it once it has undergone more testing.

**Comment by nedrichards** [comment]
This is asking for GPU access. --device=dri in finish-args will give it.

**Comment by barthalion** [comment]
bot, build com.chatterino.chatterino

**Pull request closed without merging**
