### PR TITLE
imager.

### PR DESCRIPTION
**Pull request by hydra696**
I am a student and I am using Linux for a while. I noticed  there is no good gallery app in Linux. so I coded this app. the name of this app is image imager. it's my first GitHub project.

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Slackadays** [comment]
Is there a manifest here?

**Comment by hydra696** [comment]
Dear Jackson Huff,

Thank you for reaching out to me. To clarify, could you please specify what
you mean by "here"? Are you referring to the pull request or the repository?

Looking forward to your response.

Best regards,
Max Op

**Comment by hfiguiere** [comment]
While you acknowledge to have read it you didn't follow the submission guide:

https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

There is no manifest file in the submission. Instead there is some python which doesn't belong in the submission.

**Comment by hydra696** [comment]
Dear Hubert Figuière,

Thank you for your email regarding my app submission. I apologize for not
following the submission guide and for including python code in the
submission instead of the manifest file.

I appreciate your feedback and will make the necessary changes to the
submission as soon as possible. Thank you for bringing this to my attention.

Best regards,
Max Op

**Comment by hfiguiere** [comment]
Two month without followup. There is nothing to work with.

Feel free to reopen when you actually resolve the issues.

**Pull request closed without merging**
