### PR TITLE
Add org.getmonero.Monero

### PR DESCRIPTION
**Pull request by roundtheworldman**
### Please confirm your submission meets all the criteria

* [Y]  I have read the [App Requirements](https://github.com/flathub/flathub/wiki/App-Requirements) and [App Maintenance](https://github.com/flathub/flathub/wiki/App-Maintenance) pages.

* [Y]  My pull request follows the instructions at [App Submission](https://github.com/flathub/flathub/wiki/App-Submission).

* [Y]  I am using only the minimal set of permissions. _(If not, please explain each non-standard permission.)_

* [Y]  All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.

* [Cant contact developers ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.

* [N]  I own the domain used in the application ID or the domain has a policy for delegating subdomains

* [No Patches]  Any additional patches or files have been submitted to the upstream projects concerned.

### CODE REVIEW

**Comment by roundtheworldman** [comment]
bot, build org.getmonero.Monero

**Comment by roundtheworldman** [comment]
bot, build org.getmonero.Monero

**Comment by roundtheworldman** [comment]
bot, build org.getmonero.Monero

**Comment by roundtheworldman** [comment]
bot, build org.getmonero.Monero

**Comment by roundtheworldman** [comment]
bot, build org.getmonero.Monero

**Comment by roundtheworldman** [comment]
bot, build org.getmonero.Monero

**Comment by hfiguiere** [comment]
#2124 is still active. Can't have two of the same.

**Comment by tommytran732** [comment]
#2124 is added so I think this one should be closed.

**Comment by bilelmoussaoui** [comment]
Thanks @tommytran732

**Pull request closed without merging**
