### PR TITLE
Add org.freedesktop.Sdk.Extension.avr-gcc

### PR DESCRIPTION
**Pull request by ashahir05**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by ashahir05** [comment]
bot, build org.freedesktop.Sdk.Extension.avr-gcc

**Comment by ashahir05** [comment]
bot, build org.freedesktop.Sdk.Extension.avr-gcc

**Comment by ashahir05** [comment]
bot, build org.freedesktop.Sdk.Extension.avr-gcc

**Comment by hfiguiere** [comment]
what is the intent of this SDK since the avr compiler doesn't target any flatpak supported target?

**Comment by tinywrkb** [comment]
I don't see the point of having just the toolchain.  
If you're packaging an AVR SDK, then ship everything that is needed for AVR development, and it would be better to just name it `org.freedesktop.Sdk.Extension.avr`.   
Specifically, this is missing gdb, avrdude, and if it were me packaging this, then I would add a simavr for simulation.  
In fact, I packaged this [here](https://github.com/tinywrkb/flatpaks/blob/master/org.freedesktop.Sdk.Extension.avr/org.freedesktop.Sdk.Extension.avr.yaml) a while back, and tried to make it host architecture agnostic, but I haven't tested that it builds on aarch64.

@hfiguiere this could be useful for any embedded development or simulation app that targets AVR or Arduino, though AFAIK the Arduino IDE Flathub package currently uses a pre-built toolchain.

ping @A6GibKm

**Comment by A6GibKm** [comment]
Yes, arduino requires a very specific set of dependencies shipped by themselves.

**Comment by hfiguiere** [comment]
> @hfiguiere this could be useful for any embedded development or simulation app that targets AVR or Arduino, though AFAIK the Arduino IDE Flathub package currently uses a pre-built toolchain.

Maybe it's not a SDK extension then but rather a "runtime". Not sure we have an extension point for that though.

**Comment by tinywrkb** [comment]
> Yes, arduino requires a very specific set of dependencies shipped by themselves.

And if I understand it correctly, IDE v2 switches to use arudino-cli, the toolchain will be downloaded during run-time and won't be packaged.  

> > @hfiguiere this could be useful for any embedded development or simulation app that targets AVR or Arduino, though AFAIK the Arduino IDE Flathub package currently uses a pre-built toolchain.
> 
> Maybe it's not a SDK extension then but rather a "runtime". Not sure we have an extension point for that though.

I don't think there is a `subdirectories` extension point for the runtime, which would've been nice to have and avoid deploying from SDK extensions to apps (e.g. Java) or using a base app (e.g. Wine).

So if this is not appropriate as SDK extension, and there are no apps that are expected to make use of this extension, the maybe this should be packaged as an app or a base app?

**Comment by tinywrkb** [comment]
I think the best course of action is the following:

1. Show that this would be useful for an actual application.   
It could be a CLI app, avrdude comes to mind.  
It could also be a GUI app, avrdudess seems to be alive, though not very active. I got it to run, though only tesedt that the main UI is loading, you just need to build libgdiplus (with giflib), and manually deploy mono from the mono6 extension (the packaged install script does a poor job). 

2. Create a generic embedded development base app that will have a sdk/toolchain mount point with extension subdirectories enabled (see `man:flatpak-metadata(5)`). This base app could be used to build other toolchains, e.g. `riscv{32,64}-unknown-elf` and `arm-none-eabi`. I might be interested in riscv toolchain for package [Ripes](https://github.com/mortbopet/Ripes).  
I suggest using the KDE runtime, as it will give a good coverage of widget toolkits.  
Also add a few shared libs that are likely will be used by apps. libusb for example.

3. Submit the sdk/toolchain as an extension of the baseapp.  
Try to avoid binary dependency of extension files on libs from the base app to avoid ABI breakage on user installations.

**Comment by ashahir05** [comment]
@hfiguiere this is meant to be a tool used in flatpak'd IDEs and text editors like vscode.

**Pull request closed without merging**
