### PR TITLE
Added io.github.muse_sequencer.Muse

### PR DESCRIPTION
**Pull request by hfiguiere**
This is Muse 4, the newer release of Muse3 already flathub. Upstream changed the app-id, and I changed it again as they no longer have the domain.

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Just a new version of the old app with an ID change**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge). - _**the application ID is renamed to io.github.muse_sequencer.Muse**_ See details https://github.com/muse-sequencer/muse/issues/989
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.musesequencer.Muse4

**Comment by nedrichards** [comment]
Does upstream intend for Muse3 to continue on its own as a parallel installable system or will that be EOLd?

**Comment by hfiguiere** [comment]
The config directory (in XDG) isn't versioned, so it's likely not parallel installable. 

(but different flatpak can)

**Comment by hfiguiere** [comment]
If you think it's better to just keep the old id, I'm ok with that.

**Comment by barthalion** [comment]
I guess the question is whether people would use both or not, and if 3.x is still being maintained. If it's not, it will be tricky to migrate users to new ID.

**Comment by nedrichards** [comment]
But also obviously tricky if the app itself is using the new ID everywhere.

**Comment by hfiguiere** [comment]
I did rename anyway.

Upstream issue. https://github.com/muse-sequencer/muse/issues/989

I will submit a PR.

**Comment by hfiguiere** [comment]
bot, build io.github.muse_sequencer.Muse

**Comment by hfiguiere** [comment]
Upstream: Muse 3.x is EOL, and they are OK with that app-id. (will submit a PR upstream)

I will deprecate Muse3 when this gets merged.

**Comment by hfiguiere** [comment]
PR upstream for the app-id 
https://github.com/muse-sequencer/muse/pull/991

**Pull request closed without merging**
