### PR TITLE
Add Amarok

### PR DESCRIPTION
**Pull request by Mailaender**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. _Please ping them._
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* https://invent.kde.org/multimedia/amarok/-/merge_requests/48

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
cc @flathub/kde

**Comment by nedrichards** [comment]
Put the .service into /app/share/dbus-1/services and it should get exported I believe.

**Comment by Mailaender** [comment]
bot, build org.kde.amarok

**Comment by tsdgeos** [comment]
This would have to go to beta since it's building an "unstable" version of Amarok

Have you explored what is missing because of 

-- The following OPTIONAL packages have not been found:

 * Taglib-Extras
 * Googlemock
 * MySQLe, MySQL Embedded Library (libmysqld), <https://www.mysql.com>
 * LibOFA, Open-source audio fingerprint by MusicIP, <http://code.google.com/p/musicip-libofa/>
   Enable MusicDNS service
 * Ipod, Support Apple iPod/iPad/iPhone audio devices, <http://sourceforge.net/projects/gtkpod/>
 * Loudmouth, Loudmouth is the communication backend needed by mp3tunes for syncing., <http://www.loudmouth-project.org>

And how hard would to get them compiled in?

**Comment by Mailaender** [comment]
I tried `Taglib-Extras` and failed so far, because Taglib seems to be in the SDK, when I install an older version for extras the Amarok compilation will fail. Googlemock is probably just for testing. I can't find MySQLe, but I think we need it. There is an error message at startup. LibOFA is unmaintained and needs patches. gtkpod and loudmouth did not compile.

**Pull request closed without merging**
