### PR TITLE
add org.gtk.Gtk3theme.High-Sierra-Dark flatpak theme

### PR DESCRIPTION
**Pull request by chengjk84**
Here by I attach manifest file for High Sierra Dark theme which compressed version maintain by me at https://github.com/chengjk84/high-sierra-gtk-theme

And the source version maintain by Vince at https://github.com/vinceliuice/Sierra-gtk-theme

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build org.git.Gtk3theme.High-Sierra-Dark

**Comment by nedrichards** [comment]
bot, build org.gtk.Gtk3theme.High-Sierra-Dark

**Comment by chengjk84** [comment]
done building it...

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gtk.Gtk3theme.High-Sierra-Dark

**Pull request closed without merging**
