### PR TITLE
Add org.kryogenix.hushboard

### PR DESCRIPTION
**Pull request by stuartlangridge**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by stuartlangridge** [comment]
bot, build org.kryogenix.hushboard

**Comment by barthalion** [comment]
I see the icon change when I'm typing, but it doesn't look like my microphone gets muted on Fedora 35 Silverblue. Not sure if this trace has anything to do with it, as it happens only on launch:

```
[bpiotrowski@risuku ~]$ flatpak run org.kryogenix.hushboard
Gtk-Message: 09:40:15.344: Failed to load module "canberra-gtk-module"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/app/hushboard/__main__.py", line 109, in wait
    self.mute()
  File "/app/hushboard/__main__.py", line 127, in mute
    self.pulse.source_mute(m.index, 1)
  File "/app/hushboard/pulsectl.py", line 595, in _wrapper
    except c.pa.CallError as err: raise PulseOperationInvalid(err.args[-1])
  File "/usr/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/app/hushboard/pulsectl.py", line 482, in _pulse_op_cb
    if not self._actions[act_id]: raise PulseOperationFailed(act_id)
hushboard.pulsectl.PulseOperationFailed: 1
```

**Comment by stuartlangridge** [comment]
> I see the icon change when I'm typing, but it doesn't look like my microphone gets muted on Fedora 35 Silverblue. 
> hushboard.pulsectl.PulseOperationFailed: 1

Hm. It works on Ubuntu 20.04, but maybe things are different. Not sure what might be causing that; I'll try to find a way to diagnose why that doesn't work on what you're running. Thank you!

**Comment by stuartlangridge** [comment]
bot, build org.kryogenix.hushboard

**Comment by stuartlangridge** [comment]
bot, build org.kryogenix.hushboard

**Comment by stuartlangridge** [comment]
> I see the icon change when I'm typing, but it doesn't look like my microphone gets muted on Fedora 35 Silverblue. Not sure if this trace has anything to do with it, as it happens only on launch:

@barthalion I believe this should be fixed in the latest build.

**Pull request closed without merging**
