### PR TITLE
Add com.github.zhuzhuyule.HexoEditor (hexoeditor-flatpak)

### PR DESCRIPTION
**Pull request by scx**
**HexoEditor** is a markdown editor for Hexo.

See also:
https://github.com/zhuzhuyule/HexoEditor
https://github.com/scx/hexoeditor-flatpak
https://github.com/scx/flathub/tree/com.github.zhuzhuyule.HexoEditor

### CODE REVIEW

**Comment by scx** [comment]
Upstream participation request:
https://github.com/zhuzhuyule/HexoEditor/issues/57

As for the AppData, I will try to push this upstream after review.

**Comment by scx** [comment]
testbot, build com.github.zhuzhuyule.HexoEditor

**Comment by LeandroStanger** [comment]
bot, build build com.github.zhuzhuyule.HexoEditor

**Comment by LeandroStanger** [comment]
bot, build com.github.zhuzhuyule.HexoEditor

**Pull request closed without merging**
