### PR TITLE
Add com.netxms.NetXMSClient50

### PR DESCRIPTION
**Pull request by alkk**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly.

This package is a rich client for network monitoring system NetXMS. Client is Java (SWT) based and depends on Java17+.
Package is build from release version which we publish on our site.

This particular package is for 5.0.x branch. We keep protocol compatiblity between server and client across major.minor releases, but some users need to access different versions of the server at the same time (e.g. during test deployment/upgrade).

"Duplicate" package com.netxms.NetXMSClient already exist, but it's developed for branch 4.5. I plan to rename it to com.netxms.NetXMSClient45 in the future (via submiting new app and EOL-ing this one) to keep names consistent.

- [X] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read the and followed all the [Submission and licence requirements][reqs].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:** https://netxms.com/about-us, right side of the page

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by bbhtt** [comment]
> Duplicate" package com.netxms.NetXMSClient already exist, but it's developed for branch 4.5. I plan to rename it to com.netxms.NetXMSClient45 in the future (via submiting new app and EOL-ing this one) to keep names consistent.

Not worth changing the app id, You can just rename the metadata to show the new name.

**Comment by bbhtt** [comment]
bot, build om.netxms.NetXMSClient50

**Comment by alkk** [comment]
> bot, build om.netxms.NetXMSClient50

There is a typo in the name, please restart build.

**Comment by bbhtt** [comment]
bot, build com.netxms.NetXMSClient50

**Pull request closed without merging**
