### PR TITLE
Add org.nanuc.Axolotl

### PR DESCRIPTION
**Pull request by olof-nord**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/nanu-c/axolotl/issues/288
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge). **Link:** [see comment below](https://github.com/flathub/flathub/pull/2149#issuecomment-796967020)
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build org.nanuc.Axolotl

**Comment by olof-nord** [comment]
bot, build org.nanuc.Axolotl

**Comment by olof-nord** [comment]
bot, build org.nanuc.Axolotl

**Comment by olof-nord** [comment]
bot, build org.nanuc.Axolotl

**Comment by olof-nord** [comment]
bot, build org.nanuc.Axolotl

**Comment by olof-nord** [comment]
bot, build org.nanuc.Axolotl

**Comment by olof-nord** [comment]
bot, build org.nanuc.Axolotl

**Comment by olof-nord** [comment]
Hello @nanu-c, in the FlatHub submission criteria I understand it as we need your approval as domain owner for the domain used in the application ID.

Could you give that approval?

> I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).

**Comment by nanu-c** [comment]
I give you and flathub the permission to use the nanu-c.org domain for the axolotl project!

**Comment by olof-nord** [comment]
@LeandroStanger, this MR is ready to be reviewed. (Pinging you due to your [comment](https://github.com/flathub/flathub/pull/2149#issuecomment-790979204) earlier)

Note that the appdata is in this repo only due to the latest stable release didnt have the required <screenshot> section.

The appdata changes required are already upstreamed, and with the next release we will only need the Flatpak Manifest in this repo.

**Pull request closed without merging**
