### PR TITLE
Org.gnome.crossword.puzzle sets.xword dl

### PR DESCRIPTION
**Pull request by blandford**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.gnome.Crosswords.PuzzleSets.xword-dl

**Comment by hfiguiere** [comment]
For extensions, you need:

1. a `flathub.json` with a     `"skip-icons-check": true`
2. an appstream file. Alternatively you can add `"skip-appstream-check": true` to the `flathub.json`, but having the appstream files has benefits: display the version, and GNOME Software will use it to show the add-ons with the app.

**Comment by blandford** [comment]
bot, build org.gnome.Crosswords.PuzzleSets.xword-dl

**Comment by blandford** [comment]
bot, build org.gnome.Crosswords.PuzzleSets.xword-dl

**Comment by blandford** [comment]
bot, build org.gnome.Crosswords.PuzzleSets.xword-dl

**Pull request closed without merging**
