### PR TITLE
Add io.github.peazip.PeaZip.Addon.i386

### PR DESCRIPTION
**Pull request by catsout**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by catsout** [comment]
bot, build io.github.peazip.PeaZip.i386

**Comment by catsout** [comment]
bot, build io.github.peazip.PeaZip.i386

**Comment by barthalion** [comment]
Is there any reason to make this an extension? Sounds like something that can be shipped with PeaZip itself, directly.

**Comment by catsout** [comment]
I want to build aarch64 version, but some format require i386 sdk  
I moved them to this extension

**Comment by catsout** [comment]
These formats are optional for peazip,  but if I package these with peazip, the i386 sdk extension is required.  
Is there some way to optionally require sdk-extension like `only-arches`?  

https://peazip.github.io/peazip-linux-arm.html

**Comment by barthalion** [comment]
Yeah, that's not currently possible. Makes sense to me in that case.

**Comment by catsout** [comment]
bot, build io.github.peazip.PeaZip.i386

**Comment by catsout** [comment]
bot, build io.github.peazip.PeaZip.Addon.i386

**Comment by catsout** [comment]
bot, build io.github.peazip.PeaZip.Addon.i386

**Comment by catsout** [comment]
bot, build io.github.peazip.PeaZip.Addon.i386

**Comment by catsout** [comment]
@barthalion  
I notice that sometimes the file in archive can't be previewed.  
It seems related with https://github.com/flatpak/flatpak/issues/3438  
Is it ok to put large file on `$XDG_RUNTIME_DIR/app/$FLATPAK_ID`?  
Peazip will delete the temp files created by itself when exits.

**Comment by barthalion** [comment]
Sure, some apps already do that.

**Comment by catsout** [comment]
bot, build io.github.peazip.PeaZip.Addon.i386

**Comment by barthalion** [comment]
@catsout Let me know when you consider it ready to merge.

**Comment by catsout** [comment]
@barthalion I think it's already ready.

**Pull request closed without merging**
