### PR TITLE
Add org.xonotic.Xonotic

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build org.xonotic.Xonotic

**Comment by barthalion** [comment]
bot, build org.xonotic.Xonotic

**Comment by AsciiWolf** [comment]
By the way, I [contacted](https://gitlab.com/xonotic/xonotic/issues/214#note_89438230) upstream and they are interested in co-maintaining the Xonotic Flatpak and even want to advertise the Flatpak on the official Xonotic website. :-)

**Comment by nedrichards** [comment]
Build success: https://flathub.org/builds/#/builders/2/builds/3015

**Comment by nedrichards** [comment]
lgtm, what's upstream's github username?

**Comment by ghisvail** [comment]
Likely [xonotic](https://github.com/xonotic).

I was interested in working on a Flatpak for Xonotic. Glad someone beat me to it :-)

**Comment by nedrichards** [comment]
@ghisvail that's just an org-name I think, and github permissions don't quite casecade that way. I meant names like: https://github.com/xonotic/xonotic/graphs/contributors

in either case, will add and they can make themselves known!

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.xonotic.Xonotic

**Pull request closed without merging**
