### PR TITLE
Add io.github.nuttyartist.notes

### PR DESCRIPTION
**Pull request by guihkx**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. 
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

---

Notes is an open source and cross-platform note-taking app that is both beautiful and powerful.

Website: https://get-notes.com/

Please add myself, @nuttyartist, @zjeffer and @bjorn as collaborators.

Thank you!

### CODE REVIEW

**Comment by guihkx** [comment]
bot, build

**Comment by guihkx** [comment]
Did I break something?

**Comment by zjeffer** [comment]
bot, build io.github.nuttyartist.notes

**Comment by zjeffer** [comment]
It works! 
image

:D

**Comment by hfiguiere** [comment]
why do you need the screenshots in the repository? The files are never referenced.

**Comment by guihkx** [comment]
The screenshots we have in our [appdata](https://github.com/nuttyartist/notes/blob/v2.1.0/packaging/linux/common/notes.appdata.xml.in#L32-L52) are currently hosted on an awkward place ([this GitHub issue](https://github.com/nuttyartist/notes/issues/501#issuecomment-1454867449) in our repository), so having them stored on the Flathub repository seems much better.

Sure, I could have uploaded them later instead of now, but why not avoid a pointless CI run? :P

I'll update the screenshots in the manifest once the app gets accepted into Flathub.

**Comment by hfiguiere** [comment]
> The screenshots we have in our [appdata](https://github.com/nuttyartist/notes/blob/v2.1.0/packaging/linux/common/notes.appdata.xml.in#L32-L52) are currently hosted on an awkward place ([this GitHub issue](https://github.com/nuttyartist/notes/issues/501#issuecomment-1454867449) in our repository), so having them stored on the Flathub repository seems much better.

This is not useful. To have them here. And if the upstream appdata reference them from here, then it's even worse.

> Sure, I could have uploaded them later instead of now, but why not avoid a pointless CI run? :P

There is no pointless CI run.

**Comment by guihkx** [comment]
>This is not useful. To have them here. 

I don't understand. Where should we host them? Plenty of apps are hosting their screenshots on their Flathub repository.

>And if the upstream appdata reference them from here, then it's even worse.

The appdata does not reference them from here yet (as they don't exist). What I'm saying is that they will, in the next version.

>There is no pointless CI run.

Technically, there is. If the app gets accepted into Flathub, I will push a commit adding the screenshots again, and the Flathub CI will kick in pointlessly.

**Comment by hfiguiere** [comment]
> > This is not useful. To have them here.
> 
> I don't understand. Where should we host them? Plenty of apps are hosting their screenshots on their Flathub repository.

Unless the appdata is in the flathub repo then it's wrong.
Two wrongs don't make a right.

> 
> > And if the upstream appdata reference them from here, then it's even worse.
> 
> The appdata does not reference them from here yet (as they don't exist). What I'm saying is that they will, in the next version.

Then even more so. There is no need to have the screenshots here. They should be upstream. An easy way is in the git repository of the upstream source code, or their website.

**Comment by hfiguiere** [comment]
Just to clarify: drop that screenshot directory from the pull request.

**Comment by guihkx** [comment]
I think we can upload them elsewhere.

I've asked @nuttyartist where he prefers the screenshots to be hosted. I'm waiting for a response.

>Unless the appdata is in the flathub repo then it's wrong.

Wrong according to what?

>They should be upstream

Is there any guidelines I can inform myself about that?  The only mention of 'screenshot' I could find on [Flathub's AppData guidelines](https://github.com/flathub/flathub/wiki/AppData-Guidelines#content) only refers to the [official AppData specification](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info), which only states (emphasis mine):

>The value of the `<image/>` tag is a direct URL to a screenshot uploaded to a **public location on the web**. 

There's no mention that screenshots *should* be hosted upstream.

>An easy way is in the git repository of the upstream source code

I'll just note that I'm not a big fan of this approach in particular, because it would increase the general size of a repository that is supposed to host code, for no good reason. And it'd only get worse if we were to update the screenshots in the future.

>or their website.

Not really an option if a project doesn't have a website.

**Comment by guihkx** [comment]
bot, build io.github.nuttyartist.notes

**Comment by hfiguiere** [comment]
> > Unless the appdata is in the flathub repo then it's wrong.
> 
> Wrong according to what?

Feel free to ignore reviewers. 

> > The value of the `<image/>` tag is a direct URL to a screenshot uploaded to a **public location on the web**.
> 
> There's no mention that screenshots _should_ be hosted upstream.

And the URL in the current appdata (AppStrem) file seems to work, doesn't it? And it's not referencing these. As for the should, think about it. The AppStream file is NOT flatpak specific. So in which logical way would Flathub repo be the place for the screenshot referenced from a file upstream? 

Again, feel free to ignore reviewers. 

> 
> > An easy way is in the git repository of the upstream source code
> 
> I'll just note that I'm not a big fan of this approach in particular, because it would increase the general size of a repository that is supposed to host code, for no good reason. And it'd only get worse if we were to update the screenshots in the future. 

So following your logic, how does it make sense to put them here?

> > or their website.
> 
> Not really an option if a project doesn't have a website.

1. github pages is available to all github projects.
2. I gave another alternative that you seem to oppose.

Again I'm just a reviewer.

**Comment by guihkx** [comment]
>Feel free to ignore reviewers.

I did not ignore you. I removed the screenshots... lol

I did ask, however, if you could provide evidence to back up your claims, which in my opinion look rather arbitrary.

>And the URL in the current appdata (AppStrem) file seems to work, doesn't it?

I feel like I'm repeating myself, but once again: The screenshots of `v2.1.0` (our latest release) are currently hosted on a very awkward place (a random GitHub issue) because we didn't have a better place to host them in the first place.

>And it's not referencing these

Of course it's not referencing these **yet**, `v2.1.0` had to be released *before* we submitted it to Flathub, therefore before I uploaded the screenshots. How could I reference them if they didn't exist on the Flathub repo yet? LOL.

>So in which logical way would Flathub repo be the place for the screenshot referenced from a file upstream?

In my opinion, having them hosted on the FlatHub repository would be a vastly better option, because:

- Contributors could take better screenshots (or add new ones), and quickly send a pull request
- Repositories for Flathub apps are *mostly* hosting metadata (i.e. no code), and screenshots would fit into that category

Besides, I thought of hosting the screenshots on the Flathub repository because that's the only place *actually* making use of them (at least currently).

>So following your logic, how does it make sense to put them here?

It does, because Flathub repos are mostly hosting build recipes and metadata (and yes, I know it sometimes hosts code too, but that's neither [recommended](https://github.com/flathub/flathub/wiki/App-Requirements#patches), or common).

>I gave another alternative that you seem to oppose.

You did, but in my opinion, my approach remains better for the reasons I just mentioned.

>Again I'm just a reviewer.

And I thank you very much for that! I don't see a problem if we disagree from each other.

**Pull request closed without merging**
