### PR TITLE
Add org.kde.kcalc

### PR DESCRIPTION
**Pull request by Siosm**

### CODE REVIEW

**Comment by Siosm** [comment]
bot build org.kde.kcalc

**Comment by Siosm** [comment]
bot, build org.kde.kcalc

**Comment by Siosm** [comment]
bot, build org.kde.kcalc

**Comment by Siosm** [comment]
bot, build org.kde.kcalc

**Comment by Siosm** [comment]
bot, build org.kde.kcalc

**Comment by Siosm** [comment]
Hum, this one does not properly install icons!

**Comment by bilelmoussaoui** [comment]
It seems to use a stock icon `accessories-calculator` which is unexpected

**Comment by JBBgameich** [comment]
The stock icon from breeze could be installed to the app icon location to work around this.

**Comment by Siosm** [comment]
bot, build org.kde.kcalc

**Comment by Siosm** [comment]
bot, build org.kde.kcalc

**Comment by Siosm** [comment]
bot, build org.kde.kcalc

**Comment by Siosm** [comment]
bot, build org.kde.kcalc

**Comment by Siosm** [comment]
This is not the workaround from https://invent.kde.org/teams/flathub/issues/-/issues/3 but this should unblock us for now.

**Comment by Siosm** [comment]
Inspired by similar workaround in Dolphin.

**Pull request closed without merging**
