### PR TITLE
Update name for io.github.mak448a.Qtcord

### PR DESCRIPTION
**Pull request by mak448a**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly.
  
Qtcord is the updated name for QTCord. I just changed the capitalization.
- [X] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read the and followed all the [Submission and licence requirements][reqs].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:** https://github.com/mak448a/Qtcord

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by mak448a** [comment]
I did run the linter though, and it did give this error:

```
{
    "errors": [
        "appstream-external-screenshot-url",
        "appstream-remote-icon-not-mirrored"
    ],
    "warnings": [
        "appstream-screenshot-missing-caption"
    ],
    "info": [
        "appstream-external-screenshot-url: Screenshots are not mirrored to https://dl.flathub.org/media",
        "appstream-screenshot-missing-caption: One or more screenshots are missing captions in the Metainfo file",
        "appstream-remote-icon-not-mirrored: Remote icons are not mirrored to Flathub. Please see the docs for more information"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by mak448a** [comment]
Never mind, I'll fix it.

**Comment by hfiguiere** [comment]
> Please describe the application briefly. 
> > Qtcord is the updated name for QTCord. I just changed the capitalization.

This is not a description because it doesn't tell use reviewer what this is.

Also, changing the capitalisation only for a rename isn't supported. Github doesn't allow it.

**Comment by bbhtt** [comment]
> Qtcord is the updated name for QTCord. I just changed the capitalization.

Why does it need to be resubmitted? that's a minor change

**Comment by mak448a** [comment]
It doesn't follow the "flathub guidelines"

**Comment by mak448a** [comment]
Ok, sorry to bother you

**Comment by mak448a** [comment]
I'll just change the capitalization on the manifest then

**Comment by bbhtt** [comment]
Those guidelines are not for the App ID, you can just change the `name` in metainfo.

**Comment by mak448a** [comment]
Sorry, I meant metainfo. Yes, I'll change that.

**Pull request closed without merging**
