### PR TITLE
Add manifest for org.kde.kgeotag

### PR DESCRIPTION
**Pull request by flyingcakes85**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned.
  - appdata.patch : https://invent.kde.org/graphics/kgeotag/-/merge_requests/13 (merged)

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by flyingcakes85** [comment]
bot, build org.kde.kgeotag

**Comment by flyingcakes85** [comment]
There is one issue I'm seeing with this; I cannot choose folders. I'm not sure if a permission is missing or whether it is a Portal/Qt limitation.

This can be a user experience issue. A workaround I know of is to multi select images while importing. Of course, this will work only when all the images to be selected are in same folder.

**Comment by travier** [comment]
Manifest LGTM. Will test the app.

**Comment by travier** [comment]
CC @flathub/kde

**Comment by travier** [comment]
Apps works for me so LGTM.
Minor issue: I don't have icons when running (on Wayland).

**Comment by flyingcakes85** [comment]
> Minor issue: I don't have icons when running (on Wayland).

For me, on X11, icon doesn't appear on titlebar either. I ensured that 64x64 and 128x128 icons are being copied. Adding `copy-icon` too doesn't make any difference.

**Comment by tsdgeos** [comment]
That's an application issue https://invent.kde.org/graphics/kgeotag/-/merge_requests/14

**Comment by flyingcakes85** [comment]
> That's an application issue https://invent.kde.org/graphics/kgeotag/-/merge_requests/14

Oh didn't suspect that. Thanks for sending the merge request :)

I'll update this PR with the patch when I'm near my system tomorrow.

**Comment by nedrichards** [comment]
As soon as this is updated I'll merge. thanks all

**Comment by flyingcakes85** [comment]
bot, build org.kde.kgeotag

**Comment by flyingcakes85** [comment]
bot, build org.kde.kgeotag

**Comment by flyingcakes85** [comment]
> As soon as this is updated I'll merge. thanks all

@nedrichards done! :)

**Review by barthalion — CHANGES_REQUESTED** [review]
I see there are some static libraries lying around from protobuf. Once these are cleaned up, it's good to go for me as well.

**Comment by flyingcakes85** [comment]
bot, build org.kde.kgeotag

**Pull request closed without merging**
