### PR TITLE
Build manifest for org.gna.Warmux

### PR DESCRIPTION
**Pull request by cosimoc**
Based on the Freedesktop 1.6 SDK.

### CODE REVIEW

**Comment by Barthalion** [comment]
Can you update the appdata to include the license?

**Comment by cosimoc** [comment]
Done

**Comment by Barthalion** [comment]
Scheduled a build: https://flathub.org/builds/#/buildrequests/1743?redirect_to_build=true

**Comment by cosimoc** [comment]
It does not look like the test build actually went through?

**Comment by Barthalion** [comment]
Yeah, I don't know what happened. There's a new one: https://flathub.org/builds/#/builders/5/builds/338

**Comment by cosimoc** [comment]
Thanks, I pushed a few commits that should fix build failures on ARM.

**Comment by Barthalion** [comment]
Another take: https://flathub.org/builds/#/builders/5/builds/359

**Comment by cosimoc** [comment]
@Barthalion Thanks, I pushed one more commit that should fix this last failure.

**Comment by Barthalion** [comment]
Merged, thanks.

**Pull request closed without merging**
