### PR TITLE
Add Type Off

### PR DESCRIPTION
**Pull request by Keyikedalube**
Type Off is a game project I completed last year. Learning how to package and maintain a flatpak app with this typing speed game (as a starting point).

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build io.itch.keyikedalube_ndang.Type-Off

**Comment by Keyikedalube** [comment]
Hello @LeandroStanger 
I thought once you review the manifest file and approve my branch, the next step is pushing my binary files on this branch to initiate the build process...
But this seems to be otherwise

I'm committing my binary files and pushing them now.

**Comment by barthalion** [comment]
@LeandroStanger Can you stop triggering builds for applications that haven’t been even basically reviewed?

**Comment by barthalion** [comment]
@Keyikedalube Please read here what repository should store: https://github.com/flathub/flathub/wiki/App-Maintenance#required-files

**Comment by Keyikedalube** [comment]
I'll ping you when I've made the changes. Need (time) to create a new repository and host my files there *due to bad Internet speed over here*

**Comment by Keyikedalube** [comment]
bot, build io.itch.keyikedalube_ndang.Type-Off

**Comment by Keyikedalube** [comment]
bot, build io.itch.keyikedalube_ndang.Type-Off

**Comment by Keyikedalube** [comment]
Ping @barthalion @LeandroStanger build success. Waiting for the review :)

**Comment by Keyikedalube** [comment]
Installed the above test build and tried viewing my game page from software-center.
For screenshots, I copied directly from my itch.io page but I get this

Screenshot from 2020-02-17 10-17-23

Do I have to host my screenshots on my gitlab repo too?

**Comment by Keyikedalube** [comment]
bot, build io.itch.keyikedalube_ndang.Type-Off

**Comment by Keyikedalube** [comment]
bot, build io.itch.keyikedalube_ndang.Type-Off

**Comment by Keyikedalube** [comment]
itch.io url for screenshots worked earlier
gitlab doesn't

**Comment by Keyikedalube** [comment]
bot, build io.itch.keyikedalube_ndang.Type-Off

**Comment by Keyikedalube** [comment]
Sorry, I used the local checksum.

**Comment by Keyikedalube** [comment]
bot, build io.itch.keyikedalube_ndang.Type-Off

**Comment by barthalion** [comment]
LGTM. Is it ready to merge?

**Comment by Keyikedalube** [comment]
Yes @barthalion :)

**Comment by barthalion** [comment]
Cool, thanks for your submission!

/merge

**Pull request closed without merging**
