### PR TITLE
Build manifes for com.tux4kids.tuxtype

### PR DESCRIPTION
**Pull request by cosimoc**
Based on the Freedesktop 1.6 SDK.

### CODE REVIEW

**Comment by Barthalion** [comment]
Scheduled a test build: https://flathub.org/builds/#/buildrequests/1708?redirect_to_build=true

**Comment by cosimoc** [comment]
Pushed a commit that should fix ARM64 build failures.

**Comment by Barthalion** [comment]
Another one: https://flathub.org/builds/#/builders/5/builds/312

**Comment by Barthalion** [comment]
Oops, that's for tuxmath. Here's one for tuxtype: https://flathub.org/builds/#/buildrequests/1735?redirect_to_build=true

**Comment by cosimoc** [comment]
This one seems to have worked fine.

**Comment by Barthalion** [comment]
Merged.

**Pull request closed without merging**
