### PR TITLE
Add manifest for Sublime Music

### PR DESCRIPTION
**Pull request by sumnerevans**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://gitlab.com/sublime-music/sublime-music (proof that this account and the other account are the same user can be found at my website: https://sumnerevans.com, links to both are in the footer)
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by sumnerevans** [comment]
bot, build app.sublimemusic.SublimeMusic

**Comment by sumnerevans** [comment]
bot, build app.sublimemusic.SublimeMusic

**Comment by sumnerevans** [comment]
I'm getting the following error:
```
Can't specify build-args in sandboxed build
```
but if I don't specify the build args, I get the following error:
```
  ERROR: Could not find a version that satisfies the requirement poetry>=0.12 (from versions: none)
```
because pip can't access the internet.

**Comment by sumnerevans** [comment]
bot, build app.sublimemusic.SublimeMusic

**Comment by barthalion** [comment]
Hi @danyeaw, any ideas about the problem with poetry @sumnerevans is having?

**Comment by danyeaw** [comment]
For Gaphor (which also uses Poetry), we are using this [bash script](https://github.com/flathub/org.gaphor.Gaphor/blob/master/depends.sh) to create a yaml manifest based on the dependencies after the app has been uploaded to PyPI.

**Comment by sumnerevans** [comment]
Thanks for your input. I've decided to stop trying to support flatpak upstream (https://gitlab.com/sublime-music/sublime-music/-/issues/309). If anyone wants to continue this work, please feel free to do so.

**Pull request closed without merging**
