### PR TITLE
add org.kde.marble

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by cho2** [comment]
bot, build org.kde.marble

**Comment by cho2** [comment]
bot, build org.kde.marble

**Comment by cho2** [comment]
bot, build org.kde.marble

**Comment by tsdgeos** [comment]
There's a few optional dependencies not found, as far as i understand making it find Qt5WebEngine should be easy adding the  "base": "io.qt.qtwebengine.BaseApp"

From the rest  a few of them seem interesting, but if you prefer we can figure out how to build/add them later

**Comment by cho2** [comment]
bot, build org.kde.marble

**Comment by cho2** [comment]
bot, build org.kde.marble

**Comment by cho2** [comment]
Cuplikan layar dari 2020-09-14 10-39-55

@tsdgeos What do you think?

**Comment by tsdgeos** [comment]
Sounds, good, let's merge it :)

**Comment by cho2** [comment]
cc @flathub/reviewers

**Pull request closed without merging**
