### PR TITLE
Add org.pdfstitcher.pdfstitcher

### PR DESCRIPTION
**Pull request by cfcurtis**
### Please confirm your submission meets all the criteria
- [X] Please describe your application briefly.
> PDFStitcher is a utility to stitch together and modify line properties of PDF sewing patterns
- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I have [built][build] and tested the submission locally.
- [X] I am using only the minimal set of permissions.
> Non-standard permissions:
> ```
> --filesystem=home
> --filesystem=/media
> --filesystem=/run/media
> --filesystem=/mnt
> ```
> As this is a utility for modifying PDFs, users will need to access documents and save the modififed version. The user's home directory and its various subfolders, removable media, and network drives are common places to store files.
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link: https://github.com/cfcurtis/pdfstitcher**
- [X] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* - I will add the verification token to pdfstitcher.org when available.

### Additional info
This was originally hosted as [com.github.cfcurtis.pdfstitcher](https://github.com/flathub/com.github.cfcurtis.pdfstitcher). However, I would prefer to rename it to match pdfstitcher.org. Could someone with the requisite power please archive the original repo once the `org.pdfstitcher` version is live?

Edit: I originally said that the Flatpak build now fails due to the com.github usage, which was me incorrectly reading the error message. I'd still like to request the org.pdfstitcher.pdfstitcher repo be created, as the old one is way out of date anyway and I'd prefer the app ID be disconnected from my personal GitHub account.

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by hfiguiere** [comment]
> However, the Flatpak build now fails due to the com.github usage,

It shouldn't. we added all the existing apps to the exception list when we started enforcing the rule.

**Comment by hfiguiere** [comment]
see https://discourse.flathub.org/t/linter-breaking-change-restricting-automatic-merge/6922

**Comment by cfcurtis** [comment]
> It fail because
> 
> ```
>         "flathub-json-automerge-enabled"
> ```

Yes, I saw that as well and removed it in the PR. I now see that it's actually complaining about the `skip-appstream-check` (which I admittedly copied blindly from someone else' EOL rebase flathub.json).

I've removed that line and hopefully it will pass, although ultimately I'd like to just archive that repo and move to this new one. It's way out of date and I would prefer the app ID to be org.pdfstitcher.pdfstitcher.

**Comment by bbhtt** [comment]
Metainfo and desktop file should be submitted upstream.

**Comment by cfcurtis** [comment]
> Metainfo and desktop file should be submitted upstream.

Okay, they've been moved and referenced (and screenshots updated, while I'm at it). I ran a test build locally and it seemed to behave.

**Comment by bbhtt** [comment]
bot, build org.pdfstitcher.pdfstitcher

**Comment by cfcurtis** [comment]
Whoops, looks like my wxPython Wayland hack wasn't working the way I thought and it actually only supports X11. Fingers crossed this does the trick!

**Comment by cfcurtis** [comment]
bot, build org.pdfstitcher.pdfstitcher

**Pull request closed without merging**
