### PR TITLE
Add org.sigxcpu.Livi

### PR DESCRIPTION
**Pull request by agx**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions - unfortunately full device access is needed for the video/media devices needed by gstreamer's v4l stateless codecs
- [x] All assets referenced in the manifest are redistributable by any party
- [x] I am an upstream contributor to the project. \
- [x] I own the domain used in the application ID `sigxcpu.org`
- [x] Any additional patches or files have been submitted to the upstream projects concerned. https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/2398

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by agx** [comment]
Is there a way to restrict this package to amd64 since that's the main target?

**Comment by hfiguiere** [comment]
bot, build org.sigxcpu.Livi

**Comment by hfiguiere** [comment]
> Is there a way to restrict this package to amd64 since that's the main target?

https://github.com/flathub/flathub/wiki/App-Maintenance#only-build-on-x86_64

**Comment by hfiguiere** [comment]
but why restricting to PC?

**Comment by hfiguiere** [comment]
upstream appdata is incomplete.

**Comment by agx** [comment]
metainfo validates with `appstreamcli` *and* `appstream-util` now. I had used the former only before.

**Comment by agx** [comment]
> but why restricting to PC?

@hfiguiere i meant to say arm64 aka aarch64. My main focus is to make video smooth on linux based mobile phones which are all aarch64 atm. It will work in principle on PC but we e.g. don't build libav etc so playback there would be slower.

**Comment by hfiguiere** [comment]
> metainfo validates with `appstreamcli` _and_ `appstream-util` now. I had used the former only before.

You should use the one provided as a flatpak as `org.freedesktop.appstream-glib`.
It has more checks that match what flathub expect.

**Comment by hfiguiere** [comment]
> > but why restricting to PC?
> 
> @hfiguiere i meant to say arm64 aka aarch64. My main focus is to make video smooth on linux based mobile phones which are all aarch64 atm. It will work in principle on PC but we e.g. don't build libav etc so playback there would be slower.

That's a first. If it builds and run on x86_64 I see no reason to not build it.

**Comment by agx** [comment]
@hfiguiere Dropped the aarch64 restriction

**Comment by barthalion** [comment]
bot, build org.sigxcpu.Livi

**Comment by barthalion** [comment]
It doesn't seem to work on x86_64:

```
ERROR:../src/livi-gst-paintable.c:128:gtk_gst_paintable_video_renderer_create_video_sink: assertion failed: (self->context != NULL && ctx != NULL)
Bail out! ERROR:../src/livi-gst-paintable.c:128:gtk_gst_paintable_video_renderer_create_video_sink: assertion failed: (self->context != NULL && ctx != NULL)
```

**Comment by agx** [comment]
@barthalion it works here, both the one i built locally and the one from the `flatpakref`. Are you on wayland and OpenGL works?

**Comment by hfiguiere** [comment]
If I run it wit `--h264-demo`, I get
```
(livi:2): livi-window-WARNING **: 12:13:13.180: V4L stateless codec not in use, playback will likely be slow
```

I get a failure passing any video filename to the command line.

**Comment by agx** [comment]
@hfiguiere 

> (livi:2): livi-window-WARNING **: 12:13:13.180: V4L stateless codec not in use, playback will likely be slow

that's expected, see my remark about focusing on linux phones above. The demo does play though, right?

As for command line: It does handle videos on the command line *but* I did not set `--filesystem=home` on purpose since the main use case is being launched by "gio open <file|URL>" (which is what happens when you e.g. click on a video in nautilus etc). I can set the though if it's a requirement.

**Comment by agx** [comment]
@hfiguiere  I added `--filesystem=xdg-videos` which i think make sense for a video player so:

`flatpak run org.sigxcpu.Livi Videos/<whatever>mp4` should work now

**Comment by hfiguiere** [comment]
bot, build org.sigxcpu.Livi

**Comment by barthalion** [comment]
I'd consider adding some aliases to the desktop file like `Livi` and `uPlayer` as it's difficult to trigger the right search keyword in GNOME Shell to find it.

> it works here, both the one i built locally and the one from the `flatpakref`. Are you on wayland and OpenGL works? It can't work without it (the error basically means it couldn't great the GL context)

I switched to Wayland and it indeed works there. Does it mean X11 is unsupported? If so, `fallback-x11` should be dropped from finish-args. Other than this, LGTM.

**Comment by agx** [comment]
@barthalion x11 is indeed unsupported, dropped `fallback-x11`. Thanks for reviewing!

**Pull request closed without merging**
