### PR TITLE
Io.qt.linguist

### PR DESCRIPTION
**Pull request by JakobDev**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

Qt Linguist is already in the KDE SDK and works without any problem, so we just need to add a .desktop and a metainfo.xml file.

### CODE REVIEW

**Comment by JakobDev** [comment]
bot, build io.qt.Linguist

**Comment by nedrichards** [comment]
This is a nice way to do this.

**Comment by nedrichards** [comment]
other than these questions this lgtm

**Comment by hfiguiere** [comment]
I have another question: does this work for qt 5.15? Is it backwards compatible or does it needs its own version?

**Comment by JakobDev** [comment]
Using device=all was a copy/paste mistake. The command in the yml file must be a absolute path, or the build will fail.

Qt Linguist works with both, Qt5 and 6. There are no changes to the translation files in Qt6.

**Comment by JakobDev** [comment]
bot, build io.qt.Linguist

**Pull request closed without merging**
