### PR TITLE
Add org.project_taisei.Taisei

### PR DESCRIPTION
**Pull request by rrigby**
https://github.com/taisei-project/taisei

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build org.project_taisei.Taisei

**Comment by nedrichards** [comment]
The appdata needs oars tags please: https://hughsie.github.io/oars/

**Comment by barthalion** [comment]
bot, build org.project_taisei.Taisei

**Comment by barthalion** [comment]
bot, build  org.taisei_project.Taisei

**Comment by barthalion** [comment]
Repository has been created: https://github.com/flathub/org.taisei_project.Taisei

@Akaricchi and @laochailan, I've sent you invitations to collaborate too; let me know if someone else from your team who should have access to the repo.

Thanks!

**Pull request closed without merging**
