### PR TITLE
Added org.freedesktop.LinuxAudio.Plugins.ArtyFX

### PR DESCRIPTION
**Pull request by hfiguiere**
This will replace org.freedesktop.LinuxAudio.Lv2Plugins.ArtyFX that I will deprecate.

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.ArtyFX

**Comment by barthalion** [comment]
Is extension ID really that big deal that we need to rename it all?

**Comment by hfiguiere** [comment]
After the original design was rolled out, I learned that I could have multiple `merge-dirs` so I could have one flatpak for the same set of plugins in different format. So the idea is to have ONE extension point rule them all. This is the penultimate round of renaming.

But the goal is:

1. reduce the number of individual flatpak without impact to the user.
2. reduce the number of extension points

On overall this simplify the whole thing, given that 20.08 is around the corner and we'll need to branch for 20.08 as well.

**Pull request closed without merging**
