### PR TITLE
[WIP] add org.standardnotes.standardnotes

### PR DESCRIPTION
**Pull request by x80486**
Flatpak for [Standard Notes](https://standardnotes.org/).

Pending tasks:

- [ ] Create a baseline for a successful build :sunglasses:
- [ ] **Try to add** some other architectures
- [ ] Request an SVG icon, and if possible, some nicer screenshot(s)
- [ ] Update upstream developer(s) – if this ever works out this time

---

Looking for some Electron ninja who wants to team up on this one since I'm not super familiar with the platform :smile:

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build org.standardnotes.standardnotes

**Comment by x80486** [comment]
bot, build org.standardnotes.standardnotes

**Comment by x80486** [comment]
bot, build org.standardnotes.standardnotes

**Comment by gasinvein** [comment]
@x80486 Looks like `yarn` called from `electron-builder` still tries to use repository:
```
  • electron-builder version=20.13.3
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=linux arch=x64 appDir=/run/build/standard-notes/main/app
Error: /app/bin/node exited with code 1
Error output:
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
warning package.json: No license field
warning ../package.json: License should be a valid SPDX license expression
warning standard-notes@3.0.8: No license field
error An unexpected error occurred: "https://registry.yarnpkg.com/adm-zip: getaddrinfo EAI_AGAIN registry.yarnpkg.com:443".
```
Try adding `--install.offline true` to `.yarnrc` to force offline mode always.

**Comment by x80486** [comment]
All right! That helped...but it looks like the way I'm _merging_ the `yarn.lock` files (inside `bootstrap.sh`) in order to have only one is not cutting it:

```shell
$ electron-builder install-app-deps
  • electron-builder version=20.13.3
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=linux arch=x64 appDir=/run/build/standard-notes/main/app
Error: /app/bin/node exited with code 1
Error output:
warning package.json: No license field
warning ../package.json: License should be a valid SPDX license expression
warning standard-notes@3.0.8: No license field
error Couldn't find any versions for "adm-zip" that matches "^0.4.7" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
```

...because effectively and I don't see `adm-zip-0.4.13.tgz` inside `yarn-mirror/`.

**Comment by gasinvein** [comment]
@x80486 Since `adm-zip-0.4.13` is present in `generated-sources.json`, I guess it gets removed from local mirror during installation. Try setting `yarn-offline-mirror-pruning false` in `.yarnrc`.

**Comment by x80486** [comment]
I split the `yarn` lockfiles and looks like setting `yarn-offline-mirror-pruning` to `false` also helped, but unfortunately, I hit **exactly the same error** that I had before when using `npm` instead of `yarn`. There is a `spellchecker` dependency this project tries to build using `Python 2.x` and `node-gyp`: https://8n1.org/15200/a6c9/

I'll give it a try using the Flathub infrastructure anyway to see if I get the same error :crossed_fingers:

**Comment by x80486** [comment]
bot, build org.standardnotes.standardnotes

**Comment by x80486** [comment]
bot, build org.standardnotes.standardnotes

**Comment by gasinvein** [comment]
@x80486 Since #1004 is accepted, you may want to use it instead of bundled nodejs. Yet it probably won't fix the build.

**Comment by x80486** [comment]
Yeah, it still didn't work. There is this `spellchecker` module and it always fails when executing `prebuild-install --verbose || node-gyp rebuild` while trying to build it :anger:

Yet I don't see the module in `yarn-mirror/`, so I would try to put it as another source – or something like that.

**Comment by gasinvein** [comment]
It's here:
https://github.com/flathub/flathub/blob/cada665103357ad765107ff3982fea4b0d49dbbb/generated-sources-app.json#L696-L700

**Comment by x80486** [comment]
@gasinvein, what I was trying to say was that since `spellchecker` is [defined](https://github.com/standardnotes/desktop/blob/master/app/package.json#L20) like: `"spellchecker": "github:mobitar/node-spellchecker"`, the Yarn generator doesn't resolve the dependencies for it, so I can't see them in `yarn-mirror/`, hence the build fails while executing `prebuild-install --verbose || node-gyp rebuild` because `prebuild-install` doesn't exist.

I also tried downloading the module, but then, I don't have a place to put the `yarn.lock` file for that project :rofl:

**Comment by nedrichards** [comment]
bot, build org.standardnotes.standardnotes

**Comment by gasinvein** [comment]
@x80486 Congratulations! How did you finally managed to make it work?

**Comment by x80486** [comment]
Well, it's not quite there yet. I just managed to get a non-failing build :rofl:

I'm doing some super-hacky things right now and so far, the application it's giving me some errors while starting, but I'll have to see what's going on from now on :sunglasses:

**Comment by x80486** [comment]
bot, build org.standardnotes.standardnotes

**Comment by x80486** [comment]
bot, build org.standardnotes.standardnotes

**Comment by x80486** [comment]
bot, build org.standardnotes.standardnotes

**Comment by x80486** [comment]
Will make a **Draft Pull Request** for this one :roll_eyes:

**Comment by RavetcoFX** [comment]
What still needs to be done with this? 
Can I help?

**Comment by x80486** [comment]
I've tried several times, but I can't make it work. I think the issue is with dependency: `"spellchecker": "github:mobitar/node-spellchecker"` (in `desktop/app/package.json`). It cannot find it, but probably there is a way to make it work I'm not aware of.

I just pushed the last changes that I had for this; this is the branch: https://github.com/x80486/flathub/tree/org.standardnotes.standardnotes/ ...give it a whirl and see if you can reach to a different point.

**Pull request closed without merging**
