### PR TITLE
de.wolfvollprecht.UberWriter.Plugin.TexLive

### PR DESCRIPTION
**Pull request by somas95**
TexLive plugin for UberWriter (needs a repo of its own)

### CODE REVIEW

**Comment by somas95** [comment]
Seems that it can't find uberwriter, but the branch seems ok to me. I'm missing something?

**Comment by TingPing** [comment]
` "runtime-version": "stable",`

**Comment by TingPing** [comment]
bot, build de.wolfvollprecht.UberWriter.Plugin.TexLive

**Comment by somas95** [comment]
It should work now

**Comment by somas95** [comment]
@TingPing I set the manifest to skip the only arch that failed the build, so it should build now without problems

**Comment by somas95** [comment]
`Failed to download sources: module p7zip: Could not connect: Socket I/O timed out`
I think this is an issue with the bot? Also, last time the arm build was built without issues

**Comment by somas95** [comment]
@nedrichards can you give it another try, please?

**Comment by nedrichards** [comment]
bot, build de.wolfvollprecht.UberWriter.Plugin.TexLive

**Comment by somas95** [comment]
It worked :)

**Comment by somas95** [comment]
@nedrichards is necessary something more to push this to flathub?

**Comment by nedrichards** [comment]
So long as you're aware that a user can install UberWriter on aarch64 and then not be able to get this plugin (until you fix the build there).

**Comment by somas95** [comment]
Yes, I know. Texstudio is facing the same issue, I think. Luckily, the extension is not necessary for the program to work -users on aarch64 won't be able to export to pdf, but that's it. I'll search for a fix to this, but in the meantime I think it's better to have the extension for the unaffected architectures

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/de.wolfvollprecht.UberWriter.Plugin.TexLive

**Pull request closed without merging**
