### PR TITLE
Add de.shorsh.discord-screenaudio

### PR DESCRIPTION
**Pull request by maltejur**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. ~If not, I contacted upstream developers about submitting their software to Flathub.~ **Link:** https://github.com/maltejur/discord-screenaudio
- [x] I own the domain used in the application ID ~or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge)~.
- [ ] ~Any additional patches or files have been submitted to the upstream projects concerned.~ (no additional patches)

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build de.shorsh.discord-screenaudio

**Comment by hfiguiere** [comment]
Are the app developer really in control of `shorsh.de`

**Comment by maltejur** [comment]
Yes, I am https://shorsh.de/hello.txt

**Comment by hfiguiere** [comment]
```
builddir/files/share/appdata/de.shorsh.discord-screenaudio.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
Validation of files failed
```

Also at https://github.com/maltejur/discord-screenaudio/blob/master/assets/de.shorsh.discord-screenaudio.metainfo.xml.in#L19 the value of launchable is incorrect. And this will cause another failure.

**Comment by maltejur** [comment]
Thanks, both fixed. The linter didn't catch those locally for me.

**Comment by hfiguiere** [comment]
bot, build de.shorsh.discord-screenaudio

**Pull request closed without merging**
