### PR TITLE
Add com.valvesoftware.Steam.Utility.thcrap_steam_proton_wrapper

### PR DESCRIPTION
**Pull request by tactikauan**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build com.valvesoftware.Steam.Utility.thcrap_steam_proton_wrapper

**Comment by hfiguiere** [comment]
you need to disable aarch64 since there is no aarch64 steam.

**Comment by tactikauan** [comment]
bot, build com.valvesoftware.Steam.Utility.thcrap_steam_proton_wrapper

**Pull request closed without merging**
