### PR TITLE
Add io.liri.Terminal

### PR DESCRIPTION
**Pull request by plfiorini**
Terminal app with Material Design from Liri

https://liri.io
https://github.com/lirios/terminal

### CODE REVIEW

**Comment by plfiorini** [comment]
This depends on #654

**Comment by TingPing** [comment]
I question the value of Flatpaking a terminal without Flatpak specific modifications. It just isn't very useful.

**Comment by plfiorini** [comment]
Can you point me to what Flatpak specific changes I should do to the terminal?
As it stands right now I have to poke a hole through the sandbox giving it access to the whole file system and devices, but being an upstream developer I can make this Flatpak friendly.

**Comment by TingPing** [comment]
You would want to run the tty on the host basically, its a non-trivial change. GNOME-Builder does it but I don't know the part of code off-hand: https://github.com/GNOME/gnome-builder/search?q=tty&unscoped_q=tty

**Comment by plfiorini** [comment]
Looks like /bin/bash must be executed on the host (with either `flatpak-spawn` or `org.freedesktop.Flatpak.Development`.

However only Flatpak can break out of the containment zone so it needs the `--allow=devel` permission.

**Comment by TingPing** [comment]
> However only Flatpak can break out of the containment zone so it needs the --allow=devel permission.

No. It needs `--talk-name=org.freedesktop.Flatpak`

**Comment by BrainBlasted** [comment]
Here's a small example of a terminal a terminal that can run within Flatpak: https://gitlab.gnome.org/chergert/flatterm

**Comment by Saroufim** [comment]
Tilix has been flatpaked on Fedora. This release contains the necessary commits https://github.com/gnunn1/tilix/compare/1.7.0...master

**Comment by plfiorini** [comment]
Thanks I have seen the example and I was in the right track.
Will take a look again as soon as I have time.

**Pull request closed without merging**
