### PR TITLE
Build manifest for org.audacityteam.Audacity

### PR DESCRIPTION
**Pull request by cosimoc**
Based on the GNOME 3.24 SDK.

### CODE REVIEW

**Comment by Barthalion** [comment]
Build status [here](https://flathub.org/builds/#/buildrequests/846?redirect_to_build=true).

**Comment by Barthalion** [comment]
The build failed for everything but x86_64. Is that expected? If yes, you can create a file named `flathub.json` with content like this:

```json
{
  "skip-arches": ["arm"]
}
```

**Comment by cosimoc** [comment]
No, I'd like to fix those failures when I get a chance.

**Comment by cosimoc** [comment]
I added a patch that may at least fix i386 builds. How can I try the build again?

**Comment by Barthalion** [comment]
I am the button for now… [Here](https://flathub.org/builds/#/builders/5/builds/165) it comes.

**Comment by Barthalion** [comment]
Hm, I will trigger a new one, not sure if pressing "rebuild" was a good idea.

**Comment by Barthalion** [comment]
[Here](https://flathub.org/builds/#/buildrequests/916?redirect_to_build=true).

**Comment by Barthalion** [comment]
Sorry, I was away for the past week. Another build submitted: https://flathub.org/builds/#/builders/5/builds/223

**Comment by Barthalion** [comment]
configure script still insists on checking SSE availability on ARM architectures

**Comment by cosimoc** [comment]
@Barthalion Pushed another commit that hopefully would do it...

**Comment by Barthalion** [comment]
Looks good so far – it passed configure phase so I guess it might work this time.

http://flathub.org/builds/#/builders/5/builds/228

**Comment by Barthalion** [comment]
And it succeeded! Merged into https://github.com/flathub/org.audacityteam.Audacity and added you to collaborators. Thanks!

**Pull request closed without merging**
