### PR TITLE
Add GNOME Crosswords Editor as a standalone package

### PR DESCRIPTION
**Pull request by blandford**
This is the Crossword Editor for GNOME Crosswords pulled into its own package.

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

### CODE REVIEW

**Comment by blandford** [comment]
bot, build org.gnome.Crosswords.Editor

**Comment by blandford** [comment]
(I think I figured out the error correctly)

**Comment by JakobDev** [comment]
You should add `x-checker-data`

**Comment by blandford** [comment]
> You should add `x-checker-data`

I'll look into it for future releases. Looks like there's quite a lot there.

**Pull request closed without merging**
