### PR TITLE
Build manifest for net.minetest.Minetest

### PR DESCRIPTION
**Pull request by cosimoc**
Based on the Freedesktop 1.6 SDK.

Based on the work at https://github.com/est31/minetest-flatpak.

### CODE REVIEW

**Comment by Barthalion** [comment]
Indentation seems slightly off, but that's just a nitpick. Test build: https://flathub.org/builds/#/buildrequests/1412?redirect_to_build=true

**Comment by cosimoc** [comment]
Fixed the indentation. I think the test build had a problem, maybe you did not specify the correct remote?

**Comment by Barthalion** [comment]
Could be, submitted another one [here](https://flathub.org/builds/#/buildrequests/1427?redirect_to_build=true).

**Comment by cosimoc** [comment]
Pushed a commit that updates LuaJIT to 2.1.0 beta which supports ARM64.

**Comment by Barthalion** [comment]
https://flathub.org/builds/#/buildrequests/1443?redirect_to_build=true

**Comment by cosimoc** [comment]
This one seems to have worked well now.

**Comment by Barthalion** [comment]
[Merged](https://github.com/flathub/net.minetest.Minetest), thanks!

**Pull request closed without merging**
