### PR TITLE
add fr.free.homebank flatpak

### PR DESCRIPTION
**Pull request by nedrichards**
Everything works fine except the offline help which is distributed as HTML and fails with:

> Browser error:
> Could not display the URL 'file:/app/share/homebank/help/index.html'

Which I don't consider a blocker, but would be good to fix.

### CODE REVIEW

**Comment by cosimoc** [comment]
This looks pretty good to me, but I noticed two things:
- the application looks for an optional `libofx` dependency. I wonder if we should bundle it with the app.
- the application installs a mime handler for `application/x-homebank` but it does not get exported because it's not called like the app ID. I think you'd need to manually rename it (do the equivalent of what `rename-icon` does basically)

**Comment by cosimoc** [comment]
Test build at https://flathub.org/builds/#/builders/1/builds/503

**Comment by nedrichards** [comment]
Libofx is a fair bit of pain to get working. Spent 20 minutes wresting with a _gengetopt_ a downstream of a downstream dependency before deciding that I had something better to do with my Sunday evening. Will try and get back to it at some point though.

Mime handler is an interesting one, I'll absolutely do that but I wonder if a convenience helper would be useful here for more apps.

**Comment by cosimoc** [comment]
Cool! Yeah I think it would be a great idea to have a convenience tag in flatpak-builder for it like we do for other things, but it's definitely not as common. See https://github.com/flatpak/flatpak-builder/issues/1

**Comment by nedrichards** [comment]
OK - that should be both changes - could we have a test build when that's all up and running?

**Comment by Barthalion** [comment]
https://flathub.org/builds/#/buildrequests/3506?redirect_to_build=true

**Comment by nedrichards** [comment]
Annoying, both kinds of ARM and i386 issues in the new bit. Will take a further look.

**Comment by nedrichards** [comment]
Another build with these changes https://flathub.org/builds/#/builders/1/builds/631

**Comment by TingPing** [comment]
Repository has been created: https://github.com/flathub/fr.free.Homebank

**Pull request closed without merging**
