### PR TITLE
Add com.github.Moeditor.Moeditor (moeditor-flatpak)

### PR DESCRIPTION
**Pull request by scx**
**Moeditor** is all-purpose markdown editor.

See also:
https://moeditor.js.org
https://github.com/Moeditor/Moeditor
https://github.com/scx/moeditor-flatpak
https://github.com/scx/flathub/tree/com.github.Moeditor.Moeditor

### CODE REVIEW

**Comment by scx** [comment]
Upstream participation request:
https://github.com/Moeditor/Moeditor/issues/187

As for the AppData, I will try to push this upstream after review.

**Comment by scx** [comment]
testbot, build com.github.Moeditor.Moeditor

**Comment by scx** [comment]
testbot, build com.github.Moeditor.Moeditor

**Comment by LeandroStanger** [comment]
bot, build com.github.Moeditor.Moeditor

**Pull request closed without merging**
