### PR TITLE
Add org.gnumeric.Gnumeric

### PR DESCRIPTION
**Pull request by hfiguiere**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge). I don't own it. gnumeric.org is upstream domian
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*
Will submit the appdata patch https://gitlab.gnome.org/GNOME/gnumeric/-/merge_requests/21
[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.gnumeric.Gnumeric

**Comment by hfiguiere** [comment]
bot, build org.gnumeric.Gnumeric

**Comment by nedrichards** [comment]
Does upstream want to be involved?

**Pull request closed without merging**
