### PR TITLE
Add com.github.lainsce.coin

### PR DESCRIPTION
**Pull request by lainsce**
This is the file that makes possible to build a Flatpak for Coin, my own cryptocurrency tracker application made for elementary OS, but now in Flatpak format.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.github.lainsce.coin

**Comment by nedrichards** [comment]
Does the app need the elementry theme and iconset? If so, those should be packaged and overriden within the flatpak.

**Comment by Alexander-Wilms** [comment]
I think you need to add this module: https://github.com/flathub/org.gtk.Gtk3theme.elementary/blob/master/org.gtk.Gtk3theme.elementary.json#L12 aswell

**Comment by lainsce** [comment]
If I do that, it complains it's a read-only filesystem and can't copy that module's files.

**Comment by Alexander-Wilms** [comment]
You'll have to replace the `/usr` with `/app`

**Comment by lainsce** [comment]
This worked. :thinking:

**Comment by Alexander-Wilms** [comment]
With this, it actually uses the elementary theme.
```
        {
            "name": "elementary",
            "buildsystem": "simple",
            "build-commands": [
                "install -dm755 /app/share/themes/elementary/gtk-3.0",
                "cp -aL gtk-3.22/* /app/share/themes/elementary/gtk-3.0",
                "cp -a index.theme /app/share/themes/elementary"
            ],
            "sources": [
                {
                    "type": "git",
                    "url": "git://github.com/elementary/stylesheet.git",
                    "branch": "5.1.1",
                    "commit": "6a96d0f3227f15533c11e136b101ee44052eb750"
                }
            ]
        },
```

**Comment by lainsce** [comment]
The windows stays in the background because this is an applet for the desktop, like Nimbus by Daniel Foré.

Also, I'm going to use that block of code.

**Comment by nedrichards** [comment]
bot, build com.github.lainsce.coin

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.github.lainsce.coin

**Pull request closed without merging**
