### PR TITLE
Add org.kde.okular.kirigami

### PR DESCRIPTION
**Pull request by jbruechert**
This is based directly on the Okular manifest, and the changes are split into separate commits to make review easy.

- [x] Please describe the application briefly.
  Mobile interface for the Okular PDF viewer

- [x] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [x] I have read the and followed all the [Submission and licence requirements][reqs].
- [x] I have [built][build] and tested the submission locally.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:** https://matrix.to/#/!iotruiWARuYNvXiTDB:kde.org/$XRybn93-Pn2iBITRe964G2O-FlZk0kSPD4_dLYW1zcc?via=matrix.org&via=kde.org&via=im.kde.org

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements#control-over-domain
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
cc @flathub/kde 

Is this a valid app-id?

**Comment by travier** [comment]
This is a valid KDE App. Is the question that we should use another id?

**Comment by hfiguiere** [comment]
the appstream documentation doesn't take flathub into account.

**Comment by hfiguiere** [comment]
No. This is the question I asked in https://github.com/flathub/flathub/pull/5426#issuecomment-2234432799

**Comment by bbhtt** [comment]
> This is a valid KDE App. Is the question that we should use another id?

What ID does it internally use? If it uses a D-Bus name or an internal ID, it should match with that.

**Comment by bbhtt** [comment]
So I guess the ID is fine then.

> Its appstream metadata uses org.kde.okular.kirigami.desktop.

Since provides and replaces works fine, it'd be better if you can add the tags upstream and rename it to `org.kde.okular.kirigami`. https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#provides

**Comment by bbhtt** [comment]
Seems fine, waiting for the review from flathub/kde.

**Comment by tsdgeos** [comment]
Did you copy/adapt the manifest from the "regular" okular one in flathub?

**Comment by tsdgeos** [comment]
Looks reasonable to me

**Comment by travier** [comment]
Tested, LGTM. Thanks!

**Pull request closed without merging**
