### PR TITLE
Add com.valvesoftware.Steam.CompatibilityTool.Proton-Exp

### PR DESCRIPTION
**Pull request by gasinvein**
Proton experimental is a new branch of Proton with newest, not always stable, changes.

### CODE REVIEW

**Comment by gasinvein** [comment]
bot, build com.valvesoftware.Steam.CompatibilityTool.Proton-Exp

**Comment by gasinvein** [comment]
bot, build com.valvesoftware.Steam.CompatibilityTool.Proton-Exp

**Comment by tim77** [comment]
LGTM, but some games doesn't work with this build. For example Borderlands 3 doesn't start, probably due to something gstreamer related and [this](https://github.com/ValveSoftware/Proton/commit/f244e5917637679df7a3560550345ea10ef45583).
```
0:00:06.841327128 436 0x7f541757db00 ERROR protonvideoconverter src/videoconv.rs:237:protonmediaconverter::videoconv: MEDIACONV_VIDEO_TRANSCODED_FILE is not set!
```
Full log: [proton-experimental-gst.log](https://github.com/flathub/flathub/files/5743223/proton-experimental-gst.log)

**Pull request closed without merging**
