### PR TITLE
Add org.kde.kcharselect

### PR DESCRIPTION
**Pull request by Mailaender**
### Please confirm your submission meets all the criteria

- [X] Please describe your application briefly.
> KDE utility to display special characters
- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I have [built][build] and tested the submission locally.
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://invent.kde.org/teams/flathub/issues/-/issues/14
- [X] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* https://invent.kde.org/utilities/kcharselect/-/merge_requests/22

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by Mailaender** [comment]
bot, build org.kde.kcharselect

**Comment by Mailaender** [comment]
bot, build org.kde.kcharselect

**Comment by Mailaender** [comment]
bot, build org.kde.kcharselect

**Comment by hfiguiere** [comment]
This is missing

> Please describe your application briefly.

**Comment by Mailaender** [comment]
bot, build org.kde.kcharselect

**Comment by travier** [comment]
LGTM.
Can you sort the finish-args and make sure that the content is well indented?
Thanks!

**Comment by hfiguiere** [comment]
bot, build org.kde.kcharselect

**Comment by hfiguiere** [comment]
problems with kde infra it seems.

**Comment by tsdgeos** [comment]
bot, build

**Comment by tsdgeos** [comment]
bot, build org.kde.kcharselect

**Comment by bbhtt** [comment]
bot, build org.kde.kcharselect

**Comment by bbhtt** [comment]
Merge action failed due to a 404, @Mailaender you have to reopen a new one likely.

**Comment by hfiguiere** [comment]
the repo was created.

**Comment by hfiguiere** [comment]
https://github.com/flathub/org.kde.kcharselect

**Comment by bbhtt** [comment]
The @ flathub/kde confused it, because it is not a github user.

The team is added automatically to org.kde.* apps by the script.

**Comment by travier** [comment]
> The @ flathub/kde confused it, because it is not a github user.
> 
> The team is added automatically to org.kde.* apps by the script.

Looks like it did not work this time as I don't have access to https://flathub.org/apps/manage/org.kde.kcharselect

**Comment by travier** [comment]
No luck. It keeps saying:
> Whoops!
>
>You are unauthorized to view this content.
>
> You might want to retry or go back [home](https://flathub.org/).

**Comment by bbhtt** [comment]
I added myself to the KDE team and it seems to show up. You probably need to wait a bit on your end.

image

**Comment by travier** [comment]
Ah, I had to refresh the app list for this to work. All good now. Thanks

**Pull request closed without merging**
