### PR TITLE
Add com.github.JannikHv.Gydl

### PR DESCRIPTION
**Pull request by AsavarTzeth**

### CODE REVIEW

**Comment by nedrichards** [comment]
Tested. This app appears to work well but doesn't pass the [Flathub review guidelines](https://github.com/flathub/flathub/wiki/Review-Guidelines) as it doesn't have an appstream file. 

(note: I am not an official Flathub reviewer, I'd just like to see this app available)

**Comment by nedrichards** [comment]
(please ignore previous deleted comment!)

In end user testing this works well on x86-64.

**Comment by AsavarTzeth** [comment]
Well it would be nice to get a build scheduled. I already do my own extensive testing on x86_64, with my own public repository and all. So that it works on that arch isn't really news to me. Still always happy to hear it working for other people.

Now if I could just get a build scheduled I would find out about ARM and hopefully get this accepted.

*By the way I think you caught that comment quick enough. I still have not got an email notification and I read it first now. :)*

**Comment by TingPing** [comment]
Test build: https://flathub.org/builds/#/builders/1/builds/305

**Comment by AsavarTzeth** [comment]
Looks like I have some *lame* issues to resolve tomorrow, haha.

**Comment by nedrichards** [comment]
For aarch64 you're going to need to blow away the shipped configure and use the host's version which knows about the architecture(!). Here's [an example of how to do it from Xiphos](https://github.com/flathub/org.xiphos.Xiphos/blob/master/org.xiphos.Xiphos.json#L70).

**Comment by nedrichards** [comment]
The i386 error may be due to an architecture issue with Flathub currently @ramcq is looking at this (it's actually really i386 not i586) so I don't think you can actually do anything here - we might have to ban this from i386 in the meantime.

**Comment by ramcq** [comment]
There's no toolchain problem thankfully, it's just that the lame configure doesn't correctly select whether SSE should be used and detects it wrong. Debian has a patch to add -msse in the right place, but also adding build-options like this to the lame module should work around the issue:
```
"build-options" : {
    "arch": {
        "i386": {
            "cflags": "-msse",
        }
    }
},
```

**Comment by ramcq** [comment]
Oh, ha - https://github.com/search?q=org%3Aflathub+lame&type=Code

**Comment by AsavarTzeth** [comment]
Yes, the last thing I did yesterday was that very same search. Perhaps this lame is good a candidate for a shared module. Now we have two applications using it and there has been some duplicated debugging work already.

**Comment by TingPing** [comment]
Test build: https://flathub.org/builds/#/builders/1/builds/316

**Comment by Alexander-Wilms** [comment]
Something went wrong with that build

**Comment by Barthalion** [comment]
Triggered a new one: https://flathub.org/builds/#/builders/1/builds/332

**Comment by Barthalion** [comment]
Another one because I can't copy&paste correctly: https://flathub.org/builds/#/builders/1/builds/334

**Comment by Barthalion** [comment]
Builds fine. I will merge it tomorrow.

**Comment by Barthalion** [comment]
Done, thank you!

**Pull request closed without merging**
