### PR TITLE
[WIP] Add com.github.tsujan.Kvantum

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
bot, build com.github.tsujan.Kvantum

**Comment by TheEvilSkeleton** [comment]
bot, build

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Comment by TheEvilSkeleton** [comment]
Oh, this is incomplete AF

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Comment by TheEvilSkeleton** [comment]
bot, build

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Comment by TheEvilSkeleton** [comment]
bot, build org.kde.KStyle.Kvantum

**Review by barthalion — CHANGES_REQUESTED** [review]
You can't ship both application and theme extension in the single "app". It's just not going to work.

**Comment by TheEvilSkeleton** [comment]
> You can't ship both application and theme extension in the single "app". It's just not going to work.

You got a point. I guess I'll have to close it. It was fun playing with Flatpak to be honest

**Comment by barthalion** [comment]
I don't know how Kvantum works, but I guess you can still submit the app and the theme separately.

**Comment by TheEvilSkeleton** [comment]
That seems to be a bit too hard for my end I guess. I thought it would've been much easier than expected

**Pull request closed without merging**
