### PR TITLE
Sublime Text dev utils

### PR DESCRIPTION
**Pull request by ptomato**
This contains various packages (Node and Python) needed for running various Sublime Text linter packages and other developer aids.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.sublimetext.three.DevUtils

**Comment by nedrichards** [comment]
bot, build com.sublimetext.three.DevUtils

**Comment by nedrichards** [comment]
You need a flathub.json for arm and aarch64 - other than that, seems fine https://flathub.org/builds/#/builders/2/builds/2021

**Comment by ptomato** [comment]
OK, done!

**Comment by nedrichards** [comment]
bot, build com.sublimetext.three.DevUtils

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.sublimetext.three.DevUtils

**Pull request closed without merging**
