### PR TITLE
page.codeberg.papojari.Find_Billy: init at 0.31.0

### PR DESCRIPTION
**Pull request by papojari**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by papojari** [comment]
bot, build page.codeberg.papojari.Find_Billy

**Comment by papojari** [comment]
bot, stop page.codeberg.papojari.Find_Billy

**Comment by papojari** [comment]
welp that didn't work I guess

**Comment by papojari** [comment]
bot, build page.codeberg.papojari.Find_Billy

**Comment by papojari** [comment]
I fixed missing dependencies inside of the game.

**Comment by papojari** [comment]
bot, build page.codeberg.papojari.Find_Billy

**Comment by papojari** [comment]
Nice, it works. It launches via command line and via launcher that use .desktop files.

**Comment by papojari** [comment]
@barthalion

**Comment by barthalion** [comment]
It does not start for me:

```
[bpiotrowski@risuku ~]$ flatpak run page.codeberg.papojari.Find_Billy
Godot Engine v3.4.2.stable.flathub.45eaa2daf - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL ES Batching: ON
 
ERROR: Condition "err" is true. Returned: err
   at: load_source_code (modules/gdscript/gdscript.cpp:775)
ERROR: Cannot load source code from file 'res://models/nope_sign/default.gd'.
   at: load (modules/gdscript/gdscript.cpp:2179)
ERROR: Failed loading resource: res://models/nope_sign/default.gd. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: res://models/nope_sign/default.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://models/nope_sign/default.gd
   at: poll (scene/resources/resource_format_text.cpp:412)
ERROR: Failed to load resource 'res://models/nope_sign/default.tscn'.
   at: load (core/io/resource_loader.cpp:206)
ERROR: Failed loading resource: res://models/nope_sign/default.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: res://levels/main.tscn:9 - Parse Error: [ext_resource] referenced nonexistent resource at: res://models/nope_sign/default.tscn
   at: poll (scene/resources/resource_format_text.cpp:412)
ERROR: Failed to load resource 'res://levels/main.tscn'.
   at: load (core/io/resource_loader.cpp:206)
ERROR: Failed loading resource: res://levels/main.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: Failed loading scene: res://levels/main.tscn
   at: start (main/main.cpp:2011)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object.cpp:2064)
```

**Comment by papojari** [comment]
But that should be fixed in the second build 🤨. Did you try the first or the second build?

**Comment by barthalion** [comment]
Oh, I don't actually know. Let me trigger a new one just to be sure.

**Comment by barthalion** [comment]
bot, build page.codeberg.papojari.Find_Billy

**Comment by papojari** [comment]
@barthalion is it ok to ping you when you're needed or will you check the pull requests yourself? Currently I don't know if you forgot this or if you're busy with somerhing else.

**Comment by papojari** [comment]
@barthalion is it ok to ping you when you're needed or will you check the pull requests yourself? Currently I don't know if you forgot this or if you're busy with something else.

**Comment by barthalion** [comment]
bot, build page.codeberg.papojari.Find_Billy

**Comment by barthalion** [comment]
@papojari Please ping me if I seem to forget about something. I'm usually busy with something else, but that's not a good excuse for that.

/merge

**Pull request closed without merging**
