### PR TITLE
Add art.taunoerik.taunomonitor

### PR DESCRIPTION
**Pull request by taunoe**
I already have an existing same app:

https://github.com/flathub/art.taunoerik.tauno-monitor

But I have to remove the hyphen from the app id. That's why new.

### Please confirm your submission meets all the criteria

- [x] Please describe your application briefly.
- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by hfiguiere** [comment]
> I already have an existing same app:
> 
> https://github.com/flathub/art.taunoerik.tauno-monitor
> 
> But I have to remove the hyphen from the app id. That's why new.

WHY? What's the point?

**Comment by taunoe** [comment]
What does this error then mean or how i fix it

https://buildbot.flathub.org/#/builders/6/builds/115864

"E: art.taunoerik.tauno-monitor.desktop:3: cid-rdns-contains-hyphen",

**Comment by hfiguiere** [comment]
That's because the metainfo doesn't have the right app-id.

When you the "rnds" form, NEVER should it have `.desktop`.

image

**Comment by taunoe** [comment]
Thank You!

**Pull request closed without merging**
