### PR TITLE
Add fyi.zoey.TeX-Match

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
a re-submission of https://flathub.org/apps/details/uk.co.mrbenshef.TeX-Match

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributible by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** cc @zoeyfyi   @zanderbrown
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build fyi.zoey.TeX-Match

**Comment by bilelmoussaoui** [comment]
bot, build fyi.zoey.TeX-Match

**Comment by zoeyfyi** [comment]
Also looks good, thanks again!

**Pull request closed without merging**
