### PR TITLE
Added LeoCAD (again).

### PR DESCRIPTION
**Pull request by leozide**

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build org.leocad.LeoCAD

**Comment by leozide** [comment]
bot, build org.leocad.LeoCAD

**Comment by barthalion** [comment]
It says `LeoCAD could not find a compatible Parts Library so only a small number of parts will be available.` at start.

Other than that, looks good! Message above can be fixed later.

**Comment by barthalion** [comment]
Repository has been created: https://github.com/flathub/org.leocad.LeoCAD
Thanks!

**Pull request closed without merging**
