### PR TITLE
Add com.github.artemanufrij.playmyvideos

### PR DESCRIPTION
**Pull request by gasinvein**
playmyvideos is a video library/player designed for elementaryOS.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.github.artemanufrij.playmyvideos

**Comment by nedrichards** [comment]
@gasinvein is @artemanufrij interested in co-maintaining?

**Comment by gasinvein** [comment]
@nedrichards I hope he is, there is already one [his app](/flathub/com.github.artemanufrij.playmymusic) on Flathub.

**Comment by bilelmoussaoui** [comment]
@gasinvein you may want to enforce using the elementary gtk/icons themes.

**Comment by gasinvein** [comment]
Why do so? The app looks fine to me.

**Comment by bilelmoussaoui** [comment]
@gasinvein I have packaged a lot of elementary apps in the past and a lot of them uses some icons or CSS classes that are specific to Granite.

**Comment by gasinvein** [comment]
@bilelmoussaoui But the app looks fine as it is and doesn't complain about missing icons or something. And enforcing use of elementary theme would make the app look alien in DEs other than Pantheon.

**Comment by bilelmoussaoui** [comment]
To be honest it's up to the developer if they want to fix any theme issues or want to go with the look he wanted to give to his app.

**Comment by barthalion** [comment]
So, what's the decision, are we good with it as is? @bilelmoussaoui  @gasinvein

**Comment by nedrichards** [comment]
@barthalion it's fine as an app, but I don't see an upstream ticket yet or evidence that upstream would like to be involved.

**Comment by nedrichards** [comment]
@bilelmoussaoui I know, but from the reviewer/flathub's perspective just because someone wants to be involved with two things doesn't necessarily mean they want to be involved with a third. It'd be rude to assume!

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.github.artemanufrij.playmyvideos

**Pull request closed without merging**
