### PR TITLE
Add org.kde.PlatformTheme.QGnomePlatform

### PR DESCRIPTION
**Pull request by grulja**

### CODE REVIEW

**Comment by grulja** [comment]
bot, build

**Comment by TingPing** [comment]
I mentioned this in the other issue but Flathub doesn't support building multiple versions which will be needed for 5.9, 5.10, and future releases. Gtk only gets by this since 3.22 was the last release.

**Comment by grulja** [comment]
I know, that's why I used "5.9" branch for now as all KDE apps use this branch too. Not sure about KDE apps here in flathub, but given "5.10" branch is relatively new and Qt 5.9 is LTS release, it should be okay for now. In KDE apps repo we also have this only for "5.9" branch.

**Comment by nedrichards** [comment]
I would be distressed about only supporting one version of the KDE SDK whilst having apps that targeted another version. This is why I suggested hosting on another repo for now - we'd be happy to import automatically using buildbot until this limitation can be fixed.

**Comment by grulja** [comment]
Do we need to have separate repositories for each theme or platform theme? Or can still all be part of kde-applications repository and you just pick up what you want?

**Comment by nedrichards** [comment]
My understanding is that we have to have one in each repo e.g. 

1. org.kde.PlatformTheme.QGnomePlatform (with branches for each version)
2. org.kde.KStyle.HighContrast (with branches for each version)
3. org.kde.KStyle.Adwaita (with branches for each version)

It's somewhat frustrating I know.

**Comment by barthalion** [comment]
The best would be to wait for Alex with decision, but IMHO we could handle it the same way Flathub "imports" KDE runtime.

**Comment by nedrichards** [comment]
@barthalion that's literally why we have this issue saying we do it in exactly that way already: https://github.com/flathub/buildbot-config/issues/24 ;-) based on the discussion there that's what I thought we were going to do.

**Comment by ramcq** [comment]
So what's the actual problem? Someone raise a PR against https://github.com/flathub/buildbot-config/blob/master/builds.json#L20 and we can merge it before we create these repos.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.kde.PlatformTheme.QGnomePlatform

**Pull request closed without merging**
