### PR TITLE
org.freedesktop.Sdk.Extension.swift

### PR DESCRIPTION
**Pull request by TingPing**
This is just a work in progress and hasn't been tested since it takes hours to build and locks up my machine but it might work and be a starting point if somebody is interested in it.

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
bot, build org.freedesktop.Sdk.Extension.swift

**Comment by TingPing** [comment]
bot, build org.freedesktop.Sdk.Extension.swift

**Comment by nedrichards** [comment]
fwiw the Swift Linux community seems to have mode some progress on their own, with some useful documentation as well: https://swift-linux.refi64.com/en/latest/index.html

**Comment by TingPing** [comment]
Looks like it just uses the prebuilt binaries sadly. What I have here shouldn't be far from working honestly. I gave up because it took like 30GB of disk space or something stupid.

**Comment by kirbyfan64** [comment]
Yeah, I just reused the binaries...I just don't have the disk space to fit an entire Swift build.

**Comment by kirbyfan64** [comment]
On that note, part of the reason I didn't bother submitting to Flathub (other than the rules against prebuilt binaries) was because I wanted to be able to run the compiler itself from the Flatpak, and I wasn't sure what Flathub's policy for things like that is.

**Comment by barthalion** [comment]
Our golang extension already re-uses binaries so I don't think it matters if bootstrapping is impractical.

I'm closing it due to inactivity – but please re-open it or resubmit as new pull request if you would like to see it merged in the future.

**Pull request closed without merging**
