### PR TITLE
Add uk.co.ibboard.cawbird

### PR DESCRIPTION
**Pull request by p1u3o**
This is a manifest for https://github.com/IBBoard/cawbird. This includes it's own limited build of gst-plugins-bad because the one inside the runtime has a bug which is fixed upstream.

If you could add @IBBoard (upstream dev) to the repository, that'd be great.

### CODE REVIEW

**Comment by p1u3o** [comment]
bot, build uk.co.ibboard.cawbird

**Comment by p1u3o** [comment]
bot, build uk.co.ibboard.cawbird

**Comment by nedrichards** [comment]
@p1u3o is there a bug report for the runtime gst issue? not a blocker to have bug fixes included but it'd be good to see this available to everyone

**Comment by p1u3o** [comment]
@nedrichards https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/commit/cfa0f1858075a3390def50250eafc89d270178d3 was the commit that fixed the playback bug, I'm not sure on what the actual bug is, other than what commit broke it and what commit fixed it.

**Comment by nedrichards** [comment]
no worries, so it landed after the last stable release. nothing much to do other than wait.

**Comment by p1u3o** [comment]
Thanks @nedrichards

**Pull request closed without merging**
