### PR TITLE
Add 4 Adapta-gtk-theme variants to flathub

### PR DESCRIPTION
**Pull request by tista500**
Hi, I'm an author of Adapta-gtk-theme.

Then I've created 8 files for 4 our theme variants (based on Arc's files)
  * Adapta (Light and standard widget size)
  * Adapta-Nokto (Dark and standard widget size)
  * Adapta-Eta (Light and compact widget size)
  * Adapta-Nokto-Eta (Dark and compact widget size)

Regards.

### CODE REVIEW

**Comment by TingPing** [comment]
This looks fine btw, just need to find the time to setup 4 repos.

**Comment by jp7677** [comment]
Hi @TingPing, any chance to get this merged anytime soon? Can't wait for flatpaks to perfectly blend in into my desktop ;). Thanks a lot for your work!

**Comment by TingPing** [comment]
All 4 repos have been created. A the time of posting the builds seemed to fail on ARM but that doesn't seem to be a problem with the package so we will look into that.

**Comment by tista500** [comment]
Thanks!

**Pull request closed without merging**
