### PR TITLE
Add manifest for org.kde.kphotoalbum

### PR DESCRIPTION
**Pull request by flyingcakes85**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned.
  - https://invent.kde.org/graphics/kphotoalbum/-/merge_requests/18

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by flyingcakes85** [comment]
bot, build org.kde.kphotoalbum

**Comment by flyingcakes85** [comment]
Ping @flathub/kde

**Comment by nedrichards** [comment]
> Error when extracting video thumbnails.
Error was: Unknown error

Other than that it does actually play the video file in the demo, even if it doesn't show a thumbnail.

**Comment by flyingcakes85** [comment]
I only tested with images, not videos. Indeed, it doesn't show thumbnail, and I don't remember adding any related dependency to manifest.

A quick grep in KPhotoAlbum's source code, I find that it tries to discover ffmpeg binary at run time (i.e. expecting system to have it installed).

```
MainWindow/FeatureDialog.cpp:64:                 "<p>KPhotoAlbum relies on QtAv for displaying videos; this in turn relies on ffmpeg</p>");
MainWindow/FeatureDialog.cpp:67:                 "<p>KPhotoAlbum can use <tt>ffmpeg</tt> to extract thumbnails from videos. These thumbnails are used to preview "
MainWindow/FeatureDialog.cpp:116:QString FeatureDialog::ffmpegBinary()
MainWindow/FeatureDialog.cpp:118:    QString ffmpeg = QStandardPaths::findExecutable(QString::fromLatin1("ffmpeg"));
MainWindow/FeatureDialog.cpp:119:    return ffmpeg;
```
Should ffmpeg too be compiled in manifest?
Should I add ffmpeg to manifest?

**Comment by barthalion** [comment]
I think that would be the best. The ffmpeg-full extension has a limited selection of codecs. You can find a few examples for bundling a full build at https://github.com/search?q=org%3Aflathub+ffmpeg.org%2Freleases&type=code.

**Comment by flyingcakes85** [comment]
I've added ffmpeg to manifest. Those errors mentioned above now don't pop up. But I still cannot see thumbnails for videos. In terminal, I have this printed many times
```
QImage::scaled: Image is a null image
```

I've taken a quick glance at its available config opts and don't find anything that could help.
As a side note, I installed kphotoalbum and ffmpeg via my distro package manager and even that couldn't display video thumbnails, so I suspect it may have something to do with the specific videos I have.

**Comment by flyingcakes85** [comment]
bot, build org.kde.kphotoalbum

**Pull request closed without merging**
