### PR TITLE
Add org.easycoding.TunedSwitcher

### PR DESCRIPTION
**Pull request by gasinvein**
TunedSwitcher a small program that provides a tray icon with menu for managing [Tuned](https://tuned-project.org/) profiles.

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
  - `--system-talk-name=com.redhat.tuned` - talks to Tuned on host for the core function
  - `--system-talk-name=org.freedesktop.systemd1` - asks systemd to start `tuned.service` if not already running
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

Please add @xvitaly (the developer) to collaborators.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by gasinvein** [comment]
bot, build org.easycoding.TunedSwitcher

**Comment by gasinvein** [comment]
bot, build org.easycoding.TunedSwitcher

**Comment by gasinvein** [comment]
A weird thing. Looks like `appstream-compose` saves icons under the name specified in `<launchable>` desktop file basename (`org.easycoding.TunedSwitcher.Applet`), despite the actual desktop file specifies `Icon` with the base app ID (`org.easycoding.TunedSwitcher`).

**Comment by gasinvein** [comment]
bot, build org.easycoding.TunedSwitcher

**Comment by nedrichards** [comment]
It'd be ideal if the description mentioned a bit more clearly that you must have the tuned service installed on your system already to use the app.

**Comment by gasinvein** [comment]
@nedrichards You mean the description in metainfo?

**Comment by barthalion** [comment]
Yeah, otherwise it will be unclear to users what the app requires n the host.

**Comment by gasinvein** [comment]
Proposed EasyCoding/tuned-switcher#19.

**Comment by barthalion** [comment]
It's okay to have a patch here.

**Comment by xvitaly** [comment]
> Proposed EasyCoding/tuned-switcher#19.

Merged. Thanks.

**Comment by gasinvein** [comment]
@xvitaly Can you please tag a `0.2.1` release? It would be very helpful, 'cause we can get rid of backported patches.

**Comment by gasinvein** [comment]
bot, build org.easycoding.TunedSwitcher

**Comment by xvitaly** [comment]
> Can you please tag a 0.2.1 release?

Done.

**Comment by gasinvein** [comment]
@xvitaly Thanks. I don't see the git tag, did you push it? It's not a big deal, though, I can just use the commit.

**Comment by gasinvein** [comment]
bot, build org.easycoding.TunedSwitcher

**Comment by xvitaly** [comment]
> Thanks. I don't see the git tag, did you push it? It's not a big deal, though, I can just use the commit.

Tag created.

**Pull request closed without merging**
