### PR TITLE
add dev.paullee.scraterpreter.Scrape

### PR DESCRIPTION
**Pull request by hillcrestpaul0719**
https://github.com/scraterpreter/scrape

Thanks!

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build dev.paullee.scraterpreter.Scrapec

**Comment by hillcrestpaul0719** [comment]
bot, build dev.paullee.scraterpreter.Scrape

**Comment by hillcrestpaul0719** [comment]
bot, build dev.paullee.scraterpreter.Scrape

**Comment by hillcrestpaul0719** [comment]
bot, build dev.paullee.scraterpreter.Scrape

**Comment by hillcrestpaul0719** [comment]
bot, build dev.paullee.scraterpreter.Scrape

**Comment by hillcrestpaul0719** [comment]
bot, build dev.paullee.scraterpreter.Scrape

**Comment by hillcrestpaul0719** [comment]
bot, build dev.paullee.scraterpreter.Scrape

**Comment by hillcrestpaul0719** [comment]
bot, build dev.paullee.scraterpreter.Scrape

**Comment by hillcrestpaul0719** [comment]
bot, build dev.paullee.scraterpreter.Scrape

**Pull request closed without merging**
