### PR TITLE
Add com.xnview.XnSketch (xnsketch-flatpak)

### PR DESCRIPTION
**Pull request by scx**
**XnSketch** allows you to turn your photos into cartoon or sketch images.
https://github.com/scx/flathub/tree/com.xnview.XnSketch

See also:
https://www.xnview.com/en/xnsketch/
https://github.com/scx/xnsketch-flatpak

### CODE REVIEW

**Comment by scx** [comment]
The vendor developer has been notified.

**Comment by scx** [comment]
bot, build com.xnview.XnSketch

**Comment by pierrexn** [comment]
Thanks

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.xnview.XnSketch

**Comment by scx** [comment]
@nedrichards 

Thanks! There are also [XnView MP](https://github.com/flathub/flathub/pull/882) and [XnConvert](https://github.com/flathub/flathub/pull/883) from the same developer.

**Pull request closed without merging**
