### PR TITLE
Import Kadas Albireo 2 to Flathub

### PR DESCRIPTION
**Pull request by aleixpol**
This was done with collaboration with upstream @manisandro and @pka.

https://github.com/kadas-albireo/kadas-albireo2

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build com.sourcepole.albireo

**Comment by aleixpol** [comment]
bot, build com.sourcepole.kadas

**Comment by nedrichards** [comment]
So there isn't a qtwebkit for ARM it seems, you'll need to ban that build with a flathub.json file. Otherwise it looks like the appdata file isn't being named correctly for the export https://flathub.org/builds/#/builders/51/builds/1550

**Comment by barthalion** [comment]
bot, build com.sourcepole.albireo

**Comment by barthalion** [comment]
bot, build com.sourcepole.kadas

**Comment by aleixpol** [comment]
bot, build com.sourcepole.kadas

**Comment by bilelmoussaoui** [comment]
The desktop file mentions kadas as an icon name. See https://github.com/kadas-albireo/kadas-albireo2/blob/master/com.sourcepole.kadas.desktop#L5 and https://github.com/kadas-albireo/kadas-albireo2/blob/401189e973ddd9a325770fb121dd744cccd572f7/CMakeLists.txt#L80 You need to add a `"rename-icon": "kadas"` to the manifest

**Comment by aleixpol** [comment]
bot, build com.sourcepole.kadas

**Comment by aleixpol** [comment]
bot, build com.sourcepole.kadas

**Comment by pka** [comment]
Valid screenshot URL: https://github.com/kadas-albireo/kadas-albireo2/raw/gh-pages/images/redlining.png

**Comment by aleixpol** [comment]
bot, build com.sourcepole.kadas

**Comment by pka** [comment]
Test ok.

**Pull request closed without merging**
