### PR TITLE
Add io.qt.QtCreator.Extension.Qt5

### PR DESCRIPTION
**Pull request by 4c0n**
This will make Qt5 optional for Qt Creator and needs to be available before we can merge: https://github.com/flathub/io.qt.QtCreator/blob/use-extension/io.qt.QtCreator.yaml to beta and test it.

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
on a higher level, why is this x86_64 only?

**Comment by 4c0n** [comment]
> on a higher level, why is this x86_64 only?

In the past the Qt Creator builds for other architectures would fail on the build platform because of resource limitations, out of memory or out of disk space was a common theme. I could try and open it up again and see if those issues are still there if you'd like.

**Comment by hfiguiere** [comment]
On the builders? The builders can handle it.

**Comment by 4c0n** [comment]
They couldn't in the past, but I have zero problems with trying it again as long as there is some way of getting support if the worker fails for reasons like the above ones.

**Pull request closed without merging**
