### PR TITLE
Add page.codeberg.alexispurslane.kissg

### PR DESCRIPTION
**Pull request by alexispurslane**
## Description

A simple libadwaita application for creating HTML pages from a content file and a few placeholder substitutions according to a template. Fills the niche of offering basic HTML templating capabilities to those who want to maintain their own website and understand bass HTML and CSS, but aren't comfortable dealing with a full static site generator.

### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly.
- [X] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read the and followed all the [Submission and licence requirements][reqs].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission.

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements#control-over-domain
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Review by hfiguiere — CHANGES_REQUESTED** [review]
This repository is NOT to store upstrean sources.

**Comment by hfiguiere** [comment]
Also you didn't

> Please describe the application briefly.

The checkboxes aren't CAPTCHA

**Comment by alexispurslane** [comment]
Sorry, I didn't see a field to add a description in the template layout for the pull request, so I assumed you simply meant to describe it briefly in the meta-data. Also, apologies, I wasn't aware that storing upstream sources wasn't allowed, given that the flathub required files section specifies to include any sources necessary to build the application alongside the manifest if you don't use an upstream URL in it. But I can change that as well.
-------- Original Message --------On 7/10/24 7:53 PM, Hubert Figuière  wrote:
Also you didn't

Please describe the application briefly.

The checkboxes aren't CAPTCHA

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/flathub/flathub/pull/5405#issuecomment-2221727063",
"url": "https://github.com/flathub/flathub/pull/5405#issuecomment-2221727063",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hfiguiere** [comment]
> Sorry, I didn't see a field to add a description

This is a whole text field

image

**Comment by alexispurslane** [comment]
> > Sorry, I didn't see a field to add a description
> 
> This is a whole text field
> 
> image

Sigh. A field *in the template layout of the pull request*, as many other projects have in their PR templates, which I assumed I was supposed to adhere to. So I wasn't sure where it was desired I put it.

**Pull request closed without merging**
