### PR TITLE
[WIP] Add org.spyder ide.Spyder

### PR DESCRIPTION
**Pull request by kevinsmia1939**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/spyder-ide/spyder/issues/6898
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

From the link above, upstream are not interested to package and maintain Spyder as Flatpak.

### CODE REVIEW

**Comment by kevinsmia1939** [comment]
bot, build org.spyder_ide.Spyder

**Comment by kevinsmia1939** [comment]
hmmm interesting 
`src.lib.errors.ManifestFileTooLarge: Manifest file size 148.0 KiB exceeds 100.0 KiB: /srv/buildbot/worker/build-x86_64/build/spyder_deps.json`

**Comment by kevinsmia1939** [comment]
bot, build org.spyder_ide.Spyder

**Comment by kevinsmia1939** [comment]
bot, build org.spyder_ide.Spyder

**Comment by hfiguiere** [comment]
The appstream can be found:
```
Not exporting share/metainfo/org.spyder_ide.spyder.appdata.xml, non-allowed export filename
```

It's case sensitive. I suggest fixing it here to match upstream.

**Comment by hfiguiere** [comment]
also the upstream appstream file lack `releases`, `url` and `content_rating`.

**Comment by kevinsmia1939** [comment]
oops, I rename the branch and it got deleted.

**Comment by hfiguiere** [comment]
you never need to rename a branch for a submission.

**Comment by kevinsmia1939** [comment]
> you never need to rename a branch for a submission.

ok thanks, will keep that in mind.

**Pull request closed without merging**
