### PR TITLE
add net.sourceforge.kmidimon

### PR DESCRIPTION
**Pull request by pedrolcl**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link: https://sourceforge.net/projects/kmidimon/**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(no patches)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by pedrolcl** [comment]
bot, build net.sourceforge.kmidimon

**Comment by pedrolcl** [comment]
bot, build net.sourceforge.kmidimon

**Comment by pedrolcl** [comment]
The Open File dialog does not work, and produces error messages like:

~~~
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
~~~

**Comment by hfiguiere** [comment]
> The Open File dialog does not work, and produces error messages like:
> 
> ```
> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
>  "Not connected to D-Bus server"
> ```

Not sure why it would need this, but adding `--system-talk-name=org.freedesktop.UDisks2` to the finish args should grant the DBus permissions.

**Comment by pedrolcl** [comment]
bot, build net.sourceforge.kmidimon

**Comment by pedrolcl** [comment]
bot, build net.sourceforge.kmidimon

**Comment by pedrolcl** [comment]
> > The Open File dialog does not work, and produces error messages like:
> 
> Not sure why it would need this, but adding `--system-talk-name=org.freedesktop.UDisks2` to the finish args should grant the DBus permissions.

Solved now. The DBus problem is local to my system, but the file open dialog problem was present on other systems. It was a problem with the mime types. The library Drumstick::File provides a mime type description for Cakewalk files. It may be useful for users wanting to associate WRK files with some application like kmidimon, or dmidiplayer. But then, the open file function in kmidimon is using mime types instead of name filters, and that was the problem.

**Pull request closed without merging**
