### PR TITLE
Add nl.v0yd.Capsule

### PR DESCRIPTION
**Pull request by sonnyp**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge). [jonas2515](https://github.com/jonas2515) does
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by sonnyp** [comment]
bot, build

**Comment by sonnyp** [comment]
bot, build nl.v0yd.Capsule

**Comment by dginovker** [comment]
You're missing an Appstream file: https://github.com/flathub/flathub/wiki/App-Requirements#Appstream

If upstream doesn't supply one, you can make your own. Here's an example: https://github.com/flathub/vet.rsc.OpenRSC.Launcher/blob/master/vet.rsc.OpenRSC.Launcher.appdata.xml

**Comment by dginovker** [comment]
You're also missing other required files, like a .desktop and icons. Be sure to go through the https://github.com/flathub/flathub/wiki/App-Requirements section

**Comment by hfiguiere** [comment]
No. The error is that the value of `<launchable>` in the appstream file is incorrect. It misses the `.desktop` suffix since it is the name of the desktop file.

From the logs:
```
Invalid desktop filename: nl.v0yd.Capsule
```

**Comment by sonnyp** [comment]
bot, build nl.v0yd.Capsule

**Comment by sonnyp** [comment]
bot, build nl.v0yd.Capsule

**Comment by sonnyp** [comment]
@hfiguiere thank you and solved :heavy_check_mark:

**Pull request closed without merging**
