### PR TITLE
Add LSP LV2 plugins extension

### PR DESCRIPTION
**Pull request by AsavarTzeth**
The lsp-plugins collection of LADSPA/LV2/VST compatible plugins use a
rare funding model. All plugins are proprietary until a donation
milestone is reached. This means some plugins can only be provided
from binary sources.

Fortunately this is not an issue, because the license does allow
unmodified re-distribution of the upstream provided binaries.

For now, this solves license compatibility uncertainties with
com.github.wwmm.pulseeffects. It also allows users to choose
whether they want to install this or not.

### CODE REVIEW

**Comment by AsavarTzeth** [comment]
Oh, bugger. A few seconds later and I notice the branch name is wrong. It should of course be **com.github.wwmm.pulseeffects.plugin.lsp-plguins**.

**Comment by nedrichards** [comment]
bot, build com.github.wwmm.pulseeffects.plugin.lsp-plguins

**Comment by AsavarTzeth** [comment]
It seems the build failed because it expects a json manifest.

This is my first pull request, using YAML. Can I not use `.yml` initally?

**Comment by nedrichards** [comment]
bot, build com.github.wwmm.pulseeffects.plugin.lsp-plugins

**Comment by AsavarTzeth** [comment]
Sorry, try again. I forgot to push the extension points update.

**Comment by nedrichards** [comment]
bot, build com.github.wwmm.pulseeffects.plugin.lsp-plugins

**Comment by AsavarTzeth** [comment]
The last build was a success. See [here](https://flathub.org/builds/#/builders/2/builds/2479). Any chance of adding a repo?

Not sure why GitHub thinks it failed and links to an older build.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.github.wwmm.pulseeffects.plugin.lsp-plugins

**Pull request closed without merging**
