### PR TITLE
com.github.bcedu.vgrive

### PR DESCRIPTION
**Pull request by bcedu**
Main page: https://github.com/bcedu/VGrive

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build com.github.bcedu.vgrive

**Comment by LeandroStanger** [comment]
bot, build com.github.bcedu.vgrive

**Comment by bilelmoussaoui** [comment]
Mind patching the app here or forcing the theme upstream as some icons are missing 
Screenshot from 2019-11-02 09-25-18
Screenshot from 2019-11-02 09-25-22

**Comment by bcedu** [comment]
I am already working on it:

https://github.com/bcedu/VGrive/issues/29

You can wait until it is solved or merge the PR and I will update the versions

**Comment by bcedu** [comment]
@bilelmoussaoui With the new update the icons should be aviable

**Comment by LeandroStanger** [comment]
bot, build com.github.bcedu.vgrive

**Pull request closed without merging**
