### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SammyMayn**
### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
not sure what you are trying to do, but there is nothing looking like a Flatpak manifest.

**Comment by SammyMayn** [comment]
Hi,
I'm simply trying to add my app to the flatpak repository.
I included the manifest.md file from my app, is that wrong?
How do I generate a flatpak manifest file?
Any help would be greatly appreciated.
Sy.

**Comment by barthalion** [comment]
Please have a look at https://docs.flatpak.org/en/latest/building.html.

**Comment by barthalion** [comment]
@SammyMayn The extension usage is described at https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11#usage. You may need to pass `-install-deps-from=flathub` to flatpak-builder when testing the build locally.

**Pull request closed without merging**
