### PR TITLE
Add com.dangeredwolf.ModernDeck

### PR DESCRIPTION
**Pull request by Lunarequest**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Lunarequest** [comment]
bot, build com.dangeredwolf.ModernDeck

**Comment by Lunarequest** [comment]
bot, build com.dangeredwolf.ModernDeck

**Comment by Lunarequest** [comment]
bot, build com.dangeredwolf.ModernDeck

**Comment by nedrichards** [comment]
When I press exit I get

> 10:21:55.508 › Install on explicit quitAndInstall
10:21:55.508 › Error: Error: No valid update available, can't quit and install
    at AppImageUpdater.install (/app/bin/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:45:32)
    at AppImageUpdater.quitAndInstall (/app/bin/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:15:34)
    at click (/app/bin/resources/app.asar/main.js:1225:143)
    at MenuItem.click (electron/js2c/browser_init.js:73:1742)
    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)

and it doesn't actually exit. Other than that, lgtm

**Comment by Lunarequest** [comment]
I have attempted to fix the issue @nedrichards could you test this?

**Comment by Lunarequest** [comment]
bot, build com.dangeredwolf.ModernDeck

**Comment by nedrichards** [comment]
I'm still seeing the error, are you from the test build?

**Comment by Lunarequest** [comment]
> I'm still seeing the error, are you from the test build?

I don't quite get what you mean? I am not able to reproduce the issue which makes things a bit harder

**Comment by hfiguiere** [comment]
I just started it, selected language (English - Canada) and then it crashed:

```
% flatpak run com.dangeredwolf.ModernDeck
[3 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/bin/moderndeck --type=zygote
{}
Gtk-Message: 19:33:28.565: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:33:28.565: Failed to load module "canberra-gtk-module"
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:3) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at EventEmitter.i.send (electron/js2c/renderer_init.js:105:312)
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:101:357)
(Use `moderndeck --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Lunarequest** [comment]
> I just started it, selected language (English - Canada) and then it crashed:
> 
> ```
> % flatpak run com.dangeredwolf.ModernDeck
> [3 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/bin/moderndeck --type=zygote
> {}
> Gtk-Message: 19:33:28.565: Failed to load module "canberra-gtk-module"
> Gtk-Message: 19:33:28.565: Failed to load module "canberra-gtk-module"
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> (node:3) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
>     at EventEmitter.i.send (electron/js2c/renderer_init.js:105:312)
>     at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:101:357)
> (Use `moderndeck --trace-warnings ...` to show where the warning was created)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:3) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

Not sure why that happened @dangeredwolf any ideas?

**Comment by dangeredwolf** [comment]
@hfiguiere @Lunarequest When you set a language in ModernDeck, it restarts. However, running it from flatpak in command line causes it to not reopen automatically. If you run it again, it will work fine.

 The "An object could not be cloned." error occurs on Windows as well but it runs fine even with it. It's not clear what is causing it but it seems to have been related to an Electron update, and doesn't hinder operation.

**Comment by hfiguiere** [comment]
it did ask me.

**Comment by nedrichards** [comment]
Sorry, I meant are you running the build from https://github.com/flathub/flathub/pull/2726#issuecomment-1007894738 as well?

**Comment by Lunarequest** [comment]
> Sorry, I meant are you running the build from [#2726 (comment)](https://github.com/flathub/flathub/pull/2726#issuecomment-1007894738) as well?

Yes, I haven't been able to reproduce the issue

**Comment by barthalion** [comment]
Yeah, it does not seem to start automatically after changing language here, either. But I don't think it's a blocker? Everything works fine apart from that. FTFY it wouldn't be the first app on Linux that doesn't restart automatically.

**Pull request closed without merging**
