### PR TITLE
Add org.freedesktop.LinuxAudio.Plugins.Guitarix

### PR DESCRIPTION
**Pull request by hfiguiere**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)* - **n/a**
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** this is just a fork out of the already submitted app: the lv2 plugins. See below for an explanation
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge). **n/a**
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* working on it. See https://github.com/brummer10/guitarix/pull/62

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
This has to be split because I can't build an extension with a differnt branch.
See https://github.com/flatpak/flatpak-builder/issues/388
And the workaround to build the app on a branch was dropped https://github.com/flathub/org.guitarix.Guitarix/commit/066b22bbdf1148a1761797de301779d6761a1269

Until https://github.com/flatpak/flatpak-builder/issues/388 is solved this is the only route.

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.Guitarix

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.Guitarix

**Comment by barthalion** [comment]
I'd argue that #388 is a bug, an extension built as part of the app should always match app's branch.

/merge

**Pull request closed without merging**
