### PR TITLE
add Teleport

### PR DESCRIPTION
**Pull request by jsparber**

### CODE REVIEW

**Comment by nedrichards** [comment]
test build: https://flathub.org/builds/#/builders/1/builds/751

**Comment by jsparber** [comment]
Do we need to do something?

**Comment by nedrichards** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.frac_tion.teleport <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
