### PR TITLE
Add org.freedesktop.LinuxAudio.Plugins.UhhyouPlugins

### PR DESCRIPTION
**Pull request by hfiguiere**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
    n/a
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
  audio plugisn extensions
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*
  They are for JUCE, already fixed in later versions.

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flatpak.org/en/latest/first-build.html

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.UhhyouPlugins

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.UhhyouPlugins

**Comment by hfiguiere** [comment]
bot, build org.freedesktop.LinuxAudio.Plugins.UhhyouPlugins

**Review by bbhtt — COMMENTED** [review]
Seems fine to me.

**Pull request closed without merging**
