### PR TITLE
Add com.visualstudio.code.tool.fish

### PR DESCRIPTION
**Pull request by gasinvein**
This enables using the fish shell inside flatpak sandbox, e.g. in VS Code built-in terminal. Fish requires a TTY and, thus, can't be ran via `flatpak-spawn --host`.

### CODE REVIEW

**Comment by gasinvein** [comment]
bot, build org.freedesktop.Sdk.Extension.fish

**Comment by gasinvein** [comment]
bot, build org.freedesktop.Sdk.Extension.fish

**Comment by LeandroStanger** [comment]
bot, build org.freedesktop.Sdk.Extension.fish

**Comment by barthalion** [comment]
I'm hesitant to see general purpose tools available as SDK extension. Fish is not a build requirement for any application and it gives a wrong idea of extensions being package dependencies.

There were talks about having generic tools extension point available in FDO runtime. @nanonyme do you happen to remember if any issue was opened about it?

**Comment by FakeShemp** [comment]
@barthalion Could it still be a VS Code extension?

**Comment by barthalion** [comment]
@FakeShemp Yes, you don't need separate repository for it: https://github.com/flathub/com.visualstudio.code.oss/blob/master/com.visualstudio.code.oss.json#L1

Probably would be better to have single `Tools` extension for all VSCode versions/branches, there's PR with the prerelease pending.

**Comment by gasinvein** [comment]
bot, build com.visualstudio.code.tool.fish

**Comment by gasinvein** [comment]
bot, build com.visualstudio.code.tool.fish

**Comment by gasinvein** [comment]
Sorry for the noise.

bot, build com.visualstudio.code.tool.fish

**Comment by gasinvein** [comment]
bot, build com.visualstudio.code.tool.fish

**Comment by gasinvein** [comment]
@barthalion Can I use `com.visualstudio.code-oss` as runtime here, so this extension could be built for more architectures?

**Comment by barthalion** [comment]
Yes, but it still should be tackled on the runtime/SDK level rather than application.

**Comment by gasinvein** [comment]
You mean it should have branch `19.08`? Seems like a good idea, but it would require changes on the app side.

**Comment by gasinvein** [comment]
bot, build com.visualstudio.code.tool.fish

**Comment by gasinvein** [comment]
bot, build com.visualstudio.code.tool.fish

**Comment by gasinvein** [comment]
@barthalion Both vscode and code-oss now have tools extension point with version matching SDK branch.

**Pull request closed without merging**
