### PR TITLE
Add org.gtk.Gtk3theme.Yaru-Amber

### PR DESCRIPTION
**Pull request by Mek101**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/Jannomag/Yaru-Colors/issues/76#issuecomment-790435452
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Mek101** [comment]
bot, build org.gtk.Gtk3theme.Yaru-Amber

**Comment by Mek101** [comment]
This is 1 of the 45 variants of Yaru-Colors https://github.com/Jannomag/Yaru-Colors. Once/if this pr request is accepted, and eventual changes propagated to the others, should I send them in all in one batch or should I break them in smaller batches day to day in order to not fill up the "Pull requests" page?

**Comment by barthalion** [comment]
Feel free to submit them at once. (Also sorry for late review!)

/merge @Jannomag

**Pull request closed without merging**
