### PR TITLE
Add org.bitbucket.mystery_keeper.VapourSynthEditor.Plugin.FFMS2

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by FakeShemp** [comment]
bot, build org.bitbucket.mystery_keeper.VapourSynthEditor.Plugin.FFMS2

**Comment by FakeShemp** [comment]
bot, build org.bitbucket.mystery_keeper.VapourSynthEditor.Plugin.FFMS2

**Comment by FakeShemp** [comment]
```
error: No extension point matching org.bitbucket.mystery_keeper.VapourSynthEditor.Plugin.FFMS2 in app/org.bitbucket.mystery_keeper.VapourSynthEditor/aarch64/stable
```
I'm not really sure what I'm doing wrong right now. Could I get some help? Are there a limit to how many dots can be in a plugin ID?

**Comment by FakeShemp** [comment]
As far as I can tell, the plugin builds if I remove `FFMS2` and change the ID to `org.bitbucket.mystery_keeper.VapourSynthEditor.Plugin`. I have no idea what's going on.

**Comment by FakeShemp** [comment]
bot, build org.bitbucket.mystery_keeper.VapourSynthEditor.Plugin.FFMS2

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.bitbucket.mystery_keeper.VapourSynthEditor.Plugin.FFMS2

**Pull request closed without merging**
