### PR TITLE
Add org.sugarlabs.HelloWorld

### PR DESCRIPTION
**Pull request by tchx84**
HelloWorld is a demo application used in tutorials for porting Sugar applications to Flatpak.

### CODE REVIEW

**Comment by tchx84** [comment]
bot, build org.sugarlabs.HelloWorld

**Comment by barthalion** [comment]
No complaints about manifest, just wondering if a "hello world" application really belongs here. Is it actually useful or acts as an example how to flatpak Sugar apps?

**Comment by tchx84** [comment]
> No complaints about manifest, just wondering if a "hello world" application really belongs here. Is it actually useful or acts as an example how to flatpak Sugar apps?

That's a good point, is not really a useful app per-se... It is Sugar equivalent to https://github.com/flathub/electron-sample-app

**Comment by barthalion** [comment]
We can merge it as "sugar-sample-app" if you wish, it just won't be installable.

**Comment by tchx84** [comment]
> We can merge it as "sugar-sample-app" if you wish, it just won't be installable.

No need :) I just (mistakenly) had the idea that we were also hosting other demo apps like this. I can publish this repo on my personal account.

**Pull request closed without merging**
