### PR TITLE
Add com.obsproject.Studio.Plugin.NVFBC

### PR DESCRIPTION
**Pull request by guihkx**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://gitlab.com/fzwoch/obs-nvfbc/-/issues/4
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

This OBS Studio plugin allows NVIDIA users to screen record with lower latency/CPU usage than OBS's XSHM. However, in order for it to work properly on consumer-grade NVIDIA GPUs, it requires manually patching both host and Flatpak drivers.

If an user installs this plugin without having patched drivers or a professional-grade NVIDIA GPU, OBS' functionality should be  unaffected.

I've added a step-by-step guide on how to manually patch the drivers, but with a big disclaimer mentioning the risk.

Thanks guys!

### CODE REVIEW

**Comment by guihkx** [comment]
bot, build com.obsproject.Studio.Plugin.NVFBC

**Comment by hfiguiere** [comment]
@GeorgesStavracas can you have a look at this OBS plus submission?

**Review by GeorgesStavracas — APPROVED** [review]
Overall, this looks good I think. It makes me sadistically happy to see the effort in scaring people away from shooting their own feet in the README file :slightly_smiling_face:

**Pull request closed without merging**
