### PR TITLE
Atlantik

### PR DESCRIPTION
**Pull request by Mailaender**
### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://invent.kde.org/games/atlantik/-/merge_requests/3
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* https://invent.kde.org/games/atlantik/-/merge_requests/3 https://invent.kde.org/games/atlantik/-/merge_requests/4

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by Mailaender** [comment]
bot, build org.kde.atlantik

**Comment by tsdgeos** [comment]
Why are you packaging atlantik? It has not had a release since 14 years ago

**Comment by Mailaender** [comment]
It was advertised at https://apps.kde.org/atlantik/ so I built it to check its state and was surprised to see it maintained.

**Comment by Mailaender** [comment]
bot, build org.kde.atlantik

**Comment by tsdgeos** [comment]
Yes, Pino put some work on it last year, but if it's not release, it should not be packaged, ping him about making a release.

**Comment by Mailaender** [comment]
Shall we add it as beta or not at all?

**Comment by tsdgeos** [comment]
I'm fine with adding it as beta if you want

**Pull request closed without merging**
