### PR TITLE
Add org.gnome.Calls

### PR DESCRIPTION
**Pull request by darkdragon-001**
Copied manifest from [upstream](https://gitlab.gnome.org/GNOME/calls).

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. https://gitlab.gnome.org/GNOME/calls/-/issues/125#note_1288009
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build org.gnome.Calls

**Comment by hfiguiere** [comment]
You probably need to declare some dbus name to talk to. Pass to `flatpak run` :  `--log-session-bus` to log the the session dbus and `--log-system-bus` for the system bus to figure them out.

**Comment by darkdragon-001** [comment]
bot, build org.gnome.Calls

**Comment by darkdragon-001** [comment]
bot, build org.gnome.Calls

**Comment by darkdragon-001** [comment]
@barthalion `--system-talk-name` seems to do the trick for the warning. How do I need to adapt the manifest?

**Comment by darkdragon-001** [comment]
Everything seems to work fine in the latest build. So I think this should be ready from my side :smiley:

**Pull request closed without merging**
