### PR TITLE
org.fkoehler.KTailctl

### PR DESCRIPTION
**Pull request by f-koehler**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. Except for unrestricted permissions I am using:
  - `--talk-name=org.kde.StatusNotifierWatcher` to create a tray icon
  - `--talk-name=org.freedesktop.Flatpak` to use `flatpak-spawn` to run the Tailscale CLI tool.
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** [https://github.com/f-koehler/KTailctl](https://github.com/f-koehler/KTailctl)
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by f-koehler** [comment]
bot, build org.fkoehler.KTailctl

**Comment by barthalion** [comment]
bot, build org.fkoehler.KTailctl

**Comment by f-koehler** [comment]
Building fails due to a linter error, as the app requires access to `flatpak-spawn` via the `org.freedesktop.Flatpak` interface. I opened a PR https://github.com/flathub/flatpak-builder-lint/pull/140 to add an exception. Once it gets merged the build should succeed.

**Comment by barthalion** [comment]
Trayscale simply bundles Tailscale CLI: https://github.com/flathub/dev.deedles.Trayscale/blob/master/dev.deedles.Trayscale.yml#L44

Any reason it couldn't be done here as well?

**Comment by f-koehler** [comment]
@barthalion actually, I cannot think of my reason why it should not work for this project as well. Just did not think about doing it that way, the LICENSE permits that. I will try it.

**Comment by f-koehler** [comment]
bot, build org.fkoehler.KTailctl

**Comment by f-koehler** [comment]
I updated the manifest to bundle Tailscale. I was able to remove the `org.flatpak.Flatpak` DBus Interface permission. However, I had to add the `--filesystem=/run/tailscale:ro` permission to provide read-only access to the Tailscale socket.

However, now I am struggling with a DNS name resolution issue when the `go build` command tries to fetch the required go modules. On my local machine I added the `--share=network` build argument under the `build-options` section. But this does not seem to work in the sandboxed build by @flathubbot (see [build 41839](https://buildbot.flathub.org/#/builders/6/builds/41839)).

I would appreciate any pointers on how to resolve this issue.

**Comment by barthalion** [comment]
Builds are done offline. Trayscale vendors Go dependencies to avoid network access: https://github.com/flathub/dev.deedles.Trayscale/blob/master/dev.deedles.Trayscale.yml#L54

**Comment by f-koehler** [comment]
bot, build org.fkoehler.KTailctl

**Comment by f-koehler** [comment]
> Builds are done offline. Trayscale vendors Go dependencies to avoid network access: https://github.com/flathub/dev.deedles.Trayscale/blob/master/dev.deedles.Trayscale.yml#L54

Thanks for making me aware, I implemented something similar. Now, I am facing another issue and will continue to work on this tomorrow.

**Comment by f-koehler** [comment]
bot, build org.fkoehler.KTailctl

**Comment by f-koehler** [comment]
bot, build org.fkoehler.KTailctl

**Comment by f-koehler** [comment]
bot, build org.fkoehler.KTailctl

**Comment by f-koehler** [comment]
So everything build now, hopefully the app is ready to be published on flathub.

**Pull request closed without merging**
