### PR TITLE
Add com.voxdsp.PacGal

### PR DESCRIPTION
**Pull request by BeverlyCode**
### Please confirm your submission meets all the criteria

- [A 3D remake of PAC-MAN the game] Please describe your application briefly.
- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by bbhtt** [comment]
Closing the app seems to crash the GNOME session. GNOME 46/Fedora 40 inside a VM.

**Comment by bbhtt** [comment]
> I am going to try to replicate your environment, are you using QEMU or VirtualBox?

GNOME Boxes, it is a QEMU frontend. I could consistently see the crash in the VM. If you can't repro I'll mark it as ready.

**Comment by bbhtt** [comment]
Ok marked it as ready for merge since it can't be reproduced.

**Comment by GeopJr** [comment]
This was made (and merged) against `master` and the page seems to be broken https://flathub.org/apps/com.voxdsp.PacGal

**Comment by bbhtt** [comment]
It will take some time before it is shown on the website.

**Pull request closed without merging**
