### PR TITLE
Add io.github.xverizex.RetroSpriteEditor

### PR DESCRIPTION
**Pull request by xverizex**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
why do you keep closing the PR to open a new one?

**Comment by xverizex** [comment]
I just don't work well with git. I can't correct it correctly.

**Comment by xverizex** [comment]
Sorry.

**Comment by xverizex** [comment]
Network is need to show news and tutorial in the future.

**Comment by xverizex** [comment]
bot, build io.github.xverizex.RetroSpriteEditor

**Comment by xverizex** [comment]
bot, build io.github.xverizex.RetroSpriteEditor

**Comment by xverizex** [comment]
@hfiguiere bot write that libxml2 is not found in /usr/lib. but my gnome builder builds fine.

**Comment by xverizex** [comment]
bot, build io.github.xverizex.RetroSpriteEditor

**Comment by xverizex** [comment]
bot, build io.github.xverizex.RetroSpriteEditor

**Comment by xverizex** [comment]
bot, build io.github.xverizex.RetroSpriteEditor

**Comment by xverizex** [comment]
bot, build io.github.xverizex.RetroSpriteEditor

**Comment by xverizex** [comment]
What's next?

**Comment by xverizex** [comment]
bot, build io.github.xverizex.RetroSpriteEditor

**Comment by xverizex** [comment]
works fine.

**Comment by xverizex** [comment]
bot, build io.github.xverizex.RetroSpriteEditor

**Comment by barthalion** [comment]
bot, build io.github.xverizex.RetroSpriteEditor

**Pull request closed without merging**
