### PR TITLE
Add LLVM 12 as a freedesktop SDK extension

### PR DESCRIPTION
**Pull request by Lctrs**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Not needed**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *Patches took from freedesktop SDK or already applied upstream*

Should be merged in `branch/20.08`.

Please also add @Erick555 as a co-maintainer and in https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm11 as well.

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build org.freedesktop.Sdk.Extension.llvm12

What are you planning to use it for?

**Comment by Lctrs** [comment]
It's for `net.rpcs3.RPCS3`. Upstream likes to live on the edge.

Also, I heard it might be useful for other people : `org.chromium.Chromium` now uses llvm11 and might use llvm12.

Also, [they are considering remove llvm from the SDK](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1215), so llvm extensions might become common.

**Comment by Erick555** [comment]
@Lctrs did the tablegen patch no longer apply? Could you try if using llvm from runtime instead of llvm11 extension fixes the build issue for aarch64?

**Comment by Lctrs** [comment]
@Erick555 Yes, it does not apply anymore since [upstream replaced llvm-build by cmake](https://github.com/llvm/llvm-project/commit/9218ff50f93085d0a16a974db28ca8f14bc66f64#diff-aa65b3dc6baadb6ed294aaa7558dc2e75ea957ee9992416f764aebe37dbe187f).

**Comment by Lctrs** [comment]
bot, build

**Comment by Lctrs** [comment]
bot, build org.freedesktop.Sdk.Extension.llvm12

**Comment by Erick555** [comment]
@barthalion I think it's reasonably ok to merge. I'll look at polishing it a bit after that.

**Pull request closed without merging**
