### PR TITLE
add org.kde.kiten

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by cho2** [comment]
bot, build org.kde.kiten

**Comment by cho2** [comment]
bot, build org.kde.kiten

**Comment by cho2** [comment]
bot, build org.kde.kiten

**Comment by cho2** [comment]
bot, build org.kde.kiten

**Comment by cho2** [comment]
What do you think @tsdgeos ?

**Comment by nedrichards** [comment]
@cho2 is the appdata patch submitted upstream?

**Comment by nedrichards** [comment]
@flathub/kde

**Comment by tsdgeos** [comment]
Hmmmmm, i'm confused, why does it work fot you?

It asserts for me
tsdgeos@xps:~:$ flatpak run org.kde.kiten 
ASSERT failure in KCatalogPrivate::setupGettextEnv: "You need to instantiate a Q*Application before using KCatalog", file src/kcatalog.cpp, line 223

Are you running a special sdk? or am i?

**Comment by tsdgeos** [comment]
And why don't i get that warning with my self compiled kiten?

**Comment by tsdgeos** [comment]
ok, i can reproduce it on my self compiled kiten now, i'll fix it upstream.

I'm guessing you're using a language which kiten is not translated into?

**Comment by tsdgeos** [comment]
Fix here, let's see if i can get some reviewer 

https://invent.kde.org/education/kiten/-/merge_requests/6/diffs

**Comment by tsdgeos** [comment]
Patch's been merged upstream already, can you add it here until 20.08.3 ?

**Comment by cho2** [comment]
> @cho2 is the appdata patch submitted upstream?

@nedrichards It's merged https://invent.kde.org/education/kiten/-/merge_requests/5

**Comment by cho2** [comment]
> Patch's been merged upstream already, can you add it here until 20.08.3 ?

@tsdgeos no problem

**Comment by eszlari** [comment]
khtml and kjs are not needed anymore: https://www.archlinux.org/packages/extra/x86_64/kiten/

**Comment by cho2** [comment]
> khtml and kjs are not needed anymore: https://www.archlinux.org/packages/extra/x86_64/kiten/

Let's try to remove it and build again

**Comment by cho2** [comment]
bot, build org.kde.kiten

**Pull request closed without merging**
