### PR TITLE
Add cc.retroshare.retroshare-gui 0.6.5

### PR DESCRIPTION
**Pull request by G10h4ck**

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build cc.retroshare.retroshare-gui

**Comment by G10h4ck** [comment]
All tests seems to fail after compilation which seems to b successful, with this error 8:18 failed 'stat builddir/*/share/app-info/xmls/cc.retroshare.retroshare-gui.xml.gz' any clue of what/how that file should be generated?

**Comment by bilelmoussaoui** [comment]
@G10h4ck Because the application doesn't ship an appdata file. See the specs  here https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps and the requirements of Flathub here https://github.com/flathub/flathub/wiki/App-Requirements#appstream

**Comment by G10h4ck** [comment]
bot, build cc.retroshare.retroshare-gui

**Comment by bilelmoussaoui** [comment]
Oh, you forgot about OARS tag. 
`• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]`

here's how you can generate one https://hughsie.github.io/oars/generate.html

**Comment by G10h4ck** [comment]
bot, build cc.retroshare.retroshare-gui

**Comment by G10h4ck** [comment]
> Oh, you forgot about OARS tag.
> `• tag-missing : <content_rating> required [use https://odrs.gnome.org/oars]`
> 
> here's how you can generate one https://hughsie.github.io/oars/generate.html

Thanks!

**Comment by nedrichards** [comment]
> libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965


You need to add `--device=dri` to your finish-args to fix this.

**Comment by G10h4ck** [comment]
Thanks for testing and suggesting!

**Comment by nedrichards** [comment]
bot, build cc.retroshare.retroshare-gui

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/cc.retroshare.retroshare-gui

**Comment by G10h4ck** [comment]
Thanks!

**Pull request closed without merging**
