### PR TITLE
adding org.americanmonk.TipitakaPaliReader

### PR DESCRIPTION
**Pull request by bksubhuti**
### Please confirm your submission meets all the criteria

- [x ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ x] My pull request follows the instructions at [App Submission][submission].
- [ x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

### CODE REVIEW

**Comment by hfiguiere** [comment]
Still missing the appstream file.

**Comment by bksubhuti** [comment]
appstream file according to gpt is the xml file and icons etc.  desktop.
all of that is inside the tar.gz file.
The build works locally on my machine as a bundle or as direct flatpak builder install.

I think you will find all you need in the url given.
I modeled this directly against an app called Feeel

When this is over.. I would like to help give better documentation.  Without gpt and another sample file.. this would be impossible to get this far.

**Comment by bksubhuti** [comment]
I also made a bundle and tested it.
Everything should work fine.
(although I did not test the removed comment or the removed arch_only label).
https://www.dropbox.com/s/vhtsu3i5og63tkr/TipitakaPaliReader.flatpak?dl=0 

when I'm done.. maybe I can make a video on how to do this.
The example docs are too simple but unrealistic for the real world..
I also bet cannabera errors and gtk appmenu errors when running from the command line, but it does not affect my app.
I posted on discourse.flathub but did not see an answer or solution.
gpt said if I don't see any problems in the app, then , it does not matter so much.

**Comment by bksubhuti** [comment]
I modeled my submission based on a flutter app already accepted.
https://github.com/flathub/com.enjoyingfoss.feeel

**Comment by bksubhuti** [comment]
My apologies for closing the pr.  I don't know git pr's so well.  I asked chatgpt if I did the wrong thing by closing and making a new pr and it said it is preferred to make an update.  I've only done a few pr in my life and never edited a pr before.  In any case.. please see the new pr and I will learn to update if that is refused as well.

the other project feeel seems to have the appstream xml already in the bundle and he was approved.  I also did the same thing.  I think there is nothing really different from my yml desktop and xml file .. the only difference is the gz.tar file .. but even that was done with flutter and sqlite.

**Comment by bksubhuti** [comment]
Is there any way I can get some help or advice?

**Comment by barthalion** [comment]
You already opened a new one at https://github.com/flathub/flathub/pull/4302 so let's continue there.

**Pull request closed without merging**
