### PR TITLE
Add com.github.uwlabs.BloomRPC

### PR DESCRIPTION
**Pull request by Arxcis**
## BloomRPC
Github - https://github.com/uw-labs/bloomrpc

## Review comments
- [x] Build app from source, instead of pulling a pre-built deb-package.
- [x] Use scripts from `flatpak-builder-tools` to build from source more easily.

## [App submission](https://github.com/flathub/flathub/wiki/App-Submission)
- [x] Fork https://github.com/flathub/flathub
- [x] Clone the fork: git clone --branch=new-pr git@github.com:your_github_username/flathub.git
- [x] Create a new branch with your app’s name: git checkout -b your_app_name
- [x] Add your app’s manifest to the branch, commit it and push the commit
- [x] Open a pull request against the new-pr branch on Github
- [ ] Your pull request will then be reviewed by the Flathub admins

## [App requirements](https://github.com/flathub/flathub/wiki/App-Requirements)
- [ ] All content hosted on Flathub must allow legal redistribution, and the license must be correctly specified in the app's appdata file.
- [x] Each application should have a unique application ID, following the standard reverse-DNS schema.
- [x] The manifest must be at the top level and named after the application ID with the extension .json.
- [x] Manifests should therefore refer to tarballs or git tags and not the tip of a branch.
- [x] Applications must be built against an SDK that is itself hosted on Flathub. This requirement also applies to SDK extensions that may be required in order to build an application. 
- [ ] Take care to check the build directory for unnecessary files. These should be added to cleanup, in order to ensure smaller package sizes.
- [x] Applications must include a desktop file and pass desktop-file-validate.
- [x] Applications must provide application icons
- [x] Permissions should still be limited as much as possible
- [x] Always append :ro if write access is not needed. (`--filesystem=home:ro`)
- [ ] If an application uses $TMPDIR to contain lock files it may make sense to use --env=TMPDIR=/var/tmp or if it shares those files outside the sandbox you may need to crete a wrapper script that sets it to $XDG_CACHE_HOME.  **Is this relevant to this app??**

## About me
- I am NOT a developer of BloomRPC, but I have discussed with one of the devs over there @ https://github.com/uw-labs/bloomrpc/issues/183, and he was positive to let a member of the community maintain a Flathub manifest.
- I am a very happy user of BloomRPC and would really like to have it together with all my other tools on Flathub.

### CODE REVIEW

**Comment by gasinvein** [comment]
Did you try to build it from source?

**Comment by Arxcis** [comment]
> Did you try to build it from source?

I have built from source on my local machine outside of Flatpak, but not inside Flatpak.

Here are the steps to build from source
```
git clone https://github.com/uw-labs/bloomrpc.git
cd bloomrpc

yarn install && ./node_modules/.bin/electron-rebuild
npm run package
```
https://github.com/uw-labs/bloomrpc#build-from-source

`node` and `yarn` are required.

**Comment by Arxcis** [comment]
Would it be better to build from source, instead of pulling the `.deb` image?

**Comment by nedrichards** [comment]
Yes, it would. There are scripts available at https://github.com/flatpak/flatpak-builder-tools that make it easier to do.

**Comment by Arxcis** [comment]
Cheers @nedrichards :) I will look into it.

**Comment by LeandroStanger** [comment]
bot, build com.github.uwlabs.BloomRP

**Comment by Arxcis** [comment]
Hi @LeandroStanger . This build error does not make any sense to me
```
Can't load 'com.github.uwlabs.BloomRP.json': Failed to open file “/srv/buildbot-master/master/workers/MasterWorkerUntrusted/Builds/build/com.github.uwlabs.BloomRP.json”: No such file or directory
```
The name is wrong, BloomRP vs BloomRPC, and it tries to use `.json` instead of `.yaml`.

**Comment by LeandroStanger** [comment]
bot, build com.github.uwlabs.BloomRPC

**Comment by Arxcis** [comment]
> Build [17970 failed](https://flathub.org/builds/#/builders/32/builds/17970)

This is the error I am expecting :+1 Thanks

**Pull request closed without merging**
