### PR TITLE
Add org.freedesktop.Sdk.Extension.action-inject

### PR DESCRIPTION
**Pull request by wsgalaxy**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

This extension make it possible to inject addition actions from the outside of the container, it is mainly used with vscode as you can enable Sdk extensions with FLATPAK_ENABLE_SDK_EXT.

**Usage:**
1. Add actions to ~/.action-inject or any other file and set FLATPAK_ACTION_INJECT to that file(relative to ~);
2. Start vscode by: `FLATPAK_ENABLE_SDK_EXT=action-inject flatpak run com.visualstudio.code`

### CODE REVIEW

**Comment by wsgalaxy** [comment]
bot, build org.freedesktop.Sdk.Extension.action-inject

**Comment by wsgalaxy** [comment]
It is very useful  if you want to use external sdk(kotlin, groovy, etc) outside the container and hope the IDE(vscode) could detect it from PATH or any other environment variables

**Comment by wsgalaxy** [comment]
bot, build org.freedesktop.Sdk.Extension.action-inject

**Comment by wsgalaxy** [comment]
bot, build org.freedesktop.Sdk.Extension.action-inject

**Comment by wsgalaxy** [comment]
bot, build org.freedesktop.Sdk.Extension.action-inject

**Comment by hfiguiere** [comment]
this PR should be submitted against the `new-pr` branch.

**Comment by wsgalaxy** [comment]
@hfiguiere I have reopened this PR on #2474

**Pull request closed without merging**
