### PR TITLE
Add com.belmoussaoui.Authenticator

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build com.belmoussaoui.Authenticator

**Comment by barthalion** [comment]
The old app does not start anymore:

```
Gtk-Message: 10:45:14.057: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/Authenticator/application.py", line 208, in _is_locked_changed
    Window.get_default().refresh_view()
  File "/app/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 70, in get_default
    Window.instance = Window()
  File "/app/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 55, in __init__
    self.init_template('Window')
TypeError: <lambda>() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/Authenticator/application.py", line 77, in do_activate
    window = Window.get_default()
  File "/app/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 70, in get_default
    Window.instance = Window()
  File "/app/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 55, in __init__
    self.init_template('Window')
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```

**Comment by bilelmoussaoui** [comment]
> The old app does not start anymore:
> 
> ```
> Gtk-Message: 10:45:14.057: Failed to load module "canberra-gtk-module"
> Traceback (most recent call last):
>   File "/app/lib/python3.8/site-packages/Authenticator/application.py", line 208, in _is_locked_changed
>     Window.get_default().refresh_view()
>   File "/app/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 70, in get_default
>     Window.instance = Window()
>   File "/app/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 55, in __init__
>     self.init_template('Window')
> TypeError: <lambda>() takes 0 positional arguments but 1 was given
> Traceback (most recent call last):
>   File "/app/lib/python3.8/site-packages/Authenticator/application.py", line 77, in do_activate
>     window = Window.get_default()
>   File "/app/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 70, in get_default
>     Window.instance = Window()
>   File "/app/lib/python3.8/site-packages/Authenticator/widgets/window.py", line 55, in __init__
>     self.init_template('Window')
> TypeError: <lambda>() takes 0 positional arguments but 1 was given
> ```

Ah not great. I didn't expect an update to land at all but rather an EOL message :/

**Comment by bilelmoussaoui** [comment]
I wonder if there's a way to push an update to an EOL-ed app to unbreak it for users that don't know how to downgrade to an older commit?

**Comment by barthalion** [comment]
I can do that on the repo side, but I will need commit hash for all architectures if it's not a problem.

**Comment by bilelmoussaoui** [comment]
That would be really appreciated, I was thinking of just pushing a new commit with a patch that unbreak the old app with 3.38

**Comment by bilelmoussaoui** [comment]
The latest working commits:
x86_64: ffbbb5af1b92760e3a0476be59de13998f114e288f983da2296a39f787741469
aarch64: c931f4968c96db6d50e9806970e5ef1978cb6ac3509a2e72be91a9e9f0a88b86

Is that all the information you need? :)

**Comment by barthalion** [comment]
It does not seem to work the way I think I would:

```
Error: While pulling app/com.github.bilelmoussaoui.Authenticator/x86_64/stable from remote flathub: Update is older than current version
```

So I guess fixing it properly might be the safest choice here.

**Comment by bilelmoussaoui** [comment]
Thanks for checking! I will go that road

**Comment by bilelmoussaoui** [comment]
Should be fixed by https://github.com/flathub/com.github.bilelmoussaoui.Authenticator/pull/25

**Pull request closed without merging**
