### PR TITLE
submit build 59 update

### PR DESCRIPTION
**Pull request by bksubhuti**
### Please confirm your submission meets all the criteria

- [ x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ x] My pull request follows the instructions at [App Submission][submission].
- [ x] I have [built][build] and tested the submission locally.
- [ x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flatpak.org/en/latest/first-build.html

### CODE REVIEW

**Comment by hfiguiere** [comment]
this package already exist https://github.com/flathub/org.americanmonk.TipitakaPaliReader

**Comment by bksubhuti** [comment]
I realized that the xml was not updated.. I'm uploading now.. Then I will redo.  Hopefully that is the reason you think it exists. I have uploaded and installed via the url location..  Will edit my pr.  Sorry about that.

**Comment by bksubhuti** [comment]
It is pushed.. I think it will be reflected on this without making a new PR?

**Comment by razzeee** [comment]
hey @bksubhuti 

you should have commit access to https://github.com/flathub/org.americanmonk.TipitakaPaliReader you will need to do all further work (updates etc) in that repo.

So you likely want to checkout that (or maybe even fork) and send a MR targeting the `master` branch of that repo.

You can also use github to edit the file, but that's probably more work, if you know how git works.

**Comment by bksubhuti** [comment]
okay.. I appreciate your guidance.  
I'm not so good at git.  so I will fork and do a merge request.  I will close this.

**Pull request closed without merging**
