### PR TITLE
Add org.opencpn.OpenCPN

### PR DESCRIPTION
**Pull request by leamas**
This is the second attempt on opencpn, the first was #1528, accidentally closed.

I have hopefully fixed applicable review remarks and fixes, squashing the history.

>  does David have GitHub account so we can invite him to the new repo as well?

That is @bdbcat

### CODE REVIEW

**Comment by leamas** [comment]
bot, build org.opencpn.OpenCPN

**Comment by leamas** [comment]
Thanks for all your input and final approval. 

Let's wait until the final 5.1 release is out before actually merging.

**Comment by eszlari** [comment]
Are you aware of the implications of using the 18.08 runtime?

current 18.08 Mesa version: `19.1.7`
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/18.08/NEWS

current 19.08 Mesa version: `20.0.5`
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/19.08/NEWS

In other words: If your app is utilizing 3D acceleration in any way, you will miss support for newer hardware and performance optimizations/fixes for older hardware.

**Comment by leamas** [comment]
I wouldn't say I'm aware of all the implications, certainly not. That said, you don't need to convince me to move to 19.08. It must be done, question is just when.

As I described in #1528, there is already a small echosystem of flatpak plugins to opencpn. Any change like this will need to replicated in all plugins.

There are also more issues which will lead to an ABI break: gtk2 -> gtk3 and wxwidgets 3.0 -> 3.2. Of these, wxwidgets 3.2 is still not available,  although it should arrive "this spring".

So, the reason to postpone the 18.08 -> 19.08 change is to make a single ABI break which sorts out both gtk2/3, wxWidgets and flatpak runtime instead of having several breaks. Whether this is the right way to handle is far from certain, but my best guess at this point.

**Comment by nedrichards** [comment]
It seems the most sane to me, depending on timing you may want to take advantage of 20.08 as well.

**Comment by eszlari** [comment]
In the original PR you didn't mention, that you have your on repo:

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak

```
flatpak install --user http://opencpn.duckdns.org/opencpn-beta/opencpn.flatpakref
error: Unable to load summary from remote opencpn: Signature made Wed May 20 18:35:45 2020 using RSA key ID FB9CFA2C940F2381
Can't check signature: public key not found
```

How are these plugins distributed? (As flatpak extensions?)

**Comment by leamas** [comment]
They are not regular flatpak extensions, they are just dl-loaded plugins built against the flatpak runtime.

BTW: The missing key is available at http://opencpn.duckdns.org/opencpn-beta/opencpn.key

**Comment by leamas** [comment]
bot, build org.opencpn.OpenCPN

**Comment by leamas** [comment]
@barthalion 

Hi,

Upstream release 5.2.0 is out. The package is updated and ready to be merged

**Comment by leamas** [comment]
@bilelmoussaoui @nedrichards :^

**Comment by leamas** [comment]
@bilelmoussaoui @barthalion : 

Thanks for a simple and fast packaging process.

**Pull request closed without merging**
