### PR TITLE
Add org.glimpse_editor.Glimpse

### PR DESCRIPTION
**Pull request by bochecha**
This is based on the manifest maintained upstream for the development
branch:

https://github.com/glimpse-editor/Glimpse/blob/dev-g210/build/flatpak/org.glimpse_editor.Glimpse.json

---

Note: This is not ready to be pushed to Flathub. Most importantly this builds from the tip of the development branch because a release hasn't been made yet.

However, I figured it wouldn't hurt to start the review process early to save some time. :slightly_smiling_face:

TODO:

* [x] Add screenshots to the appdata;
* [x] Add release notes to the appdata;
* [ ] Build the release once it's available;

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build org.glimpse_editor.Glimpse

**Comment by bochecha** [comment]
Build failed validating the appdata file, as expected. (see the TODO items in the original comment)

**Comment by bochecha** [comment]
bot, build org.glimpse_editor.Glimpse

**Comment by bochecha** [comment]
I was told it is possible to have the app approved (if it passes review of course) even before the release, so we can push it straight to the beta channel. That would be great. :slightly_smiling_face:

**Comment by bilelmoussaoui** [comment]
Looks fine to me.
/merge:beta

**Pull request closed without merging**
