### PR TITLE
Add org.nongnu.enigma

### PR DESCRIPTION
**Pull request by MrTarantoga**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link: https://lists.nongnu.org/archive/html/enigma-devel/2021-09/msg00000.html**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by MrTarantoga** [comment]
bot, build org.nongnu.enigma

**Comment by MrTarantoga** [comment]
bot, build org.nongnu.enigma

**Comment by MrTarantoga** [comment]
bot, build org.nongnu.enigma

**Comment by MrTarantoga** [comment]
bot, build org.nongnu.enigma

**Comment by MrTarantoga** [comment]
bot, build org.nongnu.enigma

**Comment by MrTarantoga** [comment]
bot, build org.nongnu.enigma

**Comment by MrTarantoga** [comment]
bot, build org.nongnu.enigma

**Comment by hfiguiere** [comment]
PR should be against `new-pr`

**Comment by MrTarantoga** [comment]
> PR should be against `new-pr`

Sorry, i missed that.

**Comment by barthalion** [comment]
You will need to open new PR, as GitHub is confused when a branch s removed/

**Pull request closed without merging**
