### PR TITLE
Add io.qt.qtwebengine.BaseApp

### PR DESCRIPTION
**Pull request by grulja**

### CODE REVIEW

**Comment by grulja** [comment]
We can test to build this once https://github.com/flathub/buildbot-config/pull/67 is merged.

**Comment by nedrichards** [comment]
How many versions are you going to want to support for this or will it go across all future runtimes? I assume there'll need to be a version for 5.14, 6.0 etc. we tend to put these on 'versioned' branches like //5.13 for the runtime that they're targeting e.g. https://github.com/flathub/io.atom.electron.BaseApp with 1.6 and 18.08 versions

**Comment by grulja** [comment]
Yes, that's what I would like to have, this one should go into branch/5.13, similar to what is used with qtwebkit [1].

[1] - https://github.com/flathub/io.qt.qtwebkit.BaseApp

**Comment by grulja** [comment]
bot, build

**Comment by grulja** [comment]
@nedrichards do you know why I cannot run a test build?

**Comment by nedrichards** [comment]
@grulja when you're in a 'review' PR like this you need to specify an app-id like so (if you leave it out it uses the repo name as the app-id which in this case is flathub):

bot, build io.qt.qtwebengine.BaseApp

**Comment by grulja** [comment]
bot, build io.qt.qtwebengine.BaseApp

**Comment by grulja** [comment]
bot, build io.qt.qtwebengine.BaseApp

**Comment by LeandroStanger** [comment]
bot, build io.qt.qtwebengine.BaseApp

**Comment by grulja** [comment]
bot, build io.qt.qtwebengine.BaseApp

**Comment by grulja** [comment]
QtWebEngine is now again part of the runtime.

**Pull request closed without merging**
