### PR TITLE
ar.com.tuxguitar.TuxGuitar

### PR DESCRIPTION
**Pull request by gabops**
TuxGuitar is a free and open-source tablature editor, which includes features such as tablature editing, score editing, and import and export of Guitar Pro gp3, gp4, and gp5 files. In addition, TuxGuitar's tablature and staff interfaces function as basic MIDI editors.

TuxGuitar's mascot and namesake is Tux, the penguin mascot of many games and programs originally designed for Linux.

The program is written in the Java programming language and is released under version 2.1 of the GNU Lesser General Public License.

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build ar.com.tuxguitar.TuxGuitar

**Comment by LeandroStanger** [comment]
bot, build ar.com.tuxguitar.TuxGuitar

**Comment by LeandroStanger** [comment]
bot, build ar.com.tuxguitar.TuxGuitar

**Comment by LeandroStanger** [comment]
bot, build ar.com.tuxguitar.TuxGuitar

**Comment by nedrichards** [comment]
bot, build ar.com.tuxguitar.TuxGuitar

**Comment by gabops** [comment]
bot, build ar.com.tuxguitar.TuxGuitar

**Comment by gabops** [comment]
bot, build ar.com.tuxguitar.TuxGuitar

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/ar.com.tuxguitar.TuxGuitar

**Pull request closed without merging**
