### PR TITLE
Add org.gnome.design.Palette

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This replaces https://github.com/flathub/org.gnome.zbrown.Palette

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.design.Palette

**Comment by LeandroStanger** [comment]
bot, build org.gnome.design.Palette

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.design.Palette

**Comment by bilelmoussaoui** [comment]
bot, build org.gnome.design.Palette

**Pull request closed without merging**
