### PR TITLE
Add org.sugarlabs.CellGame

### PR DESCRIPTION
**Pull request by SudoSu-bham**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly.
Aliens have abducted two each of six species from Earth. All are currently held captive on a spaceship returning to the alien home-planet, with each species in a different cell. The player's goal is to have one of each type of species escape to the center of the ship. A group of unique individuals, one for each species, will give the player the strength they need to overpower the alien guards and release everyone.

- [X] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read the and followed all the [Submission and licence requirements][reqs].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:**

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by SudoSu-bham** [comment]
cc @tchx84

**Comment by hfiguiere** [comment]
bot, build org.sugarlabs.CellGame

**Comment by bbhtt** [comment]
is the close button on top right working?

**Comment by SudoSu-bham** [comment]
> is the close button on top right working? seems to be doing nothing for me.

I updated the activity version in the manifest file and now it is working properly. please review.

**Comment by SudoSu-bham** [comment]
bot, build org.sugarlabs.CellGame

**Pull request closed without merging**
