### PR TITLE
Add org.kde.kfourinline

### PR DESCRIPTION
**Pull request by cho2**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of [permissions](https://invent.kde.org/packaging/flatpak-kde-applications/-/blob/master/org.kde.kfourinline.json#L10). 
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. 
  - I am a member of [KDE Team on Flathub](https://github.com/orgs/flathub/teams/kde/members).
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
  - KDE project owns the domain
- [x] Any additional patches or files have been submitted to the upstream projects concerned. 
  - https://invent.kde.org/games/kfourinline/-/merge_requests/2

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by cho2** [comment]
bot, build org.kde.kfourinline

**Comment by cho2** [comment]
cc @flathub/kde

**Comment by travier** [comment]
LGTM. Not tested but it's a game so I trust @cho2  🙂.

**Comment by hfiguiere** [comment]
are you sure it doesn't need dri?

**Comment by travier** [comment]
```
libEGL warning: wayland-egl: could not open /dev/dri/renderD128 (No such file or directory)
```

It does! Thanks @hfiguiere

**Comment by cho2** [comment]
```
flatpak run org.kde.kfourinline                                                  
Qt: Session management error: Could not open network socket
-----------------------------------------------------------
KGamePropertyHandler:: Debug this= KGamePropertyHandler(0x55c1a22c8650)
  Registered properties: (Policy,Lock,Emit,Optimized, Dirty)
   7 : p= 3 l= false e= true o= false d= true
   8 : p= 3 l= false e= true o= false d= true
   6 : p= 3 l= false e= true o= false d= true
-----------------------------------------------------------
org.kde.games.private.kgame: :id= 0  Cannot emitSignal because there is no handler set
-----------------------------------------------------------
KGamePropertyHandler:: Debug this= KGamePropertyHandler(0x55c1a22c8650)
  Registered properties: (Policy,Lock,Emit,Optimized, Dirty)
   7 : p= 2 l= false e= true o= false d= true
   8 : p= 2 l= false e= true o= false d= true
   28672 : p= 3 l= false e= true o= false d= false
   28673 : p= 3 l= false e= true o= false d= false
   28674 : p= 3 l= false e= true o= false d= true
   28675 : p= 3 l= false e= true o= false d= true
   28676 : p= 3 l= false e= true o= false d= true
   28677 : p= 3 l= false e= true o= false d= false
   28678 : p= 3 l= false e= true o= false d= true
   28679 : p= 3 l= false e= true o= false d= true
   28680 : p= 3 l= false e= true o= false d= true
   28681 : p= 3 l= false e= true o= false d= true
   28682 : p= 3 l= false e= true o= false d= true
   6 : p= 2 l= false e= true o= false d= true
   28683 : p= 2 l= false e= true o= false d= true
-----------------------------------------------------------
QGraphicsScene::addItem: item has already been added to this scene
QGraphicsScene::addItem: item has already been added to this scene
QGraphicsScene::addItem: item has already been added to this scene
QGraphicsScene::addItem: item has already been added to this scene
QGraphicsScene::addItem: item has already been added to this scene
QGraphicsScene::addItem: item has already been added to this scene
QGraphicsScene::addItem: item has already been added to this scene
QGraphicsScene::addItem: item has already been added to this scene
QGraphicsScene::addItem: item has already been added to this scene
QGraphicsScene::addItem: item has already been added to this scene
QGraphicsScene::addItem: item has already been added to this scene
: 13 KGameProperty objects
: 13 KGameProperty objects
libGL error: MESA-LOADER: failed to retrieve device information
```
do we need dri and network?

**Comment by nedrichards** [comment]
Absolutely needs DRI

**Comment by cho2** [comment]
bot, build org.kde.kfourinline

**Comment by travier** [comment]
LGTM

**Comment by tsdgeos** [comment]
:+1:

**Pull request closed without merging**
