### PR TITLE
add org.kde.blinken

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by cho2** [comment]
bot, build org.kde.blinken

**Comment by cho2** [comment]
bot, build org.kde.blinken

**Comment by tsdgeos** [comment]
I can't hear anything. Please fix that the game is mega hard if you can't hear :)

**Comment by cho2** [comment]
bot, build org.kde.blinken

**Comment by cho2** [comment]
```
Qt: Session management error: Could not open network socket
```
add `--share=network`

**Comment by cho2** [comment]
bot, build org.kde.blinken

**Comment by cho2** [comment]
Cuplikan layar dari 2020-09-14 10-41-05

LGTM

**Pull request closed without merging**
