### PR TITLE
Add org.mixxx.Mixxx

### PR DESCRIPTION
**Pull request by FakeShemp**
https://www.mixxx.org/

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build org.mixxx.Mixxx

**Comment by FakeShemp** [comment]
bot, build org.mixxx.Mixxx

**Comment by nedrichards** [comment]
@FakeShemp have you spoken to Mixxxx about supporting this themselves?

**Comment by FakeShemp** [comment]
Yes. I invited them over here :)

**Comment by FakeShemp** [comment]
bot, build org.mixxx.Mixxx

**Comment by FakeShemp** [comment]
bot, build org.mixxx.Mixxx

**Comment by FakeShemp** [comment]
bot, build org.mixxx.Mixxx

**Comment by nedrichards** [comment]
@FakeShemp cool, do you have a URL for tracking/looking up or was it on that new fangled real time chat ;-)

**Comment by FakeShemp** [comment]
@nedrichards It was on that Zulip thingie, yes. I think messages persist there though.

**Comment by FakeShemp** [comment]
bot, build org.mixxx.Mixxx

**Comment by FakeShemp** [comment]
bot, build org.mixxx.Mixxx

**Comment by nedrichards** [comment]
bot, build org.mixxx.Mixxx

**Comment by FakeShemp** [comment]
Server issues I think :/
bot, build org.mixxx.Mixxx

**Comment by nedrichards** [comment]
I get a bunch of dconf warnings running this, looks like you need to add those permissions. Other than that, and a few alsalib warnings that don't seem critical this lgtm.

**Comment by FakeShemp** [comment]
bot, build org.mixxx.Mixxx

**Comment by nedrichards** [comment]
@FakeShemp dconf means we need all these four:

> --filesystem=xdg-run/dconf
--filesystem=~/.config/dconf:ro
--talk-name=ca.desrt.dconf
--env=DCONF_USER_CONFIG_DIR=.config/dconf

http://docs.flatpak.org/en/latest/sandbox-permissions.html#dconf-access for more.

**Comment by FakeShemp** [comment]
bot, build org.mixxx.Mixxx

**Comment by FakeShemp** [comment]
bot, build org.mixxx.Mixxx

**Comment by FakeShemp** [comment]
bot, build org.mixxx.Mixxx

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.mixxx.Mixxx

**Comment by nedrichards** [comment]
@FakeShemp cool, let us know any people from upstream who need to be added as per usual.

**Comment by Be-ing** [comment]
Hi @nedrichards, I'm an upstream Mixxx developer. I just [updated Flathub to our recent release](https://github.com/flathub/org.mixxx.Mixxx/pull/33). I'm willing to maintain this now that distros have started shipping PipeWire for audio. Could you make me a maintainer of the org.mixxx.Mixxx repository?

**Pull request closed without merging**
