### PR TITLE
Add io.qt.qtdatavis3d.BaseApp

### PR DESCRIPTION
**Pull request by filipestevao**
This is a BaseApp for AlphaPlot app

### CODE REVIEW

**Comment by filipestevao** [comment]
bot, build io.qt.qtdatavis3d.BaseApp

**Comment by filipestevao** [comment]
```
builddir/files/share/appdata/io.qt.qtdatavis3d.BaseApp.appdata.xml: FAILED:
• attribute-invalid     : <component> has invalid type attribute
• style-invalid         : Not enough <screenshot> tags, minimum is 1
Validation of files failed
```
This is a BaseApp. Is necessary the flathub.json file with tag: "skip-appstream-check": true?

**Comment by filipestevao** [comment]
bot, build io.qt.qtdatavis3d.BaseApp

**Comment by bilelmoussaoui** [comment]
I'm not sure what's the purpose of this BaseApp? will it be shared with other apps?

**Comment by filipestevao** [comment]
The purpose of this BaseApp is to use the qtdatavis3d submodule in the AlphaPlot app. I thought of leaving it separate in case another app uses it. However, if you are not interested in having this separate library, I can package it with the AlphaPlot app. There are no problems with that.

**Comment by bilelmoussaoui** [comment]
Please merge it with the app itself. A separate BaseApp would make sense only if its contains modules that are used by a bunch of apps or that might take a long time to build.

**Comment by filipestevao** [comment]
That's right. Thank you very much.

**Pull request closed without merging**
