### PR TITLE
org.mozilla.Firefox

### PR DESCRIPTION
**Pull request by sdsy**
bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1278719
(I'm not a FF dev)

### CODE REVIEW

**Comment by Barthalion** [comment]
This is too high profile application to be maintained downstream. Possibly Mozilla will maintain it themselves at some point.

**Comment by sdsy** [comment]
Mozilla had 2 years to create a configuration. It has never provided debs, rpms or snaps. I'm pretty sure they'll *never* provide a flatpak or any specific package for linux besides the tar.bz2

**Comment by lachmanfrantisek** [comment]
There is already some [unofficial flatpak repo](https://firefox-flatpak.mojefedora.cz/) (github repo [here](https://github.com/xhorak/firefox-devedition-flatpak)). It looks quite active.

**Comment by TingPing** [comment]
There have been discussions with Mozilla over the subject. It isn't guaranteed to happen but that is the goal. If Mozilla explicitly says they will never do it then perhaps it can be reconsidered.

**Comment by sdsy** [comment]
@lachmanfrantisek those are for the dev and nightly versions and they give access to the entire filesystem.

**Comment by lachmanfrantisek** [comment]
@sdsy  you are right. Maybe, you can ask for adding the stable version there.

------

Not sure about the filesystem, they use:
```
"--filesystem=xdg-download:rw",
```

or
```
 "--filesystem=home:rw",
```

**Comment by sdsy** [comment]
@TingPing if we're so dependent on the developers' whims then how will flatpak grow in adoption? Right now, flatpak is mostly used for a few niché packages which require special treatment like spotify, steam etc. For flatpak and snap to fulfill their goals they need to provide a wide palette of applications and right now, flathub doesn't have a usable browser.

@lachmanfrantisek the fedora devs explicitly stated that the packages are *just* for testing purposes, I doubt they'll want to maintain one more. And they're not on flathub.

**Comment by TingPing** [comment]
Firefox is the only application this applies to because it is very high profile from a security perspective and will be higher maintenance than most applications and Mozilla has shown some interest in shipping their own in the future.

**Comment by prcastro** [comment]
In the mean time, Canonical added Firefox to their Snap Store. From the user perspective Snap is right now the most viable app store alternative, since it's the only that contains the most daily-used apps (firefox/chromium).

Flathub users need two app managers (flatpak + one to install firefox) while Snap users only need one.

**Comment by TingPing** [comment]
> Flathub users need two app managers (flatpak + one to install firefox) while Snap users only need one.

Frankly this is the place that it matters least. Firefox is well maintained by distros and kept up to date because it has to for security reasons.

Anyway for Firefox the ball is in Mozillas court.

**Comment by trialism** [comment]
@prcastro there's barely anything in the snap store compared to flathub so, it's not an alternative and most certainly not better. Most of snap store's content are either toy projects or *very* outdated oss. Also consider the fact that snaps are strongly tied to ubuntu and canonical - and the latter likes to abandon projects which makes snap even less appealing. Of course canonical uses snap but the rest of the distros don't really want that because it doesn't offer anything.

**Pull request closed without merging**
