### PR TITLE
Add org.cubocore.CoreTerminal

### PR DESCRIPTION
**Pull request by s96Abrar**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by s96Abrar** [comment]
bot, build org.cubocore.CoreTerminal

**Comment by s96Abrar** [comment]
bot, build org.cubocore.CoreTerminal

**Comment by hfiguiere** [comment]
Did you submit the appdata upstream?

**Comment by s96Abrar** [comment]
Yeah, I have to store the appdata at flathub until we provide a release. Very soon those will be moved from here.

**Comment by barthalion** [comment]
I suspect it doesn't work the way you think it does. The shell is spawned **inside** the sandbox, so the command set is limited to org.kde.Platform. You should probably take a look at GNOME Builder or Tilix source code to check how to make it run shell on the host.

**Comment by s96Abrar** [comment]
So A terminal app for flatpak is not good? 
(Although I never thought why any flatpak terminal is not available.)

**Comment by bilelmoussaoui** [comment]
> So A terminal app for flatpak is not good?
> (Although I never thought why any flatpak terminal is not available.)

It's possible, yes. but requires a bit of work, see https://blogs.gnome.org/chergert/2019/04/25/flatpaking-terminals/

**Comment by s96Abrar** [comment]
Yeah, understood. Closing the request as the app not appropriate and provides functionality it's needed to.

**Pull request closed without merging**
