### PR TITLE
Add io.crow_translate.CrowTranslate

### PR DESCRIPTION
**Pull request by gasinvein**
### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
  crow-translate/crow-translate#79
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
  The domain crow-translate.io isn't registered. But since the app ID was established long ago, and app has public DBus API that serves on this bus name, it doesn't seem feasible to change the ID now.
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

### CODE REVIEW

**Comment by gasinvein** [comment]
bot, build io.crow_translate.CrowTranslate

**Comment by tim77** [comment]
Can't run app:
```
❯ flatpak run io.crow_translate.CrowTranslate                                                              
lstmeval: error while loading shared libraries: libunicharset_training.so: cannot open shared object file: No such file or directory
```

**Comment by Shatur** [comment]
Looks like something wrong with Tesseract.

**Comment by gasinvein** [comment]
Ugh, that's weird. My local build from the very same manifest works fine.

**Comment by gasinvein** [comment]
Ah, Crow Translate works fine, just launch it from the .desktop file. It's some Tesseract binary broken, the binary is picked up as the flatpak entrypoint because I've forgot to set `command` explicitly. I'll fix it right away.

**Comment by gasinvein** [comment]
bot, build io.crow_translate.CrowTranslate

**Comment by gasinvein** [comment]
@Shatur Does the app need Tesseract programs at all? If not, I guess we can (and should) just remove them from the bundle.

**Comment by Shatur** [comment]
Not needed, I only use the library.

**Comment by gasinvein** [comment]
bot, build io.crow_translate.CrowTranslate

**Comment by tim77** [comment]
Not sure is this related to flatpak build, but there is no icons.
изображение
OS: Fedora 36; GNOME v42; Xorg.

**Comment by Shatur** [comment]
Looks like missing Qt SVG module.

**Comment by gasinvein** [comment]
Nah, QtSVG is certainly there. I can see all the icons with Breeze and Papirus icon themes, most (but not all) icons with elementary theme, but none with the default Adwaita theme. I guess there should be some fallback that isn't working?

**Comment by Shatur** [comment]
Ah, yes, there is such issue: https://github.com/crow-translate/crow-translate/issues/330
I tried to solve it many times, but no success.

**Comment by gasinvein** [comment]
Hmm, so, if it's not specific to flatpak, I guess it's not a blocker for flatpak either.

**Comment by Shatur** [comment]
> If setting QT_STYLE_OVERRIDE=Breeze helps and makes the fallback work, then the cause must be not in GNOME itself but in QGnomePlatform, I guess.

Yep, the fallback works on KDE.

**Comment by barthalion** [comment]
Yeah, let's go with `QT_STYLE_OVERRIDE=Breeze`.

**Comment by gasinvein** [comment]
I wonder what happens if someone has global override of the same env var, e.g. `--env=QT_STYLE_OVERRIDE=qt5ct`. Will the app-specific finish-arg take priority?

**Comment by barthalion** [comment]
Sure, whatever works.

**Comment by Shatur** [comment]
> Ah, yes, there is such issue

The issue was fixed by @gasinvein. Drafted a new release.

**Comment by gasinvein** [comment]
bot, build io.crow_translate.CrowTranslate

**Comment by Shatur** [comment]
Sorry, forgot to update install rule. Let me fix it.

**Comment by gasinvein** [comment]
What install rule?

**Comment by Shatur** [comment]
Icons that was used in CMake install rule: https://github.com/crow-translate/crow-translate/commit/31c641a7cbabd7178482c2303571234067372915
Done, please, update the hash.

**Comment by gasinvein** [comment]
Oh, I see.

bot, build io.crow_translate.CrowTranslate

**Comment by tim77** [comment]
Light theme variant works correctly now, but same issue with dark variant:
Снимок экрана от 2022-05-13 09-10-29
Снимок экрана от 2022-05-13 09-10-41
Maybe i should report this upstream and we can improve this in future? Not related to current flatpak build i guess.

**Comment by Shatur** [comment]
> Maybe i should report this upstream and we can improve this in future?

Yes, probably we should bundle light and dark icon variants. Not sure how currently.

**Comment by tim77** [comment]
> > Maybe i should report this upstream and we can improve this in future?
> 
> Yes, probably we should bundle light and dark icon variants. Not sure how currently.

[Done](https://github.com/crow-translate/crow-translate/issues/427). Thank you for packaging such great app on Flathub and make it available for everyone.

**Comment by gasinvein** [comment]
> same issue with dark variant

It's not really _same_ - icons are there, just barely visible on dark background.

**Pull request closed without merging**
