### PR TITLE
Add com.valvesoftware.Steam.Utility.vkBasalt

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Closes https://github.com/flathub/com.valvesoftware.Steam/issues/625

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
bot, build com.valvesoftware.Steam.Utility.vkBasalt

**Comment by TheEvilSkeleton** [comment]
bot, build com.valvesoftware.Steam.Utility.vkBasalt

**Comment by TheEvilSkeleton** [comment]
bot, build com.valvesoftware.Steam.Utility.vkBasalt

**Comment by TheEvilSkeleton** [comment]
@gasinvein I tried the flatpak, but it doesn't seem to work. I tried to understand the logs, but I have no clue what I was reading. Can you help?

**Comment by gasinvein** [comment]
@TheEvilSkeleton Did you install test build from here? If so, I guess the extension is not even enabled in the app, since flatpak branches do not match (`test` here vs. `stable` in Steam). Check if it's actually mounted at `/app/utils/vkBasalt` inside the sandbox.

**Comment by barthalion** [comment]
cc @nanonyme

**Comment by nanonyme** [comment]
Released to stable changes for using test extensions with app. Extension work looks good to me.

**Comment by TheEvilSkeleton** [comment]
> @TheEvilSkeleton Did you install test build from here? If so, I guess the extension is not even enabled in the app, since flatpak branches do not match (`test` here vs. `stable` in Steam). Check if it's actually mounted at `/app/utils/vkBasalt` inside the sandbox.

No, only MangoHud (`com.valvesoftware.Steam.Utility.MangoHud`) is there. I cannot find vkBasalt. Perhaps, as you said, it's in the `test` branch whereas Steam is in the `stable` branch?

**Comment by TheEvilSkeleton** [comment]
By any chance, do you guys know where vkBasalt.conf is located at? Or do we have to create it manually?

**Comment by tim77** [comment]
> By any chance, do you guys know where vkBasalt.conf is located at? Or do we have to create it manually?

This example conf file enough to run app https://github.com/DadSchoorse/vkBasalt/blob/master/config/vkBasalt.conf. You can installed it in `/etc` and should be fine.

**Comment by gasinvein** [comment]
You can't install anything to `/etc` in flatpak. Doesn't vkBasalt support user config, e.g. `~/.var/app/com.valvesoftware.Steam/config/vkBasalt/vkBasalt.conf` or something?

**Comment by tim77** [comment]
Any of this directories should be fine https://github.com/DadSchoorse/vkBasalt#configure

**Comment by gasinvein** [comment]
Ah, so `/etc` and `/usr/share` are [hardcoded](https://github.com/DadSchoorse/vkBasalt/blob/ca921c88f17c154d27583edc0240c172a66da445/src/config.cpp#L28-L31). If we need system-wide default config, this needs to be patched.

**Comment by gasinvein** [comment]
@TheEvilSkeleton Submitted DadSchoorse/vkBasalt#123 for proper system-wide config placement. For now you can add that PR as patch.
With this patch, the default config should work if installed to `$FLATPAK_DEST/etc/vkBasalt/vkBasalt.conf`.

**Comment by TheEvilSkeleton** [comment]
Hope it works. This is my first time actually using patch files.

**Comment by TheEvilSkeleton** [comment]
bot, build com.valvesoftware.Steam.Utility.vkBasalt

**Comment by gasinvein** [comment]
@TheEvilSkeleton This is not enough for vkBasalt to pick up default config, you also need to install the actual config file to the bundle. Add something like this to one of the vkBasalt modules:
```yaml
post-install:
  - install -Dm644 ../config/vkBasalt.conf ${FLATPAK_DEST}/etc/vkBasalt/vkBasalt.conf
```

**Comment by TheEvilSkeleton** [comment]
I wouldn't mind dropping the patches, since as you said differently, this should be edited per-user.

**Comment by gasinvein** [comment]
Well, I didn't mean you should drop the patch. What I said was that you need to bundle actual config file for the patch to be useful.

**Comment by gasinvein** [comment]
I guess the question here is - should vkBasalt do something without explicit configuration by the user?
- If so, you should bundle the system-wide config and patch vkBasalt to load it
- If not and vkBasalt should be no-op by default, then you don't need to ship default config

**Comment by TheEvilSkeleton** [comment]
> I guess the question here is - should vkBasalt do something without explicit configuration done by the user?

I personally think that it should provide the default config that comes with vkBasalt. I can set up a README in a couple of days to inform the user where the configuration file is located.

**Comment by TheEvilSkeleton** [comment]
bot, build com.valvesoftware.Steam.Utility.vkBasalt

**Comment by TheEvilSkeleton** [comment]
bot, build com.valvesoftware.Steam.Utility.vkBasalt

**Comment by TheEvilSkeleton** [comment]
@gasinvein like this right? https://github.com/flathub/flathub/pull/1921/commits/da18cee7ac265c47b9bd07285de15bddbf074484

**Comment by TheEvilSkeleton** [comment]
```bash
[📦 com.valvesoftware.Steam vkBasalt]$ pwd; ls
/app/utils/vkBasalt/etc/vkBasalt
vkBasalt.conf
```
Can confirm it has worked.

**Comment by gasinvein** [comment]
@TheEvilSkeleton Yes, it should work. Yet it's may be better to run some vulkan app and check console output from vkBasalt to confirm that it did load the config.

**Comment by TheEvilSkeleton** [comment]
> check console output from vkBasalt to confirm that it did load the config.

I had no idea this was possible. Can you guide me on this? I loaded up ARK on Proton and I will check visually if it has worked or not.

**Comment by gasinvein** [comment]
Steam's stdout is a bit messy and it may be hard to find something there, but AFAIK it doesn't eat up stdout from child processes. So just run Steam from cli with vkBasalt enabled (e.g. `flatpak run --env=ENABLE_VKBASALT=1 com.valvesoftware.Steam`), run a game and look carefully.

**Comment by TheEvilSkeleton** [comment]
I think it's sharper

# Without vkBasalt:
Screenshot from 2020-11-10 18-43-47

# With vkBasalt
Screenshot from 2020-11-10 18-37-29

**Comment by TheEvilSkeleton** [comment]
> Steam's stdout is a bit messy and it may be hard to find something there, but AFAIK it doesn't eat up stdout from child processes. So just run Steam from cli with vkBasalt enabled (e.g. `flatpak run --env=ENABLE_VKBASALT=1 com.valvesoftware.Steam`), run a game and look carefully.

Awesome, I will test it.

**Comment by TheEvilSkeleton** [comment]
```bash
flatpak run --env=ENABLE_VKBASALT=1 com.valvesoftware.Steam
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Overriding TZ to America/Toronto
Running Steam on org.freedesktop.platform 20.08.1.2 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/themainone/.local/share/Steam/ubuntu12_32/steam
```

It doesn't launch, but that's the only output I got when writing the command.

**Comment by gasinvein** [comment]
I guess you have Steam client already running, you need to exit it first to see it's output on console.

**Comment by TheEvilSkeleton** [comment]
Oh my god, I thought I closed it. Good thing you noticed it.

**Comment by TheEvilSkeleton** [comment]
Alright, here's what I got:

```bash
[...]

Could not connect to X session manager: None of the authentication protocols specified are supported
[1110/185827.422834:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
vkBasalt info:  config file: /app/utils/vkBasalt/etc/vkBasalt/vkBasalt.conf
vkBasalt info:  effects = cas
vkBasalt info:  reshadeTexturePath = /path/to/reshade-shaders/Textures
vkBasalt info:  reshadeIncludePath = /path/to/reshade-shaders/Shaders
vkBasalt info:  depthCapture = off
vkBasalt info:  toggleKey = Home
vkBasalt info:  casSharpness = 0.4
vkBasalt info:  dlsSharpness = 0.5
vkBasalt info:  dlsDenoise = 0.17
vkBasalt info:  fxaaQualitySubpix = 0.75
vkBasalt info:  fxaaQualityEdgeThreshold = 0.125
vkBasalt info:  fxaaQualityEdgeThresholdMin = 0.0312
vkBasalt info:  smaaEdgeDetection = luma
vkBasalt info:  smaaThreshold = 0.05
vkBasalt info:  smaaMaxSearchSteps = 32
vkBasalt info:  smaaMaxSearchStepsDiag = 16
vkBasalt info:  smaaCornerRounding = 25
vkBasalt info:  lutFile = /path/to/lut
Installing breakpad exception handler for appid(steam)/version(1603992987)
Could not connect to X session manager: None of the authentication protocols specified are supported

[...]
```

**Comment by TheEvilSkeleton** [comment]
So I have a `vkBasalt.conf` file in `~/.var/app/com.valvesoftware.Steam/config/vkBasalt.conf`, but it still picks the file up in `/app/utils/vkBasalt/etc/vkBasalt/vkBasalt.conf`.

**Comment by gasinvein** [comment]
I guess that's because it should be `~/.var/app/com.valvesoftware.Steam/config/vkBasalt/vkBasalt.conf` (note the `vkBasalt/` subdir).

**Comment by TheEvilSkeleton** [comment]
You're right, thank you.

**Comment by TheEvilSkeleton** [comment]
Seems to be working!

**Comment by TheEvilSkeleton** [comment]
Related to https://github.com/DadSchoorse/vkBasalt/pull/20#issuecomment-545101852.

@DadSchoorse if you want, you can maintain it. I really don't mind.

**Comment by TheEvilSkeleton** [comment]
bot, build com.valvesoftware.Steam.Utility.vkBasalt

**Comment by TheEvilSkeleton** [comment]
I forgot to mention: it is ready to be merged.

**Comment by barthalion** [comment]
Merge is on hold until we manage to rebuild GNOME runtime or https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1155 is fixed.

**Comment by gasinvein** [comment]
@barthalion Not sure how it is related - both Steam and this extension use freedesktop runtime.

**Comment by TheEvilSkeleton** [comment]
I agree, I don't understand why it is related.

**Comment by barthalion** [comment]
The toolchain-i386 ABI compatibility affects runtimes using it, so both KDE and GNOME. I couldn't allow more random build failures, sorry. We've managed to get GNOME runtime build fixed today.

**Pull request closed without merging**
