### PR TITLE
Add com.endlessnetwork.whitehouse

### PR DESCRIPTION
**Pull request by mwleeds**
This packaging was done by Travis Reitter and Alex Meyer. I'm just the one submitting it. If this is merged it would make sense to give these people write access: @mwleeds @treitter @alexthemighty @nanchu

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build com.endlessnetwork.whitehouse

**Comment by alexthemighty** [comment]
@mwleeds   Its trying to build architectures not outlined in the manifest.  Sorry, I should have doubled checked to make sure you had a file here.  Can you add a file to the repo called  "flathub.json"  with the contents:

{
   "only-arches": ["x86_64"]
}

That'll stop the current build fail problems.

**Comment by LeandroStanger** [comment]
flathubbot : WARNINGS
https://flathub.org/builds/#/builders/39/builds/544
```
builddir/files/share/appdata/com.endlessnetwork.whitehouse.appdata.xml: FAILED:
• tag-missing           : <translation> not specified
• value-missing         : <!-- Copyright [year] [name] --> is not present
• style-invalid         : <summary> cannot end in '.' [Using the magic of CSS, hack your world into a unique burst of color and light revealing hidden objects and clues.]
• translations-required  : <name> has no translations
• translations-required  : <summary> has no translations
• translations-required  : <description> has no translations
Validation of files failed
```

**Comment by nedrichards** [comment]
Those warnings are not blockers.

**Comment by mwleeds** [comment]
bot, build com.endlessnetwork.whitehouse

**Comment by mwleeds** [comment]
I installed the test build and it seems to work, with two caveats:

1. The screenshots don't load in GNOME Software, and there's a 404 error in the output, but the main screenshot links don't 404 (e.g. [this one](https://github.com/endless-network/WhiteHouse_Binary/raw/master/WH1.png)). It's just the thumbnail ones generated by Flathub that do (e.g. [this one](https://flathub.org/repo/screenshots/com.endlessnetwork.whitehouse-test/624x351/com.endlessnetwork.whitehouse-4613d2ba840441aa17e)), and I think it's a problem specific to the test repo since the thumbnails are working for apps already on Flathub.
2. The graphics don't seem as crisp in the game as they look in the screenshots, but I installed another Endless Studios game (Dragon's Apprentice) and it has the same issue. So up to you @alexthemighty if you want to look into that.

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/com.endlessnetwork.whitehouse

**Pull request closed without merging**
