### PR TITLE
gtk3 theme, Pop-slim-dark

### PR DESCRIPTION
**Pull request by Luke-Nukem**

### CODE REVIEW

**Comment by nedrichards** [comment]
Upstream conversation at https://github.com/pop-os/gtk-theme/issues/197

**Comment by Luke-Nukem** [comment]
Cool, thanks for the heads up.

**Comment by nedrichards** [comment]
bot, build org.gtk.Gtk3theme.Pop-slim-dark

**Comment by nedrichards** [comment]
Repository has been created: https://github.com/flathub/org.gtk.Gtk3theme.Pop-slim-dark

**Pull request closed without merging**
